/*
    Three phases per placement
    Generated from the Frontier Accelerator content workbook by generate.py.
    Do not hand-edit. Re-runnable: every statement is an ExternalId-keyed MERGE, nothing is deleted.
    309 phases. HuddleTopicId stays populated so topic-scoped queries keep working.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
DECLARE @unresolved INT;
BEGIN TRANSACTION;

;WITH raw AS (
    SELECT * FROM (VALUES
        (N'PH-AE-ORIENT-PREP', N'WF-ORIENT-01', N'AE-ORIENT', 1, N'Preparation'),
        (N'PH-AE-PLAN-PREP', N'WF-X-PLAN-01', N'AE-PLAN', 1, N'Preparation'),
        (N'PH-AE-PIPE-1-PREP', N'WF-X-PIPE-01', N'AE-PIPE-1', 1, N'Preparation'),
        (N'PH-AE-PIPE-2-PREP', N'WF-X-PIPE-01', N'AE-PIPE-2', 1, N'Preparation'),
        (N'PH-AE-OPP-PREP', N'WF-X-OPP-01', N'AE-OPP', 1, N'Preparation'),
        (N'PH-AE-CONV-PREP', N'WF-X-CONV-01', N'AE-CONV', 1, N'Preparation'),
        (N'PH-AE-DEAL-PREP', N'WF-X-DEAL-01', N'AE-DEAL', 1, N'Preparation'),
        (N'PH-AE-RENEW-PREP', N'WF-X-RENEW-01', N'AE-RENEW', 1, N'Preparation'),
        (N'PH-AE-INVEST-PREP', N'WF-INVEST-01', N'AE-INVEST', 1, N'Preparation'),
        (N'PH-AE-ORCH-PREP', N'WF-X-ORCH-01', N'AE-ORCH', 1, N'Preparation'),
        (N'PH-AE-VALUE-PREP', N'WF-X-VALUE-01', N'AE-VALUE', 1, N'Preparation'),
        (N'PH-ATS-ORIENT-PREP', N'WF-ORIENT-01', N'ATS-ORIENT', 1, N'Preparation'),
        (N'PH-ATS-INTEL-PREP', N'WF-X-PLAN-01', N'ATS-INTEL', 1, N'Preparation'),
        (N'PH-ATS-NARR-PREP', N'WF-X-CONV-01', N'ATS-NARR', 1, N'Preparation'),
        (N'PH-ATS-WORKLOAD-PREP', N'WF-X-PLAN-01', N'ATS-WORKLOAD', 1, N'Preparation'),
        (N'PH-ATS-TECH-PREP', N'WF-X-ARCH-01', N'ATS-TECH', 1, N'Preparation'),
        (N'PH-ATS-EBC-PREP', N'WF-X-CONV-01', N'ATS-EBC', 1, N'Preparation'),
        (N'PH-ATS-TALK-PREP', N'WF-X-CONV-01', N'ATS-TALK', 1, N'Preparation'),
        (N'PH-ATS-TEAM-PREP', N'WF-X-ORCH-01', N'ATS-TEAM', 1, N'Preparation'),
        (N'PH-ATS-INVEST-PREP', N'WF-INVEST-01', N'ATS-INVEST', 1, N'Preparation'),
        (N'PH-ATS-CBR-PREP', N'WF-X-VALUE-01', N'ATS-CBR', 1, N'Preparation'),
        (N'PH-ATS-HEALTH-PREP', N'WF-X-HEALTH-01', N'ATS-HEALTH', 1, N'Preparation'),
        (N'PH-ATS-PARTNER-PREP', N'WF-X-ORCH-01', N'ATS-PARTNER', 1, N'Preparation'),
        (N'PH-SSP-ORIENT-PREP', N'WF-ORIENT-01', N'SSP-ORIENT', 1, N'Preparation'),
        (N'PH-SSP-LEAD-PREP', N'WF-X-OPP-01', N'SSP-LEAD', 1, N'Preparation'),
        (N'PH-SSP-PLAN-PREP', N'WF-X-PLAN-01', N'SSP-PLAN', 1, N'Preparation'),
        (N'PH-SSP-VALUE-PREP', N'WF-X-VALUE-01', N'SSP-VALUE', 1, N'Preparation'),
        (N'PH-SSP-CONV-PREP', N'WF-X-CONV-01', N'SSP-CONV', 1, N'Preparation'),
        (N'PH-SSP-ORCH-PREP', N'WF-X-ORCH-01', N'SSP-ORCH', 1, N'Preparation'),
        (N'PH-SSP-COMP-PREP', N'WF-X-DEAL-01', N'SSP-COMP', 1, N'Preparation'),
        (N'PH-SSP-DEAL-PREP', N'WF-X-DEAL-01', N'SSP-DEAL', 1, N'Preparation'),
        (N'PH-SSP-INVEST-PREP', N'WF-INVEST-01', N'SSP-INVEST', 1, N'Preparation'),
        (N'PH-SE-ORIENT-PREP', N'WF-ORIENT-01', N'SE-ORIENT', 1, N'Preparation'),
        (N'PH-SE-CONV-PREP', N'WF-X-CONV-01', N'SE-CONV', 1, N'Preparation'),
        (N'PH-SE-ARCH-1-PREP', N'WF-X-ARCH-01', N'SE-ARCH-1', 1, N'Preparation'),
        (N'PH-SE-ARCH-2-PREP', N'WF-X-ARCH-01', N'SE-ARCH-2', 1, N'Preparation'),
        (N'PH-SE-ARCH-3-PREP', N'WF-X-ARCH-01', N'SE-ARCH-3', 1, N'Preparation'),
        (N'PH-SE-DISC-PREP', N'WF-X-DISC-01', N'SE-DISC', 1, N'Preparation'),
        (N'PH-SE-HEALTH-PREP', N'WF-X-HEALTH-01', N'SE-HEALTH', 1, N'Preparation'),
        (N'PH-SE-ASSET-PREP', N'WF-X-ASSET-01', N'SE-ASSET', 1, N'Preparation'),
        (N'PH-SE-INVEST-PREP', N'WF-INVEST-01', N'SE-INVEST', 1, N'Preparation'),
        (N'PH-CE-ORIENT-PREP', N'WF-ORIENT-01', N'CE-ORIENT', 1, N'Preparation'),
        (N'PH-CE-HEALTH-PREP', N'WF-X-HEALTH-01', N'CE-HEALTH', 1, N'Preparation'),
        (N'PH-CE-DEAL-1-PREP', N'WF-X-DEAL-01', N'CE-DEAL-1', 1, N'Preparation'),
        (N'PH-CE-DEAL-2-PREP', N'WF-X-DEAL-01', N'CE-DEAL-2', 1, N'Preparation'),
        (N'PH-CE-DEAL-3-PREP', N'WF-X-DEAL-01', N'CE-DEAL-3', 1, N'Preparation'),
        (N'PH-CE-ORCH-PREP', N'WF-X-ORCH-01', N'CE-ORCH', 1, N'Preparation'),
        (N'PH-CE-RENEW-PREP', N'WF-X-RENEW-01', N'CE-RENEW', 1, N'Preparation'),
        (N'PH-CE-POLICY-PREP', N'WF-X-POLICY-01', N'CE-POLICY', 1, N'Preparation'),
        (N'PH-CE-INVEST-PREP', N'WF-INVEST-01', N'CE-INVEST', 1, N'Preparation'),
        (N'PH-CSA-ORIENT-PREP', N'WF-ORIENT-01', N'CSA-ORIENT', 1, N'Preparation'),
        (N'PH-CSA-PIPE-PREP', N'WF-X-CONSUME-01', N'CSA-PIPE', 1, N'Preparation'),
        (N'PH-CSA-CONV-PREP', N'WF-X-CONV-01', N'CSA-CONV', 1, N'Preparation'),
        (N'PH-CSA-ARCH-1-PREP', N'WF-X-ARCH-01', N'CSA-ARCH-1', 1, N'Preparation'),
        (N'PH-CSA-ARCH-2-PREP', N'WF-X-ARCH-01', N'CSA-ARCH-2', 1, N'Preparation'),
        (N'PH-CSA-HEALTH-PREP', N'WF-X-HEALTH-01', N'CSA-HEALTH', 1, N'Preparation'),
        (N'PH-CSA-VALUE-1-PREP', N'WF-X-VALUE-01', N'CSA-VALUE-1', 1, N'Preparation'),
        (N'PH-CSA-VALUE-2-PREP', N'WF-X-VALUE-01', N'CSA-VALUE-2', 1, N'Preparation'),
        (N'PH-CSA-INVEST-PREP', N'WF-INVEST-01', N'CSA-INVEST', 1, N'Preparation'),
        (N'PH-CSAM-ORIENT-PREP', N'WF-ORIENT-01', N'CSAM-ORIENT', 1, N'Preparation'),
        (N'PH-CSAM-SPLAN-PREP', N'WF-X-PLAN-01', N'CSAM-SPLAN', 1, N'Preparation'),
        (N'PH-CSAM-HEALTH-PREP', N'WF-X-HEALTH-01', N'CSAM-HEALTH', 1, N'Preparation'),
        (N'PH-ALL-USECASE-PREP', N'WF-X-USECASE-01', N'ALL-USECASE', 1, N'Preparation'),
        (N'PH-CSAM-EXEC-PREP', N'WF-X-CONV-01', N'CSAM-EXEC', 1, N'Preparation'),
        (N'PH-CSAM-ORCH-PREP', N'WF-X-ORCH-01', N'CSAM-ORCH', 1, N'Preparation'),
        (N'PH-CSAM-VALUE-PREP', N'WF-X-VALUE-01', N'CSAM-VALUE', 1, N'Preparation'),
        (N'PH-CSAM-RENEW-PREP', N'WF-X-RENEW-01', N'CSAM-RENEW', 1, N'Preparation'),
        (N'PH-CSAM-ESCALATE-PREP', N'WF-X-HEALTH-01', N'CSAM-ESCALATE', 1, N'Preparation'),
        (N'PH-CSAM-INVEST-PREP', N'WF-INVEST-01', N'CSAM-INVEST', 1, N'Preparation'),
        (N'PH-ALL-DEAL-PREP', N'WF-X-DEAL-01', N'ALL-DEAL', 1, N'Preparation'),
        (N'PH-AE-HEALTH-PREP', N'WF-X-HEALTH-01', N'AE-HEALTH', 1, N'Preparation'),
        (N'PH-ALL-TRANSITION-PREP', N'WF-X-TRANSITION-01', N'ALL-TRANSITION', 1, N'Preparation'),
        (N'PH-ALL-HANDOFF-PREP', N'WF-X-HANDOFF-01', N'ALL-HANDOFF', 1, N'Preparation'),
        (N'PH-ATS-CONSUME-PREP', N'WF-X-CONSUME-01', N'ATS-CONSUME', 1, N'Preparation'),
        (N'PH-ALL-SPONSOR-PREP', N'WF-X-SPONSOR-01', N'ALL-SPONSOR', 1, N'Preparation'),
        (N'PH-ALL-FYPLAN-PREP', N'WF-X-FYPLAN-01', N'ALL-FYPLAN', 1, N'Preparation'),
        (N'PH-ALL-ASSET-PREP', N'WF-X-ASSET-01', N'ALL-ASSET', 1, N'Preparation'),
        (N'PH-CSAM-CONSUME-PREP', N'WF-X-CONSUME-01', N'CSAM-CONSUME', 1, N'Preparation'),
        (N'PH-SSP-CONSUME-PREP', N'WF-X-CONSUME-01', N'SSP-CONSUME', 1, N'Preparation'),
        (N'PH-SE-CONSUME-PREP', N'WF-X-CONSUME-01', N'SE-CONSUME', 1, N'Preparation'),
        (N'PH-ALL-CLOSE-PREP', N'WF-X-CLOSE-01', N'ALL-CLOSE', 1, N'Preparation'),
        (N'PH-DAE-SIGNAL-PREP', N'WF-X-SIGNAL-01', N'DAE-SIGNAL', 1, N'Preparation'),
        (N'PH-DSS-SIGNAL-PREP', N'WF-X-SIGNAL-01', N'DSS-SIGNAL', 1, N'Preparation'),
        (N'PH-DAE-PARTNER-PREP', N'WF-X-PARTNER-01', N'DAE-PARTNER', 1, N'Preparation'),
        (N'PH-PSS-PARTNER-PREP', N'WF-X-PARTNER-01', N'PSS-PARTNER', 1, N'Preparation'),
        (N'PH-DCSA-CONSUME-PREP', N'WF-X-CONSUME-01', N'DCSA-CONSUME', 1, N'Preparation'),
        (N'PH-DSE-ARCH-PREP', N'WF-X-ARCH-01', N'DSE-ARCH', 1, N'Preparation'),
        (N'PH-DAE-TERRITORY-PREP', N'WF-X-TERRITORY-01', N'DAE-TERRITORY', 1, N'Preparation'),
        (N'PH-DSS-TERRITORY-PREP', N'WF-X-TERRITORY-01', N'DSS-TERRITORY', 1, N'Preparation'),
        (N'PH-PSS-JOINTPLAN-PREP', N'WF-X-TERRITORY-01', N'PSS-JOINTPLAN', 1, N'Preparation'),
        (N'PH-DAE-ORIENT-PREP', N'WF-ORIENT-01', N'DAE-ORIENT', 1, N'Preparation'),
        (N'PH-DAE-CONV-PREP', N'WF-X-CONV-01', N'DAE-CONV', 1, N'Preparation'),
        (N'PH-DAE-DEAL-PREP', N'WF-X-DEAL-01', N'DAE-DEAL', 1, N'Preparation'),
        (N'PH-DAE-RENEW-PREP', N'WF-X-RENEW-01', N'DAE-RENEW', 1, N'Preparation'),
        (N'PH-DAE-HEALTH-PREP', N'WF-X-HEALTH-01', N'DAE-HEALTH', 1, N'Preparation'),
        (N'PH-SMEC-CE-ORIENT-PREP', N'WF-ORIENT-01', N'SMEC-CE-ORIENT', 1, N'Preparation'),
        (N'PH-SMEC-CE-RENEW-PREP', N'WF-X-RENEW-01', N'SMEC-CE-RENEW', 1, N'Preparation'),
        (N'PH-SMEC-CE-DEAL-PREP', N'WF-X-DEAL-01', N'SMEC-CE-DEAL', 1, N'Preparation'),
        (N'PH-SMEC-CE-HEALTH-PREP', N'WF-X-HEALTH-01', N'SMEC-CE-HEALTH', 1, N'Preparation'),
        (N'PH-DSS-ORIENT-PREP', N'WF-ORIENT-01', N'DSS-ORIENT', 1, N'Preparation'),
        (N'PH-DSS-CONV-PREP', N'WF-X-CONV-01', N'DSS-CONV', 1, N'Preparation'),
        (N'PH-DSS-DEAL-PREP', N'WF-X-DEAL-01', N'DSS-DEAL', 1, N'Preparation'),
        (N'PH-DSS-VALUE-PREP', N'WF-X-VALUE-01', N'DSS-VALUE', 1, N'Preparation'),
        (N'PH-AE-ORIENT-EXPL', N'WF-ORIENT-01', N'AE-ORIENT', 2, N'Explore and Practice'),
        (N'PH-AE-PLAN-EXPL', N'WF-X-PLAN-01', N'AE-PLAN', 2, N'Explore and Practice'),
        (N'PH-AE-PIPE-1-EXPL', N'WF-X-PIPE-01', N'AE-PIPE-1', 2, N'Explore and Practice'),
        (N'PH-AE-PIPE-2-EXPL', N'WF-X-PIPE-01', N'AE-PIPE-2', 2, N'Explore and Practice'),
        (N'PH-AE-OPP-EXPL', N'WF-X-OPP-01', N'AE-OPP', 2, N'Explore and Practice'),
        (N'PH-AE-CONV-EXPL', N'WF-X-CONV-01', N'AE-CONV', 2, N'Explore and Practice'),
        (N'PH-AE-DEAL-EXPL', N'WF-X-DEAL-01', N'AE-DEAL', 2, N'Explore and Practice'),
        (N'PH-AE-RENEW-EXPL', N'WF-X-RENEW-01', N'AE-RENEW', 2, N'Explore and Practice'),
        (N'PH-AE-INVEST-EXPL', N'WF-INVEST-01', N'AE-INVEST', 2, N'Explore and Practice'),
        (N'PH-AE-ORCH-EXPL', N'WF-X-ORCH-01', N'AE-ORCH', 2, N'Explore and Practice'),
        (N'PH-AE-VALUE-EXPL', N'WF-X-VALUE-01', N'AE-VALUE', 2, N'Explore and Practice'),
        (N'PH-ATS-ORIENT-EXPL', N'WF-ORIENT-01', N'ATS-ORIENT', 2, N'Explore and Practice'),
        (N'PH-ATS-INTEL-EXPL', N'WF-X-PLAN-01', N'ATS-INTEL', 2, N'Explore and Practice'),
        (N'PH-ATS-NARR-EXPL', N'WF-X-CONV-01', N'ATS-NARR', 2, N'Explore and Practice'),
        (N'PH-ATS-WORKLOAD-EXPL', N'WF-X-PLAN-01', N'ATS-WORKLOAD', 2, N'Explore and Practice'),
        (N'PH-ATS-TECH-EXPL', N'WF-X-ARCH-01', N'ATS-TECH', 2, N'Explore and Practice'),
        (N'PH-ATS-EBC-EXPL', N'WF-X-CONV-01', N'ATS-EBC', 2, N'Explore and Practice'),
        (N'PH-ATS-TALK-EXPL', N'WF-X-CONV-01', N'ATS-TALK', 2, N'Explore and Practice'),
        (N'PH-ATS-TEAM-EXPL', N'WF-X-ORCH-01', N'ATS-TEAM', 2, N'Explore and Practice'),
        (N'PH-ATS-INVEST-EXPL', N'WF-INVEST-01', N'ATS-INVEST', 2, N'Explore and Practice'),
        (N'PH-ATS-CBR-EXPL', N'WF-X-VALUE-01', N'ATS-CBR', 2, N'Explore and Practice'),
        (N'PH-ATS-HEALTH-EXPL', N'WF-X-HEALTH-01', N'ATS-HEALTH', 2, N'Explore and Practice'),
        (N'PH-ATS-PARTNER-EXPL', N'WF-X-ORCH-01', N'ATS-PARTNER', 2, N'Explore and Practice'),
        (N'PH-SSP-ORIENT-EXPL', N'WF-ORIENT-01', N'SSP-ORIENT', 2, N'Explore and Practice'),
        (N'PH-SSP-LEAD-EXPL', N'WF-X-OPP-01', N'SSP-LEAD', 2, N'Explore and Practice'),
        (N'PH-SSP-PLAN-EXPL', N'WF-X-PLAN-01', N'SSP-PLAN', 2, N'Explore and Practice'),
        (N'PH-SSP-VALUE-EXPL', N'WF-X-VALUE-01', N'SSP-VALUE', 2, N'Explore and Practice'),
        (N'PH-SSP-CONV-EXPL', N'WF-X-CONV-01', N'SSP-CONV', 2, N'Explore and Practice'),
        (N'PH-SSP-ORCH-EXPL', N'WF-X-ORCH-01', N'SSP-ORCH', 2, N'Explore and Practice'),
        (N'PH-SSP-COMP-EXPL', N'WF-X-DEAL-01', N'SSP-COMP', 2, N'Explore and Practice'),
        (N'PH-SSP-DEAL-EXPL', N'WF-X-DEAL-01', N'SSP-DEAL', 2, N'Explore and Practice'),
        (N'PH-SSP-INVEST-EXPL', N'WF-INVEST-01', N'SSP-INVEST', 2, N'Explore and Practice'),
        (N'PH-SE-ORIENT-EXPL', N'WF-ORIENT-01', N'SE-ORIENT', 2, N'Explore and Practice'),
        (N'PH-SE-CONV-EXPL', N'WF-X-CONV-01', N'SE-CONV', 2, N'Explore and Practice'),
        (N'PH-SE-ARCH-1-EXPL', N'WF-X-ARCH-01', N'SE-ARCH-1', 2, N'Explore and Practice'),
        (N'PH-SE-ARCH-2-EXPL', N'WF-X-ARCH-01', N'SE-ARCH-2', 2, N'Explore and Practice'),
        (N'PH-SE-ARCH-3-EXPL', N'WF-X-ARCH-01', N'SE-ARCH-3', 2, N'Explore and Practice'),
        (N'PH-SE-DISC-EXPL', N'WF-X-DISC-01', N'SE-DISC', 2, N'Explore and Practice'),
        (N'PH-SE-HEALTH-EXPL', N'WF-X-HEALTH-01', N'SE-HEALTH', 2, N'Explore and Practice'),
        (N'PH-SE-ASSET-EXPL', N'WF-X-ASSET-01', N'SE-ASSET', 2, N'Explore and Practice'),
        (N'PH-SE-INVEST-EXPL', N'WF-INVEST-01', N'SE-INVEST', 2, N'Explore and Practice'),
        (N'PH-CE-ORIENT-EXPL', N'WF-ORIENT-01', N'CE-ORIENT', 2, N'Explore and Practice'),
        (N'PH-CE-HEALTH-EXPL', N'WF-X-HEALTH-01', N'CE-HEALTH', 2, N'Explore and Practice'),
        (N'PH-CE-DEAL-1-EXPL', N'WF-X-DEAL-01', N'CE-DEAL-1', 2, N'Explore and Practice'),
        (N'PH-CE-DEAL-2-EXPL', N'WF-X-DEAL-01', N'CE-DEAL-2', 2, N'Explore and Practice'),
        (N'PH-CE-DEAL-3-EXPL', N'WF-X-DEAL-01', N'CE-DEAL-3', 2, N'Explore and Practice'),
        (N'PH-CE-ORCH-EXPL', N'WF-X-ORCH-01', N'CE-ORCH', 2, N'Explore and Practice'),
        (N'PH-CE-RENEW-EXPL', N'WF-X-RENEW-01', N'CE-RENEW', 2, N'Explore and Practice'),
        (N'PH-CE-POLICY-EXPL', N'WF-X-POLICY-01', N'CE-POLICY', 2, N'Explore and Practice'),
        (N'PH-CE-INVEST-EXPL', N'WF-INVEST-01', N'CE-INVEST', 2, N'Explore and Practice'),
        (N'PH-CSA-ORIENT-EXPL', N'WF-ORIENT-01', N'CSA-ORIENT', 2, N'Explore and Practice'),
        (N'PH-CSA-PIPE-EXPL', N'WF-X-CONSUME-01', N'CSA-PIPE', 2, N'Explore and Practice'),
        (N'PH-CSA-CONV-EXPL', N'WF-X-CONV-01', N'CSA-CONV', 2, N'Explore and Practice'),
        (N'PH-CSA-ARCH-1-EXPL', N'WF-X-ARCH-01', N'CSA-ARCH-1', 2, N'Explore and Practice'),
        (N'PH-CSA-ARCH-2-EXPL', N'WF-X-ARCH-01', N'CSA-ARCH-2', 2, N'Explore and Practice'),
        (N'PH-CSA-HEALTH-EXPL', N'WF-X-HEALTH-01', N'CSA-HEALTH', 2, N'Explore and Practice'),
        (N'PH-CSA-VALUE-1-EXPL', N'WF-X-VALUE-01', N'CSA-VALUE-1', 2, N'Explore and Practice'),
        (N'PH-CSA-VALUE-2-EXPL', N'WF-X-VALUE-01', N'CSA-VALUE-2', 2, N'Explore and Practice'),
        (N'PH-CSA-INVEST-EXPL', N'WF-INVEST-01', N'CSA-INVEST', 2, N'Explore and Practice'),
        (N'PH-CSAM-ORIENT-EXPL', N'WF-ORIENT-01', N'CSAM-ORIENT', 2, N'Explore and Practice'),
        (N'PH-CSAM-SPLAN-EXPL', N'WF-X-PLAN-01', N'CSAM-SPLAN', 2, N'Explore and Practice'),
        (N'PH-CSAM-HEALTH-EXPL', N'WF-X-HEALTH-01', N'CSAM-HEALTH', 2, N'Explore and Practice'),
        (N'PH-ALL-USECASE-EXPL', N'WF-X-USECASE-01', N'ALL-USECASE', 2, N'Explore and Practice'),
        (N'PH-CSAM-EXEC-EXPL', N'WF-X-CONV-01', N'CSAM-EXEC', 2, N'Explore and Practice'),
        (N'PH-CSAM-ORCH-EXPL', N'WF-X-ORCH-01', N'CSAM-ORCH', 2, N'Explore and Practice'),
        (N'PH-CSAM-VALUE-EXPL', N'WF-X-VALUE-01', N'CSAM-VALUE', 2, N'Explore and Practice'),
        (N'PH-CSAM-RENEW-EXPL', N'WF-X-RENEW-01', N'CSAM-RENEW', 2, N'Explore and Practice'),
        (N'PH-CSAM-ESCALATE-EXPL', N'WF-X-HEALTH-01', N'CSAM-ESCALATE', 2, N'Explore and Practice'),
        (N'PH-CSAM-INVEST-EXPL', N'WF-INVEST-01', N'CSAM-INVEST', 2, N'Explore and Practice'),
        (N'PH-ALL-DEAL-EXPL', N'WF-X-DEAL-01', N'ALL-DEAL', 2, N'Explore and Practice'),
        (N'PH-AE-HEALTH-EXPL', N'WF-X-HEALTH-01', N'AE-HEALTH', 2, N'Explore and Practice'),
        (N'PH-ALL-TRANSITION-EXPL', N'WF-X-TRANSITION-01', N'ALL-TRANSITION', 2, N'Explore and Practice'),
        (N'PH-ALL-HANDOFF-EXPL', N'WF-X-HANDOFF-01', N'ALL-HANDOFF', 2, N'Explore and Practice'),
        (N'PH-ATS-CONSUME-EXPL', N'WF-X-CONSUME-01', N'ATS-CONSUME', 2, N'Explore and Practice'),
        (N'PH-ALL-SPONSOR-EXPL', N'WF-X-SPONSOR-01', N'ALL-SPONSOR', 2, N'Explore and Practice'),
        (N'PH-ALL-FYPLAN-EXPL', N'WF-X-FYPLAN-01', N'ALL-FYPLAN', 2, N'Explore and Practice'),
        (N'PH-ALL-ASSET-EXPL', N'WF-X-ASSET-01', N'ALL-ASSET', 2, N'Explore and Practice'),
        (N'PH-CSAM-CONSUME-EXPL', N'WF-X-CONSUME-01', N'CSAM-CONSUME', 2, N'Explore and Practice'),
        (N'PH-SSP-CONSUME-EXPL', N'WF-X-CONSUME-01', N'SSP-CONSUME', 2, N'Explore and Practice'),
        (N'PH-SE-CONSUME-EXPL', N'WF-X-CONSUME-01', N'SE-CONSUME', 2, N'Explore and Practice'),
        (N'PH-ALL-CLOSE-EXPL', N'WF-X-CLOSE-01', N'ALL-CLOSE', 2, N'Explore and Practice'),
        (N'PH-DAE-SIGNAL-EXPL', N'WF-X-SIGNAL-01', N'DAE-SIGNAL', 2, N'Explore and Practice'),
        (N'PH-DSS-SIGNAL-EXPL', N'WF-X-SIGNAL-01', N'DSS-SIGNAL', 2, N'Explore and Practice'),
        (N'PH-DAE-PARTNER-EXPL', N'WF-X-PARTNER-01', N'DAE-PARTNER', 2, N'Explore and Practice'),
        (N'PH-PSS-PARTNER-EXPL', N'WF-X-PARTNER-01', N'PSS-PARTNER', 2, N'Explore and Practice'),
        (N'PH-DCSA-CONSUME-EXPL', N'WF-X-CONSUME-01', N'DCSA-CONSUME', 2, N'Explore and Practice'),
        (N'PH-DSE-ARCH-EXPL', N'WF-X-ARCH-01', N'DSE-ARCH', 2, N'Explore and Practice'),
        (N'PH-DAE-TERRITORY-EXPL', N'WF-X-TERRITORY-01', N'DAE-TERRITORY', 2, N'Explore and Practice'),
        (N'PH-DSS-TERRITORY-EXPL', N'WF-X-TERRITORY-01', N'DSS-TERRITORY', 2, N'Explore and Practice'),
        (N'PH-PSS-JOINTPLAN-EXPL', N'WF-X-TERRITORY-01', N'PSS-JOINTPLAN', 2, N'Explore and Practice'),
        (N'PH-DAE-ORIENT-EXPL', N'WF-ORIENT-01', N'DAE-ORIENT', 2, N'Explore and Practice'),
        (N'PH-DAE-CONV-EXPL', N'WF-X-CONV-01', N'DAE-CONV', 2, N'Explore and Practice'),
        (N'PH-DAE-DEAL-EXPL', N'WF-X-DEAL-01', N'DAE-DEAL', 2, N'Explore and Practice'),
        (N'PH-DAE-RENEW-EXPL', N'WF-X-RENEW-01', N'DAE-RENEW', 2, N'Explore and Practice'),
        (N'PH-DAE-HEALTH-EXPL', N'WF-X-HEALTH-01', N'DAE-HEALTH', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-ORIENT-EXPL', N'WF-ORIENT-01', N'SMEC-CE-ORIENT', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-RENEW-EXPL', N'WF-X-RENEW-01', N'SMEC-CE-RENEW', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-DEAL-EXPL', N'WF-X-DEAL-01', N'SMEC-CE-DEAL', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-HEALTH-EXPL', N'WF-X-HEALTH-01', N'SMEC-CE-HEALTH', 2, N'Explore and Practice'),
        (N'PH-DSS-ORIENT-EXPL', N'WF-ORIENT-01', N'DSS-ORIENT', 2, N'Explore and Practice'),
        (N'PH-DSS-CONV-EXPL', N'WF-X-CONV-01', N'DSS-CONV', 2, N'Explore and Practice'),
        (N'PH-DSS-DEAL-EXPL', N'WF-X-DEAL-01', N'DSS-DEAL', 2, N'Explore and Practice'),
        (N'PH-DSS-VALUE-EXPL', N'WF-X-VALUE-01', N'DSS-VALUE', 2, N'Explore and Practice'),
        (N'PH-AE-ORIENT-COMMIT', N'WF-ORIENT-01', N'AE-ORIENT', 3, N'Commit to Action'),
        (N'PH-AE-PLAN-COMMIT', N'WF-X-PLAN-01', N'AE-PLAN', 3, N'Commit to Action'),
        (N'PH-AE-PIPE-1-COMMIT', N'WF-X-PIPE-01', N'AE-PIPE-1', 3, N'Commit to Action'),
        (N'PH-AE-PIPE-2-COMMIT', N'WF-X-PIPE-01', N'AE-PIPE-2', 3, N'Commit to Action'),
        (N'PH-AE-OPP-COMMIT', N'WF-X-OPP-01', N'AE-OPP', 3, N'Commit to Action'),
        (N'PH-AE-CONV-COMMIT', N'WF-X-CONV-01', N'AE-CONV', 3, N'Commit to Action'),
        (N'PH-AE-DEAL-COMMIT', N'WF-X-DEAL-01', N'AE-DEAL', 3, N'Commit to Action'),
        (N'PH-AE-RENEW-COMMIT', N'WF-X-RENEW-01', N'AE-RENEW', 3, N'Commit to Action'),
        (N'PH-AE-INVEST-COMMIT', N'WF-INVEST-01', N'AE-INVEST', 3, N'Commit to Action'),
        (N'PH-AE-ORCH-COMMIT', N'WF-X-ORCH-01', N'AE-ORCH', 3, N'Commit to Action'),
        (N'PH-AE-VALUE-COMMIT', N'WF-X-VALUE-01', N'AE-VALUE', 3, N'Commit to Action'),
        (N'PH-ATS-ORIENT-COMMIT', N'WF-ORIENT-01', N'ATS-ORIENT', 3, N'Commit to Action'),
        (N'PH-ATS-INTEL-COMMIT', N'WF-X-PLAN-01', N'ATS-INTEL', 3, N'Commit to Action'),
        (N'PH-ATS-NARR-COMMIT', N'WF-X-CONV-01', N'ATS-NARR', 3, N'Commit to Action'),
        (N'PH-ATS-WORKLOAD-COMMIT', N'WF-X-PLAN-01', N'ATS-WORKLOAD', 3, N'Commit to Action'),
        (N'PH-ATS-TECH-COMMIT', N'WF-X-ARCH-01', N'ATS-TECH', 3, N'Commit to Action'),
        (N'PH-ATS-EBC-COMMIT', N'WF-X-CONV-01', N'ATS-EBC', 3, N'Commit to Action'),
        (N'PH-ATS-TALK-COMMIT', N'WF-X-CONV-01', N'ATS-TALK', 3, N'Commit to Action'),
        (N'PH-ATS-TEAM-COMMIT', N'WF-X-ORCH-01', N'ATS-TEAM', 3, N'Commit to Action'),
        (N'PH-ATS-INVEST-COMMIT', N'WF-INVEST-01', N'ATS-INVEST', 3, N'Commit to Action'),
        (N'PH-ATS-CBR-COMMIT', N'WF-X-VALUE-01', N'ATS-CBR', 3, N'Commit to Action'),
        (N'PH-ATS-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'ATS-HEALTH', 3, N'Commit to Action'),
        (N'PH-ATS-PARTNER-COMMIT', N'WF-X-ORCH-01', N'ATS-PARTNER', 3, N'Commit to Action'),
        (N'PH-SSP-ORIENT-COMMIT', N'WF-ORIENT-01', N'SSP-ORIENT', 3, N'Commit to Action'),
        (N'PH-SSP-LEAD-COMMIT', N'WF-X-OPP-01', N'SSP-LEAD', 3, N'Commit to Action'),
        (N'PH-SSP-PLAN-COMMIT', N'WF-X-PLAN-01', N'SSP-PLAN', 3, N'Commit to Action'),
        (N'PH-SSP-VALUE-COMMIT', N'WF-X-VALUE-01', N'SSP-VALUE', 3, N'Commit to Action'),
        (N'PH-SSP-CONV-COMMIT', N'WF-X-CONV-01', N'SSP-CONV', 3, N'Commit to Action'),
        (N'PH-SSP-ORCH-COMMIT', N'WF-X-ORCH-01', N'SSP-ORCH', 3, N'Commit to Action'),
        (N'PH-SSP-COMP-COMMIT', N'WF-X-DEAL-01', N'SSP-COMP', 3, N'Commit to Action'),
        (N'PH-SSP-DEAL-COMMIT', N'WF-X-DEAL-01', N'SSP-DEAL', 3, N'Commit to Action'),
        (N'PH-SSP-INVEST-COMMIT', N'WF-INVEST-01', N'SSP-INVEST', 3, N'Commit to Action'),
        (N'PH-SE-ORIENT-COMMIT', N'WF-ORIENT-01', N'SE-ORIENT', 3, N'Commit to Action'),
        (N'PH-SE-CONV-COMMIT', N'WF-X-CONV-01', N'SE-CONV', 3, N'Commit to Action'),
        (N'PH-SE-ARCH-1-COMMIT', N'WF-X-ARCH-01', N'SE-ARCH-1', 3, N'Commit to Action'),
        (N'PH-SE-ARCH-2-COMMIT', N'WF-X-ARCH-01', N'SE-ARCH-2', 3, N'Commit to Action'),
        (N'PH-SE-ARCH-3-COMMIT', N'WF-X-ARCH-01', N'SE-ARCH-3', 3, N'Commit to Action'),
        (N'PH-SE-DISC-COMMIT', N'WF-X-DISC-01', N'SE-DISC', 3, N'Commit to Action'),
        (N'PH-SE-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'SE-HEALTH', 3, N'Commit to Action'),
        (N'PH-SE-ASSET-COMMIT', N'WF-X-ASSET-01', N'SE-ASSET', 3, N'Commit to Action'),
        (N'PH-SE-INVEST-COMMIT', N'WF-INVEST-01', N'SE-INVEST', 3, N'Commit to Action'),
        (N'PH-CE-ORIENT-COMMIT', N'WF-ORIENT-01', N'CE-ORIENT', 3, N'Commit to Action'),
        (N'PH-CE-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'CE-HEALTH', 3, N'Commit to Action'),
        (N'PH-CE-DEAL-1-COMMIT', N'WF-X-DEAL-01', N'CE-DEAL-1', 3, N'Commit to Action'),
        (N'PH-CE-DEAL-2-COMMIT', N'WF-X-DEAL-01', N'CE-DEAL-2', 3, N'Commit to Action'),
        (N'PH-CE-DEAL-3-COMMIT', N'WF-X-DEAL-01', N'CE-DEAL-3', 3, N'Commit to Action'),
        (N'PH-CE-ORCH-COMMIT', N'WF-X-ORCH-01', N'CE-ORCH', 3, N'Commit to Action'),
        (N'PH-CE-RENEW-COMMIT', N'WF-X-RENEW-01', N'CE-RENEW', 3, N'Commit to Action'),
        (N'PH-CE-POLICY-COMMIT', N'WF-X-POLICY-01', N'CE-POLICY', 3, N'Commit to Action'),
        (N'PH-CE-INVEST-COMMIT', N'WF-INVEST-01', N'CE-INVEST', 3, N'Commit to Action'),
        (N'PH-CSA-ORIENT-COMMIT', N'WF-ORIENT-01', N'CSA-ORIENT', 3, N'Commit to Action'),
        (N'PH-CSA-PIPE-COMMIT', N'WF-X-CONSUME-01', N'CSA-PIPE', 3, N'Commit to Action'),
        (N'PH-CSA-CONV-COMMIT', N'WF-X-CONV-01', N'CSA-CONV', 3, N'Commit to Action'),
        (N'PH-CSA-ARCH-1-COMMIT', N'WF-X-ARCH-01', N'CSA-ARCH-1', 3, N'Commit to Action'),
        (N'PH-CSA-ARCH-2-COMMIT', N'WF-X-ARCH-01', N'CSA-ARCH-2', 3, N'Commit to Action'),
        (N'PH-CSA-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'CSA-HEALTH', 3, N'Commit to Action'),
        (N'PH-CSA-VALUE-1-COMMIT', N'WF-X-VALUE-01', N'CSA-VALUE-1', 3, N'Commit to Action'),
        (N'PH-CSA-VALUE-2-COMMIT', N'WF-X-VALUE-01', N'CSA-VALUE-2', 3, N'Commit to Action'),
        (N'PH-CSA-INVEST-COMMIT', N'WF-INVEST-01', N'CSA-INVEST', 3, N'Commit to Action'),
        (N'PH-CSAM-ORIENT-COMMIT', N'WF-ORIENT-01', N'CSAM-ORIENT', 3, N'Commit to Action'),
        (N'PH-CSAM-SPLAN-COMMIT', N'WF-X-PLAN-01', N'CSAM-SPLAN', 3, N'Commit to Action'),
        (N'PH-CSAM-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'CSAM-HEALTH', 3, N'Commit to Action'),
        (N'PH-ALL-USECASE-COMMIT', N'WF-X-USECASE-01', N'ALL-USECASE', 3, N'Commit to Action'),
        (N'PH-CSAM-EXEC-COMMIT', N'WF-X-CONV-01', N'CSAM-EXEC', 3, N'Commit to Action'),
        (N'PH-CSAM-ORCH-COMMIT', N'WF-X-ORCH-01', N'CSAM-ORCH', 3, N'Commit to Action'),
        (N'PH-CSAM-VALUE-COMMIT', N'WF-X-VALUE-01', N'CSAM-VALUE', 3, N'Commit to Action'),
        (N'PH-CSAM-RENEW-COMMIT', N'WF-X-RENEW-01', N'CSAM-RENEW', 3, N'Commit to Action'),
        (N'PH-CSAM-ESCALATE-COMMIT', N'WF-X-HEALTH-01', N'CSAM-ESCALATE', 3, N'Commit to Action'),
        (N'PH-CSAM-INVEST-COMMIT', N'WF-INVEST-01', N'CSAM-INVEST', 3, N'Commit to Action'),
        (N'PH-ALL-DEAL-COMMIT', N'WF-X-DEAL-01', N'ALL-DEAL', 3, N'Commit to Action'),
        (N'PH-AE-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'AE-HEALTH', 3, N'Commit to Action'),
        (N'PH-ALL-TRANSITION-COMMIT', N'WF-X-TRANSITION-01', N'ALL-TRANSITION', 3, N'Commit to Action'),
        (N'PH-ALL-HANDOFF-COMMIT', N'WF-X-HANDOFF-01', N'ALL-HANDOFF', 3, N'Commit to Action'),
        (N'PH-ATS-CONSUME-COMMIT', N'WF-X-CONSUME-01', N'ATS-CONSUME', 3, N'Commit to Action'),
        (N'PH-ALL-SPONSOR-COMMIT', N'WF-X-SPONSOR-01', N'ALL-SPONSOR', 3, N'Commit to Action'),
        (N'PH-ALL-FYPLAN-COMMIT', N'WF-X-FYPLAN-01', N'ALL-FYPLAN', 3, N'Commit to Action'),
        (N'PH-ALL-ASSET-COMMIT', N'WF-X-ASSET-01', N'ALL-ASSET', 3, N'Commit to Action'),
        (N'PH-CSAM-CONSUME-COMMIT', N'WF-X-CONSUME-01', N'CSAM-CONSUME', 3, N'Commit to Action'),
        (N'PH-SSP-CONSUME-COMMIT', N'WF-X-CONSUME-01', N'SSP-CONSUME', 3, N'Commit to Action'),
        (N'PH-SE-CONSUME-COMMIT', N'WF-X-CONSUME-01', N'SE-CONSUME', 3, N'Commit to Action'),
        (N'PH-ALL-CLOSE-COMMIT', N'WF-X-CLOSE-01', N'ALL-CLOSE', 3, N'Commit to Action'),
        (N'PH-DAE-SIGNAL-COMMIT', N'WF-X-SIGNAL-01', N'DAE-SIGNAL', 3, N'Commit to Action'),
        (N'PH-DSS-SIGNAL-COMMIT', N'WF-X-SIGNAL-01', N'DSS-SIGNAL', 3, N'Commit to Action'),
        (N'PH-DAE-PARTNER-COMMIT', N'WF-X-PARTNER-01', N'DAE-PARTNER', 3, N'Commit to Action'),
        (N'PH-PSS-PARTNER-COMMIT', N'WF-X-PARTNER-01', N'PSS-PARTNER', 3, N'Commit to Action'),
        (N'PH-DCSA-CONSUME-COMMIT', N'WF-X-CONSUME-01', N'DCSA-CONSUME', 3, N'Commit to Action'),
        (N'PH-DSE-ARCH-COMMIT', N'WF-X-ARCH-01', N'DSE-ARCH', 3, N'Commit to Action'),
        (N'PH-DAE-TERRITORY-COMMIT', N'WF-X-TERRITORY-01', N'DAE-TERRITORY', 3, N'Commit to Action'),
        (N'PH-DSS-TERRITORY-COMMIT', N'WF-X-TERRITORY-01', N'DSS-TERRITORY', 3, N'Commit to Action'),
        (N'PH-PSS-JOINTPLAN-COMMIT', N'WF-X-TERRITORY-01', N'PSS-JOINTPLAN', 3, N'Commit to Action'),
        (N'PH-DAE-ORIENT-COMMIT', N'WF-ORIENT-01', N'DAE-ORIENT', 3, N'Commit to Action'),
        (N'PH-DAE-CONV-COMMIT', N'WF-X-CONV-01', N'DAE-CONV', 3, N'Commit to Action'),
        (N'PH-DAE-DEAL-COMMIT', N'WF-X-DEAL-01', N'DAE-DEAL', 3, N'Commit to Action'),
        (N'PH-DAE-RENEW-COMMIT', N'WF-X-RENEW-01', N'DAE-RENEW', 3, N'Commit to Action'),
        (N'PH-DAE-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'DAE-HEALTH', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-ORIENT-COMMIT', N'WF-ORIENT-01', N'SMEC-CE-ORIENT', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-RENEW-COMMIT', N'WF-X-RENEW-01', N'SMEC-CE-RENEW', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-DEAL-COMMIT', N'WF-X-DEAL-01', N'SMEC-CE-DEAL', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'SMEC-CE-HEALTH', 3, N'Commit to Action'),
        (N'PH-DSS-ORIENT-COMMIT', N'WF-ORIENT-01', N'DSS-ORIENT', 3, N'Commit to Action'),
        (N'PH-DSS-CONV-COMMIT', N'WF-X-CONV-01', N'DSS-CONV', 3, N'Commit to Action'),
        (N'PH-DSS-DEAL-COMMIT', N'WF-X-DEAL-01', N'DSS-DEAL', 3, N'Commit to Action'),
        (N'PH-DSS-VALUE-COMMIT', N'WF-X-VALUE-01', N'DSS-VALUE', 3, N'Commit to Action')
    ) v([ExternalId], [TopicExternalId], [PlacementExternalId], [DisplayOrder], [Name])
), src AS (
    SELECT raw.*, t.Id AS [HuddleTopicId], p.Id AS [HuddlePlacementId]
    FROM raw
    INNER JOIN dbo.HuddleTopics AS t ON t.[ExternalId] = raw.[TopicExternalId]
    INNER JOIN dbo.HuddlePlacements AS p ON p.[ExternalId] = raw.[PlacementExternalId]
)
MERGE dbo.HuddlePhases AS tgt
USING src ON tgt.[ExternalId] = src.[ExternalId]
WHEN MATCHED THEN UPDATE SET
        tgt.[HuddleTopicId] = src.[HuddleTopicId],
        tgt.[HuddlePlacementId] = src.[HuddlePlacementId],
        tgt.[DisplayOrder] = src.[DisplayOrder],
        tgt.[Name] = src.[Name],
        tgt.[UpdatedAtUtc] = SYSUTCDATETIME()
WHEN NOT MATCHED BY TARGET THEN INSERT ([ExternalId], [HuddleTopicId], [HuddlePlacementId], [DisplayOrder], [Name], [CreatedAtUtc])
    VALUES (src.[ExternalId], src.[HuddleTopicId], src.[HuddlePlacementId], src.[DisplayOrder], src.[Name], SYSUTCDATETIME());
;WITH raw AS (
    SELECT * FROM (VALUES
        (N'PH-AE-ORIENT-PREP', N'WF-ORIENT-01', N'AE-ORIENT', 1, N'Preparation'),
        (N'PH-AE-PLAN-PREP', N'WF-X-PLAN-01', N'AE-PLAN', 1, N'Preparation'),
        (N'PH-AE-PIPE-1-PREP', N'WF-X-PIPE-01', N'AE-PIPE-1', 1, N'Preparation'),
        (N'PH-AE-PIPE-2-PREP', N'WF-X-PIPE-01', N'AE-PIPE-2', 1, N'Preparation'),
        (N'PH-AE-OPP-PREP', N'WF-X-OPP-01', N'AE-OPP', 1, N'Preparation'),
        (N'PH-AE-CONV-PREP', N'WF-X-CONV-01', N'AE-CONV', 1, N'Preparation'),
        (N'PH-AE-DEAL-PREP', N'WF-X-DEAL-01', N'AE-DEAL', 1, N'Preparation'),
        (N'PH-AE-RENEW-PREP', N'WF-X-RENEW-01', N'AE-RENEW', 1, N'Preparation'),
        (N'PH-AE-INVEST-PREP', N'WF-INVEST-01', N'AE-INVEST', 1, N'Preparation'),
        (N'PH-AE-ORCH-PREP', N'WF-X-ORCH-01', N'AE-ORCH', 1, N'Preparation'),
        (N'PH-AE-VALUE-PREP', N'WF-X-VALUE-01', N'AE-VALUE', 1, N'Preparation'),
        (N'PH-ATS-ORIENT-PREP', N'WF-ORIENT-01', N'ATS-ORIENT', 1, N'Preparation'),
        (N'PH-ATS-INTEL-PREP', N'WF-X-PLAN-01', N'ATS-INTEL', 1, N'Preparation'),
        (N'PH-ATS-NARR-PREP', N'WF-X-CONV-01', N'ATS-NARR', 1, N'Preparation'),
        (N'PH-ATS-WORKLOAD-PREP', N'WF-X-PLAN-01', N'ATS-WORKLOAD', 1, N'Preparation'),
        (N'PH-ATS-TECH-PREP', N'WF-X-ARCH-01', N'ATS-TECH', 1, N'Preparation'),
        (N'PH-ATS-EBC-PREP', N'WF-X-CONV-01', N'ATS-EBC', 1, N'Preparation'),
        (N'PH-ATS-TALK-PREP', N'WF-X-CONV-01', N'ATS-TALK', 1, N'Preparation'),
        (N'PH-ATS-TEAM-PREP', N'WF-X-ORCH-01', N'ATS-TEAM', 1, N'Preparation'),
        (N'PH-ATS-INVEST-PREP', N'WF-INVEST-01', N'ATS-INVEST', 1, N'Preparation'),
        (N'PH-ATS-CBR-PREP', N'WF-X-VALUE-01', N'ATS-CBR', 1, N'Preparation'),
        (N'PH-ATS-HEALTH-PREP', N'WF-X-HEALTH-01', N'ATS-HEALTH', 1, N'Preparation'),
        (N'PH-ATS-PARTNER-PREP', N'WF-X-ORCH-01', N'ATS-PARTNER', 1, N'Preparation'),
        (N'PH-SSP-ORIENT-PREP', N'WF-ORIENT-01', N'SSP-ORIENT', 1, N'Preparation'),
        (N'PH-SSP-LEAD-PREP', N'WF-X-OPP-01', N'SSP-LEAD', 1, N'Preparation'),
        (N'PH-SSP-PLAN-PREP', N'WF-X-PLAN-01', N'SSP-PLAN', 1, N'Preparation'),
        (N'PH-SSP-VALUE-PREP', N'WF-X-VALUE-01', N'SSP-VALUE', 1, N'Preparation'),
        (N'PH-SSP-CONV-PREP', N'WF-X-CONV-01', N'SSP-CONV', 1, N'Preparation'),
        (N'PH-SSP-ORCH-PREP', N'WF-X-ORCH-01', N'SSP-ORCH', 1, N'Preparation'),
        (N'PH-SSP-COMP-PREP', N'WF-X-DEAL-01', N'SSP-COMP', 1, N'Preparation'),
        (N'PH-SSP-DEAL-PREP', N'WF-X-DEAL-01', N'SSP-DEAL', 1, N'Preparation'),
        (N'PH-SSP-INVEST-PREP', N'WF-INVEST-01', N'SSP-INVEST', 1, N'Preparation'),
        (N'PH-SE-ORIENT-PREP', N'WF-ORIENT-01', N'SE-ORIENT', 1, N'Preparation'),
        (N'PH-SE-CONV-PREP', N'WF-X-CONV-01', N'SE-CONV', 1, N'Preparation'),
        (N'PH-SE-ARCH-1-PREP', N'WF-X-ARCH-01', N'SE-ARCH-1', 1, N'Preparation'),
        (N'PH-SE-ARCH-2-PREP', N'WF-X-ARCH-01', N'SE-ARCH-2', 1, N'Preparation'),
        (N'PH-SE-ARCH-3-PREP', N'WF-X-ARCH-01', N'SE-ARCH-3', 1, N'Preparation'),
        (N'PH-SE-DISC-PREP', N'WF-X-DISC-01', N'SE-DISC', 1, N'Preparation'),
        (N'PH-SE-HEALTH-PREP', N'WF-X-HEALTH-01', N'SE-HEALTH', 1, N'Preparation'),
        (N'PH-SE-ASSET-PREP', N'WF-X-ASSET-01', N'SE-ASSET', 1, N'Preparation'),
        (N'PH-SE-INVEST-PREP', N'WF-INVEST-01', N'SE-INVEST', 1, N'Preparation'),
        (N'PH-CE-ORIENT-PREP', N'WF-ORIENT-01', N'CE-ORIENT', 1, N'Preparation'),
        (N'PH-CE-HEALTH-PREP', N'WF-X-HEALTH-01', N'CE-HEALTH', 1, N'Preparation'),
        (N'PH-CE-DEAL-1-PREP', N'WF-X-DEAL-01', N'CE-DEAL-1', 1, N'Preparation'),
        (N'PH-CE-DEAL-2-PREP', N'WF-X-DEAL-01', N'CE-DEAL-2', 1, N'Preparation'),
        (N'PH-CE-DEAL-3-PREP', N'WF-X-DEAL-01', N'CE-DEAL-3', 1, N'Preparation'),
        (N'PH-CE-ORCH-PREP', N'WF-X-ORCH-01', N'CE-ORCH', 1, N'Preparation'),
        (N'PH-CE-RENEW-PREP', N'WF-X-RENEW-01', N'CE-RENEW', 1, N'Preparation'),
        (N'PH-CE-POLICY-PREP', N'WF-X-POLICY-01', N'CE-POLICY', 1, N'Preparation'),
        (N'PH-CE-INVEST-PREP', N'WF-INVEST-01', N'CE-INVEST', 1, N'Preparation'),
        (N'PH-CSA-ORIENT-PREP', N'WF-ORIENT-01', N'CSA-ORIENT', 1, N'Preparation'),
        (N'PH-CSA-PIPE-PREP', N'WF-X-CONSUME-01', N'CSA-PIPE', 1, N'Preparation'),
        (N'PH-CSA-CONV-PREP', N'WF-X-CONV-01', N'CSA-CONV', 1, N'Preparation'),
        (N'PH-CSA-ARCH-1-PREP', N'WF-X-ARCH-01', N'CSA-ARCH-1', 1, N'Preparation'),
        (N'PH-CSA-ARCH-2-PREP', N'WF-X-ARCH-01', N'CSA-ARCH-2', 1, N'Preparation'),
        (N'PH-CSA-HEALTH-PREP', N'WF-X-HEALTH-01', N'CSA-HEALTH', 1, N'Preparation'),
        (N'PH-CSA-VALUE-1-PREP', N'WF-X-VALUE-01', N'CSA-VALUE-1', 1, N'Preparation'),
        (N'PH-CSA-VALUE-2-PREP', N'WF-X-VALUE-01', N'CSA-VALUE-2', 1, N'Preparation'),
        (N'PH-CSA-INVEST-PREP', N'WF-INVEST-01', N'CSA-INVEST', 1, N'Preparation'),
        (N'PH-CSAM-ORIENT-PREP', N'WF-ORIENT-01', N'CSAM-ORIENT', 1, N'Preparation'),
        (N'PH-CSAM-SPLAN-PREP', N'WF-X-PLAN-01', N'CSAM-SPLAN', 1, N'Preparation'),
        (N'PH-CSAM-HEALTH-PREP', N'WF-X-HEALTH-01', N'CSAM-HEALTH', 1, N'Preparation'),
        (N'PH-ALL-USECASE-PREP', N'WF-X-USECASE-01', N'ALL-USECASE', 1, N'Preparation'),
        (N'PH-CSAM-EXEC-PREP', N'WF-X-CONV-01', N'CSAM-EXEC', 1, N'Preparation'),
        (N'PH-CSAM-ORCH-PREP', N'WF-X-ORCH-01', N'CSAM-ORCH', 1, N'Preparation'),
        (N'PH-CSAM-VALUE-PREP', N'WF-X-VALUE-01', N'CSAM-VALUE', 1, N'Preparation'),
        (N'PH-CSAM-RENEW-PREP', N'WF-X-RENEW-01', N'CSAM-RENEW', 1, N'Preparation'),
        (N'PH-CSAM-ESCALATE-PREP', N'WF-X-HEALTH-01', N'CSAM-ESCALATE', 1, N'Preparation'),
        (N'PH-CSAM-INVEST-PREP', N'WF-INVEST-01', N'CSAM-INVEST', 1, N'Preparation'),
        (N'PH-ALL-DEAL-PREP', N'WF-X-DEAL-01', N'ALL-DEAL', 1, N'Preparation'),
        (N'PH-AE-HEALTH-PREP', N'WF-X-HEALTH-01', N'AE-HEALTH', 1, N'Preparation'),
        (N'PH-ALL-TRANSITION-PREP', N'WF-X-TRANSITION-01', N'ALL-TRANSITION', 1, N'Preparation'),
        (N'PH-ALL-HANDOFF-PREP', N'WF-X-HANDOFF-01', N'ALL-HANDOFF', 1, N'Preparation'),
        (N'PH-ATS-CONSUME-PREP', N'WF-X-CONSUME-01', N'ATS-CONSUME', 1, N'Preparation'),
        (N'PH-ALL-SPONSOR-PREP', N'WF-X-SPONSOR-01', N'ALL-SPONSOR', 1, N'Preparation'),
        (N'PH-ALL-FYPLAN-PREP', N'WF-X-FYPLAN-01', N'ALL-FYPLAN', 1, N'Preparation'),
        (N'PH-ALL-ASSET-PREP', N'WF-X-ASSET-01', N'ALL-ASSET', 1, N'Preparation'),
        (N'PH-CSAM-CONSUME-PREP', N'WF-X-CONSUME-01', N'CSAM-CONSUME', 1, N'Preparation'),
        (N'PH-SSP-CONSUME-PREP', N'WF-X-CONSUME-01', N'SSP-CONSUME', 1, N'Preparation'),
        (N'PH-SE-CONSUME-PREP', N'WF-X-CONSUME-01', N'SE-CONSUME', 1, N'Preparation'),
        (N'PH-ALL-CLOSE-PREP', N'WF-X-CLOSE-01', N'ALL-CLOSE', 1, N'Preparation'),
        (N'PH-DAE-SIGNAL-PREP', N'WF-X-SIGNAL-01', N'DAE-SIGNAL', 1, N'Preparation'),
        (N'PH-DSS-SIGNAL-PREP', N'WF-X-SIGNAL-01', N'DSS-SIGNAL', 1, N'Preparation'),
        (N'PH-DAE-PARTNER-PREP', N'WF-X-PARTNER-01', N'DAE-PARTNER', 1, N'Preparation'),
        (N'PH-PSS-PARTNER-PREP', N'WF-X-PARTNER-01', N'PSS-PARTNER', 1, N'Preparation'),
        (N'PH-DCSA-CONSUME-PREP', N'WF-X-CONSUME-01', N'DCSA-CONSUME', 1, N'Preparation'),
        (N'PH-DSE-ARCH-PREP', N'WF-X-ARCH-01', N'DSE-ARCH', 1, N'Preparation'),
        (N'PH-DAE-TERRITORY-PREP', N'WF-X-TERRITORY-01', N'DAE-TERRITORY', 1, N'Preparation'),
        (N'PH-DSS-TERRITORY-PREP', N'WF-X-TERRITORY-01', N'DSS-TERRITORY', 1, N'Preparation'),
        (N'PH-PSS-JOINTPLAN-PREP', N'WF-X-TERRITORY-01', N'PSS-JOINTPLAN', 1, N'Preparation'),
        (N'PH-DAE-ORIENT-PREP', N'WF-ORIENT-01', N'DAE-ORIENT', 1, N'Preparation'),
        (N'PH-DAE-CONV-PREP', N'WF-X-CONV-01', N'DAE-CONV', 1, N'Preparation'),
        (N'PH-DAE-DEAL-PREP', N'WF-X-DEAL-01', N'DAE-DEAL', 1, N'Preparation'),
        (N'PH-DAE-RENEW-PREP', N'WF-X-RENEW-01', N'DAE-RENEW', 1, N'Preparation'),
        (N'PH-DAE-HEALTH-PREP', N'WF-X-HEALTH-01', N'DAE-HEALTH', 1, N'Preparation'),
        (N'PH-SMEC-CE-ORIENT-PREP', N'WF-ORIENT-01', N'SMEC-CE-ORIENT', 1, N'Preparation'),
        (N'PH-SMEC-CE-RENEW-PREP', N'WF-X-RENEW-01', N'SMEC-CE-RENEW', 1, N'Preparation'),
        (N'PH-SMEC-CE-DEAL-PREP', N'WF-X-DEAL-01', N'SMEC-CE-DEAL', 1, N'Preparation'),
        (N'PH-SMEC-CE-HEALTH-PREP', N'WF-X-HEALTH-01', N'SMEC-CE-HEALTH', 1, N'Preparation'),
        (N'PH-DSS-ORIENT-PREP', N'WF-ORIENT-01', N'DSS-ORIENT', 1, N'Preparation'),
        (N'PH-DSS-CONV-PREP', N'WF-X-CONV-01', N'DSS-CONV', 1, N'Preparation'),
        (N'PH-DSS-DEAL-PREP', N'WF-X-DEAL-01', N'DSS-DEAL', 1, N'Preparation'),
        (N'PH-DSS-VALUE-PREP', N'WF-X-VALUE-01', N'DSS-VALUE', 1, N'Preparation'),
        (N'PH-AE-ORIENT-EXPL', N'WF-ORIENT-01', N'AE-ORIENT', 2, N'Explore and Practice'),
        (N'PH-AE-PLAN-EXPL', N'WF-X-PLAN-01', N'AE-PLAN', 2, N'Explore and Practice'),
        (N'PH-AE-PIPE-1-EXPL', N'WF-X-PIPE-01', N'AE-PIPE-1', 2, N'Explore and Practice'),
        (N'PH-AE-PIPE-2-EXPL', N'WF-X-PIPE-01', N'AE-PIPE-2', 2, N'Explore and Practice'),
        (N'PH-AE-OPP-EXPL', N'WF-X-OPP-01', N'AE-OPP', 2, N'Explore and Practice'),
        (N'PH-AE-CONV-EXPL', N'WF-X-CONV-01', N'AE-CONV', 2, N'Explore and Practice'),
        (N'PH-AE-DEAL-EXPL', N'WF-X-DEAL-01', N'AE-DEAL', 2, N'Explore and Practice'),
        (N'PH-AE-RENEW-EXPL', N'WF-X-RENEW-01', N'AE-RENEW', 2, N'Explore and Practice'),
        (N'PH-AE-INVEST-EXPL', N'WF-INVEST-01', N'AE-INVEST', 2, N'Explore and Practice'),
        (N'PH-AE-ORCH-EXPL', N'WF-X-ORCH-01', N'AE-ORCH', 2, N'Explore and Practice'),
        (N'PH-AE-VALUE-EXPL', N'WF-X-VALUE-01', N'AE-VALUE', 2, N'Explore and Practice'),
        (N'PH-ATS-ORIENT-EXPL', N'WF-ORIENT-01', N'ATS-ORIENT', 2, N'Explore and Practice'),
        (N'PH-ATS-INTEL-EXPL', N'WF-X-PLAN-01', N'ATS-INTEL', 2, N'Explore and Practice'),
        (N'PH-ATS-NARR-EXPL', N'WF-X-CONV-01', N'ATS-NARR', 2, N'Explore and Practice'),
        (N'PH-ATS-WORKLOAD-EXPL', N'WF-X-PLAN-01', N'ATS-WORKLOAD', 2, N'Explore and Practice'),
        (N'PH-ATS-TECH-EXPL', N'WF-X-ARCH-01', N'ATS-TECH', 2, N'Explore and Practice'),
        (N'PH-ATS-EBC-EXPL', N'WF-X-CONV-01', N'ATS-EBC', 2, N'Explore and Practice'),
        (N'PH-ATS-TALK-EXPL', N'WF-X-CONV-01', N'ATS-TALK', 2, N'Explore and Practice'),
        (N'PH-ATS-TEAM-EXPL', N'WF-X-ORCH-01', N'ATS-TEAM', 2, N'Explore and Practice'),
        (N'PH-ATS-INVEST-EXPL', N'WF-INVEST-01', N'ATS-INVEST', 2, N'Explore and Practice'),
        (N'PH-ATS-CBR-EXPL', N'WF-X-VALUE-01', N'ATS-CBR', 2, N'Explore and Practice'),
        (N'PH-ATS-HEALTH-EXPL', N'WF-X-HEALTH-01', N'ATS-HEALTH', 2, N'Explore and Practice'),
        (N'PH-ATS-PARTNER-EXPL', N'WF-X-ORCH-01', N'ATS-PARTNER', 2, N'Explore and Practice'),
        (N'PH-SSP-ORIENT-EXPL', N'WF-ORIENT-01', N'SSP-ORIENT', 2, N'Explore and Practice'),
        (N'PH-SSP-LEAD-EXPL', N'WF-X-OPP-01', N'SSP-LEAD', 2, N'Explore and Practice'),
        (N'PH-SSP-PLAN-EXPL', N'WF-X-PLAN-01', N'SSP-PLAN', 2, N'Explore and Practice'),
        (N'PH-SSP-VALUE-EXPL', N'WF-X-VALUE-01', N'SSP-VALUE', 2, N'Explore and Practice'),
        (N'PH-SSP-CONV-EXPL', N'WF-X-CONV-01', N'SSP-CONV', 2, N'Explore and Practice'),
        (N'PH-SSP-ORCH-EXPL', N'WF-X-ORCH-01', N'SSP-ORCH', 2, N'Explore and Practice'),
        (N'PH-SSP-COMP-EXPL', N'WF-X-DEAL-01', N'SSP-COMP', 2, N'Explore and Practice'),
        (N'PH-SSP-DEAL-EXPL', N'WF-X-DEAL-01', N'SSP-DEAL', 2, N'Explore and Practice'),
        (N'PH-SSP-INVEST-EXPL', N'WF-INVEST-01', N'SSP-INVEST', 2, N'Explore and Practice'),
        (N'PH-SE-ORIENT-EXPL', N'WF-ORIENT-01', N'SE-ORIENT', 2, N'Explore and Practice'),
        (N'PH-SE-CONV-EXPL', N'WF-X-CONV-01', N'SE-CONV', 2, N'Explore and Practice'),
        (N'PH-SE-ARCH-1-EXPL', N'WF-X-ARCH-01', N'SE-ARCH-1', 2, N'Explore and Practice'),
        (N'PH-SE-ARCH-2-EXPL', N'WF-X-ARCH-01', N'SE-ARCH-2', 2, N'Explore and Practice'),
        (N'PH-SE-ARCH-3-EXPL', N'WF-X-ARCH-01', N'SE-ARCH-3', 2, N'Explore and Practice'),
        (N'PH-SE-DISC-EXPL', N'WF-X-DISC-01', N'SE-DISC', 2, N'Explore and Practice'),
        (N'PH-SE-HEALTH-EXPL', N'WF-X-HEALTH-01', N'SE-HEALTH', 2, N'Explore and Practice'),
        (N'PH-SE-ASSET-EXPL', N'WF-X-ASSET-01', N'SE-ASSET', 2, N'Explore and Practice'),
        (N'PH-SE-INVEST-EXPL', N'WF-INVEST-01', N'SE-INVEST', 2, N'Explore and Practice'),
        (N'PH-CE-ORIENT-EXPL', N'WF-ORIENT-01', N'CE-ORIENT', 2, N'Explore and Practice'),
        (N'PH-CE-HEALTH-EXPL', N'WF-X-HEALTH-01', N'CE-HEALTH', 2, N'Explore and Practice'),
        (N'PH-CE-DEAL-1-EXPL', N'WF-X-DEAL-01', N'CE-DEAL-1', 2, N'Explore and Practice'),
        (N'PH-CE-DEAL-2-EXPL', N'WF-X-DEAL-01', N'CE-DEAL-2', 2, N'Explore and Practice'),
        (N'PH-CE-DEAL-3-EXPL', N'WF-X-DEAL-01', N'CE-DEAL-3', 2, N'Explore and Practice'),
        (N'PH-CE-ORCH-EXPL', N'WF-X-ORCH-01', N'CE-ORCH', 2, N'Explore and Practice'),
        (N'PH-CE-RENEW-EXPL', N'WF-X-RENEW-01', N'CE-RENEW', 2, N'Explore and Practice'),
        (N'PH-CE-POLICY-EXPL', N'WF-X-POLICY-01', N'CE-POLICY', 2, N'Explore and Practice'),
        (N'PH-CE-INVEST-EXPL', N'WF-INVEST-01', N'CE-INVEST', 2, N'Explore and Practice'),
        (N'PH-CSA-ORIENT-EXPL', N'WF-ORIENT-01', N'CSA-ORIENT', 2, N'Explore and Practice'),
        (N'PH-CSA-PIPE-EXPL', N'WF-X-CONSUME-01', N'CSA-PIPE', 2, N'Explore and Practice'),
        (N'PH-CSA-CONV-EXPL', N'WF-X-CONV-01', N'CSA-CONV', 2, N'Explore and Practice'),
        (N'PH-CSA-ARCH-1-EXPL', N'WF-X-ARCH-01', N'CSA-ARCH-1', 2, N'Explore and Practice'),
        (N'PH-CSA-ARCH-2-EXPL', N'WF-X-ARCH-01', N'CSA-ARCH-2', 2, N'Explore and Practice'),
        (N'PH-CSA-HEALTH-EXPL', N'WF-X-HEALTH-01', N'CSA-HEALTH', 2, N'Explore and Practice'),
        (N'PH-CSA-VALUE-1-EXPL', N'WF-X-VALUE-01', N'CSA-VALUE-1', 2, N'Explore and Practice'),
        (N'PH-CSA-VALUE-2-EXPL', N'WF-X-VALUE-01', N'CSA-VALUE-2', 2, N'Explore and Practice'),
        (N'PH-CSA-INVEST-EXPL', N'WF-INVEST-01', N'CSA-INVEST', 2, N'Explore and Practice'),
        (N'PH-CSAM-ORIENT-EXPL', N'WF-ORIENT-01', N'CSAM-ORIENT', 2, N'Explore and Practice'),
        (N'PH-CSAM-SPLAN-EXPL', N'WF-X-PLAN-01', N'CSAM-SPLAN', 2, N'Explore and Practice'),
        (N'PH-CSAM-HEALTH-EXPL', N'WF-X-HEALTH-01', N'CSAM-HEALTH', 2, N'Explore and Practice'),
        (N'PH-ALL-USECASE-EXPL', N'WF-X-USECASE-01', N'ALL-USECASE', 2, N'Explore and Practice'),
        (N'PH-CSAM-EXEC-EXPL', N'WF-X-CONV-01', N'CSAM-EXEC', 2, N'Explore and Practice'),
        (N'PH-CSAM-ORCH-EXPL', N'WF-X-ORCH-01', N'CSAM-ORCH', 2, N'Explore and Practice'),
        (N'PH-CSAM-VALUE-EXPL', N'WF-X-VALUE-01', N'CSAM-VALUE', 2, N'Explore and Practice'),
        (N'PH-CSAM-RENEW-EXPL', N'WF-X-RENEW-01', N'CSAM-RENEW', 2, N'Explore and Practice'),
        (N'PH-CSAM-ESCALATE-EXPL', N'WF-X-HEALTH-01', N'CSAM-ESCALATE', 2, N'Explore and Practice'),
        (N'PH-CSAM-INVEST-EXPL', N'WF-INVEST-01', N'CSAM-INVEST', 2, N'Explore and Practice'),
        (N'PH-ALL-DEAL-EXPL', N'WF-X-DEAL-01', N'ALL-DEAL', 2, N'Explore and Practice'),
        (N'PH-AE-HEALTH-EXPL', N'WF-X-HEALTH-01', N'AE-HEALTH', 2, N'Explore and Practice'),
        (N'PH-ALL-TRANSITION-EXPL', N'WF-X-TRANSITION-01', N'ALL-TRANSITION', 2, N'Explore and Practice'),
        (N'PH-ALL-HANDOFF-EXPL', N'WF-X-HANDOFF-01', N'ALL-HANDOFF', 2, N'Explore and Practice'),
        (N'PH-ATS-CONSUME-EXPL', N'WF-X-CONSUME-01', N'ATS-CONSUME', 2, N'Explore and Practice'),
        (N'PH-ALL-SPONSOR-EXPL', N'WF-X-SPONSOR-01', N'ALL-SPONSOR', 2, N'Explore and Practice'),
        (N'PH-ALL-FYPLAN-EXPL', N'WF-X-FYPLAN-01', N'ALL-FYPLAN', 2, N'Explore and Practice'),
        (N'PH-ALL-ASSET-EXPL', N'WF-X-ASSET-01', N'ALL-ASSET', 2, N'Explore and Practice'),
        (N'PH-CSAM-CONSUME-EXPL', N'WF-X-CONSUME-01', N'CSAM-CONSUME', 2, N'Explore and Practice'),
        (N'PH-SSP-CONSUME-EXPL', N'WF-X-CONSUME-01', N'SSP-CONSUME', 2, N'Explore and Practice'),
        (N'PH-SE-CONSUME-EXPL', N'WF-X-CONSUME-01', N'SE-CONSUME', 2, N'Explore and Practice'),
        (N'PH-ALL-CLOSE-EXPL', N'WF-X-CLOSE-01', N'ALL-CLOSE', 2, N'Explore and Practice'),
        (N'PH-DAE-SIGNAL-EXPL', N'WF-X-SIGNAL-01', N'DAE-SIGNAL', 2, N'Explore and Practice'),
        (N'PH-DSS-SIGNAL-EXPL', N'WF-X-SIGNAL-01', N'DSS-SIGNAL', 2, N'Explore and Practice'),
        (N'PH-DAE-PARTNER-EXPL', N'WF-X-PARTNER-01', N'DAE-PARTNER', 2, N'Explore and Practice'),
        (N'PH-PSS-PARTNER-EXPL', N'WF-X-PARTNER-01', N'PSS-PARTNER', 2, N'Explore and Practice'),
        (N'PH-DCSA-CONSUME-EXPL', N'WF-X-CONSUME-01', N'DCSA-CONSUME', 2, N'Explore and Practice'),
        (N'PH-DSE-ARCH-EXPL', N'WF-X-ARCH-01', N'DSE-ARCH', 2, N'Explore and Practice'),
        (N'PH-DAE-TERRITORY-EXPL', N'WF-X-TERRITORY-01', N'DAE-TERRITORY', 2, N'Explore and Practice'),
        (N'PH-DSS-TERRITORY-EXPL', N'WF-X-TERRITORY-01', N'DSS-TERRITORY', 2, N'Explore and Practice'),
        (N'PH-PSS-JOINTPLAN-EXPL', N'WF-X-TERRITORY-01', N'PSS-JOINTPLAN', 2, N'Explore and Practice'),
        (N'PH-DAE-ORIENT-EXPL', N'WF-ORIENT-01', N'DAE-ORIENT', 2, N'Explore and Practice'),
        (N'PH-DAE-CONV-EXPL', N'WF-X-CONV-01', N'DAE-CONV', 2, N'Explore and Practice'),
        (N'PH-DAE-DEAL-EXPL', N'WF-X-DEAL-01', N'DAE-DEAL', 2, N'Explore and Practice'),
        (N'PH-DAE-RENEW-EXPL', N'WF-X-RENEW-01', N'DAE-RENEW', 2, N'Explore and Practice'),
        (N'PH-DAE-HEALTH-EXPL', N'WF-X-HEALTH-01', N'DAE-HEALTH', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-ORIENT-EXPL', N'WF-ORIENT-01', N'SMEC-CE-ORIENT', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-RENEW-EXPL', N'WF-X-RENEW-01', N'SMEC-CE-RENEW', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-DEAL-EXPL', N'WF-X-DEAL-01', N'SMEC-CE-DEAL', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-HEALTH-EXPL', N'WF-X-HEALTH-01', N'SMEC-CE-HEALTH', 2, N'Explore and Practice'),
        (N'PH-DSS-ORIENT-EXPL', N'WF-ORIENT-01', N'DSS-ORIENT', 2, N'Explore and Practice'),
        (N'PH-DSS-CONV-EXPL', N'WF-X-CONV-01', N'DSS-CONV', 2, N'Explore and Practice'),
        (N'PH-DSS-DEAL-EXPL', N'WF-X-DEAL-01', N'DSS-DEAL', 2, N'Explore and Practice'),
        (N'PH-DSS-VALUE-EXPL', N'WF-X-VALUE-01', N'DSS-VALUE', 2, N'Explore and Practice'),
        (N'PH-AE-ORIENT-COMMIT', N'WF-ORIENT-01', N'AE-ORIENT', 3, N'Commit to Action'),
        (N'PH-AE-PLAN-COMMIT', N'WF-X-PLAN-01', N'AE-PLAN', 3, N'Commit to Action'),
        (N'PH-AE-PIPE-1-COMMIT', N'WF-X-PIPE-01', N'AE-PIPE-1', 3, N'Commit to Action'),
        (N'PH-AE-PIPE-2-COMMIT', N'WF-X-PIPE-01', N'AE-PIPE-2', 3, N'Commit to Action'),
        (N'PH-AE-OPP-COMMIT', N'WF-X-OPP-01', N'AE-OPP', 3, N'Commit to Action'),
        (N'PH-AE-CONV-COMMIT', N'WF-X-CONV-01', N'AE-CONV', 3, N'Commit to Action'),
        (N'PH-AE-DEAL-COMMIT', N'WF-X-DEAL-01', N'AE-DEAL', 3, N'Commit to Action'),
        (N'PH-AE-RENEW-COMMIT', N'WF-X-RENEW-01', N'AE-RENEW', 3, N'Commit to Action'),
        (N'PH-AE-INVEST-COMMIT', N'WF-INVEST-01', N'AE-INVEST', 3, N'Commit to Action'),
        (N'PH-AE-ORCH-COMMIT', N'WF-X-ORCH-01', N'AE-ORCH', 3, N'Commit to Action'),
        (N'PH-AE-VALUE-COMMIT', N'WF-X-VALUE-01', N'AE-VALUE', 3, N'Commit to Action'),
        (N'PH-ATS-ORIENT-COMMIT', N'WF-ORIENT-01', N'ATS-ORIENT', 3, N'Commit to Action'),
        (N'PH-ATS-INTEL-COMMIT', N'WF-X-PLAN-01', N'ATS-INTEL', 3, N'Commit to Action'),
        (N'PH-ATS-NARR-COMMIT', N'WF-X-CONV-01', N'ATS-NARR', 3, N'Commit to Action'),
        (N'PH-ATS-WORKLOAD-COMMIT', N'WF-X-PLAN-01', N'ATS-WORKLOAD', 3, N'Commit to Action'),
        (N'PH-ATS-TECH-COMMIT', N'WF-X-ARCH-01', N'ATS-TECH', 3, N'Commit to Action'),
        (N'PH-ATS-EBC-COMMIT', N'WF-X-CONV-01', N'ATS-EBC', 3, N'Commit to Action'),
        (N'PH-ATS-TALK-COMMIT', N'WF-X-CONV-01', N'ATS-TALK', 3, N'Commit to Action'),
        (N'PH-ATS-TEAM-COMMIT', N'WF-X-ORCH-01', N'ATS-TEAM', 3, N'Commit to Action'),
        (N'PH-ATS-INVEST-COMMIT', N'WF-INVEST-01', N'ATS-INVEST', 3, N'Commit to Action'),
        (N'PH-ATS-CBR-COMMIT', N'WF-X-VALUE-01', N'ATS-CBR', 3, N'Commit to Action'),
        (N'PH-ATS-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'ATS-HEALTH', 3, N'Commit to Action'),
        (N'PH-ATS-PARTNER-COMMIT', N'WF-X-ORCH-01', N'ATS-PARTNER', 3, N'Commit to Action'),
        (N'PH-SSP-ORIENT-COMMIT', N'WF-ORIENT-01', N'SSP-ORIENT', 3, N'Commit to Action'),
        (N'PH-SSP-LEAD-COMMIT', N'WF-X-OPP-01', N'SSP-LEAD', 3, N'Commit to Action'),
        (N'PH-SSP-PLAN-COMMIT', N'WF-X-PLAN-01', N'SSP-PLAN', 3, N'Commit to Action'),
        (N'PH-SSP-VALUE-COMMIT', N'WF-X-VALUE-01', N'SSP-VALUE', 3, N'Commit to Action'),
        (N'PH-SSP-CONV-COMMIT', N'WF-X-CONV-01', N'SSP-CONV', 3, N'Commit to Action'),
        (N'PH-SSP-ORCH-COMMIT', N'WF-X-ORCH-01', N'SSP-ORCH', 3, N'Commit to Action'),
        (N'PH-SSP-COMP-COMMIT', N'WF-X-DEAL-01', N'SSP-COMP', 3, N'Commit to Action'),
        (N'PH-SSP-DEAL-COMMIT', N'WF-X-DEAL-01', N'SSP-DEAL', 3, N'Commit to Action'),
        (N'PH-SSP-INVEST-COMMIT', N'WF-INVEST-01', N'SSP-INVEST', 3, N'Commit to Action'),
        (N'PH-SE-ORIENT-COMMIT', N'WF-ORIENT-01', N'SE-ORIENT', 3, N'Commit to Action'),
        (N'PH-SE-CONV-COMMIT', N'WF-X-CONV-01', N'SE-CONV', 3, N'Commit to Action'),
        (N'PH-SE-ARCH-1-COMMIT', N'WF-X-ARCH-01', N'SE-ARCH-1', 3, N'Commit to Action'),
        (N'PH-SE-ARCH-2-COMMIT', N'WF-X-ARCH-01', N'SE-ARCH-2', 3, N'Commit to Action'),
        (N'PH-SE-ARCH-3-COMMIT', N'WF-X-ARCH-01', N'SE-ARCH-3', 3, N'Commit to Action'),
        (N'PH-SE-DISC-COMMIT', N'WF-X-DISC-01', N'SE-DISC', 3, N'Commit to Action'),
        (N'PH-SE-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'SE-HEALTH', 3, N'Commit to Action'),
        (N'PH-SE-ASSET-COMMIT', N'WF-X-ASSET-01', N'SE-ASSET', 3, N'Commit to Action'),
        (N'PH-SE-INVEST-COMMIT', N'WF-INVEST-01', N'SE-INVEST', 3, N'Commit to Action'),
        (N'PH-CE-ORIENT-COMMIT', N'WF-ORIENT-01', N'CE-ORIENT', 3, N'Commit to Action'),
        (N'PH-CE-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'CE-HEALTH', 3, N'Commit to Action'),
        (N'PH-CE-DEAL-1-COMMIT', N'WF-X-DEAL-01', N'CE-DEAL-1', 3, N'Commit to Action'),
        (N'PH-CE-DEAL-2-COMMIT', N'WF-X-DEAL-01', N'CE-DEAL-2', 3, N'Commit to Action'),
        (N'PH-CE-DEAL-3-COMMIT', N'WF-X-DEAL-01', N'CE-DEAL-3', 3, N'Commit to Action'),
        (N'PH-CE-ORCH-COMMIT', N'WF-X-ORCH-01', N'CE-ORCH', 3, N'Commit to Action'),
        (N'PH-CE-RENEW-COMMIT', N'WF-X-RENEW-01', N'CE-RENEW', 3, N'Commit to Action'),
        (N'PH-CE-POLICY-COMMIT', N'WF-X-POLICY-01', N'CE-POLICY', 3, N'Commit to Action'),
        (N'PH-CE-INVEST-COMMIT', N'WF-INVEST-01', N'CE-INVEST', 3, N'Commit to Action'),
        (N'PH-CSA-ORIENT-COMMIT', N'WF-ORIENT-01', N'CSA-ORIENT', 3, N'Commit to Action'),
        (N'PH-CSA-PIPE-COMMIT', N'WF-X-CONSUME-01', N'CSA-PIPE', 3, N'Commit to Action'),
        (N'PH-CSA-CONV-COMMIT', N'WF-X-CONV-01', N'CSA-CONV', 3, N'Commit to Action'),
        (N'PH-CSA-ARCH-1-COMMIT', N'WF-X-ARCH-01', N'CSA-ARCH-1', 3, N'Commit to Action'),
        (N'PH-CSA-ARCH-2-COMMIT', N'WF-X-ARCH-01', N'CSA-ARCH-2', 3, N'Commit to Action'),
        (N'PH-CSA-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'CSA-HEALTH', 3, N'Commit to Action'),
        (N'PH-CSA-VALUE-1-COMMIT', N'WF-X-VALUE-01', N'CSA-VALUE-1', 3, N'Commit to Action'),
        (N'PH-CSA-VALUE-2-COMMIT', N'WF-X-VALUE-01', N'CSA-VALUE-2', 3, N'Commit to Action'),
        (N'PH-CSA-INVEST-COMMIT', N'WF-INVEST-01', N'CSA-INVEST', 3, N'Commit to Action'),
        (N'PH-CSAM-ORIENT-COMMIT', N'WF-ORIENT-01', N'CSAM-ORIENT', 3, N'Commit to Action'),
        (N'PH-CSAM-SPLAN-COMMIT', N'WF-X-PLAN-01', N'CSAM-SPLAN', 3, N'Commit to Action'),
        (N'PH-CSAM-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'CSAM-HEALTH', 3, N'Commit to Action'),
        (N'PH-ALL-USECASE-COMMIT', N'WF-X-USECASE-01', N'ALL-USECASE', 3, N'Commit to Action'),
        (N'PH-CSAM-EXEC-COMMIT', N'WF-X-CONV-01', N'CSAM-EXEC', 3, N'Commit to Action'),
        (N'PH-CSAM-ORCH-COMMIT', N'WF-X-ORCH-01', N'CSAM-ORCH', 3, N'Commit to Action'),
        (N'PH-CSAM-VALUE-COMMIT', N'WF-X-VALUE-01', N'CSAM-VALUE', 3, N'Commit to Action'),
        (N'PH-CSAM-RENEW-COMMIT', N'WF-X-RENEW-01', N'CSAM-RENEW', 3, N'Commit to Action'),
        (N'PH-CSAM-ESCALATE-COMMIT', N'WF-X-HEALTH-01', N'CSAM-ESCALATE', 3, N'Commit to Action'),
        (N'PH-CSAM-INVEST-COMMIT', N'WF-INVEST-01', N'CSAM-INVEST', 3, N'Commit to Action'),
        (N'PH-ALL-DEAL-COMMIT', N'WF-X-DEAL-01', N'ALL-DEAL', 3, N'Commit to Action'),
        (N'PH-AE-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'AE-HEALTH', 3, N'Commit to Action'),
        (N'PH-ALL-TRANSITION-COMMIT', N'WF-X-TRANSITION-01', N'ALL-TRANSITION', 3, N'Commit to Action'),
        (N'PH-ALL-HANDOFF-COMMIT', N'WF-X-HANDOFF-01', N'ALL-HANDOFF', 3, N'Commit to Action'),
        (N'PH-ATS-CONSUME-COMMIT', N'WF-X-CONSUME-01', N'ATS-CONSUME', 3, N'Commit to Action'),
        (N'PH-ALL-SPONSOR-COMMIT', N'WF-X-SPONSOR-01', N'ALL-SPONSOR', 3, N'Commit to Action'),
        (N'PH-ALL-FYPLAN-COMMIT', N'WF-X-FYPLAN-01', N'ALL-FYPLAN', 3, N'Commit to Action'),
        (N'PH-ALL-ASSET-COMMIT', N'WF-X-ASSET-01', N'ALL-ASSET', 3, N'Commit to Action'),
        (N'PH-CSAM-CONSUME-COMMIT', N'WF-X-CONSUME-01', N'CSAM-CONSUME', 3, N'Commit to Action'),
        (N'PH-SSP-CONSUME-COMMIT', N'WF-X-CONSUME-01', N'SSP-CONSUME', 3, N'Commit to Action'),
        (N'PH-SE-CONSUME-COMMIT', N'WF-X-CONSUME-01', N'SE-CONSUME', 3, N'Commit to Action'),
        (N'PH-ALL-CLOSE-COMMIT', N'WF-X-CLOSE-01', N'ALL-CLOSE', 3, N'Commit to Action'),
        (N'PH-DAE-SIGNAL-COMMIT', N'WF-X-SIGNAL-01', N'DAE-SIGNAL', 3, N'Commit to Action'),
        (N'PH-DSS-SIGNAL-COMMIT', N'WF-X-SIGNAL-01', N'DSS-SIGNAL', 3, N'Commit to Action'),
        (N'PH-DAE-PARTNER-COMMIT', N'WF-X-PARTNER-01', N'DAE-PARTNER', 3, N'Commit to Action'),
        (N'PH-PSS-PARTNER-COMMIT', N'WF-X-PARTNER-01', N'PSS-PARTNER', 3, N'Commit to Action'),
        (N'PH-DCSA-CONSUME-COMMIT', N'WF-X-CONSUME-01', N'DCSA-CONSUME', 3, N'Commit to Action'),
        (N'PH-DSE-ARCH-COMMIT', N'WF-X-ARCH-01', N'DSE-ARCH', 3, N'Commit to Action'),
        (N'PH-DAE-TERRITORY-COMMIT', N'WF-X-TERRITORY-01', N'DAE-TERRITORY', 3, N'Commit to Action'),
        (N'PH-DSS-TERRITORY-COMMIT', N'WF-X-TERRITORY-01', N'DSS-TERRITORY', 3, N'Commit to Action'),
        (N'PH-PSS-JOINTPLAN-COMMIT', N'WF-X-TERRITORY-01', N'PSS-JOINTPLAN', 3, N'Commit to Action'),
        (N'PH-DAE-ORIENT-COMMIT', N'WF-ORIENT-01', N'DAE-ORIENT', 3, N'Commit to Action'),
        (N'PH-DAE-CONV-COMMIT', N'WF-X-CONV-01', N'DAE-CONV', 3, N'Commit to Action'),
        (N'PH-DAE-DEAL-COMMIT', N'WF-X-DEAL-01', N'DAE-DEAL', 3, N'Commit to Action'),
        (N'PH-DAE-RENEW-COMMIT', N'WF-X-RENEW-01', N'DAE-RENEW', 3, N'Commit to Action'),
        (N'PH-DAE-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'DAE-HEALTH', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-ORIENT-COMMIT', N'WF-ORIENT-01', N'SMEC-CE-ORIENT', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-RENEW-COMMIT', N'WF-X-RENEW-01', N'SMEC-CE-RENEW', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-DEAL-COMMIT', N'WF-X-DEAL-01', N'SMEC-CE-DEAL', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'SMEC-CE-HEALTH', 3, N'Commit to Action'),
        (N'PH-DSS-ORIENT-COMMIT', N'WF-ORIENT-01', N'DSS-ORIENT', 3, N'Commit to Action'),
        (N'PH-DSS-CONV-COMMIT', N'WF-X-CONV-01', N'DSS-CONV', 3, N'Commit to Action'),
        (N'PH-DSS-DEAL-COMMIT', N'WF-X-DEAL-01', N'DSS-DEAL', 3, N'Commit to Action'),
        (N'PH-DSS-VALUE-COMMIT', N'WF-X-VALUE-01', N'DSS-VALUE', 3, N'Commit to Action')
    ) v([ExternalId], [TopicExternalId], [PlacementExternalId], [DisplayOrder], [Name])
)
SELECT @unresolved = 309 - COUNT(*) FROM raw
    INNER JOIN dbo.HuddleTopics AS t ON t.[ExternalId] = raw.[TopicExternalId]
    INNER JOIN dbo.HuddlePlacements AS p ON p.[ExternalId] = raw.[PlacementExternalId];
IF @unresolved <> 0
    THROW 51000, 'HuddlePhases: 309 source rows were expected to resolve their foreign keys but some did not. Run the earlier scripts in order and re-check the workbook.', 1;

COMMIT TRANSACTION;
GO
