/*
    AI agents, including the new WhenNotToUseIt and StepsToGetStarted copy
    Generated from the Frontier Accelerator content workbook by generate.py.
    Do not hand-edit. Re-runnable: every statement is an ExternalId-keyed MERGE, nothing is deleted.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
DECLARE @unresolved INT;
BEGIN TRANSACTION;

;WITH raw AS (
    SELECT * FROM (VALUES
        (N'AGT-001', N'Sales Agent', N'Conversational sales agent in Microsoft 365 Copilot, reached through the agent picker as Sales. Deal Agent runs as a skill inside Sales Chat and triggers automatically when you ask about a renewal or a deal.', N'Orchestrator', N'Search, synthesize, and act on sales data, and support repeatable execution-focused sales workflows. Through the Deal Agent skill it also runs enterprise renewals end to end: deal discovery and history, Deal Book generation, EA quotes and proposals, amendments, pre-approvals, and licensing questions, traversing more than a dozen source systems from a natural language prompt.', N'Account, opportunity, pipeline, meeting preparation, CRM updates, and configured sales actions. For renewals and deals, ask about enrollments, renewal agreements, agreement summaries, license estate, Azure consumption against commitment, Deal Books, EA quotes, proposals, amendments, and pre-approvals. EA and MCA-E renewals are the primary motion. Lead with an identifier such as a TPID, agreement number, or enrollment number; specific prompts return real deal data and vague prompts return generic answers.', N'Do not treat Deal Agent as a separate agent to select; it is a skill inside Sales Chat. Do not rely on it alone for complex negotiations or sensitive disclosures, and do not bypass the legal approval chain for material amendments. Do not treat a first response as final on a complex deal; re-run and verify against current data. Do not use it for work outside the CRM such as decks, emails, and documents; that is Cowork.', N'Open Microsoft 365 Copilot in Teams or Outlook. Use the agent picker to find and select Sales; no separate install is required. Start a new chat with a deal prompt such as: List my upcoming renewals this quarter. Deal Agent triggers automatically. Keep one chat thread per deal so the context stays clean.', N'Brings sales data and actions into the flow of work. For renewals, work that previously meant gathering data from seven or eight portals over two to three weeks becomes a few natural language prompts, with the Deal Book assembled across more than a dozen source systems.', N'https://aka.ms/SalesM365', N'Open Sales Agent'),
        (N'AGT-002', N'ECIF Agent', N'AI-powered experience layer, available through Sales Agent and Microsoft 365, that connects the systems used across the end-to-end ECIF journey.', N'Domain agent', N'Understand eligible investment offers; create compliant ECIF workscopes with guided, auto-populated inputs; identify suitable suppliers; submit requests; and track status, milestones, overdue actions, and delivery progress.', N'Preparing or refining an ECIF funding request; selecting an eligible offer or supplier for an Opportunity and location; submitting a request; or tracking milestones and delivery across internal or partner-led projects.', N'Do not treat the agent as the final authority for policy, eligibility, compliance, funding approval, or supplier selection. Review generated content and required evidence before submission, and use governed ECIF channels for exceptions or approvals.', N'Open Microsoft 365 Copilot and select Sales from the left navigation. Start an ECIF conversation using one of the suggested prompts or the Prompt Gallery; include the Opportunity ID or customer name and a clear command such as list, give, or track. Review the generated workscope, supplier recommendation, or request status before taking the next governed action.', N'Reduces seller toil by bringing ECIF guidance and actions into one conversational flow; improves workscope completeness and first-pass quality; speeds the path from scope creation to IO/PO; and provides a connected view of requests, milestones, alerts, and delivery progress.', N'https://aka.ms/SalesM365', N'Open ECIF Agent'),
        (N'AGT-003', N'Microsoft 365 Copilot', N'AI assistant across Microsoft 365 apps and work data.', N'General agent', N'Draft, summarize, analyze, prepare, and create within familiar Microsoft 365 experiences.', N'Everyday work grounded in emails, meetings, chats, files, and app content.', N'Do not use as a substitute for a specialized agent when the work requires a specific system or workflow.', N'Open Microsoft 365 Copilot from the app launcher or copilot.cloud.microsoft and start in Chat.', N'Reduces time spent drafting, summarizing, and preparing work; uses permitted Microsoft 365 context to keep work grounded.', N'https://m365.cloud.microsoft/chat', N'Open Microsoft 365 Copilot'),
        (N'AGT-004', N'Cowork', N'Agentic Microsoft 365 experience for longer-running, outcome-focused, multi-source work.', N'Agentic workspace', N'Plans and executes multistep work, invokes skills, and creates deliverables with checkpoints.', N'Complex tasks spanning Microsoft 365, Dynamics 365 data, documents, presentations, and recommendations.', N'Avoid for a quick single answer when Copilot Chat or a specialized agent is sufficient.', N'Open Microsoft 365 Copilot and select Cowork beside Chat. Describe the outcome you want rather than a single question, then review the work at each checkpoint it presents.', N'Executes multi-step work across Microsoft 365 instead of answering one question at a time. Built for delegation: it plans, invokes skills, works across data sources, and produces deliverables with review checkpoints.', N'https://m365.cloud.microsoft/', N'Open Cowork'),
        (N'AGT-005', N'Scout', N'Always-on agent designed to keep work moving across Microsoft 365 and the desktop.', N'Agent', N'Your AI desktop assistant for seller work. Prepare for customer meetings, summarize communications, organize actions, monitor priorities, and automate repetitive work across Microsoft 365 and sales systems.', N'Continuous or proactive work that should persist beyond one chat.', N'Do not use it for a quick single answer that Copilot Chat would handle, and do not use it to bypass a human checkpoint just because it can run unattended. Anything it produces while running on its own still needs the same review as anything else.', N'Go to aka.ms/m, the internal Scout hub. Request the access package, complete the agreement, download and install Scout, then sign in with Microsoft 365 and GitHub as instructed. Start with a business outcome rather than a tool command.', N'Keeps work moving between sessions rather than inside one chat. Monitors signals, coordinates follow-through, and prepares materials within organizational controls.', N'https://aka.ms/m', N'Get started with Scout'),
        (N'AGT-006', N'Researcher', N'Deep research agent in Microsoft 365 Copilot that produces structured, source-cited reports.', N'Reasoning agent', N'Combines work content and web research across multiple steps.', N'Customer, market, competitor, industry, and strategic research requiring citations. Researcher is also reachable inside Sales Agent, which uses it to answer research questions; call Researcher directly when you want the full sourced report rather than an answer inside a sales conversation.', N'Avoid for quick summaries or lightweight drafting.', N'Open Microsoft 365 Copilot and select the Researcher agent, then state the research question and sources.', N'Produces source-cited research reports rather than unattributed summaries, combining work content and web research across multiple steps so claims can be traced.', N'https://m365.cloud.microsoft/chat', N'Open Researcher'),
        (N'AGT-007', N'Analyst', N'Data-analysis agent in Microsoft 365 Copilot for statistics, trends, outliers, charts, and reports.', N'Reasoning agent', N'Analyzes supplied data and produces understandable findings and visuals.', N'Multi-file quantitative analysis, trend analysis, and executive-ready data insights.', N'Avoid when authoritative operational reporting must come directly from a certified business system.', N'Open Microsoft 365 Copilot and select the Analyst agent, then attach the data you want analysed.', N'Turns supplied data into findings and visuals a non-analyst can act on, including trends, outliers, and executive-ready charts, without building the analysis by hand.', N'https://m365.cloud.microsoft/chat', N'Open Analyst'),
        (N'AGT-008', N'MSXI Assist V2', N'Assistance within MSXI for report discovery, KPI definitions, and report actions.', N'Assistant', N'Helps users find reports, understand KPI definitions, and take supported report actions.', N'When the job is navigating MSXI content or understanding a metric.', N'Keep separate from the in-report MSXI Copilot until product owners confirm convergence.', N'Open MSXI and select the robot icon in the top ribbon to launch the Assist pane. No enrollment is required.', N'Finds reports using natural language, explains KPI definitions in business terms, launches reports and applies filters, and detects issues with self-service resolution and one-click support escalation.', N'https://aka.ms/MSXIAssistV2', N'Open MSXI Assist V2'),
        (N'AGT-009', N'Agent J.ai', N'Text-based coaching experience grounded in Microsoft 365 context and curated content.', N'Coaching agent', N'Helps users sharpen messages, rehearse conversations, anticipate objections, and plan next steps.', N'Customer conversation preparation and role-play.', N'Do not use as the authoritative source for CRM or commercial data.', N'Open Agent J.ai in Microsoft 365 Copilot, then describe the conversation you want to rehearse and who you will be speaking to.', N'Rehearsal before the real conversation. Sharpens messages, surfaces objections you had not anticipated, and coaches on clarity and next step, grounded in Microsoft 365 context and curated content.', N'https://aka.ms/AgentJCopilot', N'Open Agent J.ai'),
        (N'AGT-010', N'Auto-Fix Pipeline Agent', N'Agent in MSX intended to resolve supported pipeline hygiene issues.', N'Domain agent', N'Supports targeted pipeline cleanup inside MSX.', N'When a Practice explicitly addresses supported pipeline hygiene correction.', N'Do not generalize beyond supported issues.', N'In MSX, open the Pipeline Hygiene workspace and select Auto-Fixes. Choose which automated fixes to enable, then review, accept, or revert the changes after they are applied.', N'One-click cleanup for supported pipeline hygiene violations, with review and revert available so the seller stays in control of what changes.', N'Open MSX, then any account, then the Hygiene tab, then Auto-Fixes. No standalone URL is published.', N'Open Auto-Fixes in MSX'),
        (N'AGT-011', N'MSXI Copilot', N'Copilot experience in MSXI reports for interpreting enabled business data.', N'In-report copilot', N'Interpret enabled business metrics, report views, and signals in context.', N'Use when the job starts from an enabled MSXI report or certified business signal.', N'Do not use as a replacement for human interpretation of KPI scope, report filters, or customer context.', N'Open an AI-certified MSXI report and use the embedded Copilot panel to ask questions about the metrics and trends in front of you. Availability varies by report.', N'Answers questions against certified report data without leaving the report. Explains what a metric means in the context of the filters and view currently applied.', N'https://msxi.microsoft.com/', N'Open MSX Insights'),
        (N'AGT-012', N'Customer Success Agent', N'Teams-based customer success experience referenced in Customer Health Success Program dispatch guidance.', N'Domain assistant', N'Supports Success Program dispatch and customer-success workflow steps where available.', N'Customer Health Success Program dispatch or customer-success process steps that are explicitly supported.', N'Do not use as authority for policy, delivery commitments or customer-facing claims.', N'Confirm access, install the app in Teams if required, then follow the supported Customer Health Success Program dispatch workflow.', N'Connects Customer Health Success Program execution to CSAM workflow steps in Teams, so dispatch and follow-through happen where the team already works.', N'Open the Customer Success Agent app in Teams. No published entry-point URL was located.', N'Open Customer Success Agent'),
        (N'SYS-001', N'MSX Deal Assistance', N'The investment request front door inside MSX. Consolidates ECIF, ACO, Azure Access, and Solution Assessment requests that were previously spread across separate tools.', N'Transactional system', N'Create, submit, and track investment requests against an opportunity, with ROI calculation and opportunity data prepopulated rather than retyped.', N'When an investment request needs to be created or submitted, or when you need the current status of one you already submitted.', N'Not for building the workscope itself, which happens in ECIF Central, and not for policy or eligibility judgments, which stay with the accountable owner.', N'Open an MSX opportunity, go to the Deal Assistance tab, select New Request, then choose the request type such as ECIF, ACO, or Azure Access.', N'One front door instead of several legacy request tools. Opportunity data and ROI calculation carry over, so the request starts mostly complete.', N'https://microsoftsales.crm.dynamics.com/main.aspx?appid=fe0c3504-3700-e911-a849-000d3a10b7cc&forceUCI=1&pagetype=entitylist&etn=opportunity&viewid=00000000-0000-0000-00aa-000010003000&viewType=1039', N'Open MSX Opportunities'),
        (N'SYS-002', N'ECIF Central', N'Where the workscope is built and where delivery actually runs, including supplier collaboration, milestones, and change requests.', N'Execution platform', N'Create a workscope against an opportunity, add suppliers and scope detail, calculate the spend plan, and track execution and milestones once funding is approved.', N'When you need to build or revise a workscope, onboard or work with a supplier, or check delivery progress and milestones.', N'Not the submission point. The completed workscope is submitted through MSX Deal Assistance.', N'Open ECIF Central, create a workscope using the MSX Opportunity ID, add suppliers and scope detail, calculate the spend plan, then generate the completed workscope for submission. Suppliers collaborate through partner.ecifcentral.microsoft.com.', N'Keeps workscope, supplier collaboration, and delivery tracking in one place instead of email threads and spreadsheets.', N'https://aka.ms/ECIFCentral', N'Open ECIF Central'),
        (N'SYS-003', N'Investment Tracker', N'The status view inside MSX Deal Assistance showing where a request sits, who holds it, and what is blocking it. Sometimes called the Pizza Tracker.', N'Tracking view', N'See request stage, current owner, blockers, and recommended next steps without asking someone for a status update.', N'When a submitted request has gone quiet and you need to know where it is and who holds it.', N'Not a substitute for contacting the owner when a request is genuinely stuck. It shows status, not urgency.', N'Open your submitted request in MSX Deal Assistance and review the tracker view for stage, ownership, and blockers. FY27 material describes proactive at-risk alerts; confirm current availability with the ECIF program team.', N'Replaces the status-chasing email with a view. Makes ownership visible so the next action has a name attached.', N'Open the request in MSX Deal Assistance; the tracker is a view within it. No standalone URL is published.', N'Open in MSX Deal Assistance'),
        (N'SYS-004', N'Azure Offer Navigator', N'The front door for Azure investment offers, including Azure Accelerate, with eligibility guidance and nomination support.', N'Request experience', N'Find which Azure offers an opportunity is eligible for, choose the right one, submit the nomination, and track its status.', N'When the investment is Azure-specific and you need to identify and request the right offer.', N'Not for non-Azure ECIF requests, which go through MSX Deal Assistance.', N'Open the Navigator, enter the MSX Opportunity ID, review the eligible offers it returns, select the appropriate one, and submit through the Navigator workflow.', N'One place to see what an opportunity actually qualifies for, with recommendations and next-best-action guidance rather than reading offer documentation.', N'https://aka.ms/AzureOfferNavigator', N'Open Azure Offer Navigator'),
        (N'SYS-005', N'MCAPS Help for ECIF', N'Support, guidance, and ticketing for ECIF and investment process questions.', N'Support experience', N'Get help when a request is blocked, access is missing, or the process itself is unclear, and raise a case when self-help does not resolve it.', N'When you are blocked on process, access, or tooling rather than on a business decision.', N'Not for eligibility, policy, or funding decisions, which belong to the accountable owners rather than support.', N'Open MCAPS Help for ECIF, search the guidance first, and raise a case if the answer is not there. Have the opportunity ID and request ID ready.', N'A defined path for process and access problems, so a blocked request does not sit waiting on an informal ask.', N'https://aka.ms/MCAPSHelpECIF', N'Get ECIF help'),
        (N'SYS-006', N'Consumption Manager', N'Consumption plan information used inside Global ECIF and ACO request flows.', N'Request-flow component', N'Supply and review the consumption plan detail that a Global ECIF or ACO request requires.', N'When submitting a Global ECIF or ACO request that needs consumption plan information.', N'Not a standalone consumption reporting tool. For consumption trends and ACR, use Sales Agent or MSXI.', N'Encountered as part of a Global ECIF or ACO submission rather than opened directly. Confirm current behavior with the ECIF program team.', N'Keeps consumption planning attached to the investment request rather than tracked separately.', N'Reached within the Global ECIF and ACO request flow. No standalone URL was found in current documentation.', N'Reached within the request flow')
    ) v([ExternalId], [Name], [ShortDescription], [WhatItIs], [WhatItHelpsYouDo], [WhenToUseIt], [WhenNotToUseIt], [StepsToGetStarted], [KeyBenefits], [AccessUrl], [AccessLinkLabel])
), src AS (
    SELECT raw.*
    FROM raw
)
MERGE dbo.HuddleAgents AS tgt
USING src ON tgt.[ExternalId] = src.[ExternalId]
WHEN MATCHED THEN UPDATE SET
        tgt.[Name] = src.[Name],
        tgt.[ShortDescription] = src.[ShortDescription],
        tgt.[WhatItIs] = src.[WhatItIs],
        tgt.[WhatItHelpsYouDo] = src.[WhatItHelpsYouDo],
        tgt.[WhenToUseIt] = src.[WhenToUseIt],
        tgt.[WhenNotToUseIt] = src.[WhenNotToUseIt],
        tgt.[StepsToGetStarted] = src.[StepsToGetStarted],
        tgt.[KeyBenefits] = src.[KeyBenefits],
        tgt.[AccessUrl] = src.[AccessUrl],
        tgt.[AccessLinkLabel] = src.[AccessLinkLabel],
        tgt.[UpdatedAtUtc] = SYSUTCDATETIME()
WHEN NOT MATCHED BY TARGET THEN INSERT ([ExternalId], [Name], [ShortDescription], [WhatItIs], [WhatItHelpsYouDo], [WhenToUseIt], [WhenNotToUseIt], [StepsToGetStarted], [KeyBenefits], [AccessUrl], [AccessLinkLabel], [CreatedAtUtc])
    VALUES (src.[ExternalId], src.[Name], src.[ShortDescription], src.[WhatItIs], src.[WhatItHelpsYouDo], src.[WhenToUseIt], src.[WhenNotToUseIt], src.[StepsToGetStarted], src.[KeyBenefits], src.[AccessUrl], src.[AccessLinkLabel], SYSUTCDATETIME());

COMMIT TRANSACTION;
GO
