/*
    Resources
    Generated from the Frontier Accelerator content workbook by generate.py.
    Do not hand-edit. Re-runnable: every statement is an ExternalId-keyed MERGE, nothing is deleted.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
DECLARE @unresolved INT;
BEGIN TRANSACTION;

;WITH raw AS (
    SELECT * FROM (VALUES
        (N'RES-GLOBAL-01', N'Role Hub', N'Always-available hub for role guidance and enablement.', N'https://microsoft.sharepoint.com/sites/AIX/SitePages/AIT-Role-Hub.aspx', N'Hub', N'Open Role Hub', 1),
        (N'RES-001', N'Sales Agent Capabilities Guide', N'Detailed reference for Sales Agent components, capabilities, and example prompts.', N'https://microsoft.sharepoint.com/sites/Salesagent', N'Internal guide', N'Sales Agent resources', 0),
        (N'RES-002', N'Use Sales Agent in Microsoft 365 Copilot', N'Official overview and use guidance for Sales Agent.', N'https://learn.microsoft.com/en-us/microsoft-sales-copilot/sales-chat-overview', N'Microsoft Learn', N'Open on Microsoft Learn', 0),
        (N'RES-003', N'Use Dynamics 365 Sales skills in Copilot Cowork', N'Official scenarios and skill model for Dynamics 365 Sales in Cowork.', N'https://learn.microsoft.com/en-us/microsoft-365/copilot/cowork/', N'Microsoft Learn', N'Open on Microsoft Learn', 0),
        (N'RES-004', N'Frontier Accelerator Content and Learning Model', N'Working model for huddle content, practice cards, experiments, validation, and app rendering.', N'Frontier_Accelerator_Huddles_Content_and_Learning_Model_Updated.docx', N'Internal model', N'Open content model', 0),
        (N'RES-005', N'ATS Finalized Content System', N'ATS-specific working recommendations, coherence pass, capability coverage, and ECIF decisions.', N'Frontier_Accelerator_Huddle_Content_System_v5.8_ATS_Finalized.xlsx', N'Internal workbook', N'Open ATS source workbook', 0),
        (N'RES-006', N'Agent J.ai Reference', N'MCAPS agent reference for coaching and conversation rehearsal.', N'https://aka.ms/AgentJCopilot', N'Internal reference', N'Open Agent J.ai reference', 0),
        (N'RES-007', N'MSXI Report and KPI Help', N'MSXI report discovery and KPI interpretation support.', N'https://aka.ms/MSXIAssistV2', N'Internal resource', N'Open MSXI support', 0),
        (N'RES-008', N'ECIF Guidance and Agent Reference', N'Guidance for ECIF workflow, access surface, and governed review.', N'https://aka.ms/MCAPSHelpECIF', N'Internal resource', N'Open ECIF guidance', 0),
        (N'RES-CSAM-RSG', N'RSG - Customer Success Account Management (CSAM)', N'Role Success Guide content for CSAM customer health, consumption and usage excellence, delivery excellence, AI transition and customer outcomes.', N'https://microsoft.sharepoint.com/sites/C_D_I/_layouts/15/Doc.aspx?sourcedoc=%7B0E40E0A6-67DA-4431-A789-C03FE145C2A8%7D&file=RSG%20-%20Customer%20Success%20Account%20Management%20(CSAM).pptx&action=edit&mobileredirect=true&DefaultItemOpen=1', N'Role guidance', N'Open CSAM RSG', 0),
        (N'RES-CSAM-IMPACT', N'CSAM Impact Guide', N'FY27 CSAM impact guidance covering customer trust, health, cloud adoption, Frontier transformation and AI-enabled effectiveness.', N'https://microsoft.sharepoint.com/teams/CS_CSAM/_layouts/15/Doc.aspx?sourcedoc=%7BEB76E124-BAC8-41D5-BD40-835BB5194433%7D&file=CSAM%20Impact%20Guide.pptx&action=edit&mobileredirect=true&DefaultItemOpen=1', N'Impact guide', N'Open CSAM Impact Guide', 0),
        (N'RES-CSAM-PERSONA', N'CSAM_Persona_FY27', N'Persona source with CSAM tasks for customer health, adoption, success planning, renewal, delivery governance, consumption and orchestration.', N'https://microsoft.sharepoint.com/teams/AITChangeStudio-FieldFeedback/_layouts/15/Doc.aspx?sourcedoc=%7B97F77D44-DF3B-4452-A887-8C2595B43223%7D&file=CSAM_Persona_FY27.pptx&action=edit&mobileredirect=true&DefaultItemOpen=1', N'Persona deck', N'Open CSAM Persona', 0),
        (N'RES-CSAM-HEALTH', N'Customer Health Success Programs - M365 - CSAM Guide', N'CSAM guide for Customer Health Success Program initiation, stakeholder alignment, delivery partner coordination, report out, CSP, RAID and CSDR follow-through.', N'https://microsoft.sharepoint.com/teams/CS_CSAM/_layouts/15/Doc.aspx?sourcedoc=%7B4B198510-3C8C-43A2-A122-FE59A7B31BBD%7D&file=Customer%20Health%20Success%20Programs%20-%20M365%20-%20CSAM%20Guide.docx&action=default&mobileredirect=true&DefaultItemOpen=1', N'Delivery guide', N'Open Customer Health CSAM Guide', 0),
        (N'RES-CSAM-AIINNOV', N'AI Innovation Success Programs - CSAM Delivery Guide', N'CSAM orchestration and follow-through guide for AI Innovation Success engagements, focused on strategic alignment, scoping, delivery handoff and measurable outcomes.', N'https://microsoft.sharepoint.com/teams/CS_CSAM/_layouts/15/Doc.aspx?sourcedoc=%7B330D399B-0AA7-4C17-9555-B82CF96EEC9B%7D&file=AI%20Innovation%20Success%20Programs%20-%20CSAM%20Delivery%20Guide.pptx&action=edit&mobileredirect=true&DefaultItemOpen=1', N'Delivery guide', N'Open AI Innovation CSAM Guide', 0),
        (N'RES-CSAM-CSP', N'FY27 CAIP Enterprise CSA Handbook - Customer Success Planning excerpt', N'Customer Success Planning guidance stating CSAM accountability for Customer Success Plans and monthly review through CSDR or QBR rhythms.', N'https://microsoft.sharepoint.com/sites/CloudAICSU/_layouts/15/Doc.aspx?sourcedoc=%7B112A0789-02C8-4926-9061-EF071233A3E1%7D&file=FY27_CAIP-ENT_EnterpriseCSA_ICandManager_Handbook.pptx&action=edit&mobileredirect=true&DefaultItemOpen=1', N'Planning guidance', N'Open Customer Success Planning guidance', 0),
        (N'RES-SSP-VALIDATION', N'SSP Path Validation Notes', N'Internal validation notes captured in this workbook.', N'See Executive_Summary and Improvement_Recommendations sheets.', N'Workbook note', N'Review recommendations', 0),
        (N'RES-DA-01', N'Deal Agent central hub', N'Central SharePoint site for Deal Agent, the deal making features invoked through Sales Agent. Start here for current features, guidance, and enablement.', N'https://microsoft.sharepoint.com/sites/DealAgent', N'Internal hub', N'Open the Deal Agent hub', 0),
        (N'RES-DA-02', N'Deal Agent enhancements', N'Release notes for Deal Agent, which ships on a bi-weekly cadence. Check before a huddle so examples match what is live.', N'https://microsoft.sharepoint.com/sites/DealAgent/SitePages/Deal-Agent-Enhancements-(June-Edition).aspx', N'Release notes', N'See what shipped recently', 0),
        (N'RES-DA-03', N'Deal Agent community on Viva Engage', N'Community for questions, field examples, and feedback that reaches the Deal Agent product team.', N'https://engage.cloud.microsoft/main/org/microsoft.com/groups/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiIyNTYyNzEwNTY4OTYifQ', N'Community', N'Join the Deal Agent community', 0),
        (N'RES-DA-04', N'Deal Agent huddle deck', N'Huddle deck from the earlier agent-oriented motion. Useful for demonstration flow and worked examples.', N'https://microsoft.sharepoint.com/:p:/s/AIX/cQp7N-0fvlZWT6ITbU68vKrQEgUCRx71l7i3N1KCoEdVJTN4pQ', N'Huddle material', N'Open the Deal Agent huddle deck', 0),
        (N'RES-DA-05', N'Deal Agent golden prompts', N'Working prompt patterns for deal discovery, exploration, consumption insight, and deal book creation. Every pattern leads with a unique identifier.', N'https://aka.ms/DealAgent', N'Prompt library', N'Open the golden prompts', 0),
        (N'RES-DA-06', N'Deal Agent Proposal Builder', N'Proposal Builder for Deal Agent, used with bring your own data proposal creation for MCA-E and EA to MCA-E transitions.', N'https://aka.ms/da_proposal', N'Internal tool', N'Open Proposal Builder', 0),
        (N'RES-ECIF-01', N'ECIF investment workflow: which system, when', N'The investment path across systems. Sales Agent and the ECIF Agent for guidance, ECIF Central for the workscope, MSX Deal Assistance for submission and tracking, MCAPS Help when blocked. For Azure offers, start at Azure Offer Navigator.', N'https://aka.ms/ECIFCentral', N'Process guidance', N'Open ECIF Central', 0),
        (N'RES-SCOUT-01', N'Microsoft Scout FAQ', N'What Scout is, what it can do across files, browser, shell and Microsoft 365, and how autonomous and scheduled work behaves.', N'https://learn.microsoft.com/en-us/microsoft-scout/faq', N'Microsoft Learn', N'Open the Scout FAQ', 0),
        (N'RES-SCOUT-02', N'MCAPS Lobster Pound community', N'Seller community sharing working Scout patterns, including account planning, customer language mining and recurring monitoring.', N'https://microsoft.sharepoint.com/teams/MCAPSLobsterPound', N'Community', N'Open the Lobster Pound', 0),
        (N'RES-SKILLS-CAT', N'CAT Agent Skills catalog', N'Curated catalog of reusable agent skills for Cowork and Microsoft Scout. Filter by platform to see only what runs in the tool you are using.', N'https://microsoft.github.io/cat-agent-skills/', N'Skill catalog', N'Browse agent skills', 1),
        (N'RES-SKILLS-SHACK', N'Skill Shack', N'Field-submitted Scout skills contributed by Microsoft sellers and technical roles, organised by category. Useful when a seller workflow already has a community-built skill behind it.', N'https://microsoft.sharepoint.com/sites/skill-shack', N'Skill catalog', N'Browse Skill Shack', 1),
        (N'RES-SK-COACH', N'Skill Authoring Coach', N'Turn a prompt or activity your team runs repeatedly into a reusable skill with clear triggers, instructions and packaging. Use this when a huddle activity works well enough that the team wants it to become permanent.', N'https://microsoft.github.io/cat-agent-skills/skills/skill-authoring-coach', N'Agent skill', N'Open skill', 1),
        (N'RES-SK-ONEPAGER', N'Cowork Use Case One-Pager', N'Turn a working session into a short use case write-up. Pairs with the Field Contribution route when a huddle produces something worth sharing beyond the team.', N'https://microsoft.github.io/cat-agent-skills/skills/cowork-use-case-one-pager', N'Agent skill', N'Open skill', 1),
        (N'RES-SK-BRIEF', N'Work Brief', N'Scout skill that reads mail, calendar and Teams to produce a prioritised brief of what is owed and what is coming.', N'https://microsoft.github.io/cat-agent-skills/skills/work-brief', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-AWAIT', N'Awaiting Reply', N'Scout skill that finds sent messages which asked for something and never got an answer, then prepares follow-ups.', N'https://microsoft.github.io/cat-agent-skills/skills/awaiting-reply', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-RADAR', N'Pattern Radar', N'Scans your Microsoft 365 signals to surface recurring patterns worth automating. A practical way to find the next workflow to bring to a huddle.', N'https://microsoft.github.io/cat-agent-skills/skills/pattern-radar', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-MEET', N'Meeting Analyzer', N'Extracts decisions, commitments and unspoken signals from meeting content rather than only summarising it.', N'https://microsoft.github.io/cat-agent-skills/skills/meeting-analyzer', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-VOICE', N'Own Voice Builder', N'Builds a reusable voice profile from your own sent messages so drafted content reads like you wrote it.', N'https://microsoft.github.io/cat-agent-skills/skills/own-voice-builder', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-KNOW', N'Institutional Knowledge Archivist', N'Turns scattered Microsoft 365 signals into a structured, searchable knowledge base. Useful for account handover and reusable assets.', N'https://microsoft.github.io/cat-agent-skills/skills/institutional-knowledge', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-REG', N'Regulation Monitor', N'Locks a confirmed list of authoritative sources and sweeps them on a schedule, reporting only what changed. Domain-agnostic - works for commercial policy as well as regulation.', N'https://microsoft.github.io/cat-agent-skills/skills/regulation-monitor', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-QUAL', N'Content Quality Auditor', N'Scores a document against a stated rubric and returns specific edits rather than general feedback.', N'https://microsoft.github.io/cat-agent-skills/skills/content-quality-auditor', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-CASE', N'Anonymised Case Study Writer', N'Turns engagement notes into a shareable case study with customer-identifying detail removed.', N'https://microsoft.github.io/cat-agent-skills/skills/anonymised-case-study-writer', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-TALK', N'Presentation Talk Track Builder', N'Writes first-person presenter scripts for a deck, calibrated to a target duration, without changing the slides.', N'https://microsoft.github.io/cat-agent-skills/skills/presentation-talk-track-builder', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-CHART', N'Chart Builder', N'Produces clean charts from supplied data - useful when a pipeline or consumption view needs to be shown rather than described.', N'https://microsoft.github.io/cat-agent-skills/skills/chart-builder', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-PANEL', N'Persona Reaction Panel', N'Pre-tests a narrative or artefact against role-based personas to surface blind spots and credible-detractor risk before it is used live.', N'https://microsoft.github.io/cat-agent-skills/skills/persona-reaction-panel', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-OUT', N'B2B Outreach Suite', N'Prospect research, outreach drafting, follow-up cadences and objection handling in one skill.', N'https://microsoft.github.io/cat-agent-skills/skills/b2b-outreach-suite', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-UCASE', N'AI Use Case Assessment', N'Scores an AI use case against a structured rubric so value claims are tested rather than asserted.', N'https://microsoft.github.io/cat-agent-skills/skills/ai-usecase-assessment', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-REMIND', N'Conditional Chat Reminder', N'Scout automation that only nudges when the expected update has not appeared - reduces chase without dropping follow-through.', N'https://microsoft.github.io/cat-agent-skills/skills/conditional-chat-reminder', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-ROUTE', N'What to Use When', N'Routes a request to the best-fit Copilot agent and reserves Cowork for longer multi-output work. Useful early in a role path when tool choice is still forming.', N'https://microsoft.github.io/cat-agent-skills/skills/what-to-use-when', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-NEG', N'Stoic Negotiator', N'Structured negotiation preparation covering position, alternatives and zone of agreement, with sourced research.', N'https://microsoft.github.io/cat-agent-skills/skills/stoic-negotiator', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-CONTRACT', N'Vendor Contract Risk Review', N'First-pass review of contract or SOW clauses that commonly cause problems, flagged by risk level to prepare for legal review rather than replace it.', N'https://microsoft.github.io/cat-agent-skills/skills/vendor-contract-risk-review', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-REDLINE', N'Redlining Content', N'Compares a document against a reference or template and produces tracked redlines.', N'https://microsoft.github.io/cat-agent-skills/skills/redlining-content', N'Agent skill', N'Open skill', 0),
        (N'RES-SK-PROCESS', N'AI-First Process Redesign', N'Redesigns an existing process assuming AI capability rather than bolting AI onto the current steps.', N'https://microsoft.github.io/cat-agent-skills/skills/ai-first-process-redesign', N'Agent skill', N'Open skill', 0)
    ) v([ExternalId], [Title], [Description], [Url], [Type], [LinkLabel], [IsGlobal])
), src AS (
    SELECT raw.*
    FROM raw
)
MERGE dbo.HuddleResources AS tgt
USING src ON tgt.[ExternalId] = src.[ExternalId]
WHEN MATCHED THEN UPDATE SET
        tgt.[Title] = src.[Title],
        tgt.[Description] = src.[Description],
        tgt.[Url] = src.[Url],
        tgt.[Type] = src.[Type],
        tgt.[LinkLabel] = src.[LinkLabel],
        tgt.[IsGlobal] = src.[IsGlobal],
        tgt.[UpdatedAtUtc] = SYSUTCDATETIME()
WHEN NOT MATCHED BY TARGET THEN INSERT ([ExternalId], [Title], [Description], [Url], [Type], [LinkLabel], [IsGlobal], [CreatedAtUtc])
    VALUES (src.[ExternalId], src.[Title], src.[Description], src.[Url], src.[Type], src.[LinkLabel], src.[IsGlobal], SYSUTCDATETIME());

COMMIT TRANSACTION;
GO
