<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.18" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.18" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.14.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AitoWorkflowAndHuddleGenerator.Application\AitoWorkflowAndHuddleGenerator.Application.csproj" />
    <ProjectReference Include="..\AitoWorkflowAndHuddleGenerator.Domain\AitoWorkflowAndHuddleGenerator.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MicrosoftGraph\" />
    <Folder Include="Options\" />
    <Folder Include="Persistence\Migrations\" />
    <Folder Include="Persistence\Repositories\" />
    <Folder Include="Persistence\Seed\" />
  </ItemGroup>

</Project>
