/*
    OPTIONAL -- corrections to data already loaded (review each block before running)
    Generated by comparing the 9.16.2026 Frontier Accelerator workbook against the 9.15.2026
    workbook that produced fresh-install-v11.78 (see 00_README_New_Data_Only.md in this folder).
    Everything in this file is an UPDATE to a row that already exists in the database -- nothing
    here is a new row. Per the review instructions for this task, changed-existing-record data is
    reported and made available for manual review, not applied automatically. Read each section
    before running it. Not part of any required install path.

    All of it stems from one workbook correction (Change Summary row 60, dated 2026-09-16):
    "Deal Agent now has catalog ID AGT-016 ... Ten existing Deal Agent activity mappings use
    AGT-016 ... move four Deal Agent resource joins from AGT-001 to AGT-016 ... their launch
    labels name Deal Agent." Section 1 re-attributes those 10 HuddleActivityAgents rows from
    AGT-001 to AGT-016. Section 2 re-attributes the 4 HuddleAgentResources rows the same way.
    Section 3 updates the matching Activities.LaunchLabel text. Section 4 is unrelated wording
    edits to two already-loaded HuddleAgents rows (ECIF Agent, Sales Home).

    Must run AFTER 01_Seed_New_Deal_Agent.sql (Section 1/2 need AGT-016 to exist).

    NOTE ON PRECEDENT: database/huddle-2026.09.15-update/13_OPTIONAL_Existing_Data_Corrections.sql
    sets `aa.UpdatedAtUtc = SYSUTCDATETIME()` when updating dbo.HuddleActivityAgents rows. Per the
    schema in 01_Schema_All_Migrations.sql, HuddleActivityAgents (and HuddleAgentResources,
    HuddleTopicAgents) have no UpdatedAtUtc/CreatedAtUtc column at all -- only HuddleAgents and
    HuddleActivities do. That prior script would fail with "Invalid column name 'UpdatedAtUtc'" if
    it were ever run as-is against this schema. It was apparently never executed (its own header
    says so), so this was never caught. This script does NOT repeat that: Sections 1 and 2 omit
    UpdatedAtUtc for the join tables; Sections 3 and 4 include it, because HuddleActivities and
    HuddleAgents do have the column.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

-- =====================================================================================
-- 1) Re-attribute 10 existing HuddleActivityAgents rows from AGT-001 to AGT-016.
--    Composite PK is (HuddleActivityId, HuddleAgentId, UsageType); HuddleAgentId is being
--    changed in place. DisplayLabel already reads "Deal Agent, surfaced through Sales Agent"
--    on all 10 -- unchanged, only the AgentID they resolve to moves off the generic Sales
--    Agent row. No UpdatedAtUtc column exists on this table (see note above).
-- =====================================================================================
UPDATE aa SET aa.HuddleAgentId = new_ag.Id
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities act ON act.Id = aa.HuddleActivityId AND act.ExternalId = N'WF-CE-RENEW-01-P-CE-01'
INNER JOIN dbo.HuddleAgents old_ag ON old_ag.Id = aa.HuddleAgentId AND old_ag.ExternalId = N'AGT-001'
CROSS JOIN (SELECT Id FROM dbo.HuddleAgents WHERE ExternalId = N'AGT-016') new_ag
WHERE aa.UsageType = N'Primary';
UPDATE aa SET aa.HuddleAgentId = new_ag.Id
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities act ON act.Id = aa.HuddleActivityId AND act.ExternalId = N'CE-02-DEAL-01'
INNER JOIN dbo.HuddleAgents old_ag ON old_ag.Id = aa.HuddleAgentId AND old_ag.ExternalId = N'AGT-001'
CROSS JOIN (SELECT Id FROM dbo.HuddleAgents WHERE ExternalId = N'AGT-016') new_ag
WHERE aa.UsageType = N'Primary';
UPDATE aa SET aa.HuddleAgentId = new_ag.Id
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities act ON act.Id = aa.HuddleActivityId AND act.ExternalId = N'AE-05-P01'
INNER JOIN dbo.HuddleAgents old_ag ON old_ag.Id = aa.HuddleAgentId AND old_ag.ExternalId = N'AGT-001'
CROSS JOIN (SELECT Id FROM dbo.HuddleAgents WHERE ExternalId = N'AGT-016') new_ag
WHERE aa.UsageType = N'Primary';
UPDATE aa SET aa.HuddleAgentId = new_ag.Id
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities act ON act.Id = aa.HuddleActivityId AND act.ExternalId = N'AE-05-DEAL-01'
INNER JOIN dbo.HuddleAgents old_ag ON old_ag.Id = aa.HuddleAgentId AND old_ag.ExternalId = N'AGT-001'
CROSS JOIN (SELECT Id FROM dbo.HuddleAgents WHERE ExternalId = N'AGT-016') new_ag
WHERE aa.UsageType = N'Primary';
UPDATE aa SET aa.HuddleAgentId = new_ag.Id
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities act ON act.Id = aa.HuddleActivityId AND act.ExternalId = N'AE-07-P01'
INNER JOIN dbo.HuddleAgents old_ag ON old_ag.Id = aa.HuddleAgentId AND old_ag.ExternalId = N'AGT-001'
CROSS JOIN (SELECT Id FROM dbo.HuddleAgents WHERE ExternalId = N'AGT-016') new_ag
WHERE aa.UsageType = N'Primary';
UPDATE aa SET aa.HuddleAgentId = new_ag.Id
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities act ON act.Id = aa.HuddleActivityId AND act.ExternalId = N'ALL-DEAL-01'
INNER JOIN dbo.HuddleAgents old_ag ON old_ag.Id = aa.HuddleAgentId AND old_ag.ExternalId = N'AGT-001'
CROSS JOIN (SELECT Id FROM dbo.HuddleAgents WHERE ExternalId = N'AGT-016') new_ag
WHERE aa.UsageType = N'Primary';
UPDATE aa SET aa.HuddleAgentId = new_ag.Id
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities act ON act.Id = aa.HuddleActivityId AND act.ExternalId = N'ALL-DEAL-02'
INNER JOIN dbo.HuddleAgents old_ag ON old_ag.Id = aa.HuddleAgentId AND old_ag.ExternalId = N'AGT-001'
CROSS JOIN (SELECT Id FROM dbo.HuddleAgents WHERE ExternalId = N'AGT-016') new_ag
WHERE aa.UsageType = N'Primary';
UPDATE aa SET aa.HuddleAgentId = new_ag.Id
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities act ON act.Id = aa.HuddleActivityId AND act.ExternalId = N'ALL-DEAL-03'
INNER JOIN dbo.HuddleAgents old_ag ON old_ag.Id = aa.HuddleAgentId AND old_ag.ExternalId = N'AGT-001'
CROSS JOIN (SELECT Id FROM dbo.HuddleAgents WHERE ExternalId = N'AGT-016') new_ag
WHERE aa.UsageType = N'Primary';
UPDATE aa SET aa.HuddleAgentId = new_ag.Id
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities act ON act.Id = aa.HuddleActivityId AND act.ExternalId = N'AE-05-QUOTE-01'
INNER JOIN dbo.HuddleAgents old_ag ON old_ag.Id = aa.HuddleAgentId AND old_ag.ExternalId = N'AGT-001'
CROSS JOIN (SELECT Id FROM dbo.HuddleAgents WHERE ExternalId = N'AGT-016') new_ag
WHERE aa.UsageType = N'Primary';
UPDATE aa SET aa.HuddleAgentId = new_ag.Id
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities act ON act.Id = aa.HuddleActivityId AND act.ExternalId = N'CE-02-BYOD-01'
INNER JOIN dbo.HuddleAgents old_ag ON old_ag.Id = aa.HuddleAgentId AND old_ag.ExternalId = N'AGT-001'
CROSS JOIN (SELECT Id FROM dbo.HuddleAgents WHERE ExternalId = N'AGT-016') new_ag
WHERE aa.UsageType = N'Primary';

-- =====================================================================================
-- 2) Re-attribute 4 existing HuddleAgentResources rows from AGT-001 to AGT-016.
--    Composite PK is (HuddleAgentId, HuddleResourceId); HuddleAgentId is being changed in
--    place. DisplayOrder is unchanged in the workbook for all 4. No UpdatedAtUtc column
--    exists on this table (see note above).
-- =====================================================================================
UPDATE ar SET ar.HuddleAgentId = new_ag.Id
FROM dbo.HuddleAgentResources ar
INNER JOIN dbo.HuddleResources res ON res.Id = ar.HuddleResourceId AND res.ExternalId = N'RES-DA-01'
INNER JOIN dbo.HuddleAgents old_ag ON old_ag.Id = ar.HuddleAgentId AND old_ag.ExternalId = N'AGT-001'
CROSS JOIN (SELECT Id FROM dbo.HuddleAgents WHERE ExternalId = N'AGT-016') new_ag;
UPDATE ar SET ar.HuddleAgentId = new_ag.Id
FROM dbo.HuddleAgentResources ar
INNER JOIN dbo.HuddleResources res ON res.Id = ar.HuddleResourceId AND res.ExternalId = N'RES-DA-05'
INNER JOIN dbo.HuddleAgents old_ag ON old_ag.Id = ar.HuddleAgentId AND old_ag.ExternalId = N'AGT-001'
CROSS JOIN (SELECT Id FROM dbo.HuddleAgents WHERE ExternalId = N'AGT-016') new_ag;
UPDATE ar SET ar.HuddleAgentId = new_ag.Id
FROM dbo.HuddleAgentResources ar
INNER JOIN dbo.HuddleResources res ON res.Id = ar.HuddleResourceId AND res.ExternalId = N'RES-DA-02'
INNER JOIN dbo.HuddleAgents old_ag ON old_ag.Id = ar.HuddleAgentId AND old_ag.ExternalId = N'AGT-001'
CROSS JOIN (SELECT Id FROM dbo.HuddleAgents WHERE ExternalId = N'AGT-016') new_ag;
UPDATE ar SET ar.HuddleAgentId = new_ag.Id
FROM dbo.HuddleAgentResources ar
INNER JOIN dbo.HuddleResources res ON res.Id = ar.HuddleResourceId AND res.ExternalId = N'RES-DA-06'
INNER JOIN dbo.HuddleAgents old_ag ON old_ag.Id = ar.HuddleAgentId AND old_ag.ExternalId = N'AGT-001'
CROSS JOIN (SELECT Id FROM dbo.HuddleAgents WHERE ExternalId = N'AGT-016') new_ag;

-- =====================================================================================
-- 3) Update Activities.LaunchLabel on the same 10 activities, from "Open Sales Agent" to
--    "Open Sales Agent for Deal Agent". LaunchUrl is unchanged (still aka.ms/SalesM365 /
--    the Sales Agent chat URL -- Deal Agent has no separate launch surface).
-- =====================================================================================
UPDATE dbo.HuddleActivities
SET LaunchLabel = N'Open Sales Agent for Deal Agent', UpdatedAtUtc = SYSUTCDATETIME()
WHERE ExternalId IN (N'WF-CE-RENEW-01-P-CE-01', N'CE-02-DEAL-01', N'AE-05-P01', N'AE-05-DEAL-01', N'AE-07-P01', N'ALL-DEAL-01', N'ALL-DEAL-02', N'ALL-DEAL-03', N'AE-05-QUOTE-01', N'CE-02-BYOD-01')
  AND LaunchLabel = N'Open Sales Agent';

-- =====================================================================================
-- 4) Wording-only edits to two already-loaded HuddleAgents rows. No AgentID/FK changes.
--    Review before running -- these overwrite existing description/label text.
-- =====================================================================================

-- AGT-002 (ECIF Agent): WhatItIs, ShortDescription and StepsToGetStarted reworded to lead
-- with "Surfaced through Sales Agent" (matches the same convention now applied to Deal Agent
-- and Sales Home) while still noting ECIF Agent also has its own standalone entry point.
UPDATE dbo.HuddleAgents
SET
    ShortDescription = N'Surfaced through Sales Agent, ECIF Agent brings investment guidance and actions together with account and opportunity data in a single pane of glass. It also exists as a standalone agent with its own entry point, but Sales Agent is the recommended way to use it. It supports the end-to-end ECIF journey, connecting the systems used across it.',
    WhatItIs = N'Surfaced through Sales Agent; also available as a standalone domain agent.',
    StepsToGetStarted = N'Open Sales Agent and ask for ECIF or investment help in the chat. This keeps investment questions alongside account and opportunity data in a single pane of glass. ECIF Agent also has a standalone entry point, but you do not need to open it separately.',
    UpdatedAtUtc = SYSUTCDATETIME()
WHERE ExternalId = N'AGT-002';

-- AGT-013 (Sales Home): WhatItIs now names the SME&C scope explicitly.
UPDATE dbo.HuddleAgents
SET
    WhatItIs = N'SME&C Seller surface within Sales Agent',
    UpdatedAtUtc = SYSUTCDATETIME()
WHERE ExternalId = N'AGT-013';

COMMIT TRANSACTION;
GO
