
SET NOCOUNT ON;
SET XACT_ABORT ON;
DECLARE @unresolved INT;
BEGIN TRANSACTION;

;WITH raw AS (
    SELECT * FROM (VALUES
        (N'DSE-ORIENT', N'SR-SMEC-DSE', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-week huddle motion: why Frontier Accelerator exists, what happens in a thirty-minute huddle, the five roles that make it work, and what is expected of you between sessions.', N'Understand how the huddle motion runs, what you are being asked to do each week, and where your own judgment stays yours.', N'You are Customer Zero. Before we ask a customer to put AI at the centre of how they work, we do it on our own work and find out honestly where it helps and where it does not. The aim is to get time back from the assembling, and to find out first-hand where AI earns that time and where it does not.', N'You know how the motion works, what happens in each huddle, what is expected of you between sessions, and you leave with one thing to try before the next one.', 1),
        (N'DSE-DISC', N'SR-SMEC-DSE', N'WF-X-DISC-01', N'SEC-ROLEPATH', 2, N'Find Out What Has Already Been Discovered', N'Establish what the partner, the DAE and the specialist already know before you start asking, so the customer is not taken through the same questions twice.', N'Work out what discovery has already happened and what only you can establish.', N'Asking a customer something a partner asked them last week makes the whole team look uncoordinated, and it costs you the goodwill you needed for the hard questions.', N'A clear read on what is already known, what is only assumed, and the short list of things that genuinely need you rather than repeating discovery somebody has already done.', 1),
        (N'DSE-PROOF', N'SR-SMEC-DSE', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 4, N'Prove It Without Building It Again', N'Decide the smallest proof that would settle the decision, and reach for something that already exists before building anything bespoke.', N'Settle one customer''s technical doubt without building a proof from scratch.', N'A bespoke proof per customer does not scale to the number of customers you cover. The engineers who keep up are the ones who reuse.', N'The decision the proof must settle named, an existing asset found or ruled out, and the smallest sufficient proof scoped.', 1),
        (N'DSE-CONV', N'SR-SMEC-DSE', N'WF-X-CONV-01', N'SEC-ROLEPATH', 5, N'Answer a Question You Were Not Asked Directly', N'Handle a technical question relayed to you by a partner or a seller, where you are not in the room and your answer will be passed on in your absence.', N'Answer one relayed technical question in a form that survives being repeated by somebody else.', N'Your answer gets forwarded, pasted and paraphrased. Writing it for the person who will relay it, rather than for yourself, is what stops it arriving wrong.', N'The real question established, an answer written to survive relay, and the parts that must not be paraphrased marked.', 1),
        (N'DSE-HEALTH', N'SR-SMEC-DSE', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 6, N'Find the Problem Before the Customer Does', N'Locate the customers running a configuration you already know is fragile, and get the fix moving through whoever actually operates it.', N'Identify which of your customers are exposed to a technical problem you have already seen elsewhere.', N'You will not find these by inspection, because you do not operate any of it and there are too many. You find them by recognizing the pattern you have already met.', N'The exposed customers identified, the ones whose partner already knows separated out, and one fix routed to whoever operates it.', 1),
        (N'DCSA-ORIENT', N'SR-SMEC-DCSA', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-week huddle motion: why Frontier Accelerator exists, what happens in a thirty-minute huddle, the five roles that make it work, and what is expected of you between sessions.', N'Understand how the huddle motion runs, what you are being asked to do each week, and where your own judgment stays yours.', N'You are Customer Zero. Before we ask a customer to put AI at the centre of how they work, we do it on our own work and find out honestly where it helps and where it does not. The aim is to get time back from the assembling, and to find out first-hand where AI earns that time and where it does not.', N'You know how the motion works, what happens in each huddle, what is expected of you between sessions, and you leave with one thing to try before the next one.', 1),
        (N'DCSA-PARTNER', N'SR-SMEC-DCSA', N'WF-X-PARTNER-01', N'SEC-ROLEPATH', 3, N'Get Technical Work Done by People You Do Not Manage', N'Hand technical work to a delivery partner with enough for them to act, and set up a way of knowing whether it landed, without a support agreement or an escalation path behind you.', N'Hand one piece of technical work to a partner in a form they can act on without you.', N'On these accounts there is no Unified agreement and no funded delivery. If the partner cannot act on what you gave them, nothing happens at all.', N'One technical handover a partner can act on unaided, with a named signal that would tell you whether it worked.', 1),
        (N'DCSA-CONV', N'SR-SMEC-DCSA', N'WF-X-CONV-01', N'SEC-ROLEPATH', 4, N'Make the One Conversation Count', N'Prepare for a technical conversation you may not get to repeat, and leave the customer with something that keeps working after you have moved on to the next account.', N'Prepare one customer conversation on the assumption that it is the only one you will get.', N'At this coverage you are not building a relationship, you are making a single intervention. What you leave behind matters more than what you say.', N'A conversation prepared around one decision, with something durable left behind and the next owner named.', 1),
        (N'DCSA-VALUE', N'SR-SMEC-DCSA', N'WF-X-VALUE-01', N'SEC-ROLEPATH', 5, N'Evidence an Outcome Somebody Else Delivered', N'Work out what can honestly be claimed about technical outcomes when a partner did the delivery and there is no support engagement record to draw on.', N'Establish what your portfolio can actually evidence, and get it to the people who need it at renewal.', N'Without a Unified engagement there is no delivery record behind you. If you do not capture the evidence, the renewal conversation happens without it.', N'Outcomes separated into evidenced, partner-held and unevidenced, with the evidenced ones passed to whoever owns the renewal.', 1),
        (N'PSS-ORIENT', N'SR-SMEC-PSS', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-week huddle motion: why Frontier Accelerator exists, what happens in a thirty-minute huddle, the five roles that make it work, and what is expected of you between sessions.', N'Understand how the huddle motion runs, what you are being asked to do each week, and where your own judgment stays yours.', N'You are Customer Zero. Before we ask a customer to put AI at the centre of how they work, we do it on our own work and find out honestly where it helps and where it does not. The aim is to get time back from the assembling, and to find out first-hand where AI earns that time and where it does not.', N'You know how the motion works, what happens in each huddle, what is expected of you between sessions, and you leave with one thing to try before the next one.', 1),
        (N'PSS-DEMAND', N'SR-SMEC-PSS', N'WF-X-OPP-01', N'SEC-ROLEPATH', 4, N'Work the Demand Coming the Other Way', N'Handle opportunity that originates with a partner and arrives at Microsoft, where the qualification you can do is limited and the clock is already running.', N'Take one partner-originated opportunity and establish whether it is real before the window closes on it.', N'Everyone else pushes work out to partners. You also receive it, and what arrives is qualified to the partner''s standard rather than to yours.', N'Partner-originated opportunities separated by what can actually be verified, with one progressed and the registration requirements checked.', 1),
        (N'PSS-ORCH', N'SR-SMEC-PSS', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 5, N'Run a Rhythm Across More Partners Than You Can Meet', N'Decide which partners get your time this month and what each meeting is actually for, when the commitment is a minimum cadence per partner seller.', N'Decide which partners get your attention this month and which get a lighter touch, deliberately.', N'A cadence obligation across a portfolio becomes a calendar full of status meetings unless somebody decides what each one is for.', N'Your partner portfolio triaged for the month, with the meetings that need an agenda separated from the ones that need only a check-in.', 1),
        (N'PSS-VALUE', N'SR-SMEC-PSS', N'WF-X-VALUE-01', N'SEC-ROLEPATH', 6, N'Find Out What Happened After the Partner Closed It', N'Close the visibility gap that opens once a partner transacts and delivers, because you are the only route Microsoft has back to what the customer actually got.', N'Establish what is known about outcomes at customers your partners closed, and what only the partner can tell you.', N'Once a partner closes and delivers, Microsoft largely stops seeing the customer. If you do not ask, nobody finds out until the renewal.', N'The visibility gap mapped across recent partner-closed deals, with one partner asked directly about outcomes.', 1),
        (N'SMEC-CE-POLICY', N'SR-SMEC-CE', N'WF-X-POLICY-01', N'SEC-ROLEPATH', 5, N'Check the Rules Before the Structure Hardens', N'Run a deal against the policy, licensing and eligibility questions it will eventually meet, at a point where the answer can still change the shape.', N'Find the policy question on one live deal that would be expensive to discover at approval.', N'Policy questions found at approval cost weeks. Found now they cost a conversation, and you are the only person on the deal who will think to ask.', N'One deal checked against the questions it will face, with every unresolved item routed to the authoritative owner rather than guessed.', 1),
        (N'SMEC-CE-NEG', N'SR-SMEC-CE', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 6, N'Prepare the Negotiation You May Not Be In', N'Set the concession logic and authority boundaries for a negotiation that a partner may actually conduct, so the limits hold when you are not in the room.', N'Set the concession boundary on one deal before anyone is under pressure to move it.', N'A boundary defined in the room is defined under pressure by whoever is least able to be objective about it. Yours has to survive being applied by someone else.', N'Concession logic and authority limits written down, with the escalation trigger named and the partner briefed on what they cannot concede.', 1),
        (N'SMEC-CE-ORCH', N'SR-SMEC-CE', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 7, N'Get the Approvals Moving When You Do Not Own the Deal', N'Route commercial approvals and execution steps to named owners on a deal where the partner transacts and several of the steps are not yours to take.', N'Replace every implied approval owner on one deal with a named one.', N'Approvals discovered one at a time cost a week each. At this book size nobody is going to map them for you, and the partner cannot.', N'The approval path mapped with a named owner and required evidence for each step, and the steps that belong to the partner identified as theirs.', 1),
        (N'SMEC-CE-DEAL2', N'SR-SMEC-CE', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 8, N'Make the Commercial Case Reviewable', N'Turn an agreed commercial structure into a narrative an approver or a customer executive can inspect and act on, in a segment where you will usually not be in the room to explain it.', N'Turn one commercial structure into a narrative that can be approved without you present.', N'Commercial logic that only lives in your head cannot be approved by anyone else. Through a partner, you are not there to explain it.', N'A commercial narrative that states the decision being asked for, traces every figure to a source, names its assumptions, and sets out the approval route.', 1),
        (N'DCSA-ARCH', N'SR-SMEC-DCSA', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 6, N'Design Something That Will Run Without You There', N'Shape a deployment-ready architecture for a customer you will not be on site for, where a partner or the customer''s own team does the building and nobody has premier support to fall back on.', N'Take one design and make it survivable by the people who will actually operate it.', N'A design that needs you present to work is a design that fails the week you move to the next account. At this portfolio size you are never coming back.', N'One architecture tested against who will build it, who will run it, and what happens when it breaks with nobody senior in the room.', 1),
        (N'DCSA-HEALTH', N'SR-SMEC-DCSA', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 7, N'Find the Technical Problem Before It Reaches the Number', N'Work technical health across a portfolio too large to inspect account by account, and decide which risk is worth your time while it is still cheap to fix.', N'Find the technical risk in your portfolio that will be expensive if it is found late, and start on it.', N'Consumption falling is the last signal you get, not the first. By the time it shows in the number, the technical cause is months old and the customer has already worked around you.', N'The portfolio scanned for technical risk, the most costly one identified with evidence, and a standing check set up so the next one reaches you sooner.', 1),
        (N'DCSA-EXPAND', N'SR-SMEC-DCSA', N'WF-X-RENEW-01', N'SEC-ROLEPATH', 8, N'Find the Next Workload Inside the One That Works', N'Use deployment and usage evidence to identify the workload a customer is genuinely ready for, rather than the one that is easiest to propose.', N'Test one expansion idea against what the customer is actually succeeding with.', N'The best expansion signal you will ever get is a workload the customer is already running well. Everything else is a pitch, and at this volume pitches do not scale.', N'One evidenced expansion hypothesis with the readiness signal named, handed to whoever owns the commercial conversation.', 1),
        (N'DSE-ASSET', N'SR-SMEC-DSE', N'WF-X-ASSET-01', N'SEC-ROLEPATH', 7, N'Stop Rebuilding What You Already Built', N'Turn work you have already done into something a colleague can pick up without asking you first, in a segment where the same technical problem arrives repeatedly across different customers.', N'Capture one thing you built so another engineer could use it unaided.', N'At this volume, rebuilding what exists is the single most expensive habit available to you. The same question is being answered from scratch across the team every week.', N'One reusable asset captured with enough context that somebody who was not there can tell whether it fits their situation.', 1),
        (N'DSE-PARTNER', N'SR-SMEC-DSE', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 8, N'Close the Partner Capability Gap That Is Holding a Deal', N'Find where a partner''s technical confidence is what is actually stopping a partner-led opportunity, and close that gap rather than doing the work for them.', N'Find one partner technical gap that is blocking progress and start closing it.', N'When a partner-led opportunity stalls, partner technical confidence is a cause worth testing before you look at the product. Doing the work yourself closes this deal and leaves the same gap open for the next one.', N'One partner capability gap named with evidence, and an enablement action owned and dated rather than absorbed by you.', 1),
        (N'DSS-COMP', N'SR-SMEC-DSS', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 7, N'Build a Competitive Position the Customer Would Recognize', N'Work out where your solution area genuinely wins against what the customer is actually comparing it to, and where it does not.', N'Test one competitive position against the customer''s real decision criteria rather than against a feature list.', N'A differentiator the customer does not value is a feature, not an advantage. At this volume you will not get a second meeting to correct the framing.', N'A competitive position the customer would recognize, where differentiation is evidenced, genuine gaps are named rather than defended, and the objections you will actually meet are prepared.', 1),
        (N'DSS-ORCH', N'SR-SMEC-DSS', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 8, N'Make the Ask Specific Enough to Be Accepted', N'Mobilize the technical, partner or funding support an opportunity needs, in a segment where nobody is assigned to your deal and every ask competes with someone else''s.', N'Turn one vague support need into a specific ask with a named owner and a date.', N'A vague ask gets a vague response two weeks later. You have no v-team and no assigned specialists, so how you ask is most of whether you get it.', N'One support ask made specific, sent to a named person, with a date and a standing check on whether it was answered.', 1),
        (N'PSS-CAPACITY', N'SR-SMEC-PSS', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 7, N'Confirm the Partner Has the Capacity to Deliver', N'Assess whether a partner has the capability and the capacity to deliver what is being routed to them, before the customer finds out they do not.', N'Find the capability or capacity gap most likely to stall partner-led delivery, and name what closing it would take.', N'Routing work to a partner who cannot deliver it damages the customer and the partner at once, and you will be the one who chose them.', N'A readiness view where demonstrated capability is separated from asserted capacity, one gap is named, and the closing action carries an owner and a date.', 1),
        (N'PSS-CONV', N'SR-SMEC-PSS', N'WF-X-CONV-01', N'SEC-ROLEPATH', 8, N'Have the Conversation in the Partner''s Economics', N'Prepare the partner conversation that changes behavior, grounded in what the partner''s business actually gains rather than in what Microsoft needs.', N'Prepare one partner conversation framed in the partner''s own economics with a specific ask.', N'Partners act on their business case, not on our targets. A conversation framed in Microsoft priorities gets agreement in the room and nothing afterwards.', N'A partner conversation brief in the partner''s terms, with one specific ask and the likely objections prepared.', 1),
        (N'DSS-INVEST', N'SR-SMEC-DSS', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Choose the Investment Route Before You Build the Case', N'Work out which investment route a solution-area opportunity actually qualifies for, before spending effort on a request that was never going to fit.', N'Match one opportunity to the investment route it genuinely qualifies for.', N'Picking the wrong investment vehicle means rebuilding the request against the right one. The selection takes an hour and the rebuild takes two weeks.', N'One opportunity matched to a route, with the eligibility questions routed to their authoritative owner rather than assumed.', 1),
        (N'PSS-INVEST', N'SR-SMEC-PSS', N'WF-INVEST-01', N'SEC-ADDITIONAL', 3, N'Use the Partner-Led Investment Routes Properly', N'Work the investment routes that run through partners rather than around them, which is where most SME&C investment actually sits.', N'Match one partner opportunity to the partner-led investment route it qualifies for.', N'Most SME&C investment is partner-led by design. If you only know the direct route you are working the smallest part of what is available.', N'One partner opportunity matched to a partner-led route, with the partner''s own obligations under it made explicit to them.', 1),
        (N'DAE-INVEST', N'SR-SMEC-DAE', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Spot the Deal Where Investment Would Change the Answer', N'Recognize the account situations where customer investment is a genuine lever, and hand them to whoever owns the request.', N'Identify one account where investment would change the outcome, and route it.', N'You see the barrier first and more often than anyone else. Recognizing the ones investment can move is most of the value you add here.', N'One account identified where investment is a plausible lever, with the barrier evidenced and the request routed to its owner.', 1),
        (N'DSE-INVEST', N'SR-SMEC-DSE', N'WF-INVEST-01', N'SEC-ADDITIONAL', 2, N'Define What an Investment-Funded Proof Must Show', N'Set the technical success and exit criteria for work that customer investment would fund, before it is requested.', N'Define what one funded piece of technical work must demonstrate, observably.', N'You will be asked what the funded work proved. Deciding that before it starts is the difference between evidence and an argument.', N'Observable success and exit criteria for one investment-funded piece of technical work.', 1),
        (N'DCSA-INVEST', N'SR-SMEC-DCSA', N'WF-INVEST-01', N'SEC-ADDITIONAL', 2, N'Confirm the Customer Can Absorb the Funded Work', N'Check delivery readiness for work customer investment would fund, in an environment with no dedicated support relationship.', N'Establish whether one customer could absorb funded technical work, and what would block it.', N'Funded work that stalls on a customer-side dependency is recorded as a Microsoft delivery failure, and you are the person who could have seen it coming.', N'A readiness view for one funded engagement with the blocking dependencies named and owned.', 1),
        (N'SMEC-CE-INVEST', N'SR-SMEC-CE', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Know Where Investment Meets Commercial Structure', N'Recognize where a customer investment interacts with commercial structure and precedent, in a segment where the CE does not own the investment request.', N'Know what to look for when an investment appears on a deal you are structuring.', N'You will meet investment on deals you structure without owning the request. Knowing where it touches commercial precedent is the part that is yours.', N'An understanding of where investment interacts with commercial structure, and what to raise when it does.', 1),
        (N'ALL-CLOSEDWON', N'SR-ENT-ALL', N'WF-X-PIPE-01', N'SEC-ADDITIONAL', 99, N'Check What Closed in Your Book', N'Review recent closed-won opportunities in your book and decide whether each record describes what actually happened.', N'Work through recent closed-won records and decide which ones you can stand behind.', N'A closed record carries your number whether or not you set it, and one you cannot account for is still yours to explain.', N'Recent closed-won opportunities reviewed against what you know, each classified as accounted for or questionable, and any questionable record acted on - or none found, and that recorded.', 1),
        (N'CSA-VSAT', N'SR-ENT-CSA', N'WF-X-VSAT-01', N'SEC-ADDITIONAL', 2, N'Protect Customer Satisfaction on the Delivery You Own', N'Read the satisfaction signals in a live delivery, decide which one would show up in the survey, and act on it while the delivery is still running.', N'Find the thing this customer would mark you down for, and deal with it before they are asked.', N'A survey score arrives after you can do anything about it. The signals arrive while you still can.', N'A satisfaction read where the risk is evidenced rather than felt, one action is owned, and anything belonging to another role has been routed rather than absorbed.', 1),
        (N'CSA-TECHLEAD', N'SR-ENT-CSA', N'WF-X-TECHLEAD-01', N'SEC-ADDITIONAL', 3, N'Become the Technical Advisor the Customer Asks For', N'Work out what this customer''s roadmap will need you to be credible on next, compare that honestly against what you can speak to today, and close one gap.', N'Name the one thing your customer will need you to know next that you could not defend today.', N'You get called in when you are the person who can answer. That list of topics is set by the customer''s roadmap, not yours.', N'A credibility position where the customer''s next technical demand is named, the gap between that and what you can defend today is stated plainly, and one specific step to close it is owned.', 1)
    ) v([ExternalId], [SegmentRoleExternalId], [TopicExternalId], [PathSection], [Sequence], [RoleTopicName], [RoleTopicDescription], [TodayObjective], [Wiifm], [DesiredOutcome], [IsActive])
), src AS (
    SELECT raw.*, sr.Id AS [HuddleSegmentRoleId], t.Id AS [HuddleTopicId]
    FROM raw
    INNER JOIN dbo.HuddleSegmentRoles AS sr ON sr.[ExternalId] = raw.[SegmentRoleExternalId]
    INNER JOIN dbo.HuddleTopics AS t ON t.[ExternalId] = raw.[TopicExternalId]
)
MERGE dbo.HuddlePlacements AS tgt
USING src ON tgt.[ExternalId] = src.[ExternalId]
WHEN MATCHED THEN UPDATE SET
        tgt.[HuddleSegmentRoleId] = src.[HuddleSegmentRoleId],
        tgt.[HuddleTopicId] = src.[HuddleTopicId],
        tgt.[PathSection] = src.[PathSection],
        tgt.[Sequence] = src.[Sequence],
        tgt.[RoleTopicName] = src.[RoleTopicName],
        tgt.[RoleTopicDescription] = src.[RoleTopicDescription],
        tgt.[TodayObjective] = src.[TodayObjective],
        tgt.[Wiifm] = src.[Wiifm],
        tgt.[DesiredOutcome] = src.[DesiredOutcome],
        tgt.[IsActive] = src.[IsActive],
        tgt.[UpdatedAtUtc] = SYSUTCDATETIME()
WHEN NOT MATCHED BY TARGET THEN INSERT ([ExternalId], [HuddleSegmentRoleId], [HuddleTopicId], [PathSection], [Sequence], [RoleTopicName], [RoleTopicDescription], [TodayObjective], [Wiifm], [DesiredOutcome], [IsActive], [CreatedAtUtc])
    VALUES (src.[ExternalId], src.[HuddleSegmentRoleId], src.[HuddleTopicId], src.[PathSection], src.[Sequence], src.[RoleTopicName], src.[RoleTopicDescription], src.[TodayObjective], src.[Wiifm], src.[DesiredOutcome], src.[IsActive], SYSUTCDATETIME());
;WITH raw AS (
    SELECT * FROM (VALUES
        (N'DSE-ORIENT', N'SR-SMEC-DSE', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-week huddle motion: why Frontier Accelerator exists, what happens in a thirty-minute huddle, the five roles that make it work, and what is expected of you between sessions.', N'Understand how the huddle motion runs, what you are being asked to do each week, and where your own judgment stays yours.', N'You are Customer Zero. Before we ask a customer to put AI at the centre of how they work, we do it on our own work and find out honestly where it helps and where it does not. The aim is to get time back from the assembling, and to find out first-hand where AI earns that time and where it does not.', N'You know how the motion works, what happens in each huddle, what is expected of you between sessions, and you leave with one thing to try before the next one.', 1),
        (N'DSE-DISC', N'SR-SMEC-DSE', N'WF-X-DISC-01', N'SEC-ROLEPATH', 2, N'Find Out What Has Already Been Discovered', N'Establish what the partner, the DAE and the specialist already know before you start asking, so the customer is not taken through the same questions twice.', N'Work out what discovery has already happened and what only you can establish.', N'Asking a customer something a partner asked them last week makes the whole team look uncoordinated, and it costs you the goodwill you needed for the hard questions.', N'A clear read on what is already known, what is only assumed, and the short list of things that genuinely need you rather than repeating discovery somebody has already done.', 1),
        (N'DSE-PROOF', N'SR-SMEC-DSE', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 4, N'Prove It Without Building It Again', N'Decide the smallest proof that would settle the decision, and reach for something that already exists before building anything bespoke.', N'Settle one customer''s technical doubt without building a proof from scratch.', N'A bespoke proof per customer does not scale to the number of customers you cover. The engineers who keep up are the ones who reuse.', N'The decision the proof must settle named, an existing asset found or ruled out, and the smallest sufficient proof scoped.', 1),
        (N'DSE-CONV', N'SR-SMEC-DSE', N'WF-X-CONV-01', N'SEC-ROLEPATH', 5, N'Answer a Question You Were Not Asked Directly', N'Handle a technical question relayed to you by a partner or a seller, where you are not in the room and your answer will be passed on in your absence.', N'Answer one relayed technical question in a form that survives being repeated by somebody else.', N'Your answer gets forwarded, pasted and paraphrased. Writing it for the person who will relay it, rather than for yourself, is what stops it arriving wrong.', N'The real question established, an answer written to survive relay, and the parts that must not be paraphrased marked.', 1),
        (N'DSE-HEALTH', N'SR-SMEC-DSE', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 6, N'Find the Problem Before the Customer Does', N'Locate the customers running a configuration you already know is fragile, and get the fix moving through whoever actually operates it.', N'Identify which of your customers are exposed to a technical problem you have already seen elsewhere.', N'You will not find these by inspection, because you do not operate any of it and there are too many. You find them by recognizing the pattern you have already met.', N'The exposed customers identified, the ones whose partner already knows separated out, and one fix routed to whoever operates it.', 1),
        (N'DCSA-ORIENT', N'SR-SMEC-DCSA', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-week huddle motion: why Frontier Accelerator exists, what happens in a thirty-minute huddle, the five roles that make it work, and what is expected of you between sessions.', N'Understand how the huddle motion runs, what you are being asked to do each week, and where your own judgment stays yours.', N'You are Customer Zero. Before we ask a customer to put AI at the centre of how they work, we do it on our own work and find out honestly where it helps and where it does not. The aim is to get time back from the assembling, and to find out first-hand where AI earns that time and where it does not.', N'You know how the motion works, what happens in each huddle, what is expected of you between sessions, and you leave with one thing to try before the next one.', 1),
        (N'DCSA-PARTNER', N'SR-SMEC-DCSA', N'WF-X-PARTNER-01', N'SEC-ROLEPATH', 3, N'Get Technical Work Done by People You Do Not Manage', N'Hand technical work to a delivery partner with enough for them to act, and set up a way of knowing whether it landed, without a support agreement or an escalation path behind you.', N'Hand one piece of technical work to a partner in a form they can act on without you.', N'On these accounts there is no Unified agreement and no funded delivery. If the partner cannot act on what you gave them, nothing happens at all.', N'One technical handover a partner can act on unaided, with a named signal that would tell you whether it worked.', 1),
        (N'DCSA-CONV', N'SR-SMEC-DCSA', N'WF-X-CONV-01', N'SEC-ROLEPATH', 4, N'Make the One Conversation Count', N'Prepare for a technical conversation you may not get to repeat, and leave the customer with something that keeps working after you have moved on to the next account.', N'Prepare one customer conversation on the assumption that it is the only one you will get.', N'At this coverage you are not building a relationship, you are making a single intervention. What you leave behind matters more than what you say.', N'A conversation prepared around one decision, with something durable left behind and the next owner named.', 1),
        (N'DCSA-VALUE', N'SR-SMEC-DCSA', N'WF-X-VALUE-01', N'SEC-ROLEPATH', 5, N'Evidence an Outcome Somebody Else Delivered', N'Work out what can honestly be claimed about technical outcomes when a partner did the delivery and there is no support engagement record to draw on.', N'Establish what your portfolio can actually evidence, and get it to the people who need it at renewal.', N'Without a Unified engagement there is no delivery record behind you. If you do not capture the evidence, the renewal conversation happens without it.', N'Outcomes separated into evidenced, partner-held and unevidenced, with the evidenced ones passed to whoever owns the renewal.', 1),
        (N'PSS-ORIENT', N'SR-SMEC-PSS', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-week huddle motion: why Frontier Accelerator exists, what happens in a thirty-minute huddle, the five roles that make it work, and what is expected of you between sessions.', N'Understand how the huddle motion runs, what you are being asked to do each week, and where your own judgment stays yours.', N'You are Customer Zero. Before we ask a customer to put AI at the centre of how they work, we do it on our own work and find out honestly where it helps and where it does not. The aim is to get time back from the assembling, and to find out first-hand where AI earns that time and where it does not.', N'You know how the motion works, what happens in each huddle, what is expected of you between sessions, and you leave with one thing to try before the next one.', 1),
        (N'PSS-DEMAND', N'SR-SMEC-PSS', N'WF-X-OPP-01', N'SEC-ROLEPATH', 4, N'Work the Demand Coming the Other Way', N'Handle opportunity that originates with a partner and arrives at Microsoft, where the qualification you can do is limited and the clock is already running.', N'Take one partner-originated opportunity and establish whether it is real before the window closes on it.', N'Everyone else pushes work out to partners. You also receive it, and what arrives is qualified to the partner''s standard rather than to yours.', N'Partner-originated opportunities separated by what can actually be verified, with one progressed and the registration requirements checked.', 1),
        (N'PSS-ORCH', N'SR-SMEC-PSS', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 5, N'Run a Rhythm Across More Partners Than You Can Meet', N'Decide which partners get your time this month and what each meeting is actually for, when the commitment is a minimum cadence per partner seller.', N'Decide which partners get your attention this month and which get a lighter touch, deliberately.', N'A cadence obligation across a portfolio becomes a calendar full of status meetings unless somebody decides what each one is for.', N'Your partner portfolio triaged for the month, with the meetings that need an agenda separated from the ones that need only a check-in.', 1),
        (N'PSS-VALUE', N'SR-SMEC-PSS', N'WF-X-VALUE-01', N'SEC-ROLEPATH', 6, N'Find Out What Happened After the Partner Closed It', N'Close the visibility gap that opens once a partner transacts and delivers, because you are the only route Microsoft has back to what the customer actually got.', N'Establish what is known about outcomes at customers your partners closed, and what only the partner can tell you.', N'Once a partner closes and delivers, Microsoft largely stops seeing the customer. If you do not ask, nobody finds out until the renewal.', N'The visibility gap mapped across recent partner-closed deals, with one partner asked directly about outcomes.', 1),
        (N'SMEC-CE-POLICY', N'SR-SMEC-CE', N'WF-X-POLICY-01', N'SEC-ROLEPATH', 5, N'Check the Rules Before the Structure Hardens', N'Run a deal against the policy, licensing and eligibility questions it will eventually meet, at a point where the answer can still change the shape.', N'Find the policy question on one live deal that would be expensive to discover at approval.', N'Policy questions found at approval cost weeks. Found now they cost a conversation, and you are the only person on the deal who will think to ask.', N'One deal checked against the questions it will face, with every unresolved item routed to the authoritative owner rather than guessed.', 1),
        (N'SMEC-CE-NEG', N'SR-SMEC-CE', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 6, N'Prepare the Negotiation You May Not Be In', N'Set the concession logic and authority boundaries for a negotiation that a partner may actually conduct, so the limits hold when you are not in the room.', N'Set the concession boundary on one deal before anyone is under pressure to move it.', N'A boundary defined in the room is defined under pressure by whoever is least able to be objective about it. Yours has to survive being applied by someone else.', N'Concession logic and authority limits written down, with the escalation trigger named and the partner briefed on what they cannot concede.', 1),
        (N'SMEC-CE-ORCH', N'SR-SMEC-CE', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 7, N'Get the Approvals Moving When You Do Not Own the Deal', N'Route commercial approvals and execution steps to named owners on a deal where the partner transacts and several of the steps are not yours to take.', N'Replace every implied approval owner on one deal with a named one.', N'Approvals discovered one at a time cost a week each. At this book size nobody is going to map them for you, and the partner cannot.', N'The approval path mapped with a named owner and required evidence for each step, and the steps that belong to the partner identified as theirs.', 1),
        (N'SMEC-CE-DEAL2', N'SR-SMEC-CE', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 8, N'Make the Commercial Case Reviewable', N'Turn an agreed commercial structure into a narrative an approver or a customer executive can inspect and act on, in a segment where you will usually not be in the room to explain it.', N'Turn one commercial structure into a narrative that can be approved without you present.', N'Commercial logic that only lives in your head cannot be approved by anyone else. Through a partner, you are not there to explain it.', N'A commercial narrative that states the decision being asked for, traces every figure to a source, names its assumptions, and sets out the approval route.', 1),
        (N'DCSA-ARCH', N'SR-SMEC-DCSA', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 6, N'Design Something That Will Run Without You There', N'Shape a deployment-ready architecture for a customer you will not be on site for, where a partner or the customer''s own team does the building and nobody has premier support to fall back on.', N'Take one design and make it survivable by the people who will actually operate it.', N'A design that needs you present to work is a design that fails the week you move to the next account. At this portfolio size you are never coming back.', N'One architecture tested against who will build it, who will run it, and what happens when it breaks with nobody senior in the room.', 1),
        (N'DCSA-HEALTH', N'SR-SMEC-DCSA', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 7, N'Find the Technical Problem Before It Reaches the Number', N'Work technical health across a portfolio too large to inspect account by account, and decide which risk is worth your time while it is still cheap to fix.', N'Find the technical risk in your portfolio that will be expensive if it is found late, and start on it.', N'Consumption falling is the last signal you get, not the first. By the time it shows in the number, the technical cause is months old and the customer has already worked around you.', N'The portfolio scanned for technical risk, the most costly one identified with evidence, and a standing check set up so the next one reaches you sooner.', 1),
        (N'DCSA-EXPAND', N'SR-SMEC-DCSA', N'WF-X-RENEW-01', N'SEC-ROLEPATH', 8, N'Find the Next Workload Inside the One That Works', N'Use deployment and usage evidence to identify the workload a customer is genuinely ready for, rather than the one that is easiest to propose.', N'Test one expansion idea against what the customer is actually succeeding with.', N'The best expansion signal you will ever get is a workload the customer is already running well. Everything else is a pitch, and at this volume pitches do not scale.', N'One evidenced expansion hypothesis with the readiness signal named, handed to whoever owns the commercial conversation.', 1),
        (N'DSE-ASSET', N'SR-SMEC-DSE', N'WF-X-ASSET-01', N'SEC-ROLEPATH', 7, N'Stop Rebuilding What You Already Built', N'Turn work you have already done into something a colleague can pick up without asking you first, in a segment where the same technical problem arrives repeatedly across different customers.', N'Capture one thing you built so another engineer could use it unaided.', N'At this volume, rebuilding what exists is the single most expensive habit available to you. The same question is being answered from scratch across the team every week.', N'One reusable asset captured with enough context that somebody who was not there can tell whether it fits their situation.', 1),
        (N'DSE-PARTNER', N'SR-SMEC-DSE', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 8, N'Close the Partner Capability Gap That Is Holding a Deal', N'Find where a partner''s technical confidence is what is actually stopping a partner-led opportunity, and close that gap rather than doing the work for them.', N'Find one partner technical gap that is blocking progress and start closing it.', N'When a partner-led opportunity stalls, partner technical confidence is a cause worth testing before you look at the product. Doing the work yourself closes this deal and leaves the same gap open for the next one.', N'One partner capability gap named with evidence, and an enablement action owned and dated rather than absorbed by you.', 1),
        (N'DSS-COMP', N'SR-SMEC-DSS', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 7, N'Build a Competitive Position the Customer Would Recognize', N'Work out where your solution area genuinely wins against what the customer is actually comparing it to, and where it does not.', N'Test one competitive position against the customer''s real decision criteria rather than against a feature list.', N'A differentiator the customer does not value is a feature, not an advantage. At this volume you will not get a second meeting to correct the framing.', N'A competitive position the customer would recognize, where differentiation is evidenced, genuine gaps are named rather than defended, and the objections you will actually meet are prepared.', 1),
        (N'DSS-ORCH', N'SR-SMEC-DSS', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 8, N'Make the Ask Specific Enough to Be Accepted', N'Mobilize the technical, partner or funding support an opportunity needs, in a segment where nobody is assigned to your deal and every ask competes with someone else''s.', N'Turn one vague support need into a specific ask with a named owner and a date.', N'A vague ask gets a vague response two weeks later. You have no v-team and no assigned specialists, so how you ask is most of whether you get it.', N'One support ask made specific, sent to a named person, with a date and a standing check on whether it was answered.', 1),
        (N'PSS-CAPACITY', N'SR-SMEC-PSS', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 7, N'Confirm the Partner Has the Capacity to Deliver', N'Assess whether a partner has the capability and the capacity to deliver what is being routed to them, before the customer finds out they do not.', N'Find the capability or capacity gap most likely to stall partner-led delivery, and name what closing it would take.', N'Routing work to a partner who cannot deliver it damages the customer and the partner at once, and you will be the one who chose them.', N'A readiness view where demonstrated capability is separated from asserted capacity, one gap is named, and the closing action carries an owner and a date.', 1),
        (N'PSS-CONV', N'SR-SMEC-PSS', N'WF-X-CONV-01', N'SEC-ROLEPATH', 8, N'Have the Conversation in the Partner''s Economics', N'Prepare the partner conversation that changes behavior, grounded in what the partner''s business actually gains rather than in what Microsoft needs.', N'Prepare one partner conversation framed in the partner''s own economics with a specific ask.', N'Partners act on their business case, not on our targets. A conversation framed in Microsoft priorities gets agreement in the room and nothing afterwards.', N'A partner conversation brief in the partner''s terms, with one specific ask and the likely objections prepared.', 1),
        (N'DSS-INVEST', N'SR-SMEC-DSS', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Choose the Investment Route Before You Build the Case', N'Work out which investment route a solution-area opportunity actually qualifies for, before spending effort on a request that was never going to fit.', N'Match one opportunity to the investment route it genuinely qualifies for.', N'Picking the wrong investment vehicle means rebuilding the request against the right one. The selection takes an hour and the rebuild takes two weeks.', N'One opportunity matched to a route, with the eligibility questions routed to their authoritative owner rather than assumed.', 1),
        (N'PSS-INVEST', N'SR-SMEC-PSS', N'WF-INVEST-01', N'SEC-ADDITIONAL', 3, N'Use the Partner-Led Investment Routes Properly', N'Work the investment routes that run through partners rather than around them, which is where most SME&C investment actually sits.', N'Match one partner opportunity to the partner-led investment route it qualifies for.', N'Most SME&C investment is partner-led by design. If you only know the direct route you are working the smallest part of what is available.', N'One partner opportunity matched to a partner-led route, with the partner''s own obligations under it made explicit to them.', 1),
        (N'DAE-INVEST', N'SR-SMEC-DAE', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Spot the Deal Where Investment Would Change the Answer', N'Recognize the account situations where customer investment is a genuine lever, and hand them to whoever owns the request.', N'Identify one account where investment would change the outcome, and route it.', N'You see the barrier first and more often than anyone else. Recognizing the ones investment can move is most of the value you add here.', N'One account identified where investment is a plausible lever, with the barrier evidenced and the request routed to its owner.', 1),
        (N'DSE-INVEST', N'SR-SMEC-DSE', N'WF-INVEST-01', N'SEC-ADDITIONAL', 2, N'Define What an Investment-Funded Proof Must Show', N'Set the technical success and exit criteria for work that customer investment would fund, before it is requested.', N'Define what one funded piece of technical work must demonstrate, observably.', N'You will be asked what the funded work proved. Deciding that before it starts is the difference between evidence and an argument.', N'Observable success and exit criteria for one investment-funded piece of technical work.', 1),
        (N'DCSA-INVEST', N'SR-SMEC-DCSA', N'WF-INVEST-01', N'SEC-ADDITIONAL', 2, N'Confirm the Customer Can Absorb the Funded Work', N'Check delivery readiness for work customer investment would fund, in an environment with no dedicated support relationship.', N'Establish whether one customer could absorb funded technical work, and what would block it.', N'Funded work that stalls on a customer-side dependency is recorded as a Microsoft delivery failure, and you are the person who could have seen it coming.', N'A readiness view for one funded engagement with the blocking dependencies named and owned.', 1),
        (N'SMEC-CE-INVEST', N'SR-SMEC-CE', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Know Where Investment Meets Commercial Structure', N'Recognize where a customer investment interacts with commercial structure and precedent, in a segment where the CE does not own the investment request.', N'Know what to look for when an investment appears on a deal you are structuring.', N'You will meet investment on deals you structure without owning the request. Knowing where it touches commercial precedent is the part that is yours.', N'An understanding of where investment interacts with commercial structure, and what to raise when it does.', 1),
        (N'ALL-CLOSEDWON', N'SR-ENT-ALL', N'WF-X-PIPE-01', N'SEC-ADDITIONAL', 99, N'Check What Closed in Your Book', N'Review recent closed-won opportunities in your book and decide whether each record describes what actually happened.', N'Work through recent closed-won records and decide which ones you can stand behind.', N'A closed record carries your number whether or not you set it, and one you cannot account for is still yours to explain.', N'Recent closed-won opportunities reviewed against what you know, each classified as accounted for or questionable, and any questionable record acted on - or none found, and that recorded.', 1),
        (N'CSA-VSAT', N'SR-ENT-CSA', N'WF-X-VSAT-01', N'SEC-ADDITIONAL', 2, N'Protect Customer Satisfaction on the Delivery You Own', N'Read the satisfaction signals in a live delivery, decide which one would show up in the survey, and act on it while the delivery is still running.', N'Find the thing this customer would mark you down for, and deal with it before they are asked.', N'A survey score arrives after you can do anything about it. The signals arrive while you still can.', N'A satisfaction read where the risk is evidenced rather than felt, one action is owned, and anything belonging to another role has been routed rather than absorbed.', 1),
        (N'CSA-TECHLEAD', N'SR-ENT-CSA', N'WF-X-TECHLEAD-01', N'SEC-ADDITIONAL', 3, N'Become the Technical Advisor the Customer Asks For', N'Work out what this customer''s roadmap will need you to be credible on next, compare that honestly against what you can speak to today, and close one gap.', N'Name the one thing your customer will need you to know next that you could not defend today.', N'You get called in when you are the person who can answer. That list of topics is set by the customer''s roadmap, not yours.', N'A credibility position where the customer''s next technical demand is named, the gap between that and what you can defend today is stated plainly, and one specific step to close it is owned.', 1)
    ) v([ExternalId], [SegmentRoleExternalId], [TopicExternalId], [PathSection], [Sequence], [RoleTopicName], [RoleTopicDescription], [TodayObjective], [Wiifm], [DesiredOutcome], [IsActive])
)
SELECT @unresolved = 35 - COUNT(*) FROM raw
    INNER JOIN dbo.HuddleSegmentRoles AS sr ON sr.[ExternalId] = raw.[SegmentRoleExternalId]
    INNER JOIN dbo.HuddleTopics AS t ON t.[ExternalId] = raw.[TopicExternalId];
IF @unresolved <> 0
    THROW 51000, 'HuddlePlacements (new): 35 source rows were expected to resolve their foreign keys but some did not. Run the earlier scripts in order and re-check the workbook.', 1;

-- HuddleRolePathItems for the new placements that fit its (SegmentRole,WeekPosition) key.
;WITH raw AS (
    SELECT * FROM (VALUES
        (N'SR-SMEC-DSE', 1, N'WF-ORIENT-01'),
        (N'SR-SMEC-DSE', 2, N'WF-X-DISC-01'),
        (N'SR-SMEC-DSE', 4, N'WF-X-ARCH-01'),
        (N'SR-SMEC-DSE', 5, N'WF-X-CONV-01'),
        (N'SR-SMEC-DSE', 6, N'WF-X-HEALTH-01'),
        (N'SR-SMEC-DCSA', 1, N'WF-ORIENT-01'),
        (N'SR-SMEC-DCSA', 3, N'WF-X-PARTNER-01'),
        (N'SR-SMEC-DCSA', 4, N'WF-X-CONV-01'),
        (N'SR-SMEC-DCSA', 5, N'WF-X-VALUE-01'),
        (N'SR-SMEC-PSS', 1, N'WF-ORIENT-01'),
        (N'SR-SMEC-PSS', 4, N'WF-X-OPP-01'),
        (N'SR-SMEC-PSS', 5, N'WF-X-ORCH-01'),
        (N'SR-SMEC-PSS', 6, N'WF-X-VALUE-01'),
        (N'SR-SMEC-CE', 5, N'WF-X-POLICY-01'),
        (N'SR-SMEC-CE', 6, N'WF-X-DEAL-01'),
        (N'SR-SMEC-CE', 7, N'WF-X-ORCH-01'),
        (N'SR-SMEC-CE', 8, N'WF-X-DEAL-01'),
        (N'SR-SMEC-DCSA', 6, N'WF-X-ARCH-01'),
        (N'SR-SMEC-DCSA', 7, N'WF-X-HEALTH-01'),
        (N'SR-SMEC-DCSA', 8, N'WF-X-RENEW-01'),
        (N'SR-SMEC-DSE', 7, N'WF-X-ASSET-01'),
        (N'SR-SMEC-DSE', 8, N'WF-X-ORCH-01'),
        (N'SR-SMEC-DSS', 7, N'WF-X-DEAL-01'),
        (N'SR-SMEC-DSS', 8, N'WF-X-ORCH-01'),
        (N'SR-SMEC-PSS', 7, N'WF-X-HEALTH-01'),
        (N'SR-SMEC-PSS', 8, N'WF-X-CONV-01')
    ) v([SegmentRoleExternalId], [WeekPosition], [TopicExternalId])
), src AS (
    SELECT raw.*, sr.Id AS [HuddleSegmentRoleId], t.Id AS [HuddleTopicId]
    FROM raw
    INNER JOIN dbo.HuddleSegmentRoles AS sr ON sr.[ExternalId] = raw.[SegmentRoleExternalId]
    INNER JOIN dbo.HuddleTopics AS t ON t.[ExternalId] = raw.[TopicExternalId]
)
MERGE dbo.HuddleRolePathItems AS tgt
USING src ON tgt.[HuddleSegmentRoleId] = src.[HuddleSegmentRoleId] AND tgt.[WeekPosition] = src.[WeekPosition]
WHEN MATCHED THEN UPDATE SET
        tgt.[HuddleTopicId] = src.[HuddleTopicId]
WHEN NOT MATCHED BY TARGET THEN INSERT ([HuddleSegmentRoleId], [WeekPosition], [HuddleTopicId])
    VALUES (src.[HuddleSegmentRoleId], src.[WeekPosition], src.[HuddleTopicId]);
;WITH raw AS (
    SELECT * FROM (VALUES
        (N'SR-SMEC-DSE', 1, N'WF-ORIENT-01'),
        (N'SR-SMEC-DSE', 2, N'WF-X-DISC-01'),
        (N'SR-SMEC-DSE', 4, N'WF-X-ARCH-01'),
        (N'SR-SMEC-DSE', 5, N'WF-X-CONV-01'),
        (N'SR-SMEC-DSE', 6, N'WF-X-HEALTH-01'),
        (N'SR-SMEC-DCSA', 1, N'WF-ORIENT-01'),
        (N'SR-SMEC-DCSA', 3, N'WF-X-PARTNER-01'),
        (N'SR-SMEC-DCSA', 4, N'WF-X-CONV-01'),
        (N'SR-SMEC-DCSA', 5, N'WF-X-VALUE-01'),
        (N'SR-SMEC-PSS', 1, N'WF-ORIENT-01'),
        (N'SR-SMEC-PSS', 4, N'WF-X-OPP-01'),
        (N'SR-SMEC-PSS', 5, N'WF-X-ORCH-01'),
        (N'SR-SMEC-PSS', 6, N'WF-X-VALUE-01'),
        (N'SR-SMEC-CE', 5, N'WF-X-POLICY-01'),
        (N'SR-SMEC-CE', 6, N'WF-X-DEAL-01'),
        (N'SR-SMEC-CE', 7, N'WF-X-ORCH-01'),
        (N'SR-SMEC-CE', 8, N'WF-X-DEAL-01'),
        (N'SR-SMEC-DCSA', 6, N'WF-X-ARCH-01'),
        (N'SR-SMEC-DCSA', 7, N'WF-X-HEALTH-01'),
        (N'SR-SMEC-DCSA', 8, N'WF-X-RENEW-01'),
        (N'SR-SMEC-DSE', 7, N'WF-X-ASSET-01'),
        (N'SR-SMEC-DSE', 8, N'WF-X-ORCH-01'),
        (N'SR-SMEC-DSS', 7, N'WF-X-DEAL-01'),
        (N'SR-SMEC-DSS', 8, N'WF-X-ORCH-01'),
        (N'SR-SMEC-PSS', 7, N'WF-X-HEALTH-01'),
        (N'SR-SMEC-PSS', 8, N'WF-X-CONV-01')
    ) v([SegmentRoleExternalId], [WeekPosition], [TopicExternalId])
)
SELECT @unresolved = 26 - COUNT(*) FROM raw
    INNER JOIN dbo.HuddleSegmentRoles AS sr ON sr.[ExternalId] = raw.[SegmentRoleExternalId]
    INNER JOIN dbo.HuddleTopics AS t ON t.[ExternalId] = raw.[TopicExternalId];
IF @unresolved <> 0
    THROW 51000, 'HuddleRolePathItems (new): 26 source rows were expected to resolve their foreign keys but some did not. Run the earlier scripts in order and re-check the workbook.', 1;

COMMIT TRANSACTION;
GO
