
SET NOCOUNT ON;
SET XACT_ABORT ON;
DECLARE @unresolved INT;
BEGIN TRANSACTION;

;WITH raw AS (
    SELECT * FROM (VALUES
        (N'PH-DSE-ORIENT-PREP', N'WF-ORIENT-01', N'DSE-ORIENT', 1, N'Preparation'),
        (N'PH-DSE-DISC-PREP', N'WF-X-DISC-01', N'DSE-DISC', 1, N'Preparation'),
        (N'PH-DSE-PROOF-PREP', N'WF-X-ARCH-01', N'DSE-PROOF', 1, N'Preparation'),
        (N'PH-DSE-CONV-PREP', N'WF-X-CONV-01', N'DSE-CONV', 1, N'Preparation'),
        (N'PH-DSE-HEALTH-PREP', N'WF-X-HEALTH-01', N'DSE-HEALTH', 1, N'Preparation'),
        (N'PH-DCSA-ORIENT-PREP', N'WF-ORIENT-01', N'DCSA-ORIENT', 1, N'Preparation'),
        (N'PH-DCSA-PARTNER-PREP', N'WF-X-PARTNER-01', N'DCSA-PARTNER', 1, N'Preparation'),
        (N'PH-DCSA-CONV-PREP', N'WF-X-CONV-01', N'DCSA-CONV', 1, N'Preparation'),
        (N'PH-DCSA-VALUE-PREP', N'WF-X-VALUE-01', N'DCSA-VALUE', 1, N'Preparation'),
        (N'PH-PSS-ORIENT-PREP', N'WF-ORIENT-01', N'PSS-ORIENT', 1, N'Preparation'),
        (N'PH-PSS-DEMAND-PREP', N'WF-X-OPP-01', N'PSS-DEMAND', 1, N'Preparation'),
        (N'PH-PSS-ORCH-PREP', N'WF-X-ORCH-01', N'PSS-ORCH', 1, N'Preparation'),
        (N'PH-PSS-VALUE-PREP', N'WF-X-VALUE-01', N'PSS-VALUE', 1, N'Preparation'),
        (N'PH-SMEC-CE-POLICY-PREP', N'WF-X-POLICY-01', N'SMEC-CE-POLICY', 1, N'Preparation'),
        (N'PH-SMEC-CE-NEG-PREP', N'WF-X-DEAL-01', N'SMEC-CE-NEG', 1, N'Preparation'),
        (N'PH-SMEC-CE-ORCH-PREP', N'WF-X-ORCH-01', N'SMEC-CE-ORCH', 1, N'Preparation'),
        (N'PH-SMEC-CE-DEAL2-PREP', N'WF-X-DEAL-01', N'SMEC-CE-DEAL2', 1, N'Preparation'),
        (N'PH-DCSA-ARCH-PREP', N'WF-X-ARCH-01', N'DCSA-ARCH', 1, N'Preparation'),
        (N'PH-DCSA-HEALTH-PREP', N'WF-X-HEALTH-01', N'DCSA-HEALTH', 1, N'Preparation'),
        (N'PH-DCSA-EXPAND-PREP', N'WF-X-RENEW-01', N'DCSA-EXPAND', 1, N'Preparation'),
        (N'PH-DSE-ASSET-PREP', N'WF-X-ASSET-01', N'DSE-ASSET', 1, N'Preparation'),
        (N'PH-DSE-PARTNER-PREP', N'WF-X-ORCH-01', N'DSE-PARTNER', 1, N'Preparation'),
        (N'PH-DSS-COMP-PREP', N'WF-X-DEAL-01', N'DSS-COMP', 1, N'Preparation'),
        (N'PH-DSS-ORCH-PREP', N'WF-X-ORCH-01', N'DSS-ORCH', 1, N'Preparation'),
        (N'PH-PSS-CAPACITY-PREP', N'WF-X-HEALTH-01', N'PSS-CAPACITY', 1, N'Preparation'),
        (N'PH-PSS-CONV-PREP', N'WF-X-CONV-01', N'PSS-CONV', 1, N'Preparation'),
        (N'PH-DSS-INVEST-PREP', N'WF-INVEST-01', N'DSS-INVEST', 1, N'Preparation'),
        (N'PH-PSS-INVEST-PREP', N'WF-INVEST-01', N'PSS-INVEST', 1, N'Preparation'),
        (N'PH-DAE-INVEST-PREP', N'WF-INVEST-01', N'DAE-INVEST', 1, N'Preparation'),
        (N'PH-DSE-INVEST-PREP', N'WF-INVEST-01', N'DSE-INVEST', 1, N'Preparation'),
        (N'PH-DCSA-INVEST-PREP', N'WF-INVEST-01', N'DCSA-INVEST', 1, N'Preparation'),
        (N'PH-SMEC-CE-INVEST-PREP', N'WF-INVEST-01', N'SMEC-CE-INVEST', 1, N'Preparation'),
        (N'PH-CSA-VSAT-PREP', N'WF-X-VSAT-01', N'CSA-VSAT', 1, N'Preparation'),
        (N'PH-CSA-TECHLEAD-PREP', N'WF-X-TECHLEAD-01', N'CSA-TECHLEAD', 1, N'Preparation'),
        (N'PH-ALL-CLOSEDWON-PREP', N'WF-X-PIPE-01', N'ALL-CLOSEDWON', 1, N'Preparation'),
        (N'PH-DSE-ORIENT-EXPL', N'WF-ORIENT-01', N'DSE-ORIENT', 2, N'Explore and Practice'),
        (N'PH-DSE-DISC-EXPL', N'WF-X-DISC-01', N'DSE-DISC', 2, N'Explore and Practice'),
        (N'PH-DSE-PROOF-EXPL', N'WF-X-ARCH-01', N'DSE-PROOF', 2, N'Explore and Practice'),
        (N'PH-DSE-CONV-EXPL', N'WF-X-CONV-01', N'DSE-CONV', 2, N'Explore and Practice'),
        (N'PH-DSE-HEALTH-EXPL', N'WF-X-HEALTH-01', N'DSE-HEALTH', 2, N'Explore and Practice'),
        (N'PH-DCSA-ORIENT-EXPL', N'WF-ORIENT-01', N'DCSA-ORIENT', 2, N'Explore and Practice'),
        (N'PH-DCSA-PARTNER-EXPL', N'WF-X-PARTNER-01', N'DCSA-PARTNER', 2, N'Explore and Practice'),
        (N'PH-DCSA-CONV-EXPL', N'WF-X-CONV-01', N'DCSA-CONV', 2, N'Explore and Practice'),
        (N'PH-DCSA-VALUE-EXPL', N'WF-X-VALUE-01', N'DCSA-VALUE', 2, N'Explore and Practice'),
        (N'PH-PSS-ORIENT-EXPL', N'WF-ORIENT-01', N'PSS-ORIENT', 2, N'Explore and Practice'),
        (N'PH-PSS-DEMAND-EXPL', N'WF-X-OPP-01', N'PSS-DEMAND', 2, N'Explore and Practice'),
        (N'PH-PSS-ORCH-EXPL', N'WF-X-ORCH-01', N'PSS-ORCH', 2, N'Explore and Practice'),
        (N'PH-PSS-VALUE-EXPL', N'WF-X-VALUE-01', N'PSS-VALUE', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-POLICY-EXPL', N'WF-X-POLICY-01', N'SMEC-CE-POLICY', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-NEG-EXPL', N'WF-X-DEAL-01', N'SMEC-CE-NEG', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-ORCH-EXPL', N'WF-X-ORCH-01', N'SMEC-CE-ORCH', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-DEAL2-EXPL', N'WF-X-DEAL-01', N'SMEC-CE-DEAL2', 2, N'Explore and Practice'),
        (N'PH-DCSA-ARCH-EXPL', N'WF-X-ARCH-01', N'DCSA-ARCH', 2, N'Explore and Practice'),
        (N'PH-DCSA-HEALTH-EXPL', N'WF-X-HEALTH-01', N'DCSA-HEALTH', 2, N'Explore and Practice'),
        (N'PH-DCSA-EXPAND-EXPL', N'WF-X-RENEW-01', N'DCSA-EXPAND', 2, N'Explore and Practice'),
        (N'PH-DSE-ASSET-EXPL', N'WF-X-ASSET-01', N'DSE-ASSET', 2, N'Explore and Practice'),
        (N'PH-DSE-PARTNER-EXPL', N'WF-X-ORCH-01', N'DSE-PARTNER', 2, N'Explore and Practice'),
        (N'PH-DSS-COMP-EXPL', N'WF-X-DEAL-01', N'DSS-COMP', 2, N'Explore and Practice'),
        (N'PH-DSS-ORCH-EXPL', N'WF-X-ORCH-01', N'DSS-ORCH', 2, N'Explore and Practice'),
        (N'PH-PSS-CAPACITY-EXPL', N'WF-X-HEALTH-01', N'PSS-CAPACITY', 2, N'Explore and Practice'),
        (N'PH-PSS-CONV-EXPL', N'WF-X-CONV-01', N'PSS-CONV', 2, N'Explore and Practice'),
        (N'PH-DSS-INVEST-EXPL', N'WF-INVEST-01', N'DSS-INVEST', 2, N'Explore and Practice'),
        (N'PH-PSS-INVEST-EXPL', N'WF-INVEST-01', N'PSS-INVEST', 2, N'Explore and Practice'),
        (N'PH-DAE-INVEST-EXPL', N'WF-INVEST-01', N'DAE-INVEST', 2, N'Explore and Practice'),
        (N'PH-DSE-INVEST-EXPL', N'WF-INVEST-01', N'DSE-INVEST', 2, N'Explore and Practice'),
        (N'PH-DCSA-INVEST-EXPL', N'WF-INVEST-01', N'DCSA-INVEST', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-INVEST-EXPL', N'WF-INVEST-01', N'SMEC-CE-INVEST', 2, N'Explore and Practice'),
        (N'PH-CSA-VSAT-EXPL', N'WF-X-VSAT-01', N'CSA-VSAT', 2, N'Explore and Practice'),
        (N'PH-CSA-TECHLEAD-EXPL', N'WF-X-TECHLEAD-01', N'CSA-TECHLEAD', 2, N'Explore and Practice'),
        (N'PH-ALL-CLOSEDWON-EXPL', N'WF-X-PIPE-01', N'ALL-CLOSEDWON', 2, N'Explore and Practice'),
        (N'PH-DSE-ORIENT-COMMIT', N'WF-ORIENT-01', N'DSE-ORIENT', 3, N'Commit to Action'),
        (N'PH-DSE-DISC-COMMIT', N'WF-X-DISC-01', N'DSE-DISC', 3, N'Commit to Action'),
        (N'PH-DSE-PROOF-COMMIT', N'WF-X-ARCH-01', N'DSE-PROOF', 3, N'Commit to Action'),
        (N'PH-DSE-CONV-COMMIT', N'WF-X-CONV-01', N'DSE-CONV', 3, N'Commit to Action'),
        (N'PH-DSE-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'DSE-HEALTH', 3, N'Commit to Action'),
        (N'PH-DCSA-ORIENT-COMMIT', N'WF-ORIENT-01', N'DCSA-ORIENT', 3, N'Commit to Action'),
        (N'PH-DCSA-PARTNER-COMMIT', N'WF-X-PARTNER-01', N'DCSA-PARTNER', 3, N'Commit to Action'),
        (N'PH-DCSA-CONV-COMMIT', N'WF-X-CONV-01', N'DCSA-CONV', 3, N'Commit to Action'),
        (N'PH-DCSA-VALUE-COMMIT', N'WF-X-VALUE-01', N'DCSA-VALUE', 3, N'Commit to Action'),
        (N'PH-PSS-ORIENT-COMMIT', N'WF-ORIENT-01', N'PSS-ORIENT', 3, N'Commit to Action'),
        (N'PH-PSS-DEMAND-COMMIT', N'WF-X-OPP-01', N'PSS-DEMAND', 3, N'Commit to Action'),
        (N'PH-PSS-ORCH-COMMIT', N'WF-X-ORCH-01', N'PSS-ORCH', 3, N'Commit to Action'),
        (N'PH-PSS-VALUE-COMMIT', N'WF-X-VALUE-01', N'PSS-VALUE', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-POLICY-COMMIT', N'WF-X-POLICY-01', N'SMEC-CE-POLICY', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-NEG-COMMIT', N'WF-X-DEAL-01', N'SMEC-CE-NEG', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-ORCH-COMMIT', N'WF-X-ORCH-01', N'SMEC-CE-ORCH', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-DEAL2-COMMIT', N'WF-X-DEAL-01', N'SMEC-CE-DEAL2', 3, N'Commit to Action'),
        (N'PH-DCSA-ARCH-COMMIT', N'WF-X-ARCH-01', N'DCSA-ARCH', 3, N'Commit to Action'),
        (N'PH-DCSA-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'DCSA-HEALTH', 3, N'Commit to Action'),
        (N'PH-DCSA-EXPAND-COMMIT', N'WF-X-RENEW-01', N'DCSA-EXPAND', 3, N'Commit to Action'),
        (N'PH-DSE-ASSET-COMMIT', N'WF-X-ASSET-01', N'DSE-ASSET', 3, N'Commit to Action'),
        (N'PH-DSE-PARTNER-COMMIT', N'WF-X-ORCH-01', N'DSE-PARTNER', 3, N'Commit to Action'),
        (N'PH-DSS-COMP-COMMIT', N'WF-X-DEAL-01', N'DSS-COMP', 3, N'Commit to Action'),
        (N'PH-DSS-ORCH-COMMIT', N'WF-X-ORCH-01', N'DSS-ORCH', 3, N'Commit to Action'),
        (N'PH-PSS-CAPACITY-COMMIT', N'WF-X-HEALTH-01', N'PSS-CAPACITY', 3, N'Commit to Action'),
        (N'PH-PSS-CONV-COMMIT', N'WF-X-CONV-01', N'PSS-CONV', 3, N'Commit to Action'),
        (N'PH-DSS-INVEST-COMMIT', N'WF-INVEST-01', N'DSS-INVEST', 3, N'Commit to Action'),
        (N'PH-PSS-INVEST-COMMIT', N'WF-INVEST-01', N'PSS-INVEST', 3, N'Commit to Action'),
        (N'PH-DAE-INVEST-COMMIT', N'WF-INVEST-01', N'DAE-INVEST', 3, N'Commit to Action'),
        (N'PH-DSE-INVEST-COMMIT', N'WF-INVEST-01', N'DSE-INVEST', 3, N'Commit to Action'),
        (N'PH-DCSA-INVEST-COMMIT', N'WF-INVEST-01', N'DCSA-INVEST', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-INVEST-COMMIT', N'WF-INVEST-01', N'SMEC-CE-INVEST', 3, N'Commit to Action'),
        (N'PH-CSA-VSAT-COMMIT', N'WF-X-VSAT-01', N'CSA-VSAT', 3, N'Commit to Action'),
        (N'PH-CSA-TECHLEAD-COMMIT', N'WF-X-TECHLEAD-01', N'CSA-TECHLEAD', 3, N'Commit to Action'),
        (N'PH-ALL-CLOSEDWON-COMMIT', N'WF-X-PIPE-01', N'ALL-CLOSEDWON', 3, N'Commit to Action')
    ) v([ExternalId], [TopicExternalId], [PlacementExternalId], [DisplayOrder], [Name])
), src AS (
    SELECT raw.*, t.Id AS [HuddleTopicId], p.Id AS [HuddlePlacementId]
    FROM raw
    INNER JOIN dbo.HuddleTopics AS t ON t.[ExternalId] = raw.[TopicExternalId]
    INNER JOIN dbo.HuddlePlacements AS p ON p.[ExternalId] = raw.[PlacementExternalId]
)
MERGE dbo.HuddlePhases AS tgt
USING src ON tgt.[ExternalId] = src.[ExternalId]
WHEN MATCHED THEN UPDATE SET
        tgt.[HuddleTopicId] = src.[HuddleTopicId],
        tgt.[HuddlePlacementId] = src.[HuddlePlacementId],
        tgt.[DisplayOrder] = src.[DisplayOrder],
        tgt.[Name] = src.[Name],
        tgt.[UpdatedAtUtc] = SYSUTCDATETIME()
WHEN NOT MATCHED BY TARGET THEN INSERT ([ExternalId], [HuddleTopicId], [HuddlePlacementId], [DisplayOrder], [Name], [CreatedAtUtc])
    VALUES (src.[ExternalId], src.[HuddleTopicId], src.[HuddlePlacementId], src.[DisplayOrder], src.[Name], SYSUTCDATETIME());
;WITH raw AS (
    SELECT * FROM (VALUES
        (N'PH-DSE-ORIENT-PREP', N'WF-ORIENT-01', N'DSE-ORIENT', 1, N'Preparation'),
        (N'PH-DSE-DISC-PREP', N'WF-X-DISC-01', N'DSE-DISC', 1, N'Preparation'),
        (N'PH-DSE-PROOF-PREP', N'WF-X-ARCH-01', N'DSE-PROOF', 1, N'Preparation'),
        (N'PH-DSE-CONV-PREP', N'WF-X-CONV-01', N'DSE-CONV', 1, N'Preparation'),
        (N'PH-DSE-HEALTH-PREP', N'WF-X-HEALTH-01', N'DSE-HEALTH', 1, N'Preparation'),
        (N'PH-DCSA-ORIENT-PREP', N'WF-ORIENT-01', N'DCSA-ORIENT', 1, N'Preparation'),
        (N'PH-DCSA-PARTNER-PREP', N'WF-X-PARTNER-01', N'DCSA-PARTNER', 1, N'Preparation'),
        (N'PH-DCSA-CONV-PREP', N'WF-X-CONV-01', N'DCSA-CONV', 1, N'Preparation'),
        (N'PH-DCSA-VALUE-PREP', N'WF-X-VALUE-01', N'DCSA-VALUE', 1, N'Preparation'),
        (N'PH-PSS-ORIENT-PREP', N'WF-ORIENT-01', N'PSS-ORIENT', 1, N'Preparation'),
        (N'PH-PSS-DEMAND-PREP', N'WF-X-OPP-01', N'PSS-DEMAND', 1, N'Preparation'),
        (N'PH-PSS-ORCH-PREP', N'WF-X-ORCH-01', N'PSS-ORCH', 1, N'Preparation'),
        (N'PH-PSS-VALUE-PREP', N'WF-X-VALUE-01', N'PSS-VALUE', 1, N'Preparation'),
        (N'PH-SMEC-CE-POLICY-PREP', N'WF-X-POLICY-01', N'SMEC-CE-POLICY', 1, N'Preparation'),
        (N'PH-SMEC-CE-NEG-PREP', N'WF-X-DEAL-01', N'SMEC-CE-NEG', 1, N'Preparation'),
        (N'PH-SMEC-CE-ORCH-PREP', N'WF-X-ORCH-01', N'SMEC-CE-ORCH', 1, N'Preparation'),
        (N'PH-SMEC-CE-DEAL2-PREP', N'WF-X-DEAL-01', N'SMEC-CE-DEAL2', 1, N'Preparation'),
        (N'PH-DCSA-ARCH-PREP', N'WF-X-ARCH-01', N'DCSA-ARCH', 1, N'Preparation'),
        (N'PH-DCSA-HEALTH-PREP', N'WF-X-HEALTH-01', N'DCSA-HEALTH', 1, N'Preparation'),
        (N'PH-DCSA-EXPAND-PREP', N'WF-X-RENEW-01', N'DCSA-EXPAND', 1, N'Preparation'),
        (N'PH-DSE-ASSET-PREP', N'WF-X-ASSET-01', N'DSE-ASSET', 1, N'Preparation'),
        (N'PH-DSE-PARTNER-PREP', N'WF-X-ORCH-01', N'DSE-PARTNER', 1, N'Preparation'),
        (N'PH-DSS-COMP-PREP', N'WF-X-DEAL-01', N'DSS-COMP', 1, N'Preparation'),
        (N'PH-DSS-ORCH-PREP', N'WF-X-ORCH-01', N'DSS-ORCH', 1, N'Preparation'),
        (N'PH-PSS-CAPACITY-PREP', N'WF-X-HEALTH-01', N'PSS-CAPACITY', 1, N'Preparation'),
        (N'PH-PSS-CONV-PREP', N'WF-X-CONV-01', N'PSS-CONV', 1, N'Preparation'),
        (N'PH-DSS-INVEST-PREP', N'WF-INVEST-01', N'DSS-INVEST', 1, N'Preparation'),
        (N'PH-PSS-INVEST-PREP', N'WF-INVEST-01', N'PSS-INVEST', 1, N'Preparation'),
        (N'PH-DAE-INVEST-PREP', N'WF-INVEST-01', N'DAE-INVEST', 1, N'Preparation'),
        (N'PH-DSE-INVEST-PREP', N'WF-INVEST-01', N'DSE-INVEST', 1, N'Preparation'),
        (N'PH-DCSA-INVEST-PREP', N'WF-INVEST-01', N'DCSA-INVEST', 1, N'Preparation'),
        (N'PH-SMEC-CE-INVEST-PREP', N'WF-INVEST-01', N'SMEC-CE-INVEST', 1, N'Preparation'),
        (N'PH-CSA-VSAT-PREP', N'WF-X-VSAT-01', N'CSA-VSAT', 1, N'Preparation'),
        (N'PH-CSA-TECHLEAD-PREP', N'WF-X-TECHLEAD-01', N'CSA-TECHLEAD', 1, N'Preparation'),
        (N'PH-ALL-CLOSEDWON-PREP', N'WF-X-PIPE-01', N'ALL-CLOSEDWON', 1, N'Preparation'),
        (N'PH-DSE-ORIENT-EXPL', N'WF-ORIENT-01', N'DSE-ORIENT', 2, N'Explore and Practice'),
        (N'PH-DSE-DISC-EXPL', N'WF-X-DISC-01', N'DSE-DISC', 2, N'Explore and Practice'),
        (N'PH-DSE-PROOF-EXPL', N'WF-X-ARCH-01', N'DSE-PROOF', 2, N'Explore and Practice'),
        (N'PH-DSE-CONV-EXPL', N'WF-X-CONV-01', N'DSE-CONV', 2, N'Explore and Practice'),
        (N'PH-DSE-HEALTH-EXPL', N'WF-X-HEALTH-01', N'DSE-HEALTH', 2, N'Explore and Practice'),
        (N'PH-DCSA-ORIENT-EXPL', N'WF-ORIENT-01', N'DCSA-ORIENT', 2, N'Explore and Practice'),
        (N'PH-DCSA-PARTNER-EXPL', N'WF-X-PARTNER-01', N'DCSA-PARTNER', 2, N'Explore and Practice'),
        (N'PH-DCSA-CONV-EXPL', N'WF-X-CONV-01', N'DCSA-CONV', 2, N'Explore and Practice'),
        (N'PH-DCSA-VALUE-EXPL', N'WF-X-VALUE-01', N'DCSA-VALUE', 2, N'Explore and Practice'),
        (N'PH-PSS-ORIENT-EXPL', N'WF-ORIENT-01', N'PSS-ORIENT', 2, N'Explore and Practice'),
        (N'PH-PSS-DEMAND-EXPL', N'WF-X-OPP-01', N'PSS-DEMAND', 2, N'Explore and Practice'),
        (N'PH-PSS-ORCH-EXPL', N'WF-X-ORCH-01', N'PSS-ORCH', 2, N'Explore and Practice'),
        (N'PH-PSS-VALUE-EXPL', N'WF-X-VALUE-01', N'PSS-VALUE', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-POLICY-EXPL', N'WF-X-POLICY-01', N'SMEC-CE-POLICY', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-NEG-EXPL', N'WF-X-DEAL-01', N'SMEC-CE-NEG', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-ORCH-EXPL', N'WF-X-ORCH-01', N'SMEC-CE-ORCH', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-DEAL2-EXPL', N'WF-X-DEAL-01', N'SMEC-CE-DEAL2', 2, N'Explore and Practice'),
        (N'PH-DCSA-ARCH-EXPL', N'WF-X-ARCH-01', N'DCSA-ARCH', 2, N'Explore and Practice'),
        (N'PH-DCSA-HEALTH-EXPL', N'WF-X-HEALTH-01', N'DCSA-HEALTH', 2, N'Explore and Practice'),
        (N'PH-DCSA-EXPAND-EXPL', N'WF-X-RENEW-01', N'DCSA-EXPAND', 2, N'Explore and Practice'),
        (N'PH-DSE-ASSET-EXPL', N'WF-X-ASSET-01', N'DSE-ASSET', 2, N'Explore and Practice'),
        (N'PH-DSE-PARTNER-EXPL', N'WF-X-ORCH-01', N'DSE-PARTNER', 2, N'Explore and Practice'),
        (N'PH-DSS-COMP-EXPL', N'WF-X-DEAL-01', N'DSS-COMP', 2, N'Explore and Practice'),
        (N'PH-DSS-ORCH-EXPL', N'WF-X-ORCH-01', N'DSS-ORCH', 2, N'Explore and Practice'),
        (N'PH-PSS-CAPACITY-EXPL', N'WF-X-HEALTH-01', N'PSS-CAPACITY', 2, N'Explore and Practice'),
        (N'PH-PSS-CONV-EXPL', N'WF-X-CONV-01', N'PSS-CONV', 2, N'Explore and Practice'),
        (N'PH-DSS-INVEST-EXPL', N'WF-INVEST-01', N'DSS-INVEST', 2, N'Explore and Practice'),
        (N'PH-PSS-INVEST-EXPL', N'WF-INVEST-01', N'PSS-INVEST', 2, N'Explore and Practice'),
        (N'PH-DAE-INVEST-EXPL', N'WF-INVEST-01', N'DAE-INVEST', 2, N'Explore and Practice'),
        (N'PH-DSE-INVEST-EXPL', N'WF-INVEST-01', N'DSE-INVEST', 2, N'Explore and Practice'),
        (N'PH-DCSA-INVEST-EXPL', N'WF-INVEST-01', N'DCSA-INVEST', 2, N'Explore and Practice'),
        (N'PH-SMEC-CE-INVEST-EXPL', N'WF-INVEST-01', N'SMEC-CE-INVEST', 2, N'Explore and Practice'),
        (N'PH-CSA-VSAT-EXPL', N'WF-X-VSAT-01', N'CSA-VSAT', 2, N'Explore and Practice'),
        (N'PH-CSA-TECHLEAD-EXPL', N'WF-X-TECHLEAD-01', N'CSA-TECHLEAD', 2, N'Explore and Practice'),
        (N'PH-ALL-CLOSEDWON-EXPL', N'WF-X-PIPE-01', N'ALL-CLOSEDWON', 2, N'Explore and Practice'),
        (N'PH-DSE-ORIENT-COMMIT', N'WF-ORIENT-01', N'DSE-ORIENT', 3, N'Commit to Action'),
        (N'PH-DSE-DISC-COMMIT', N'WF-X-DISC-01', N'DSE-DISC', 3, N'Commit to Action'),
        (N'PH-DSE-PROOF-COMMIT', N'WF-X-ARCH-01', N'DSE-PROOF', 3, N'Commit to Action'),
        (N'PH-DSE-CONV-COMMIT', N'WF-X-CONV-01', N'DSE-CONV', 3, N'Commit to Action'),
        (N'PH-DSE-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'DSE-HEALTH', 3, N'Commit to Action'),
        (N'PH-DCSA-ORIENT-COMMIT', N'WF-ORIENT-01', N'DCSA-ORIENT', 3, N'Commit to Action'),
        (N'PH-DCSA-PARTNER-COMMIT', N'WF-X-PARTNER-01', N'DCSA-PARTNER', 3, N'Commit to Action'),
        (N'PH-DCSA-CONV-COMMIT', N'WF-X-CONV-01', N'DCSA-CONV', 3, N'Commit to Action'),
        (N'PH-DCSA-VALUE-COMMIT', N'WF-X-VALUE-01', N'DCSA-VALUE', 3, N'Commit to Action'),
        (N'PH-PSS-ORIENT-COMMIT', N'WF-ORIENT-01', N'PSS-ORIENT', 3, N'Commit to Action'),
        (N'PH-PSS-DEMAND-COMMIT', N'WF-X-OPP-01', N'PSS-DEMAND', 3, N'Commit to Action'),
        (N'PH-PSS-ORCH-COMMIT', N'WF-X-ORCH-01', N'PSS-ORCH', 3, N'Commit to Action'),
        (N'PH-PSS-VALUE-COMMIT', N'WF-X-VALUE-01', N'PSS-VALUE', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-POLICY-COMMIT', N'WF-X-POLICY-01', N'SMEC-CE-POLICY', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-NEG-COMMIT', N'WF-X-DEAL-01', N'SMEC-CE-NEG', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-ORCH-COMMIT', N'WF-X-ORCH-01', N'SMEC-CE-ORCH', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-DEAL2-COMMIT', N'WF-X-DEAL-01', N'SMEC-CE-DEAL2', 3, N'Commit to Action'),
        (N'PH-DCSA-ARCH-COMMIT', N'WF-X-ARCH-01', N'DCSA-ARCH', 3, N'Commit to Action'),
        (N'PH-DCSA-HEALTH-COMMIT', N'WF-X-HEALTH-01', N'DCSA-HEALTH', 3, N'Commit to Action'),
        (N'PH-DCSA-EXPAND-COMMIT', N'WF-X-RENEW-01', N'DCSA-EXPAND', 3, N'Commit to Action'),
        (N'PH-DSE-ASSET-COMMIT', N'WF-X-ASSET-01', N'DSE-ASSET', 3, N'Commit to Action'),
        (N'PH-DSE-PARTNER-COMMIT', N'WF-X-ORCH-01', N'DSE-PARTNER', 3, N'Commit to Action'),
        (N'PH-DSS-COMP-COMMIT', N'WF-X-DEAL-01', N'DSS-COMP', 3, N'Commit to Action'),
        (N'PH-DSS-ORCH-COMMIT', N'WF-X-ORCH-01', N'DSS-ORCH', 3, N'Commit to Action'),
        (N'PH-PSS-CAPACITY-COMMIT', N'WF-X-HEALTH-01', N'PSS-CAPACITY', 3, N'Commit to Action'),
        (N'PH-PSS-CONV-COMMIT', N'WF-X-CONV-01', N'PSS-CONV', 3, N'Commit to Action'),
        (N'PH-DSS-INVEST-COMMIT', N'WF-INVEST-01', N'DSS-INVEST', 3, N'Commit to Action'),
        (N'PH-PSS-INVEST-COMMIT', N'WF-INVEST-01', N'PSS-INVEST', 3, N'Commit to Action'),
        (N'PH-DAE-INVEST-COMMIT', N'WF-INVEST-01', N'DAE-INVEST', 3, N'Commit to Action'),
        (N'PH-DSE-INVEST-COMMIT', N'WF-INVEST-01', N'DSE-INVEST', 3, N'Commit to Action'),
        (N'PH-DCSA-INVEST-COMMIT', N'WF-INVEST-01', N'DCSA-INVEST', 3, N'Commit to Action'),
        (N'PH-SMEC-CE-INVEST-COMMIT', N'WF-INVEST-01', N'SMEC-CE-INVEST', 3, N'Commit to Action'),
        (N'PH-CSA-VSAT-COMMIT', N'WF-X-VSAT-01', N'CSA-VSAT', 3, N'Commit to Action'),
        (N'PH-CSA-TECHLEAD-COMMIT', N'WF-X-TECHLEAD-01', N'CSA-TECHLEAD', 3, N'Commit to Action'),
        (N'PH-ALL-CLOSEDWON-COMMIT', N'WF-X-PIPE-01', N'ALL-CLOSEDWON', 3, N'Commit to Action')
    ) v([ExternalId], [TopicExternalId], [PlacementExternalId], [DisplayOrder], [Name])
)
SELECT @unresolved = 105 - COUNT(*) FROM raw
    INNER JOIN dbo.HuddleTopics AS t ON t.[ExternalId] = raw.[TopicExternalId]
    INNER JOIN dbo.HuddlePlacements AS p ON p.[ExternalId] = raw.[PlacementExternalId];
IF @unresolved <> 0
    THROW 51000, 'HuddlePhases (new): 105 source rows were expected to resolve their foreign keys but some did not. Run the earlier scripts in order and re-check the workbook.', 1;

COMMIT TRANSACTION;
GO
