
SET NOCOUNT ON;
SET XACT_ABORT ON;
DECLARE @unresolved INT;
BEGIN TRANSACTION;

-- Activity to agent
;WITH raw AS (
    SELECT * FROM (VALUES
        (N'WF-SE-DISC-01-P-SE-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-SE-DEAL-01-P-SE-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-SE-ARCH-01-P-SE-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'SE-INVLINK-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-01-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-03-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-06-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-CE-APPROVAL-01-P-CE-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-CE-STRUCT-01-P-CE-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-CE-TRANS-01-P-CE-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-02-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-04-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-05-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-07-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-INVLINK-01', N'AGT-006', N'Primary', N'Researcher', 1, 2),
        (N'WF-X-HEALTH-01-P-CSA-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-TECH-CONV-01-P-CSA-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-CONSUME-01-P-CSA-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-VALUE-TECH-01-P-CSA-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CSA-INVLINK-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-04-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-03-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-05-P02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-05-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-07-P02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-07-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-06-P-AE02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-02-P02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-01-P05B', N'AGT-005', N'Primary', N'Scout', 0, 2),
        (N'AE-02-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-X-PLAN-01-P-ATS-02', N'AGT-008', N'Secondary', N'MSXI Assist V2', 0, 3),
        (N'WF-X-PLAN-01-P-ATS-03', N'AGT-008', N'Primary', N'MSXI Assist V2', 0, 2),
        (N'WF-X-CONV-01-P-ATS-03', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-X-PLAN-01-P-ATS-01', N'AGT-008', N'Secondary', N'MSXI Assist V2', 0, 3),
        (N'WF-VALUE-01-P-SSP-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-VTEAM-01-P-SSP-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'SSP-INVLINK-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-X-PLAN-01-P-ATS-INTEL-02', N'AGT-008', N'Primary', N'MSXI Assist V2', 0, 2),
        (N'CSAM-VALUE-P02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'CSAM-RENEW-P02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'CSAM-ESCALATE-P02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'CSAM-ESCALATE-ALT01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-COMP-01-P-SSP-05', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-CONV-01-P-SSP-04', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-DEAL-01-P-SSP-03', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-LEAD-01-P-SSP-04', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-SOLUTION-01-P-SSP-04', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'DAE-SIGNAL-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-SIGNAL-02', N'AGT-006', N'Primary', N'Researcher', 1, 2),
        (N'DAE-SIGNAL-03', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-SIGNAL-ALT-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSS-SIGNAL-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSS-SIGNAL-02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSS-SIGNAL-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 2),
        (N'DSS-SIGNAL-ALT-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-PARTNER-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-PARTNER-02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-PARTNER-03', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-PARTNER-ALT-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'PSS-PARTNER-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'PSS-PARTNER-02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'PSS-PARTNER-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 2),
        (N'PSS-PARTNER-ALT-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DCSA-CONSUME-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DCSA-CONSUME-02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DCSA-CONSUME-03', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DCSA-CONSUME-ALT-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSE-ARCH-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSE-ARCH-02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSE-ARCH-03', N'AGT-006', N'Primary', N'Researcher', 1, 2),
        (N'DSE-ARCH-ALT-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-TERR-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-TERR-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-TERR-04', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSS-TERR-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-TERR-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-TERR-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-TERR-04', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'PSS-JP-03', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'PSS-JP-04', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-CONV-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-CONV-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-CONV-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 2),
        (N'DAE-CONV-04', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-DEAL-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-DEAL-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-DEAL-03', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-DEAL-04', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-RENEW-04', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-HEALTH-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-HEALTH-03', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-HEALTH-04', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'SMEC-CE-DEAL-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'SMEC-CE-DEAL-03', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'SMEC-CE-DEAL-04', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'SMEC-CE-HEALTH-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'SMEC-CE-HEALTH-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'SMEC-CE-HEALTH-04', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSS-CONV-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-CONV-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-CONV-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 2),
        (N'DSS-DEAL-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-DEAL-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-DEAL-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-VALUE-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-VALUE-02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSS-VALUE-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSE-DISC-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSE-DISC-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-DISC-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSE-PROOF-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSE-PROOF-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSE-PROOF-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-CONV-01', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-CONV-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-CONV-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'DSE-HEALTH-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSE-HEALTH-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSE-HEALTH-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-PART-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DCSA-PART-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-PART-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DCSA-CONV-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DCSA-CONV-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-CONV-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DCSA-VALUE-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DCSA-VALUE-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DCSA-VALUE-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'PSS-DEM-01', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'PSS-DEM-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'PSS-DEM-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'PSS-ORCH-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'PSS-ORCH-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'PSS-ORCH-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'PSS-VAL-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'PSS-VAL-02', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'PSS-VAL-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'SMEC-CE-POL-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'SMEC-CE-POL-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'SMEC-CE-POL-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'SMEC-CE-NEG-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'SMEC-CE-NEG-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'SMEC-CE-NEG-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'SMEC-CE-ORCH-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'SMEC-CE-ORCH-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'SMEC-CE-ORCH-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'SMEC-CE-DEAL2-01', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'SMEC-CE-DEAL2-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'SMEC-CE-DEAL2-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-ARCH-01', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'DCSA-ARCH-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-ARCH-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-HEALTH-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'DCSA-HEALTH-02', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'DCSA-HEALTH-03', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'DCSA-EXPAND-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DCSA-EXPAND-02', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'DCSA-EXPAND-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-ASSET-01', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-ASSET-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-ASSET-03', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'DSE-PARTNER-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSE-PARTNER-02', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'DSE-PARTNER-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSS-COMP-01', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'DSS-COMP-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSS-COMP-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSS-ORCH-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSS-ORCH-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSS-ORCH-03', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'PSS-CAP-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'PSS-CAP-02', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'PSS-CAP-03', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'PSS-CONV-01', N'AGT-014', N'Primary', N'Know Your Partner', 1, 1),
        (N'PSS-CONV-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'PSS-CONV-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'DAE-HEALTH-05', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'SMEC-CE-HEALTH-05', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'SMEC-CE-POL-04', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'DSS-INV-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'DSS-INV-02', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'DSS-INV-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'PSS-INV-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'PSS-INV-02', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'PSS-INV-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'DAE-INV-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'DAE-INV-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-INV-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'DSE-INV-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-INV-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'DCSA-INV-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'SMEC-CE-INV-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'DSS-COMP-04', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'PSS-CAP-04', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-HEALTH-04', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'SMEC-CE-RENEW-05', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'ALL-CLOSEDWON-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'ALL-CLOSEDWON-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'WF-ARCH-01-P-CSA-02', N'AGT-005', N'Secondary', N'Scout', 0, 2),
        (N'CSA-VSAT-01-P01', N'AGT-005', N'Primary', N'Scout', 0, 1),
        (N'CSA-VSAT-01-P02', N'AGT-003', N'Primary', N'Microsoft 365 Copilot', 0, 1),
        (N'CSA-VSAT-01-P03', N'AGT-004', N'Primary', N'Cowork', 0, 1),
        (N'CSA-VSAT-01-P04', N'AGT-006', N'Primary', N'Researcher', 0, 1),
        (N'CSA-TECHLEAD-01-P01', N'AGT-006', N'Primary', N'Researcher', 0, 1),
        (N'CSA-TECHLEAD-01-P02', N'AGT-003', N'Primary', N'Microsoft 365 Copilot', 0, 1),
        (N'CSA-TECHLEAD-01-P03', N'AGT-003', N'Primary', N'Microsoft 365 Copilot', 0, 1),
        (N'CSA-TECHLEAD-01-P04', N'AGT-004', N'Primary', N'Cowork', 0, 1),
        (N'WF-SE-ARCH-01-P-SE-02', N'AGT-015', N'Secondary', N'GitHub Copilot', 1, 3),
        (N'WF-SE-DEMO-01-P-SE-01', N'AGT-015', N'Secondary', N'GitHub Copilot', 1, 2),
        (N'WF-SE-POC-01-P-SE-01', N'AGT-015', N'Secondary', N'GitHub Copilot', 1, 2),
        (N'WF-SE-ASSET-01-P-SE-01', N'AGT-015', N'Secondary', N'GitHub Copilot', 1, 2),
        (N'DAE-SIGNAL-SCOUT-01', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'DSS-SIGNAL-SCOUT-01', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'WF-X-CONV-01-P-ATS-NARR-JAI', N'AGT-009', N'Primary', N'Agent J.ai', 0, 1),
        (N'CSAM-ESCALATE-JAI', N'AGT-009', N'Primary', N'Agent J.ai', 0, 1)
    ) v([ActivityExternalId], [AgentExternalId], [UsageType], [DisplayLabel], [ShowAgentAccessLink], [DisplayOrder])
), src AS (
    SELECT raw.*, ac.Id AS [HuddleActivityId], ag.Id AS [HuddleAgentId]
    FROM raw
    INNER JOIN dbo.HuddleActivities AS ac ON ac.[ExternalId] = raw.[ActivityExternalId]
    INNER JOIN dbo.HuddleAgents AS ag ON ag.[ExternalId] = raw.[AgentExternalId]
)
MERGE dbo.HuddleActivityAgents AS tgt
USING src ON tgt.[HuddleActivityId] = src.[HuddleActivityId] AND tgt.[HuddleAgentId] = src.[HuddleAgentId] AND tgt.[UsageType] = src.[UsageType]
WHEN MATCHED THEN UPDATE SET
        tgt.[DisplayLabel] = src.[DisplayLabel],
        tgt.[ShowAgentAccessLink] = src.[ShowAgentAccessLink],
        tgt.[DisplayOrder] = src.[DisplayOrder]
WHEN NOT MATCHED BY TARGET THEN INSERT ([HuddleActivityId], [HuddleAgentId], [UsageType], [DisplayLabel], [ShowAgentAccessLink], [DisplayOrder])
    VALUES (src.[HuddleActivityId], src.[HuddleAgentId], src.[UsageType], src.[DisplayLabel], src.[ShowAgentAccessLink], src.[DisplayOrder]);
;WITH raw AS (
    SELECT * FROM (VALUES
        (N'WF-SE-DISC-01-P-SE-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-SE-DEAL-01-P-SE-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-SE-ARCH-01-P-SE-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'SE-INVLINK-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-01-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-03-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-06-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-CE-APPROVAL-01-P-CE-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-CE-STRUCT-01-P-CE-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-CE-TRANS-01-P-CE-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-02-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-04-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-05-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-07-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CE-INVLINK-01', N'AGT-006', N'Primary', N'Researcher', 1, 2),
        (N'WF-X-HEALTH-01-P-CSA-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-TECH-CONV-01-P-CSA-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-CONSUME-01-P-CSA-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-VALUE-TECH-01-P-CSA-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'CSA-INVLINK-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-04-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-03-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-05-P02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-05-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-07-P02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-07-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-06-P-AE02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-02-P02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'AE-01-P05B', N'AGT-005', N'Primary', N'Scout', 0, 2),
        (N'AE-02-ALT-02', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-X-PLAN-01-P-ATS-02', N'AGT-008', N'Secondary', N'MSXI Assist V2', 0, 3),
        (N'WF-X-PLAN-01-P-ATS-03', N'AGT-008', N'Primary', N'MSXI Assist V2', 0, 2),
        (N'WF-X-CONV-01-P-ATS-03', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-X-PLAN-01-P-ATS-01', N'AGT-008', N'Secondary', N'MSXI Assist V2', 0, 3),
        (N'WF-VALUE-01-P-SSP-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-VTEAM-01-P-SSP-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'SSP-INVLINK-01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-X-PLAN-01-P-ATS-INTEL-02', N'AGT-008', N'Primary', N'MSXI Assist V2', 0, 2),
        (N'CSAM-VALUE-P02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'CSAM-RENEW-P02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'CSAM-ESCALATE-P02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'CSAM-ESCALATE-ALT01', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-COMP-01-P-SSP-05', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-CONV-01-P-SSP-04', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-DEAL-01-P-SSP-03', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-LEAD-01-P-SSP-04', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'WF-SOLUTION-01-P-SSP-04', N'AGT-004', N'Primary', N'Cowork', 0, 2),
        (N'DAE-SIGNAL-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-SIGNAL-02', N'AGT-006', N'Primary', N'Researcher', 1, 2),
        (N'DAE-SIGNAL-03', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-SIGNAL-ALT-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSS-SIGNAL-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSS-SIGNAL-02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSS-SIGNAL-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 2),
        (N'DSS-SIGNAL-ALT-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-PARTNER-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-PARTNER-02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-PARTNER-03', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-PARTNER-ALT-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'PSS-PARTNER-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'PSS-PARTNER-02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'PSS-PARTNER-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 2),
        (N'PSS-PARTNER-ALT-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DCSA-CONSUME-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DCSA-CONSUME-02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DCSA-CONSUME-03', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DCSA-CONSUME-ALT-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSE-ARCH-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSE-ARCH-02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSE-ARCH-03', N'AGT-006', N'Primary', N'Researcher', 1, 2),
        (N'DSE-ARCH-ALT-01', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-TERR-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-TERR-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-TERR-04', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSS-TERR-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-TERR-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-TERR-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-TERR-04', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'PSS-JP-03', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'PSS-JP-04', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-CONV-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-CONV-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-CONV-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 2),
        (N'DAE-CONV-04', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-DEAL-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-DEAL-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-DEAL-03', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-DEAL-04', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-RENEW-04', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-HEALTH-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DAE-HEALTH-03', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DAE-HEALTH-04', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'SMEC-CE-DEAL-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'SMEC-CE-DEAL-03', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'SMEC-CE-DEAL-04', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'SMEC-CE-HEALTH-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'SMEC-CE-HEALTH-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'SMEC-CE-HEALTH-04', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSS-CONV-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-CONV-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-CONV-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 2),
        (N'DSS-DEAL-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-DEAL-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-DEAL-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-VALUE-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSS-VALUE-02', N'AGT-004', N'Primary', N'Cowork', 1, 2),
        (N'DSS-VALUE-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 2),
        (N'DSE-DISC-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSE-DISC-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-DISC-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSE-PROOF-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSE-PROOF-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSE-PROOF-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-CONV-01', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-CONV-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-CONV-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'DSE-HEALTH-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSE-HEALTH-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSE-HEALTH-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-PART-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DCSA-PART-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-PART-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DCSA-CONV-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DCSA-CONV-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-CONV-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DCSA-VALUE-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DCSA-VALUE-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DCSA-VALUE-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'PSS-DEM-01', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'PSS-DEM-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'PSS-DEM-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'PSS-ORCH-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'PSS-ORCH-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'PSS-ORCH-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'PSS-VAL-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'PSS-VAL-02', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'PSS-VAL-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'SMEC-CE-POL-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'SMEC-CE-POL-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'SMEC-CE-POL-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'SMEC-CE-NEG-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'SMEC-CE-NEG-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'SMEC-CE-NEG-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'SMEC-CE-ORCH-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'SMEC-CE-ORCH-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'SMEC-CE-ORCH-03', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'SMEC-CE-DEAL2-01', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'SMEC-CE-DEAL2-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'SMEC-CE-DEAL2-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-ARCH-01', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'DCSA-ARCH-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-ARCH-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-HEALTH-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'DCSA-HEALTH-02', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'DCSA-HEALTH-03', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'DCSA-EXPAND-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DCSA-EXPAND-02', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'DCSA-EXPAND-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-ASSET-01', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-ASSET-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-ASSET-03', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'DSE-PARTNER-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSE-PARTNER-02', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'DSE-PARTNER-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSS-COMP-01', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'DSS-COMP-02', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSS-COMP-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSS-ORCH-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'DSS-ORCH-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSS-ORCH-03', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'PSS-CAP-01', N'AGT-013', N'Primary', N'Sales Home (Sales Agent)', 1, 1),
        (N'PSS-CAP-02', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'PSS-CAP-03', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'PSS-CONV-01', N'AGT-014', N'Primary', N'Know Your Partner', 1, 1),
        (N'PSS-CONV-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'PSS-CONV-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'DAE-HEALTH-05', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'SMEC-CE-HEALTH-05', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'SMEC-CE-POL-04', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'DSS-INV-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'DSS-INV-02', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'DSS-INV-03', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'PSS-INV-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'PSS-INV-02', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'PSS-INV-03', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'DAE-INV-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'DAE-INV-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DSE-INV-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'DSE-INV-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-INV-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'DCSA-INV-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'SMEC-CE-INV-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'DSS-COMP-04', N'AGT-009', N'Primary', N'Agent J.ai', 1, 1),
        (N'PSS-CAP-04', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'DCSA-HEALTH-04', N'AGT-006', N'Primary', N'Researcher', 1, 1),
        (N'SMEC-CE-RENEW-05', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'ALL-CLOSEDWON-01', N'AGT-001', N'Primary', N'Sales Agent', 1, 1),
        (N'ALL-CLOSEDWON-02', N'AGT-004', N'Primary', N'Cowork', 1, 1),
        (N'WF-ARCH-01-P-CSA-02', N'AGT-005', N'Secondary', N'Scout', 0, 2),
        (N'CSA-VSAT-01-P01', N'AGT-005', N'Primary', N'Scout', 0, 1),
        (N'CSA-VSAT-01-P02', N'AGT-003', N'Primary', N'Microsoft 365 Copilot', 0, 1),
        (N'CSA-VSAT-01-P03', N'AGT-004', N'Primary', N'Cowork', 0, 1),
        (N'CSA-VSAT-01-P04', N'AGT-006', N'Primary', N'Researcher', 0, 1),
        (N'CSA-TECHLEAD-01-P01', N'AGT-006', N'Primary', N'Researcher', 0, 1),
        (N'CSA-TECHLEAD-01-P02', N'AGT-003', N'Primary', N'Microsoft 365 Copilot', 0, 1),
        (N'CSA-TECHLEAD-01-P03', N'AGT-003', N'Primary', N'Microsoft 365 Copilot', 0, 1),
        (N'CSA-TECHLEAD-01-P04', N'AGT-004', N'Primary', N'Cowork', 0, 1),
        (N'WF-SE-ARCH-01-P-SE-02', N'AGT-015', N'Secondary', N'GitHub Copilot', 1, 3),
        (N'WF-SE-DEMO-01-P-SE-01', N'AGT-015', N'Secondary', N'GitHub Copilot', 1, 2),
        (N'WF-SE-POC-01-P-SE-01', N'AGT-015', N'Secondary', N'GitHub Copilot', 1, 2),
        (N'WF-SE-ASSET-01-P-SE-01', N'AGT-015', N'Secondary', N'GitHub Copilot', 1, 2),
        (N'DAE-SIGNAL-SCOUT-01', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'DSS-SIGNAL-SCOUT-01', N'AGT-005', N'Primary', N'Scout', 1, 1),
        (N'WF-X-CONV-01-P-ATS-NARR-JAI', N'AGT-009', N'Primary', N'Agent J.ai', 0, 1),
        (N'CSAM-ESCALATE-JAI', N'AGT-009', N'Primary', N'Agent J.ai', 0, 1)
    ) v([ActivityExternalId], [AgentExternalId], [UsageType], [DisplayLabel], [ShowAgentAccessLink], [DisplayOrder])
)
SELECT @unresolved = 215 - COUNT(*) FROM raw
    INNER JOIN dbo.HuddleActivities AS ac ON ac.[ExternalId] = raw.[ActivityExternalId]
    INNER JOIN dbo.HuddleAgents AS ag ON ag.[ExternalId] = raw.[AgentExternalId];
IF @unresolved <> 0
    THROW 51000, 'HuddleActivityAgents (new): 215 source rows were expected to resolve their foreign keys but some did not. Run the earlier scripts in order and re-check the workbook.', 1;

-- Activity to resource
;WITH raw AS (
    SELECT * FROM (VALUES
        (N'AE-01-P01', N'RES-007', 2),
        (N'CSAM-HEALTH-P01', N'RES-CSAM-PERSONA', 2)
    ) v([ActivityExternalId], [ResourceExternalId], [DisplayOrder])
), src AS (
    SELECT raw.*, ac.Id AS [HuddleActivityId], rs.Id AS [HuddleResourceId]
    FROM raw
    INNER JOIN dbo.HuddleActivities AS ac ON ac.[ExternalId] = raw.[ActivityExternalId]
    INNER JOIN dbo.HuddleResources AS rs ON rs.[ExternalId] = raw.[ResourceExternalId]
)
MERGE dbo.HuddleActivityResources AS tgt
USING src ON tgt.[HuddleActivityId] = src.[HuddleActivityId] AND tgt.[HuddleResourceId] = src.[HuddleResourceId]
WHEN MATCHED THEN UPDATE SET
        tgt.[DisplayOrder] = src.[DisplayOrder]
WHEN NOT MATCHED BY TARGET THEN INSERT ([HuddleActivityId], [HuddleResourceId], [DisplayOrder])
    VALUES (src.[HuddleActivityId], src.[HuddleResourceId], src.[DisplayOrder]);
;WITH raw AS (
    SELECT * FROM (VALUES
        (N'AE-01-P01', N'RES-007', 2),
        (N'CSAM-HEALTH-P01', N'RES-CSAM-PERSONA', 2)
    ) v([ActivityExternalId], [ResourceExternalId], [DisplayOrder])
)
SELECT @unresolved = 2 - COUNT(*) FROM raw
    INNER JOIN dbo.HuddleActivities AS ac ON ac.[ExternalId] = raw.[ActivityExternalId]
    INNER JOIN dbo.HuddleResources AS rs ON rs.[ExternalId] = raw.[ResourceExternalId];
IF @unresolved <> 0
    THROW 51000, 'HuddleActivityResources (new): 2 source rows were expected to resolve their foreign keys but some did not. Run the earlier scripts in order and re-check the workbook.', 1;

COMMIT TRANSACTION;
GO
