/*
    OPTIONAL -- corrections to data already loaded (review each block before running)
    Generated by build.py against the 9.15.2026 Frontier Accelerator workbook.
    Contains ONLY rows that do not already exist in the database (per huddle-v10.2.1).
    Do not hand-edit. Re-runnable: every statement is an ExternalId-keyed MERGE that only
    inserts what is missing -- nothing already loaded is ever updated or deleted.
    Not part of the new-data install path. Covers: the SR-SMEC-CE role pointer, 4 of the 7 reclassified placements (the SSP 3-way Sequence rotation is deliberately excluded -- see Section E), 5 existing-activity prerequisite changes, and 11 existing Activity_Agents content edits. Run only after reviewing each statement.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
DECLARE @unresolved INT;
BEGIN TRANSACTION;

-- 1) HuddleSegmentRoles 'SR-SMEC-CE' should point at ROLE-SMEC-CE, not ROLE-CE.
--    Safe to run only AFTER script 02 has inserted ROLE-SMEC-CE.
UPDATE sr SET sr.RoleId = rl.Id, sr.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleSegmentRoles sr
INNER JOIN dbo.Roles rl ON rl.ExternalId = N'ROLE-SMEC-CE'
WHERE sr.ExternalId = N'SR-SMEC-CE' AND sr.RoleId <> rl.Id;

-- 2) Four placements reclassified from SEC-ADDITIONAL to SEC-ROLEPATH with a new Sequence.
UPDATE dbo.HuddlePlacements SET PathSection = N'SEC-ROLEPATH', Sequence = 3, UpdatedAtUtc = SYSUTCDATETIME()
WHERE ExternalId = N'DSE-ARCH' AND PathSection = N'SEC-ADDITIONAL' AND Sequence = 1;
UPDATE dbo.HuddlePlacements SET PathSection = N'SEC-ROLEPATH', Sequence = 2, UpdatedAtUtc = SYSUTCDATETIME()
WHERE ExternalId = N'DCSA-CONSUME' AND PathSection = N'SEC-ADDITIONAL' AND Sequence = 1;
UPDATE dbo.HuddlePlacements SET PathSection = N'SEC-ROLEPATH', Sequence = 3, UpdatedAtUtc = SYSUTCDATETIME()
WHERE ExternalId = N'PSS-PARTNER' AND PathSection = N'SEC-ADDITIONAL' AND Sequence = 1;
UPDATE dbo.HuddlePlacements SET PathSection = N'SEC-ROLEPATH', Sequence = 2, UpdatedAtUtc = SYSUTCDATETIME()
WHERE ExternalId = N'PSS-JOINTPLAN' AND PathSection = N'SEC-ADDITIONAL' AND Sequence = 2;

-- 3) Existing activities whose prerequisite link changed in the workbook.
UPDATE a SET a.PrerequisiteHuddleActivityId = pre.Id, a.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivities a INNER JOIN dbo.HuddleActivities pre ON pre.ExternalId = N'AE-07-P01'
WHERE a.ExternalId = N'AE-07-P03';
UPDATE a SET a.PrerequisiteHuddleActivityId = pre.Id, a.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivities a INNER JOIN dbo.HuddleActivities pre ON pre.ExternalId = N'CSAM-ESCALATE-P01'
WHERE a.ExternalId = N'CSAM-ESCALATE-ALT01';
UPDATE a SET a.PrerequisiteHuddleActivityId = pre.Id, a.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivities a INNER JOIN dbo.HuddleActivities pre ON pre.ExternalId = N'CSAM-ESCALATE-P01'
WHERE a.ExternalId = N'CSAM-ESCALATE-P02';
UPDATE a SET a.PrerequisiteHuddleActivityId = pre.Id, a.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivities a INNER JOIN dbo.HuddleActivities pre ON pre.ExternalId = N'CSAM-HEALTH-P01'
WHERE a.ExternalId = N'CSAM-HEALTH-P02';
UPDATE dbo.HuddleActivities SET PrerequisiteHuddleActivityId = NULL, UpdatedAtUtc = SYSUTCDATETIME()
WHERE ExternalId = N'WF-DEAL-01-P-SSP-04';

-- 4) Existing Activity-Agent links whose content changed (key pair unchanged).
UPDATE aa SET aa.DisplayLabel = N'Proactive Insights in MSXI', aa.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities a ON a.Id = aa.HuddleActivityId AND a.ExternalId = N'AE-01-P05A'
INNER JOIN dbo.HuddleAgents ag ON ag.Id = aa.HuddleAgentId AND ag.ExternalId = N'AGT-008';
UPDATE aa SET aa.UsageType = N'Secondary', aa.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities a ON a.Id = aa.HuddleActivityId AND a.ExternalId = N'WF-X-CONV-01-P-ATS-01'
INNER JOIN dbo.HuddleAgents ag ON ag.Id = aa.HuddleAgentId AND ag.ExternalId = N'AGT-004';
UPDATE aa SET aa.UsageType = N'Secondary', aa.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities a ON a.Id = aa.HuddleActivityId AND a.ExternalId = N'WF-X-CONV-01-P-ATS-02'
INNER JOIN dbo.HuddleAgents ag ON ag.Id = aa.HuddleAgentId AND ag.ExternalId = N'AGT-003';
UPDATE aa SET aa.UsageType = N'Primary', aa.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities a ON a.Id = aa.HuddleActivityId AND a.ExternalId = N'CSAM-HEALTH-P01'
INNER JOIN dbo.HuddleAgents ag ON ag.Id = aa.HuddleAgentId AND ag.ExternalId = N'AGT-008';
UPDATE aa SET aa.UsageType = N'Secondary', aa.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities a ON a.Id = aa.HuddleActivityId AND a.ExternalId = N'CSAM-HEALTH-P02'
INNER JOIN dbo.HuddleAgents ag ON ag.Id = aa.HuddleAgentId AND ag.ExternalId = N'AGT-003';
UPDATE aa SET aa.UsageType = N'Primary', aa.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities a ON a.Id = aa.HuddleActivityId AND a.ExternalId = N'CSAM-HEALTH-P02'
INNER JOIN dbo.HuddleAgents ag ON ag.Id = aa.HuddleAgentId AND ag.ExternalId = N'AGT-004';
UPDATE aa SET aa.UsageType = N'Secondary', aa.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities a ON a.Id = aa.HuddleActivityId AND a.ExternalId = N'CSAM-EXEC-P02'
INNER JOIN dbo.HuddleAgents ag ON ag.Id = aa.HuddleAgentId AND ag.ExternalId = N'AGT-003';
UPDATE aa SET aa.UsageType = N'Primary', aa.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities a ON a.Id = aa.HuddleActivityId AND a.ExternalId = N'CSAM-EXEC-P02'
INNER JOIN dbo.HuddleAgents ag ON ag.Id = aa.HuddleAgentId AND ag.ExternalId = N'AGT-004';
UPDATE aa SET aa.ShowAgentAccessLink = 1, aa.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities a ON a.Id = aa.HuddleActivityId AND a.ExternalId = N'CSAM-ORCH-P01'
INNER JOIN dbo.HuddleAgents ag ON ag.Id = aa.HuddleAgentId AND ag.ExternalId = N'AGT-001';
UPDATE aa SET aa.UsageType = N'Secondary', aa.ShowAgentAccessLink = 1, aa.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities a ON a.Id = aa.HuddleActivityId AND a.ExternalId = N'WF-CONV-01-P-SSP-04'
INNER JOIN dbo.HuddleAgents ag ON ag.Id = aa.HuddleAgentId AND ag.ExternalId = N'AGT-001';
UPDATE aa SET aa.DisplayLabel = N'Sales Agent', aa.UpdatedAtUtc = SYSUTCDATETIME()
FROM dbo.HuddleActivityAgents aa
INNER JOIN dbo.HuddleActivities a ON a.Id = aa.HuddleActivityId AND a.ExternalId = N'PSS-JP-01'
INNER JOIN dbo.HuddleAgents ag ON ag.Id = aa.HuddleAgentId AND ag.ExternalId = N'AGT-001';

COMMIT TRANSACTION;
GO
