/*
    IMPORTANT:
    Review the selected database before executing this script.
    This script was generated for manual execution in SSMS.
    It has not been executed by Codex.
*/
USE [AitoWorkflowAndHuddleGeneratorDb];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @SourceCount int = 0, @InsertedCount int = 0, @UpdatedCount int = 0, @SkippedCount int = 0, @DuplicateCount int = 0, @MissingRelationshipCount int = 0;
    DECLARE @Source TABLE(ExternalId nvarchar(100),TopicExternalId nvarchar(100),DisplayOrder int,Name nvarchar(300),Description nvarchar(max),DurationMinutes int); INSERT @Source VALUES
(N'PH-WF-ADOPT-01-01',N'WF-ADOPT-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Accelerate Adoption and Prove Value Realization.',NULL),
(N'PH-WF-ADOPT-01-02',N'WF-ADOPT-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Accelerate Adoption and Prove Value Realization.',NULL),
(N'PH-WF-ADOPT-01-03',N'WF-ADOPT-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-ARCH-01-01',N'WF-ARCH-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Design a Production-Ready Customer Architecture.',NULL),
(N'PH-WF-ARCH-01-02',N'WF-ARCH-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Design a Production-Ready Customer Architecture.',NULL),
(N'PH-WF-ARCH-01-03',N'WF-ARCH-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-CE-APPROVAL-01-01',N'WF-CE-APPROVAL-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Orchestrate Approvals and Commercial Execution.',NULL),
(N'PH-WF-CE-APPROVAL-01-02',N'WF-CE-APPROVAL-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Orchestrate Approvals and Commercial Execution.',NULL),
(N'PH-WF-CE-APPROVAL-01-03',N'WF-CE-APPROVAL-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-CE-NEG-01-01',N'WF-CE-NEG-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Prepare and Lead the Commercial Negotiation.',NULL),
(N'PH-WF-CE-NEG-01-02',N'WF-CE-NEG-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Prepare and Lead the Commercial Negotiation.',NULL),
(N'PH-WF-CE-NEG-01-03',N'WF-CE-NEG-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-CE-POLICY-01-01',N'WF-CE-POLICY-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Validate Licensing, Policy and Compliance.',NULL),
(N'PH-WF-CE-POLICY-01-02',N'WF-CE-POLICY-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Validate Licensing, Policy and Compliance.',NULL),
(N'PH-WF-CE-POLICY-01-03',N'WF-CE-POLICY-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-CE-RENEW-01-01',N'WF-CE-RENEW-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Build and Execute the Renewal Strategy.',NULL),
(N'PH-WF-CE-RENEW-01-02',N'WF-CE-RENEW-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Build and Execute the Renewal Strategy.',NULL),
(N'PH-WF-CE-RENEW-01-03',N'WF-CE-RENEW-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-CE-RISK-01-01',N'WF-CE-RISK-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Prioritize Commercial Risk and Intervention.',NULL),
(N'PH-WF-CE-RISK-01-02',N'WF-CE-RISK-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Prioritize Commercial Risk and Intervention.',NULL),
(N'PH-WF-CE-RISK-01-03',N'WF-CE-RISK-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-CE-STRUCT-01-01',N'WF-CE-STRUCT-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Develop Commercial Options and Deal Structure.',NULL),
(N'PH-WF-CE-STRUCT-01-02',N'WF-CE-STRUCT-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Develop Commercial Options and Deal Structure.',NULL),
(N'PH-WF-CE-STRUCT-01-03',N'WF-CE-STRUCT-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-CE-TRANS-01-01',N'WF-CE-TRANS-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Navigate Agreement and Commerce Transitions.',NULL),
(N'PH-WF-CE-TRANS-01-02',N'WF-CE-TRANS-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Navigate Agreement and Commerce Transitions.',NULL),
(N'PH-WF-CE-TRANS-01-03',N'WF-CE-TRANS-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-COMP-01-01',N'WF-COMP-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Develop a Competitive Position and Response Plan.',NULL),
(N'PH-WF-COMP-01-02',N'WF-COMP-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Develop a Competitive Position and Response Plan.',NULL),
(N'PH-WF-COMP-01-03',N'WF-COMP-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-CONSUME-01-01',N'WF-CONSUME-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Forecast Consumption and Intervene on Risk.',NULL),
(N'PH-WF-CONSUME-01-02',N'WF-CONSUME-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Forecast Consumption and Intervene on Risk.',NULL),
(N'PH-WF-CONSUME-01-03',N'WF-CONSUME-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-CONV-01-01',N'WF-CONV-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Prepare for a Customer Conversation.',NULL),
(N'PH-WF-CONV-01-02',N'WF-CONV-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Prepare for a Customer Conversation.',NULL),
(N'PH-WF-CONV-01-03',N'WF-CONV-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-CS-HEALTH-01-01',N'WF-CS-HEALTH-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Assess Customer Health and Prioritize Risk Response.',NULL),
(N'PH-WF-CS-HEALTH-01-02',N'WF-CS-HEALTH-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Assess Customer Health and Prioritize Risk Response.',NULL),
(N'PH-WF-CS-HEALTH-01-03',N'WF-CS-HEALTH-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-CS-ORCH-01-01',N'WF-CS-ORCH-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Orchestrate Customer, Internal Team, Partners, and Delivery.',NULL),
(N'PH-WF-CS-ORCH-01-02',N'WF-CS-ORCH-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Orchestrate Customer, Internal Team, Partners, and Delivery.',NULL),
(N'PH-WF-CS-ORCH-01-03',N'WF-CS-ORCH-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-DEAL-01-01',N'WF-DEAL-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Accelerate a Strategic Deal.',NULL),
(N'PH-WF-DEAL-01-02',N'WF-DEAL-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Accelerate a Strategic Deal.',NULL),
(N'PH-WF-DEAL-01-03',N'WF-DEAL-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-EBC-01-01',N'WF-EBC-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Design an Executive Briefing Experience.',NULL),
(N'PH-WF-EBC-01-02',N'WF-EBC-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Design an Executive Briefing Experience.',NULL),
(N'PH-WF-EBC-01-03',N'WF-EBC-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-ESC-01-01',N'WF-ESC-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Quarterback Delivery Risk, Incidents, and Escalations.',NULL),
(N'PH-WF-ESC-01-02',N'WF-ESC-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Quarterback Delivery Risk, Incidents, and Escalations.',NULL),
(N'PH-WF-ESC-01-03',N'WF-ESC-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-FCST-01-01',N'WF-FCST-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Build a Decision-Ready Forecast Narrative.',NULL),
(N'PH-WF-FCST-01-02',N'WF-FCST-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Build a Decision-Ready Forecast Narrative.',NULL),
(N'PH-WF-FCST-01-03',N'WF-FCST-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-HEALTH-01-01',N'WF-HEALTH-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Assess Customer Technical Health and Prioritize Risk.',NULL),
(N'PH-WF-HEALTH-01-02',N'WF-HEALTH-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Assess Customer Technical Health and Prioritize Risk.',NULL),
(N'PH-WF-HEALTH-01-03',N'WF-HEALTH-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-INTEL-01-01',N'WF-INTEL-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Build an Account Intelligence and Meeting Prep Brief.',NULL),
(N'PH-WF-INTEL-01-02',N'WF-INTEL-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Build an Account Intelligence and Meeting Prep Brief.',NULL),
(N'PH-WF-INTEL-01-03',N'WF-INTEL-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-LEAD-01-01',N'WF-LEAD-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Prioritize Prospects and Follow Up on Leads.',NULL),
(N'PH-WF-LEAD-01-02',N'WF-LEAD-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Prioritize Prospects and Follow Up on Leads.',NULL),
(N'PH-WF-LEAD-01-03',N'WF-LEAD-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-NARR-01-01',N'WF-NARR-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Assemble an Executive Technical Customer Narrative.',NULL),
(N'PH-WF-NARR-01-02',N'WF-NARR-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Assemble an Executive Technical Customer Narrative.',NULL),
(N'PH-WF-NARR-01-03',N'WF-NARR-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-OPP-01-01',N'WF-OPP-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Create and Qualify New Opportunities.',NULL),
(N'PH-WF-OPP-01-02',N'WF-OPP-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Create and Qualify New Opportunities.',NULL),
(N'PH-WF-OPP-01-03',N'WF-OPP-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-OPT-01-01',N'WF-OPT-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Build a FinOps and Optimization Recommendation.',NULL),
(N'PH-WF-OPT-01-02',N'WF-OPT-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Build a FinOps and Optimization Recommendation.',NULL),
(N'PH-WF-OPT-01-03',N'WF-OPT-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-PIPE-01-01',N'WF-PIPE-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Inspect Pipeline Health and Restore Signal Quality.',NULL),
(N'PH-WF-PIPE-01-02',N'WF-PIPE-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Inspect Pipeline Health and Restore Signal Quality.',NULL),
(N'PH-WF-PIPE-01-03',N'WF-PIPE-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-PLAN-01-01',N'WF-PLAN-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Prioritize Accounts and Build an Actionable Account Plan.',NULL),
(N'PH-WF-PLAN-01-02',N'WF-PLAN-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Prioritize Accounts and Build an Actionable Account Plan.',NULL),
(N'PH-WF-PLAN-01-03',N'WF-PLAN-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-RENEW-01-01',N'WF-RENEW-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Manage Renewal Risk and Expansion Readiness.',NULL),
(N'PH-WF-RENEW-01-02',N'WF-RENEW-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Manage Renewal Risk and Expansion Readiness.',NULL),
(N'PH-WF-RENEW-01-03',N'WF-RENEW-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-SE-ARCH-01-01',N'WF-SE-ARCH-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Design and Validate the Customer Architecture.',NULL),
(N'PH-WF-SE-ARCH-01-02',N'WF-SE-ARCH-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Design and Validate the Customer Architecture.',NULL),
(N'PH-WF-SE-ARCH-01-03',N'WF-SE-ARCH-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-SE-ASSET-01-01',N'WF-SE-ASSET-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Capture and Reuse Technical Assets and Learning.',NULL),
(N'PH-WF-SE-ASSET-01-02',N'WF-SE-ASSET-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Capture and Reuse Technical Assets and Learning.',NULL),
(N'PH-WF-SE-ASSET-01-03',N'WF-SE-ASSET-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-SE-DEAL-01-01',N'WF-SE-DEAL-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Manage Technical Risk and Advance the Deal.',NULL),
(N'PH-WF-SE-DEAL-01-02',N'WF-SE-DEAL-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Manage Technical Risk and Advance the Deal.',NULL),
(N'PH-WF-SE-DEAL-01-03',N'WF-SE-DEAL-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-SE-DEMO-01-01',N'WF-SE-DEMO-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Design a Demo or Workshop That Advances the Decision.',NULL),
(N'PH-WF-SE-DEMO-01-02',N'WF-SE-DEMO-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Design a Demo or Workshop That Advances the Decision.',NULL),
(N'PH-WF-SE-DEMO-01-03',N'WF-SE-DEMO-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-SE-DISC-01-01',N'WF-SE-DISC-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Lead Technical Discovery and Define Decision Criteria.',NULL),
(N'PH-WF-SE-DISC-01-02',N'WF-SE-DISC-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Lead Technical Discovery and Define Decision Criteria.',NULL),
(N'PH-WF-SE-DISC-01-03',N'WF-SE-DISC-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-SE-POC-01-01',N'WF-SE-POC-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Scope a PoC with Success and Exit Criteria.',NULL),
(N'PH-WF-SE-POC-01-02',N'WF-SE-POC-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Scope a PoC with Success and Exit Criteria.',NULL),
(N'PH-WF-SE-POC-01-03',N'WF-SE-POC-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-SE-QA-01-01',N'WF-SE-QA-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Respond to Technical Questions with Evidence and Confidence.',NULL),
(N'PH-WF-SE-QA-01-02',N'WF-SE-QA-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Respond to Technical Questions with Evidence and Confidence.',NULL),
(N'PH-WF-SE-QA-01-03',N'WF-SE-QA-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-SOLUTION-01-01',N'WF-SOLUTION-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Build a Solution-Selling Plan.',NULL),
(N'PH-WF-SOLUTION-01-02',N'WF-SOLUTION-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Build a Solution-Selling Plan.',NULL),
(N'PH-WF-SOLUTION-01-03',N'WF-SOLUTION-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-SUCCESS-01-01',N'WF-SUCCESS-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Build and Govern an Outcome-Anchored Success Plan.',NULL),
(N'PH-WF-SUCCESS-01-02',N'WF-SUCCESS-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Build and Govern an Outcome-Anchored Success Plan.',NULL),
(N'PH-WF-SUCCESS-01-03',N'WF-SUCCESS-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-TALK-01-01',N'WF-TALK-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Adjust the Technical Talk Track from Customer Signals.',NULL),
(N'PH-WF-TALK-01-02',N'WF-TALK-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Adjust the Technical Talk Track from Customer Signals.',NULL),
(N'PH-WF-TALK-01-03',N'WF-TALK-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-TEAM-01-01',N'WF-TEAM-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Mobilize the Account Team and Partners.',NULL),
(N'PH-WF-TEAM-01-02',N'WF-TEAM-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Mobilize the Account Team and Partners.',NULL),
(N'PH-WF-TEAM-01-03',N'WF-TEAM-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-TECH-01-01',N'WF-TECH-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Build the Technical Decision and Validation Path.',NULL),
(N'PH-WF-TECH-01-02',N'WF-TECH-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Build the Technical Decision and Validation Path.',NULL),
(N'PH-WF-TECH-01-03',N'WF-TECH-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-TECH-CONV-01-01',N'WF-TECH-CONV-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Prepare a Technical Advisory Customer Conversation.',NULL),
(N'PH-WF-TECH-CONV-01-02',N'WF-TECH-CONV-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Prepare a Technical Advisory Customer Conversation.',NULL),
(N'PH-WF-TECH-CONV-01-03',N'WF-TECH-CONV-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-VALUE-01-01',N'WF-VALUE-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Develop a Customer-Specific Value Narrative.',NULL),
(N'PH-WF-VALUE-01-02',N'WF-VALUE-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Develop a Customer-Specific Value Narrative.',NULL),
(N'PH-WF-VALUE-01-03',N'WF-VALUE-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-VALUE-TECH-01-01',N'WF-VALUE-TECH-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Translate Technical Progress into Customer Value.',NULL),
(N'PH-WF-VALUE-TECH-01-02',N'WF-VALUE-TECH-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Translate Technical Progress into Customer Value.',NULL),
(N'PH-WF-VALUE-TECH-01-03',N'WF-VALUE-TECH-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-VTEAM-01-01',N'WF-VTEAM-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Orchestrate the Specialist, Technical Team, Partners, and Funding.',NULL),
(N'PH-WF-VTEAM-01-02',N'WF-VTEAM-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Orchestrate the Specialist, Technical Team, Partners, and Funding.',NULL),
(N'PH-WF-VTEAM-01-03',N'WF-VTEAM-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL),
(N'PH-WF-WORKLOAD-01-01',N'WF-WORKLOAD-01',1,N'Preparation',N'Ground the Huddle in relevant context, evidence, and the current state of Prioritize AI and Azure Workloads by Readiness and Impact.',NULL),
(N'PH-WF-WORKLOAD-01-02',N'WF-WORKLOAD-01',2,N'Explore and Practice',N'Examine the workflow, discuss friction, and use one or more AI-assisted Practices relevant to Prioritize AI and Azure Workloads by Readiness and Impact.',NULL),
(N'PH-WF-WORKLOAD-01-03',N'WF-WORKLOAD-01',3,N'Commit to Action',N'Choose the next experiment, confirm the Human Checkpoint, assign ownership, and identify evidence to bring back.',NULL); SELECT @SourceCount=COUNT(*) FROM @Source; SELECT @MissingRelationshipCount=COUNT(*) FROM @Source s WHERE NOT EXISTS(SELECT 1 FROM dbo.HuddleTopics t WHERE t.ExternalId=s.TopicExternalId); SELECT @UpdatedCount=COUNT(*) FROM @Source s JOIN dbo.HuddlePhases p ON p.ExternalId=s.ExternalId; UPDATE p SET p.HuddleTopicId=t.Id,p.DisplayOrder=s.DisplayOrder,p.Name=s.Name,p.Description=s.Description,p.DurationMinutes=s.DurationMinutes,p.UpdatedAtUtc=SYSUTCDATETIME() FROM dbo.HuddlePhases p JOIN @Source s ON s.ExternalId=p.ExternalId JOIN dbo.HuddleTopics t ON t.ExternalId=s.TopicExternalId; INSERT dbo.HuddlePhases(ExternalId,HuddleTopicId,DisplayOrder,Name,Description,DurationMinutes,CreatedAtUtc) SELECT s.ExternalId,t.Id,s.DisplayOrder,s.Name,s.Description,s.DurationMinutes,SYSUTCDATETIME() FROM @Source s JOIN dbo.HuddleTopics t ON t.ExternalId=s.TopicExternalId WHERE NOT EXISTS(SELECT 1 FROM dbo.HuddlePhases p WHERE p.ExternalId=s.ExternalId); SET @InsertedCount=@@ROWCOUNT; SET @SkippedCount=@SourceCount-@InsertedCount-@UpdatedCount;
    SELECT @SourceCount AS SourceCount, @InsertedCount AS InsertedCount, @UpdatedCount AS UpdatedCount, @SkippedCount AS SkippedCount, @DuplicateCount AS DuplicateExternalIds, @MissingRelationshipCount AS MissingRelationships;
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
