/*
    IMPORTANT:
    Review the selected database before executing this script.
    This script was generated for manual execution in SSMS.
    It has not been executed by Codex.
*/
USE [AitoWorkflowAndHuddleGeneratorDb];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @SourceCount int = 0, @InsertedCount int = 0, @UpdatedCount int = 0, @SkippedCount int = 0, @DuplicateCount int = 0, @MissingRelationshipCount int = 0;
    DECLARE @Source TABLE(ExternalId nvarchar(100),TopicExternalId nvarchar(100),PhaseExternalId nvarchar(100),DisplayOrder int,Name nvarchar(300),Description nvarchar(max),DurationMinutes int,Prompt nvarchar(max),ExpectedOutput nvarchar(max),HumanCheckpoint nvarchar(max),RequiredContext nvarchar(max),BestFitJob nvarchar(max)); INSERT @Source VALUES
(N'WF-SE-DISC-01-P-SE-01',N'WF-SE-DISC-01',N'PH-WF-SE-DISC-01-01',2,N'Build the grounded technical discovery brief',NULL,NULL,N'Using the selected approved customer and technical sources, prepare for [meeting]. Summarize known outcomes, decisions, constraints, architecture context, open technical questions and missing evidence. Propose five discovery questions that advance the technical decision. Separate sourced facts from hypotheses.',N'Technical discovery brief with questions and evidence gaps.',N'SE validates the sources, technical context and whether each question is appropriate.',NULL,NULL),
(N'WF-SE-DISC-01-P-SE-02',N'WF-SE-DISC-01',N'PH-WF-SE-DISC-01-01',1,N'Rehearse the technical discovery conversation',NULL,NULL,N'Role-play [customer or stakeholder] for the upcoming technical discovery conversation. Use the approved brief only. Simulate realistic questions and objections, coach clarity and listening, and identify statements requiring technical or customer validation. Do not invent customer facts.',N'Role-play, coaching observations and improvement actions.',N'SE verifies facts, claims and commitments and decides what to change.',NULL,NULL),
(N'WF-SE-ARCH-01-P-SE-01',N'WF-SE-ARCH-01',N'PH-WF-SE-ARCH-01-01',1,N'Compare architecture options and evidence',NULL,NULL,N'Research [architecture decision] using current authoritative Microsoft and approved customer sources. Compare viable options against [decision criteria], identify assumptions, risks, dependencies and evidence gaps, and cite each material claim.',N'Sourced architecture options assessment.',N'SE and architecture SMEs validate current guidance, applicability and unsupported assumptions.',NULL,NULL),
(N'WF-SE-ARCH-01-P-SE-02',N'WF-SE-ARCH-01',N'PH-WF-SE-ARCH-01-01',2,N'Create the architecture decision record',NULL,NULL,N'Using the approved discovery brief and architecture evidence, create a decision record with customer outcome, options considered, criteria, selected direction, risks, dependencies, validation steps, unresolved questions and next technical action.',N'Architecture decision record.',N'SE validates architecture, security, operations, feasibility and customer commitments.',NULL,NULL),
(N'WF-SE-DEMO-01-P-SE-01',N'WF-SE-DEMO-01',N'PH-WF-SE-DEMO-01-02',1,N'Build the demo or workshop plan',NULL,NULL,N'Create a demo or workshop package for [customer decision]. Include audience, scenario, decision criteria, agenda, demo flow, sample data needs, roles, likely objections, tenant or permission dependencies, fallback plan and explicit next decision.',N'Demo or workshop package.',N'SE validates the environment, permissions, technical behavior, evidence and customer appropriateness.',NULL,NULL),
(N'WF-SE-DEMO-01-P-SE-02',N'WF-SE-DEMO-01',N'PH-WF-SE-DEMO-01-01',2,N'Research supporting proof and objections',NULL,NULL,N'Find current authoritative evidence for [scenario or capability]. Return only claims relevant to the customer decision, likely objections, known limitations and SME-needed flags. Cite sources.',N'Evidence and objection brief.',N'SE validates freshness and applicability before customer use.',NULL,NULL),
(N'WF-SE-POC-01-P-SE-01',N'WF-SE-POC-01',N'PH-WF-SE-POC-01-01',1,N'Scope the smallest useful proof',NULL,NULL,N'Create a PoC plan for [technical decision]. Define hypothesis, in-scope scenario, success and exit criteria, milestones, data and environment needs, roles, risks, dependencies, review gates, final decision and handoff if successful.',N'PoC plan and decision gates.',N'SE confirms scope, resources, security, feasibility and that the PoC is necessary.',NULL,NULL),
(N'WF-SE-POC-01-P-SE-02',N'WF-SE-POC-01',N'PH-WF-SE-POC-01-01',2,N'Pressure-test PoC readiness',NULL,NULL,N'Review this PoC plan. Identify vague success criteria, unowned dependencies, unrealistic milestones, missing security or data assumptions, weak linkage to the customer decision and unclear exit paths. Return five review questions and the smallest revisions needed.',N'Readiness review and revision list.',N'SE owns the go or no-go decision and confirms all required reviewers.',NULL,NULL),
(N'WF-SE-DEAL-01-P-SE-01',N'WF-SE-DEAL-01',N'PH-WF-SE-DEAL-01-01',1,N'Inspect technical deal health',NULL,NULL,N'Review [opportunity] and summarize the intended customer decision, current technical stage, exit criteria, proof completed, open blockers, recent technical engagement, missing roles and next recommended technical action. Show the source signal and flag unavailable context.',N'Technical deal-health brief.',N'SE validates MSX accuracy, customer context, technical risk and the next action.',NULL,NULL),
(N'WF-SE-DEAL-01-P-SE-02',N'WF-SE-DEAL-01',N'PH-WF-SE-DEAL-01-01',2,N'Create the technical risk and handoff plan',NULL,NULL,N'Using approved sources, create a technical risk and handoff plan with blocker, impact, evidence, owner, mitigation, checkpoint, decision needed and delivery handoff requirements.',N'Technical risk register and handoff plan.',N'SE confirms ownership, feasibility, customer commitments and delivery readiness.',NULL,NULL),
(N'WF-SE-ASSET-01-P-SE-01',N'WF-SE-ASSET-01',N'PH-WF-SE-ASSET-01-02',1,N'Package a reusable technical asset',NULL,NULL,N'Using the approved [demo, script, architecture, response or checklist], create a reusable asset package with purpose, prerequisites, steps, editable parameters, validation checks, known limitations, owner and example use.',N'Reusable asset package.',N'SE removes sensitive content, validates technical accuracy and confirms reuse permissions.',NULL,NULL),
(N'WF-SE-ASSET-01-P-SE-02',N'WF-SE-ASSET-01',N'PH-WF-SE-ASSET-01-01',2,N'Create a technical Skill Blueprint',NULL,NULL,N'Create a reusable Skill Blueprint for [SE workflow]. Define trigger, inputs, trusted sources, ordered steps, expected output, rules, exclusions, exception behavior, human review and one representative test case. Do not publish until tested.',N'Skill Blueprint and test case.',N'SE or skill owner tests representative work and validates access, outputs and safeguards.',NULL,NULL),
(N'WF-SE-QA-01-P-SE-01',N'WF-SE-QA-01',N'PH-WF-SE-QA-01-01',1,N'Draft a grounded technical answer',NULL,NULL,N'Answer the selected technical questions using approved and authoritative sources. For each item provide a grounded answer, source citation, confidence, assumptions and SME-needed flag. Preserve the question order and do not hide unsupported areas.',N'Grounded technical answer matrix.',N'SE and relevant SMEs approve technical, security, legal and product claims.',NULL,NULL),
(N'WF-SE-QA-01-P-SE-02',N'WF-SE-QA-01',N'PH-WF-SE-QA-01-01',2,N'Assemble the governed technical response',NULL,NULL,N'Using the approved answer matrix, assemble the response in the requested format. Create an exception list for unanswered items, assign suggested reviewers and provide a final quality checklist. Do not submit or send.',N'Formatted response plus exception list.',N'SE validates completeness and obtains required approvals before distribution.',NULL,NULL),
(N'WF-CE-RISK-01-P-CE-01',N'WF-CE-RISK-01',N'PH-WF-CE-RISK-01-01',1,N'Identify commercial risk and escalation priorities',NULL,NULL,N'Review proactive insights and certified business signals affecting my deals. Identify top commercial risks, supporting signal, likely impact, recommended mitigation, owner and where escalation may be required. Flag unavailable data.',N'Prioritized commercial risk view.',N'CE validates data scope, business context, risk, mitigation and escalation.',NULL,NULL),
(N'WF-CE-RISK-01-P-CE-02',N'WF-CE-RISK-01',N'PH-WF-CE-RISK-01-01',2,N'Build the commercial meeting brief',NULL,NULL,N'Prepare the CE commercial brief for [account/opportunity]. Include contract context, proposed structure, concessions available, terms to contest, current approvals, renewal or consumption risk, likely customer questions and the next commercial decision.',N'Commercial decision brief.',N'CE validates terms, authority, source freshness and customer-facing positions.',NULL,NULL),
(N'WF-CE-STRUCT-01-P-CE-01',N'WF-CE-STRUCT-01',N'PH-WF-CE-STRUCT-01-01',1,N'Compare viable commercial structures',NULL,NULL,N'For [opportunity], compare three viable commercial structures using available approved context. For each show products or SKUs, term, pricing logic, customer value, Microsoft trade-offs, risks, approvals and assumptions. Do not create or submit an offer.',N'Commercial options matrix.',N'CE validates pricing, products, licensing, authority, policy and feasibility.',NULL,NULL),
(N'WF-CE-STRUCT-01-P-CE-02',N'WF-CE-STRUCT-01',N'PH-WF-CE-STRUCT-01-01',2,N'Create the commercial decision narrative',NULL,NULL,N'Using the approved deal context and options, draft a commercial decision narrative with customer outcome, options considered, recommended structure, value trades, assumptions, risks, required reviewers and next decision.',N'Internal commercial recommendation.',N'CE approves the recommendation and routes required review.',NULL,NULL),
(N'WF-CE-POLICY-01-P-CE-01',N'WF-CE-POLICY-01',N'PH-WF-CE-POLICY-01-01',1,N'Check eligibility and execution needs',NULL,NULL,N'Using the current approved guidance and proposed segment, products, SKUs and terms, identify eligibility, required amendments, execution steps, approval needs and side-agreement risk. Cite the exact guidance used and flag uncertainty.',N'Policy and eligibility checklist.',N'CE validates source version, interpretation and required legal, finance or Deal Desk review.',NULL,NULL),
(N'WF-CE-POLICY-01-P-CE-02',N'WF-CE-POLICY-01',N'PH-WF-CE-POLICY-01-01',2,N'Inspect licensing and discount risk',NULL,NULL,N'Review the proposed licensing and discount structure for [account]. Identify compliance concerns, unused or mismatched licensing, discount exceptions, policy questions, approval requirements and renewal risk.',N'Licensing and discount risk review.',N'CE validates licensing, eligibility, discount authority, policy and recommended action.',NULL,NULL),
(N'WF-CE-NEG-01-P-CE-01',N'WF-CE-NEG-01',N'PH-WF-CE-NEG-01-01',2,N'Build the negotiation strategy and concession plan',NULL,NULL,N'Build a negotiation plan for [deal]. Include customer objectives, Microsoft objectives, opening position, must-have terms, tradable items, concession ladder, give/get logic, likely objections, walk-away or escalation triggers and next decision.',N'Negotiation and concession plan.',N'CE validates authority, customer context, policy, value trades and escalation triggers.',NULL,NULL),
(N'WF-CE-NEG-01-P-CE-02',N'WF-CE-NEG-01',N'PH-WF-CE-NEG-01-02',1,N'Rehearse the commercial negotiation',NULL,NULL,N'Role-play the upcoming commercial negotiation using the approved plan. Simulate realistic customer objections and requests. Pause for my response, then coach clarity, value trading, concession discipline, policy boundaries and the next decision. Do not invent terms or authority.',N'Negotiation rehearsal and coaching actions.',N'CE validates all positions, concessions, authority and customer commitments before use.',NULL,NULL),
(N'WF-CE-APPROVAL-01-P-CE-01',N'WF-CE-APPROVAL-01',N'PH-WF-CE-APPROVAL-01-01',1,N'Map approvals and fastest governed path',NULL,NULL,N'Review opportunity [ID] and map all known approvals, policy checks, reviewers, dependencies and escalation paths. Highlight blockers, missing evidence and the next action for each. Draft a Deal Desk justification, but do not submit it.',N'Approval map and draft justification.',N'CE validates approval requirements, evidence, routing, precedent and final submission.',NULL,NULL),
(N'WF-CE-APPROVAL-01-P-CE-02',N'WF-CE-APPROVAL-01',N'PH-WF-CE-APPROVAL-01-03',2,N'Create the commercial execution tracker',NULL,NULL,N'Using approved deal materials, create an execution tracker with action, owner, evidence, dependency, due checkpoint, status, blocker, escalation and decision required. Separate customer actions from internal actions.',N'Commercial execution tracker.',N'CE confirms owners, dates, approvals, customer commitments and system-of-record updates.',NULL,NULL),
(N'WF-CE-RENEW-01-P-CE-01',N'WF-CE-RENEW-01',N'PH-WF-CE-RENEW-01-02',1,N'Build the CE-led renewal view',NULL,NULL,N'Build a CE-led renewal view for [account] with ARR, structure, expiry, MACC trajectory, usage or consumption signals, current discounts, concessions, risk, expansion potential, amendments and the next commercial decision. Flag unavailable data.',N'Renewal decision brief.',N'CE validates contract, revenue, usage, structure, risk, authority and ownership.',NULL,NULL),
(N'WF-CE-RENEW-01-P-CE-02',N'WF-CE-RENEW-01',N'PH-WF-CE-RENEW-01-01',2,N'Inspect upcoming renewal portfolio',NULL,NULL,N'Show upcoming renewals in the selected period for my scope. Prioritize by revenue, discount exposure, consumption or MACC risk, execution complexity and expansion potential. Explain the certified signal behind each priority.',N'Prioritized renewal radar.',N'CE validates report scope, signals, ownership and recommended intervention.',NULL,NULL),
(N'WF-CE-TRANS-01-P-CE-01',N'WF-CE-TRANS-01',N'PH-WF-CE-TRANS-01-01',1,N'Research agreement and commerce changes',NULL,NULL,N'Research current differences between [legacy agreement] and [new commerce model] using authoritative Microsoft sources. Summarize commercial, administrative and customer-impact differences, risks, unresolved questions and citations.',N'Sourced transition evidence brief.',N'CE and policy, licensing or legal SMEs validate applicability and current guidance.',NULL,NULL),
(N'WF-CE-TRANS-01-P-CE-02',N'WF-CE-TRANS-01',N'PH-WF-CE-TRANS-01-01',2,N'Build the customer migration brief',NULL,NULL,N'Using approved customer contract context and validated transition guidance, create a migration brief with current state, contractual differences, administrative shift, amendment needs, red-line risks, choices, timeline, responsibilities and customer talk track.',N'Customer-specific migration brief.',N'CE validates contract interpretation, policy, dates, commitments and required reviewers.',NULL,NULL),
(N'WF-HEALTH-01-P-CSA-01',N'WF-HEALTH-01',N'PH-WF-HEALTH-01-01',1,N'Build a technical health evidence brief',NULL,NULL,N'Using approved sources for [Customer], build a technical health brief. Separate verified evidence from assumptions. Summarize architecture and delivery state, material technical risks, optimization opportunities, open commitments, dependencies and missing evidence. End with the three issues that most deserve CSA attention and why.',N'Technical health brief.',N'CSA validates architecture, delivery, support, usage interpretation, priorities and commitments.',NULL,NULL),
(N'WF-HEALTH-01-P-CSA-02',N'WF-HEALTH-01',N'PH-WF-HEALTH-01-01',2,N'Prioritize a technical risk response',NULL,NULL,N'For [Customer] and [period], identify the most material enabled consumption, usage or adoption changes visible in this report. Show supporting metrics, distinguish evidence from interpretation, state what the report cannot answer, and suggest which signals warrant deeper technical review. Do not assign a health score or infer customer intent.',N'Evidence-backed signals and technical-review priorities.',N'CSA confirms report, filters, KPI meaning, technical significance and action.',NULL,NULL),
(N'WF-ARCH-01-P-CSA-01',N'WF-ARCH-01',N'PH-WF-ARCH-01-01',1,N'Compare production architecture options',NULL,NULL,N'Research architecture options for [workload/customer scenario] using approved Microsoft and authoritative public sources. Compare security, resilience, governance, scale, operational complexity, cost considerations, dependencies and maturity. Cite claims, identify conflicting guidance or missing evidence, and do not recommend until decision criteria are explicit.',N'Sourced option comparison.',N'CSA validates source authority, applicability, security, compliance and recommendation boundaries.',NULL,NULL),
(N'WF-ARCH-01-P-CSA-02',N'WF-ARCH-01',N'PH-WF-ARCH-01-01',2,N'Create the production-ready architecture package',NULL,NULL,N'Create a production-ready architecture decision package for [Customer/workload] using approved context and option analysis. Include desired outcome, current state, recommended architecture, alternative, tradeoffs, controls, governance, dependencies, sequence, readiness criteria, open decisions, and a human-review checklist. Stop and ask when evidence conflicts or a material decision lacks an owner.',N'Architecture decision package.',N'CSA owns the recommendation and obtains required reviews.',NULL,NULL),
(N'WF-TECH-01-P-CSA-01',N'WF-TECH-01',N'PH-WF-TECH-01-01',1,N'Build the technical decision path',NULL,NULL,N'For [Customer/opportunity], summarize outcome, current technical decision, stakeholders, recent interactions available, blockers, commitments and opportunity stage. Propose a decision path with evidence required, gaps, owners, milestones and next customer-facing action. Show source signals and flag unavailable context.',N'Grounded technical decision path.',N'CSA validates customer context, technical accuracy, owners, relevance and commitments.',NULL,NULL),
(N'WF-TECH-01-P-CSA-02',N'WF-TECH-01',N'PH-WF-TECH-01-01',2,N'Design the validation and proof plan',NULL,NULL,N'Using the approved technical decision brief, build the smallest useful validation plan for [decision]. Include criteria, hypothesis, evidence available, proof gaps, activities, success measures, exit criteria, owners, milestones, dependencies, risks and expected decision. Do not expand beyond what is necessary.',N'Validation plan.',N'CSA confirms scope, feasibility, criteria, evidence quality and ownership.',NULL,NULL),
(N'WF-TECH-CONV-01-P-CSA-01',N'WF-TECH-CONV-01',N'PH-WF-TECH-CONV-01-01',2,N'Prepare the technical advisory conversation',NULL,NULL,N'Using approved customer context and technical decision package, prepare for [meeting]. Include outcome, technical state, recommendation and tradeoffs, questions, supporting evidence, likely objections, caveats, next action and ownership. Flag claims requiring review.',N'Technical advisory conversation plan.',N'CSA validates claims, tradeoffs, context, commitments and follow-through.',NULL,NULL),
(N'WF-TECH-CONV-01-P-CSA-02',N'WF-TECH-CONV-01',N'PH-WF-TECH-CONV-01-01',1,N'Rehearse the architecture recommendation',NULL,NULL,N'Use the approved conversation plan to role-play with [customer/stakeholder]. Simulate realistic architecture, readiness, security, operational, cost and implementation questions. Coach clarity, evidence, listening, tradeoffs and next step. Identify claims needing SME review. Do not invent customer facts or commitments.',N'Role-play transcript and improvement actions.',N'CSA validates facts, guidance, claims and commitments.',NULL,NULL),
(N'WF-CONSUME-01-P-CSA-01',N'WF-CONSUME-01',N'PH-WF-CONSUME-01-01',1,N'Analyze consumption trajectory and shortfall drivers',NULL,NULL,N'For [Customer] and [period], analyze enabled consumption trajectory and compare it with the relevant plan or milestone view. Break down largest changes by available dimension, identify data-supported contributors to potential shortfall, show supporting metrics and state what the report cannot answer.',N'Consumption trajectory analysis.',N'CSA confirms scope, KPI definitions, technical significance and credibility.',NULL,NULL),
(N'WF-CONSUME-01-P-CSA-02',N'WF-CONSUME-01',N'PH-WF-CONSUME-01-01',2,N'Design a technical shortfall intervention',NULL,NULL,N'Using approved consumption analysis and available context for [Customer], identify technical blockers, workload milestones, stakeholders, commitments and dependencies relevant to the potential shortfall. Propose intervention options, owner candidates, customer touchpoints and evidence needed. Do not assume cause or make commitments.',N'Intervention options with evidence, owners and gaps.',N'CSA selects intervention and validates cause, context, ownership and commitments.',NULL,NULL),
(N'WF-OPT-01-P-CSA-01',N'WF-OPT-01',N'PH-WF-OPT-01-01',1,N'Build the optimization evidence base',NULL,NULL,N'For [Customer] and [period], summarize enabled usage, consumption and cost signals relevant to optimization. Identify material changes and patterns visible in the report and supporting metrics. Separate observations from recommendations and state missing architecture or business context.',N'Optimization evidence summary.',N'CSA confirms KPI meaning, architecture context, priorities and actionability.',NULL,NULL),
(N'WF-OPT-01-P-CSA-02',N'WF-OPT-01',N'PH-WF-OPT-01-01',2,N'Create the FinOps and optimization recommendation',NULL,NULL,N'Using approved evidence, create an optimization recommendation for [Customer/workload]. Include current state, outcome, options, supported technical and financial effect, architecture tradeoffs, dependencies, risks, milestones and human-review requirements. Do not invent savings or intent.',N'Optimization recommendation.',N'CSA validates architecture, feasibility, claims, relevance and ownership.',NULL,NULL),
(N'WF-VALUE-TECH-01-P-CSA-01',N'WF-VALUE-TECH-01',N'PH-WF-VALUE-TECH-01-01',1,N'Create the technical progress and value narrative',NULL,NULL,N'Using approved architecture, delivery, adoption, consumption, optimization and risk materials for [Customer], create the CSA contribution to the business review. Connect progress to supported outcomes, explain risks and decisions, identify commitments and owners, and propose next technical actions. Separate evidence from interpretation and flag unsupported value claims.',N'Technical progress and value narrative.',N'CSA validates technical and value claims, linkage, commitments and ownership.',NULL,NULL),
(N'WF-VALUE-TECH-01-P-CSA-02',N'WF-VALUE-TECH-01',N'PH-WF-VALUE-TECH-01-01',2,N'Assemble the technical review package',NULL,NULL,N'Assemble a technical customer-review package from approved sources: executive technical summary, architecture and delivery progress, consumption or adoption evidence, optimization actions, material risks, open decisions, commitments and follow-through tracker. Preserve source links and flag missing or contradictory evidence.',N'Structured technical-review package.',N'CSA reviews with relevant account, success, technical and commercial contributors.',NULL,NULL),
(N'AE-01-P01',N'WF-PIPE-01',N'PH-WF-PIPE-01-01',2,N'Ask what the certified business data says',NULL,NULL,N'For the current quarter, where is pipeline most materially behind plan? Break the gap down by stage, solution area, expected close timing, and account. Identify the largest contributors, distinguish pipeline-volume issues from progression or timing issues, and show the metrics supporting each conclusion. Flag anything the available report cannot answer.',N'Aggregate gap analysis grounded in the enabled MSXI report.',N'Confirm the report, filters, KPI definitions, and interpretation before using the answer in a forecast or management conversation.',NULL,NULL),
(N'AE-01-P04',N'WF-PIPE-01',N'PH-WF-PIPE-01-01',1,N'Review pipeline-hygiene corrections',NULL,NULL,N'Review eligible hygiene changes for the relevant opportunities. Confirm, adjust, revert, or opt out where a suggested change does not reflect the true customer and deal timeline.',N'Cleaner eligible fields with a reviewable correction experience, depending on the current rule.',N'Seller remains accountable for pipeline accuracy and should review each material change.',NULL,NULL),
(N'AE-02-P01',N'WF-FCST-01',N'PH-WF-FCST-01-01',1,N'Analyze certified forecast movement',NULL,NULL,N'Give me my weekly forecast narrative for [scope]: qualified versus committed change since last week, the five biggest movers up and down with one-line reasons, committed deals at risk in the next 30 days, and three inspection questions. Use only the enabled certified report and show supporting metrics.',N'A decision-ready output for the named workflow activity.',N'Verify sources, access, interpretation, customer context, commitments, and any system action before use.',NULL,NULL),
(N'AE-02-P02',N'WF-FCST-01',N'PH-WF-FCST-01-01',2,N'Create the inspection brief',NULL,NULL,N'Using the approved forecast analysis and my meeting notes, draft a concise forecast-call brief that separates sourced facts, seller judgment, risks, decisions needed, and follow-up actions.',N'A decision-ready output for the named workflow activity.',N'Verify sources, access, interpretation, customer context, commitments, and any system action before use.',NULL,NULL),
(N'AE-03-P01',N'WF-PLAN-01',N'PH-WF-PLAN-01-01',1,N'Prioritize account action',NULL,NULL,N'Rank my top 10 accounts for this week. For each, show the priority driver, active opportunity stage, renewal or whitespace signal, partner context, and the single highest-impact seller action. Show the source signal and flag missing context.',N'A decision-ready output for the named workflow activity.',N'Verify sources, access, interpretation, customer context, commitments, and any system action before use.',NULL,NULL),
(N'AE-03-P02',N'WF-PLAN-01',N'PH-WF-PLAN-01-01',2,N'Build or assess the account plan',NULL,NULL,N'For [Account] and [TPID], assess the current account plan, research evidence gaps, propose additive updates to priorities, stakeholders, opportunities, and next actions, and require approval before any MSX write.',N'A decision-ready output for the named workflow activity.',N'Verify sources, access, interpretation, customer context, commitments, and any system action before use.',NULL,NULL),
(N'AE-04-P01',N'WF-OPP-01',N'PH-WF-OPP-01-01',1,N'Qualify buying signals',NULL,NULL,N'Review [Account] across MSX, recent meetings, email, and available content. Summarize buying signals, risks, existing opportunity overlap, and the top three actions to create or progress a qualified opportunity. Flag signals that lack evidence.',N'A decision-ready output for the named workflow activity.',N'Verify sources, access, interpretation, customer context, commitments, and any system action before use.',NULL,NULL),
(N'AE-04-P02',N'WF-OPP-01',N'PH-WF-OPP-01-01',2,N'Develop whitespace outreach',NULL,NULL,N'Analyze whitespace for [scope]. Identify accounts with low solution penetration relative to known priorities, propose the top three opportunity hypotheses, and create an initial outreach plan with a first-meeting agenda. Separate evidence from assumptions.',N'A decision-ready output for the named workflow activity.',N'Verify sources, access, interpretation, customer context, commitments, and any system action before use.',NULL,NULL),
(N'AE-05-P01',N'WF-DEAL-01',N'PH-WF-DEAL-01-01',1,N'Create a deal inspection',NULL,NULL,N'For [Opportunity], create a deal book with stage, value, close date, exit-criteria evidence, open approvals or pricing gaps, top three risks, and next three actions. Flag unsupported assumptions and decisions requiring CE, ATS, SSP, SE, CSAM, or partner input.',N'A decision-ready output for the named workflow activity.',N'Verify sources, access, interpretation, customer context, commitments, and any system action before use.',NULL,NULL),
(N'AE-05-P02',N'WF-DEAL-01',N'PH-WF-DEAL-01-01',2,N'Prepare customer follow-up',NULL,NULL,N'Using the reviewed deal inspection and latest customer interaction, draft a follow-up that confirms customer outcomes, open decisions, commitments, and the next agreed action. Do not invent commitments.',N'A decision-ready output for the named workflow activity.',N'Verify sources, access, interpretation, customer context, commitments, and any system action before use.',NULL,NULL),
(N'AE-07-P01',N'WF-RENEW-01',N'PH-WF-RENEW-01-01',1,N'Assess renewal risk and expansion',NULL,NULL,N'Show my accounts with renewals in the next six months. For each, summarize ARR, licensing, consumption trend, usage gaps, recent customer engagement, expansion signals, and risk evidence. Prioritize by potential impact and flag missing data.',N'A decision-ready output for the named workflow activity.',N'Verify sources, access, interpretation, customer context, commitments, and any system action before use.',NULL,NULL),
(N'AE-07-P02',N'WF-RENEW-01',N'PH-WF-RENEW-01-01',2,N'Draft a renewal outreach package',NULL,NULL,N'For [Account] renewing in [Month], use the reviewed renewal assessment and source materials to draft outreach tied to stated goals, value delivered, unresolved consumption gaps, and expansion options. Flag pricing or commercial claims for CE review.',N'A decision-ready output for the named workflow activity.',N'Verify sources, access, interpretation, customer context, commitments, and any system action before use.',NULL,NULL),
(N'AE-06-P-AE01',N'WF-CONV-01',N'PH-WF-CONV-01-01',2,N'Build the account and conversation brief',NULL,NULL,N'Prepare me for my next conversation with [Account]. Summarize priorities from the last 60 days, sentiment shifts, open commitments, active MSX opportunities, competitive mentions, engaged account-team roles, and missing context. Recommend three talking points and the single ask that best advances the customer decision. Show the source signal for each major claim.',N'Grounded AE conversation brief with source signals, gaps, talking points, and ask.',N'AE verifies current customer context, opportunity strategy, relationship nuance, claims, and ask.',NULL,NULL),
(N'WF-CONV-01-P-AE-JAI',N'WF-CONV-01',N'PH-WF-CONV-01-01',1,N'Rehearse the executive customer conversation',NULL,NULL,N'Use Agent J.ai to role-play the upcoming [meeting type] with [customer or stakeholder]. Use the approved conversation plan and focus on the AE contribution: executive narrative, customer outcome, primary ask, fallback ask, likely questions, and relationship-sensitive responses. Simulate realistic questions or objections, pause for the participant response, then provide coaching on clarity, evidence, listening, and the proposed next step. Identify claims, commitments, technical guidance, or commercial positions that require human or SME review. Do not invent customer facts or make commitments.',N'Interactive role-play, targeted coaching, realistic questions or objections, and a short improvement list.',N'Participant validates customer facts, claims, commitments, technical or commercial guidance, and decides what to change before customer use.',NULL,NULL),
(N'WF-INTEL-01-P-ATS-01',N'WF-INTEL-01',N'PH-WF-INTEL-01-01',1,N'Build the account intelligence brief',NULL,NULL,N'Act as my account intelligence analyst for [Account]. Build a meeting prep brief; explain [KPI]; prioritize AI/Azure workloads; surface technical risks; close with executive talking points and actions.',N'Account intelligence and meeting-prep brief with risks, priorities, and actions.',N'ATS validates current account context, stakeholder interpretation, technical risk, and customer relevance.',NULL,NULL),
(N'WF-INTEL-01-P-ATS-02',N'WF-INTEL-01',N'PH-WF-INTEL-01-02',2,N'Explain the KPI and locate the report',NULL,NULL,N'How is [KPI] calculated? Link me to the relevant report and explain the methodology.',N'KPI definition, methodology, and report link.',N'ATS confirms that the KPI, scope, and report match the business question.',NULL,NULL),
(N'WF-NARR-01-P-ATS-01',N'WF-NARR-01',N'PH-WF-NARR-01-01',1,N'Prepare the CxO technical briefing',NULL,NULL,N'Prepare a CxO technical briefing for [Account] on [Topic], with outcomes, architecture, risks, proof points, talking points, and technical ask.',N'CxO technical briefing with risks, proof points, talking points, and ask.',N'ATS validates architecture, risk, proof, customer context, and technical ask.',NULL,NULL),
(N'WF-NARR-01-P-ATS-02',N'WF-NARR-01',N'PH-WF-NARR-01-02',2,N'Build the executive technical deck',NULL,NULL,N'Build a 12-slide exec deck aligned to stated outcomes and the Azure/AI roadmap; flag three open technical decisions.',N'Executive technical deck with open decisions flagged.',N'ATS reviews all claims, roadmap statements, evidence, and participant-facing content.',NULL,NULL),
(N'WF-WORKLOAD-01-P-ATS-01',N'WF-WORKLOAD-01',N'PH-WF-WORKLOAD-01-01',1,N'Prioritize AI and Azure workloads',NULL,NULL,N'Turn this week’s Proactive Insights into a prioritized AI workload action list with workload, ACR upside, readiness, owner, and due date.',N'Prioritized workload action list with rationale, owner, and date.',N'ATS validates readiness, technical feasibility, upside interpretation, owner, and priority.',NULL,NULL),
(N'WF-WORKLOAD-01-P-ATS-02',N'WF-WORKLOAD-01',N'PH-WF-WORKLOAD-01-01',2,N'Research workload readiness evidence',NULL,NULL,N'Investigate [candidate workloads] for [Account]. Compare customer objectives, current estate, security posture, AI readiness, technical dependencies, adoption blockers, relevant external evidence, and validation gaps. Separate sourced facts from recommendations.',N'Evidence brief supporting workload prioritization.',N'ATS validates source quality, relevance, architecture implications, and recommendation.',NULL,NULL),
(N'WF-TECH-01-P-ATS-STRAT01',N'WF-TECH-01',N'PH-WF-TECH-01-01',3,N'Analyze consumption and technical blockers',NULL,NULL,N'Show MACC consumption versus target for [Account], flag blockers, and recommend architecture and partner actions.',N'Consumption gap and blocker view with candidate actions.',N'ATS validates consumption interpretation, architecture actions, partner need, and customer context.',NULL,NULL),
(N'WF-TECH-01-P-ATS-STRAT02',N'WF-TECH-01',N'PH-WF-TECH-01-01',4,N'Research technical options and bets',NULL,NULL,N'Analyze the main pipeline and consumption drivers for [Account] and recommend the top three technical bets. For each, include the business outcome, stakeholder, security posture, AI workload readiness, adoption blocker, first conversation, and validation gap. Separate sourced evidence from recommendations.',N'Three evidence-backed technical bets with validation gaps.',N'ATS validates evidence, feasibility, strategic fit, and recommended priority.',NULL,NULL),
(N'WF-EBC-01-P-ATS-01',N'WF-EBC-01',N'PH-WF-EBC-01-01',1,N'Design the executive briefing experience',NULL,NULL,N'Help me organize an EBC for [Customer], choose the right session, and propose a coherent timeline and prep plan. Include desired customer decisions, participants, evidence, role contributions, preparation milestones, and follow-through.',N'EBC plan with session design, participants, evidence, timeline, and follow-through.',N'ATS validates the purpose, participants, technical narrative, evidence, and customer decision.',NULL,NULL),
(N'WF-TALK-01-P-ATS-JAI',N'WF-TALK-01',N'PH-WF-TALK-01-03',1,N'Rehearse the strategic technical talk track',NULL,NULL,N'Use Agent J.ai to role-play the upcoming strategic technical conversation with [customer or stakeholder]. Use the approved narrative and focus on technical outcomes, open decisions, likely objections, evidence, and the technical ask. Pause for my response before coaching me on clarity, listening, evidence, and next step. Do not invent customer facts or commitments.',N'Interactive rehearsal, likely questions or objections, coaching, and improvement actions.',N'ATS validates customer facts, technical claims, commitments, evidence, and any response used with the customer.',NULL,NULL),
(N'WF-TALK-01-P-ATS-02',N'WF-TALK-01',N'PH-WF-TALK-01-01',2,N'Adjust the talk track from current signals',NULL,NULL,N'Using the approved account brief, recent meetings, email, and technical source materials, identify the customer signals that should change the technical talk track. Draft revised opening language, five questions, likely objections, and responses. Separate sourced facts from recommendations.',N'Revised technical talk track grounded in selected signals.',N'ATS validates signal interpretation, technical accuracy, customer relevance, and claims.',NULL,NULL),
(N'WF-TEAM-01-P-ATS-01',N'WF-TEAM-01',N'PH-WF-TEAM-01-01',1,N'Create the technical V-team alignment brief',NULL,NULL,N'Using the approved account and technical context, create a V-team alignment brief with the customer outcome, priority workloads, technical decisions, risks, required roles, dependencies, owner for each action, and next checkpoint. Flag unsupported assumptions.',N'Technical V-team alignment brief with owners and checkpoints.',N'ATS validates role need, ownership, dependencies, risk, and customer relevance.',NULL,NULL),
(N'WF-TEAM-01-P-ATS-ECIF02',N'WF-TEAM-01',N'PH-WF-TEAM-01-01',2,N'Assess ECIF investment opportunities',NULL,NULL,N'Review Opportunity ID [ID]. Using the customer architecture roadmap, consumption goals, and current deployment blockers, identify and prioritize where ECIF funding could accelerate time-to-value. Include target scenario, expected outcome, directional consumption impact, blocker reduction, risks, dependencies, and reasons ECIF may not be appropriate.',N'Prioritized ECIF funding opportunities with outcomes, impact, risks, and dependencies.',N'ATS and ECIF owner validate eligibility, funding motion, technical feasibility, consumption assumptions, dependencies, and recommendation.',NULL,NULL),
(N'WF-LEAD-01-P-SSP-01',N'WF-LEAD-01',N'PH-WF-LEAD-01-01',2,N'Build a prioritized lead follow-up plan',NULL,NULL,N'Using the approved lead, attendee, account, email, meeting, and public context, create a prioritized follow-up plan. For each lead include source, account, likely interest, solution relevance, suggested message, owner, and next action. Flag missing evidence.',N'Prioritized lead follow-up plan.',N'SSP validates consent, customer context, solution relevance, owner, and outreach language.',NULL,NULL),
(N'WF-LEAD-01-P-SSP-02',N'WF-LEAD-01',N'PH-WF-LEAD-01-01',1,N'Identify opportunities the SSP may be missing',NULL,NULL,N'For [solution area] across my active accounts, identify opportunity signals I may be missing. Show the source signal, likely customer need, relevant solution play, uncertainty, and the next discovery action.',N'Ranked opportunity hypotheses with next discovery actions.',N'SSP validates the signal, customer need, ownership, and whether an opportunity should be created or advanced.',NULL,NULL),
(N'WF-SOLUTION-01-P-SSP-01',N'WF-SOLUTION-01',N'PH-WF-SOLUTION-01-02',1,N'Build the solution-selling plan',NULL,NULL,N'Build a solution-selling plan for [solution play] at [account]. Include customer outcomes, maturity, solution vision, stakeholder coverage, value conversation arc, demo or workshop sequence, proof needs, risks, and a 30-day plan to clear the next decision. Flag missing stakeholders and unsupported claims.',N'Solution-selling plan with decisions, proof needs, and progression actions.',N'SSP validates customer need, stage, solution fit, evidence, stakeholders, and commitments.',NULL,NULL),
(N'WF-SOLUTION-01-P-SSP-02',N'WF-SOLUTION-01',N'PH-WF-SOLUTION-01-01',2,N'Create the solution strategy package',NULL,NULL,N'Using approved account and solution context, create a solution strategy package with vision, customer outcomes, stakeholder map, discovery gaps, demo or workshop plan, proof points, owners, timeline, risks, and next decision.',N'Structured solution strategy package.',N'SSP validates solution accuracy, source grounding, stakeholders, timeline, and customer-facing claims.',NULL,NULL),
(N'WF-VALUE-01-P-SSP-01',N'WF-VALUE-01',N'PH-WF-VALUE-01-02',1,N'Tailor the solution value narrative',NULL,NULL,N'Using the selected approved sources, build a customer-specific value narrative for [solution play] at [account]. Include the top three use cases, measurable or directional outcomes, proof points, differentiation, assumptions, caveats, and the next ask.',N'Customer-specific value narrative with review flags.',N'SSP validates value claims, proof, ROI or adoption assumptions, tone, and final ask.',NULL,NULL),
(N'WF-VALUE-01-P-SSP-02',N'WF-VALUE-01',N'PH-WF-VALUE-01-01',2,N'Research customer and market evidence for the value story',NULL,NULL,N'Research [customer/industry/use case] to identify relevant market evidence, customer signals, comparable proof, risks, and counterevidence for [solution play]. Separate sourced facts from recommendations and flag any unsupported value claim.',N'Evidence brief for the value narrative.',N'SSP validates source quality, application to the customer, and any value or competitor claim.',NULL,NULL),
(N'WF-CONV-01-P-SSP-01',N'WF-CONV-01',N'PH-WF-CONV-01-01',3,N'Prepare the solution-specific customer conversation',NULL,NULL,N'Prepare me for the upcoming [meeting] with [account]. Summarize priorities, stakeholders, open risks, competitive mentions, and solution context. Draft five discovery questions, proof points, likely objections with responses, and the primary next ask. Flag uncertainty.',N'Conversation plan with discovery questions, proof, objections, and ask.',N'SSP validates customer facts, evidence, competitive claims, and commitments.',NULL,NULL),
(N'WF-VTEAM-01-P-SSP-01',N'WF-VTEAM-01',N'PH-WF-VTEAM-01-02',2,N'Build the specialist and technical V-team plan',NULL,NULL,N'Create a V-team plan for [opportunity] with customer outcome, solution scope, required specialist and technical roles, partner need, funding consideration, dependencies, owner for each action, decision checkpoints, and unresolved risks.',N'V-team plan with owners and checkpoints.',N'SSP validates role need, ownership, partner or funding involvement, and commitments.',NULL,NULL),
(N'WF-VTEAM-01-P-SSP-02',N'WF-VTEAM-01',N'PH-WF-VTEAM-01-01',1,N'Recommend the right solution partner and co-sell role',NULL,NULL,N'Recommend the best partner for [solution play] at [account]. Explain relevant capabilities and prior evidence available in approved sources, the proposed role, dependencies, risks, and the next two-week ask. Draft the internal introduction message.',N'Partner recommendation and engagement plan.',N'SSP validates partner capability, evidence, conflict, customer fit, ownership, and outreach.',NULL,NULL),
(N'WF-COMP-01-P-SSP-01',N'WF-COMP-01',N'PH-WF-COMP-01-01',1,N'Build the competitive differentiation brief',NULL,NULL,N'Produce a competitive differentiation brief for [solution area] and [customer context]. Include relevant win/loss drivers, three strongest differentiators with proof, common objections with handlers, risks, and a concise talk track. Flag where data or proof is weak.',N'Competitive brief with differentiators, proof, objections, and talk track.',N'SSP validates freshness, source grounding, customer applicability, and claims before external use.',NULL,NULL),
(N'WF-COMP-01-P-SSP-02',N'WF-COMP-01',N'PH-WF-COMP-01-01',2,N'Research the competitive and industry context',NULL,NULL,N'Research [competitor], [solution area], and [customer industry]. Compare publicly supportable positions, proof, recent developments, common objections, and uncertainty. Do not infer confidential competitor information.',N'Sourced competitive context brief.',N'SSP validates source quality, timeliness, relevance, and customer-facing claims.',NULL,NULL),
(N'WF-DEAL-01-P-SSP-01',N'WF-DEAL-01',N'PH-WF-DEAL-01-01',3,N'Inspect solution opportunity readiness',NULL,NULL,N'Review opportunity [ID] for [solution play]. Summarize current stage, customer outcome, stakeholder coverage, proof or demo status, technical and commercial dependencies, partner or funding needs, blockers, and the single next decision required. Recommend actions with owners.',N'Readiness view with blockers, next decision, actions, and owners.',N'SSP validates stage, blockers, owners, dependencies, and commitments.',NULL,NULL),
(N'WF-DEAL-01-P-SSP-02',N'WF-DEAL-01',N'PH-WF-DEAL-01-01',4,N'Create the solution acceleration action plan',NULL,NULL,N'For my active [solution area] opportunities, identify stalled milestones, missing customer evidence, stakeholder gaps, and next actions. Prioritize the opportunities requiring SSP intervention this week.',N'Prioritized solution-opportunity action plan.',N'SSP validates report scope, stage, risk, intervention, and ownership.',NULL,NULL),
(N'WF-CONV-01-P-SSP-JAI',N'WF-CONV-01',N'PH-WF-CONV-01-01',4,N'Rehearse solution discovery and objection handling',NULL,NULL,N'Use Agent J.ai to role-play the upcoming [meeting type] with [customer or stakeholder]. Use the approved conversation plan and focus on solution discovery, differentiation, proof points, likely objections, next solution decision, and primary ask. Pause for the participant response, then coach clarity, evidence, listening, and next step. Do not invent customer facts or commitments.',N'Interactive role-play, targeted coaching, objections, and improvement list.',N'Participant validates facts, claims, commitments, guidance, and decides what to change.',NULL,NULL),
(N'WF-CS-HEALTH-01-P-CSAM-01',N'WF-CS-HEALTH-01',N'PH-WF-CS-HEALTH-01-01',1,N'Rank customer-health risk with evidence',NULL,NULL,N'Using the enabled customer-health experience for [portfolio/account], summarize visible usage, adoption, sentiment, support, delivery, commitment, and stakeholder signals. Prioritize the risks and opportunities without inventing a composite score. For each, show the evidence, likely driver, potential customer impact, mitigation options, owner candidates, and missing evidence.',N'Prioritized health risks and opportunities with evidence, mitigations, owners, and gaps.',N'CSAM validates customer context, health interpretation, urgency, ownership, and commitments.',NULL,NULL),
(N'WF-CS-HEALTH-01-P-CSAM-02',N'WF-CS-HEALTH-01',N'PH-WF-CS-HEALTH-01-01',2,N'Create the weekly health action plan',NULL,NULL,N'Using today’s Proactive Insights for my accounts, identify the accounts that need attention, state the visible driver for each, recommend one mitigation, and flag what should be aligned with the AE, CSA, support, or delivery this week. State what the experience cannot answer.',N'Weekly action plan with visible drivers, mitigations, alignment needs, and limitations.',N'CSAM confirms account priority, customer context, intervention, and escalation path.',NULL,NULL),
(N'WF-SUCCESS-01-P-CSAM-01',N'WF-SUCCESS-01',N'PH-WF-SUCCESS-01-01',1,N'Build an outcome-anchored success plan',NULL,NULL,N'Using the approved customer goals, commitments, meeting notes, delivery plans, and adoption evidence, draft a success plan for [Account]. Include outcomes, measures, milestones, workstreams, role assignments, customer and Microsoft actions, dependencies, review cadence, evidence gaps, and decisions needed. Separate sourced facts from recommendations.',N'Success-plan draft with outcomes, measures, milestones, owners, dependencies, and gaps.',N'CSAM validates outcomes, measures, mutual commitments, owners, and feasibility with the customer and v-team.',NULL,NULL),
(N'WF-SUCCESS-01-P-CSAM-02',N'WF-SUCCESS-01',N'PH-WF-SUCCESS-01-01',2,N'Maintain the success-plan operating rhythm',NULL,NULL,N'Review the approved [Account] success-plan sources and recent work content. Produce a package with milestone progress, evidence, open risks, blocked actions, decisions needed, owner follow-ups, and proposed changes to the next review agenda. Do not update systems or make commitments.',N'Review package with milestone status, decisions, owners, and proposed agenda changes.',N'CSAM reviews every change, confirms source quality, and decides what is communicated or recorded.',NULL,NULL),
(N'WF-CS-ORCH-01-P-CSAM-01',N'WF-CS-ORCH-01',N'PH-WF-CS-ORCH-01-01',1,N'Synthesize cross-team activity and misalignment',NULL,NULL,N'Analyze the selected approved emails, Teams messages, meetings, account records, delivery updates, and partner inputs for [Account]. List active workstreams with status, stakeholders, dependencies, blockers, and customer impact. Identify contradictory status or ownership, then propose the top five coordination actions.',N'Cross-team operating brief with workstreams, misalignment, dependencies, and actions.',N'CSAM validates participation, ownership, status, customer impact, and routing before sharing.',NULL,NULL),
(N'WF-CS-ORCH-01-P-CSAM-02',N'WF-CS-ORCH-01',N'PH-WF-CS-ORCH-01-01',2,N'Prepare a customer and stakeholder check-in',NULL,NULL,N'Prepare me for the [Account] stakeholder check-in. Summarize available recent interactions, priorities, open commitments, health or usage signals, delivery risks, and stakeholder context. Recommend three to five talking points and questions, and identify where another role should lead or review. Flag unavailable data.',N'Grounded stakeholder brief with questions, role alignment, and missing context.',N'CSAM validates customer facts, health interpretation, commitments, role ownership, and the final agenda.',NULL,NULL),
(N'WF-ESC-01-P-CSAM-01',N'WF-ESC-01',N'PH-WF-ESC-01-02',1,N'Triage delivery risk and escalations',NULL,NULL,N'For my authorized accounts, summarize the available ECIF engagements, milestones, open risks, remaining actions, owners, and items that may affect a customer outcome, Realize Value milestone, or renewal. Recommend which items require attention and draft a concise escalation request. Do not create or approve a workscope.',N'ECIF risk and action brief with milestones, owners, escalation candidates, and a draft request.',N'CSAM validates ECIF ownership, status, customer impact, program rules, escalation route, and excludes unsupported workscope authorship.',NULL,NULL),
(N'WF-ESC-01-P-CSAM-02',N'WF-ESC-01',N'PH-WF-ESC-01-01',2,N'Create the incident quarterback brief',NULL,NULL,N'Using the selected approved incident and delivery sources for [Account], create a quarterback brief with customer impact, current status, timeline, decisions, technical and support owners, open dependencies, communication needs, next checkpoints, and unresolved questions. Do not infer participation or incident facts not present in the sources.',N'Incident quarterback brief with impact, status, owners, dependencies, communications, and checkpoints.',N'CSAM validates incident facts, severity, ownership, customer communication, security or privacy boundaries, and escalation authority.',NULL,NULL),
(N'WF-CONSUME-01-P-CSAM-01',N'WF-CONSUME-01',N'PH-WF-CONSUME-01-01',3,N'Forecast consumption risk and intervention',NULL,NULL,N'For [Account/portfolio] and [period], summarize enabled ACR trends by workload, compare the visible trajectory to MACC or C+U commitments where available, identify likely drivers and milestone blockers, and propose intervention options. Show evidence and missing data.',N'Consumption-risk brief with trajectory, drivers, blockers, interventions, and gaps.',N'CSAM validates metrics, commitment context, causal claims, intervention feasibility, and owners.',NULL,NULL),
(N'WF-CONSUME-01-P-CSAM-02',N'WF-CONSUME-01',N'PH-WF-CONSUME-01-01',4,N'Connect shortfall risk to account action',NULL,NULL,N'Using the approved consumption-risk assessment for [Account] and available MSX context, identify related opportunities, active workstreams, stakeholders, milestones, and role handoffs. Recommend the next three actions and which AE, SSP, CSA, partner, or delivery owner should align.',N'Coordinated shortfall intervention plan with actions and role alignment.',N'CSAM validates opportunity linkage, role ownership, customer impact, and the next action.',NULL,NULL),
(N'WF-ADOPT-01-P-CSAM-01',N'WF-ADOPT-01',N'PH-WF-ADOPT-01-01',2,N'Identify adoption friction and next intervention',NULL,NULL,N'For [Customer/workload], investigate the stated adoption challenge using approved internal context plus current public Microsoft and industry sources. Summarize relevant usage patterns, common barriers, comparable adoption practices, evidence quality, and questions that must be answered before recommending an intervention.',N'Adoption evidence brief with barriers, practices, evidence quality, and open questions.',N'CSAM verifies relevance to the customer, avoids unsupported causal claims, and decides whether external evidence should shape the intervention.',NULL,NULL),
(N'WF-ADOPT-01-P-CSAM-02',N'WF-ADOPT-01',N'PH-WF-ADOPT-01-01',1,N'Build the value-realization brief',NULL,NULL,N'For [Account] and [period], summarize enabled month-over-month usage and adoption changes by workload. Connect only supported changes to known customer outcomes, identify evidence gaps, and draft a concise value story with the next adoption action.',N'Value-realization brief with supported signals, gaps, story, and next action.',N'CSAM validates the outcome linkage, value claims, customer context, and recommended action.',NULL,NULL),
(N'WF-RENEW-01-P-CSAM-01',N'WF-RENEW-01',N'PH-WF-RENEW-01-01',3,N'Build the renewal and expansion support view',NULL,NULL,N'For accounts renewing in [period], summarize available ARR, licensing, ACR versus commitment, major usage gaps, recent engagement, open opportunities, expansion signals supported by adoption evidence, and the AE or SSP to align with. Recommend three actions for each account and flag missing context.',N'Renewal and expansion support view with evidence, owners, actions, and gaps.',N'CSAM validates renewal facts, adoption evidence, customer intent, opportunity linkage, and ownership.',NULL,NULL),
(N'WF-RENEW-01-P-CSAM-02',N'WF-RENEW-01',N'PH-WF-RENEW-01-01',4,N'Rehearse the renewal or value-risk conversation',NULL,NULL,N'Use Agent J.ai to role-play an upcoming [renewal, value, adoption, or risk] conversation for [Account]. Use the approved evidence and plan. Simulate realistic customer questions and objections, coach clarity, evidence, listening, and next-step framing, and identify claims or commitments needing human or SME review. Do not invent customer facts.',N'Role-play, targeted coaching, likely questions or objections, and improvement actions.',N'CSAM validates all facts, commitments, value claims, commercial guidance, and the final conversation approach.',NULL,NULL); SELECT @SourceCount=COUNT(*) FROM @Source; SELECT @DuplicateCount=COUNT(*) FROM (SELECT PhaseExternalId,DisplayOrder FROM @Source GROUP BY PhaseExternalId,DisplayOrder HAVING COUNT(*)>1) d; IF @DuplicateCount>0 THROW 51003,'Duplicate activity phase/display-order source positions.',1; SELECT @MissingRelationshipCount=COUNT(*) FROM @Source s LEFT JOIN dbo.HuddleTopics t ON t.ExternalId=s.TopicExternalId LEFT JOIN dbo.HuddlePhases p ON p.ExternalId=s.PhaseExternalId WHERE t.Id IS NULL OR p.Id IS NULL; SELECT @UpdatedCount=COUNT(*) FROM @Source s JOIN dbo.HuddleActivities a ON a.ExternalId=s.ExternalId; UPDATE a SET a.DisplayOrder=-a.Id FROM dbo.HuddleActivities a JOIN @Source s ON s.ExternalId=a.ExternalId; UPDATE a SET a.HuddleTopicId=t.Id,a.HuddlePhaseId=p.Id,a.DisplayOrder=s.DisplayOrder,a.Name=s.Name,a.Description=NULL,a.DurationMinutes=NULL,a.Prompt=s.Prompt,a.ExpectedOutput=s.ExpectedOutput,a.HumanCheckpoint=s.HumanCheckpoint,a.RequiredContext=NULL,a.BestFitJob=NULL,a.UpdatedAtUtc=SYSUTCDATETIME() FROM dbo.HuddleActivities a JOIN @Source s ON s.ExternalId=a.ExternalId JOIN dbo.HuddleTopics t ON t.ExternalId=s.TopicExternalId JOIN dbo.HuddlePhases p ON p.ExternalId=s.PhaseExternalId; INSERT dbo.HuddleActivities(ExternalId,HuddleTopicId,HuddlePhaseId,DisplayOrder,Name,Description,DurationMinutes,Prompt,ExpectedOutput,HumanCheckpoint,RequiredContext,BestFitJob,CreatedAtUtc) SELECT s.ExternalId,t.Id,p.Id,s.DisplayOrder,s.Name,NULL,NULL,s.Prompt,s.ExpectedOutput,s.HumanCheckpoint,NULL,NULL,SYSUTCDATETIME() FROM @Source s JOIN dbo.HuddleTopics t ON t.ExternalId=s.TopicExternalId JOIN dbo.HuddlePhases p ON p.ExternalId=s.PhaseExternalId WHERE NOT EXISTS(SELECT 1 FROM dbo.HuddleActivities a WHERE a.ExternalId=s.ExternalId); SET @InsertedCount=@@ROWCOUNT; SET @SkippedCount=@SourceCount-@InsertedCount-@UpdatedCount;
    SELECT @SourceCount AS SourceCount, @InsertedCount AS InsertedCount, @UpdatedCount AS UpdatedCount, @SkippedCount AS SkippedCount, @DuplicateCount AS DuplicateExternalIds, @MissingRelationshipCount AS MissingRelationships;
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
