/*
    IMPORTANT:
    Review the selected database before executing this script.
    This script was generated for manual execution in SSMS.
    It has not been executed by Codex.
*/
USE [AitoWorkflowAndHuddleGeneratorDb];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @SourceCount int = 0, @InsertedCount int = 0, @UpdatedCount int = 0, @SkippedCount int = 0, @DuplicateCount int = 0, @MissingRelationshipCount int = 0;
    DECLARE @Source TABLE(ExternalId nvarchar(100),TopicExternalId nvarchar(100),SessionIntroduction nvarchar(max),KeyTalkingPoints nvarchar(max),DiscussionQuestions nvarchar(max),SuggestedTransitions nvarchar(max),WrapUpGuidance nvarchar(max)); INSERT @Source VALUES
(N'FG-001',N'WF-ADOPT-01',N'Frame Accelerate Adoption and Prove Value Realization as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-002',N'WF-ARCH-01',N'Frame Design a Production-Ready Customer Architecture as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-003',N'WF-CE-APPROVAL-01',N'Frame Orchestrate Approvals and Commercial Execution as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-004',N'WF-CE-NEG-01',N'Frame Prepare and Lead the Commercial Negotiation as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-005',N'WF-CE-POLICY-01',N'Frame Validate Licensing, Policy and Compliance as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-006',N'WF-CE-RENEW-01',N'Frame Build and Execute the Renewal Strategy as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-007',N'WF-CE-RISK-01',N'Frame Prioritize Commercial Risk and Intervention as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-008',N'WF-CE-STRUCT-01',N'Frame Develop Commercial Options and Deal Structure as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-009',N'WF-CE-TRANS-01',N'Frame Navigate Agreement and Commerce Transitions as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-010',N'WF-COMP-01',N'Frame Develop a Competitive Position and Response Plan as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-011',N'WF-CONSUME-01',N'Frame Forecast Consumption and Intervene on Risk as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-012',N'WF-CONV-01',N'Frame Prepare for a Customer Conversation as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-013',N'WF-CS-HEALTH-01',N'Frame Assess Customer Health and Prioritize Risk Response as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-014',N'WF-CS-ORCH-01',N'Frame Orchestrate Customer, Internal Team, Partners, and Delivery as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-015',N'WF-DEAL-01',N'Frame Accelerate a Strategic Deal as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-016',N'WF-EBC-01',N'Frame Design an Executive Briefing Experience as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-017',N'WF-ESC-01',N'Frame Quarterback Delivery Risk, Incidents, and Escalations as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-018',N'WF-FCST-01',N'Frame Build a Decision-Ready Forecast Narrative as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-019',N'WF-HEALTH-01',N'Frame Assess Customer Technical Health and Prioritize Risk as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-020',N'WF-INTEL-01',N'Frame Build an Account Intelligence and Meeting Prep Brief as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-021',N'WF-LEAD-01',N'Frame Prioritize Prospects and Follow Up on Leads as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-022',N'WF-NARR-01',N'Frame Assemble an Executive Technical Customer Narrative as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-023',N'WF-OPP-01',N'Frame Create and Qualify New Opportunities as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-024',N'WF-OPT-01',N'Frame Build a FinOps and Optimization Recommendation as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-025',N'WF-PIPE-01',N'Frame Inspect Pipeline Health and Restore Signal Quality as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-026',N'WF-PLAN-01',N'Frame Prioritize Accounts and Build an Actionable Account Plan as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-027',N'WF-RENEW-01',N'Frame Manage Renewal Risk and Expansion Readiness as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-028',N'WF-SE-ARCH-01',N'Frame Design and Validate the Customer Architecture as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-029',N'WF-SE-ASSET-01',N'Frame Capture and Reuse Technical Assets and Learning as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-030',N'WF-SE-DEAL-01',N'Frame Manage Technical Risk and Advance the Deal as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-031',N'WF-SE-DEMO-01',N'Frame Design a Demo or Workshop That Advances the Decision as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-032',N'WF-SE-DISC-01',N'Frame Lead Technical Discovery and Define Decision Criteria as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-033',N'WF-SE-POC-01',N'Frame Scope a PoC with Success and Exit Criteria as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-034',N'WF-SE-QA-01',N'Frame Respond to Technical Questions with Evidence and Confidence as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-035',N'WF-SOLUTION-01',N'Frame Build a Solution-Selling Plan as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-036',N'WF-SUCCESS-01',N'Frame Build and Govern an Outcome-Anchored Success Plan as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-037',N'WF-TALK-01',N'Frame Adjust the Technical Talk Track from Customer Signals as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-038',N'WF-TEAM-01',N'Frame Mobilize the Account Team and Partners as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-039',N'WF-TECH-01',N'Frame Build the Technical Decision and Validation Path as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-040',N'WF-TECH-CONV-01',N'Frame Prepare a Technical Advisory Customer Conversation as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-041',N'WF-VALUE-01',N'Frame Develop a Customer-Specific Value Narrative as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-042',N'WF-VALUE-TECH-01',N'Frame Translate Technical Progress into Customer Value as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-043',N'WF-VTEAM-01',N'Frame Orchestrate the Specialist, Technical Team, Partners, and Funding as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'),
(N'FG-044',N'WF-WORKLOAD-01',N'Frame Prioritize AI and Azure Workloads by Readiness and Impact as a real workflow the team can improve, not a tool demonstration.',NULL,N'["Where does this workflow create the most friction today?","What evidence would show improvement?","Which Practice is worth testing now?"]',N'Move from context to one practical AI-assisted experiment. Keep the discussion grounded in current work.',N'Ask participants to choose one experiment, owner, Human Checkpoint, and evidence to bring back.'); SELECT @SourceCount=COUNT(*) FROM @Source; SELECT @MissingRelationshipCount=COUNT(*) FROM @Source s WHERE NOT EXISTS(SELECT 1 FROM dbo.HuddleTopics t WHERE t.ExternalId=s.TopicExternalId); SELECT @UpdatedCount=COUNT(*) FROM @Source s JOIN dbo.HuddleFacilitatorGuides g ON g.ExternalId=s.ExternalId; UPDATE g SET g.HuddleTopicId=t.Id,g.SessionIntroduction=s.SessionIntroduction,g.KeyTalkingPoints=NULL,g.DiscussionQuestions=s.DiscussionQuestions,g.SuggestedTransitions=s.SuggestedTransitions,g.WrapUpGuidance=s.WrapUpGuidance,g.UpdatedAtUtc=SYSUTCDATETIME() FROM dbo.HuddleFacilitatorGuides g JOIN @Source s ON s.ExternalId=g.ExternalId JOIN dbo.HuddleTopics t ON t.ExternalId=s.TopicExternalId; INSERT dbo.HuddleFacilitatorGuides(ExternalId,HuddleTopicId,SessionIntroduction,KeyTalkingPoints,DiscussionQuestions,SuggestedTransitions,WrapUpGuidance,CreatedAtUtc) SELECT s.ExternalId,t.Id,s.SessionIntroduction,NULL,s.DiscussionQuestions,s.SuggestedTransitions,s.WrapUpGuidance,SYSUTCDATETIME() FROM @Source s JOIN dbo.HuddleTopics t ON t.ExternalId=s.TopicExternalId WHERE NOT EXISTS(SELECT 1 FROM dbo.HuddleFacilitatorGuides g WHERE g.ExternalId=s.ExternalId); SET @InsertedCount=@@ROWCOUNT; SET @SkippedCount=@SourceCount-@InsertedCount-@UpdatedCount;
    SELECT @SourceCount AS SourceCount, @InsertedCount AS InsertedCount, @UpdatedCount AS UpdatedCount, @SkippedCount AS SkippedCount, @DuplicateCount AS DuplicateExternalIds, @MissingRelationshipCount AS MissingRelationships;
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
