// <auto-generated />
using System;
using AitoWorkflowAndHuddleGenerator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AitoWorkflowAndHuddleGenerator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260809161627_AddHuddleDomainSchema")]
    partial class AddHuddleDomainSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvancedPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeginnerPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessOutcome")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("McemStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedOutputs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ToolCoverageLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TriggerContext")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("WorkflowBucketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("McemStage");

                    b.HasIndex("Priority");

                    b.HasIndex("RoleId");

                    b.HasIndex("WorkflowBucketId");

                    b.HasIndex("RoleId", "WorkflowBucketId", "IsActive");

                    b.ToTable("Activities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Activities_DurationMinutes", "[DurationMinutes] >= 0");
                        });
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.ActivityAiTool", b =>
                {
                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("AiToolId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ActivityId", "AiToolId");

                    b.HasIndex("AiToolId");

                    b.ToTable("ActivityAiTools", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.AiTool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IconKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("AiTools", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BestFitJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ExpectedOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HuddlePhaseId")
                        .HasColumnType("int");

                    b.Property<int>("HuddleTopicId")
                        .HasColumnType("int");

                    b.Property<string>("HumanCheckpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Prompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("HuddleTopicId");

                    b.HasIndex("HuddlePhaseId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("HuddleActivities", null, t =>
                        {
                            t.HasCheckConstraint("CK_HuddleActivities_DurationMinutes", "[DurationMinutes] IS NULL OR [DurationMinutes] > 0");
                        });
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleActivityAgent", b =>
                {
                    b.Property<int>("HuddleActivityId")
                        .HasColumnType("int");

                    b.Property<int>("HuddleAgentId")
                        .HasColumnType("int");

                    b.Property<string>("UsageType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DisplayLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("ShowAgentAccessLink")
                        .HasColumnType("bit");

                    b.HasKey("HuddleActivityId", "HuddleAgentId", "UsageType");

                    b.HasIndex("HuddleAgentId");

                    b.HasIndex("HuddleActivityId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("HuddleActivityAgents", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleActivityResource", b =>
                {
                    b.Property<int>("HuddleActivityId")
                        .HasColumnType("int");

                    b.Property<int>("HuddleResourceId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("HuddleActivityId", "HuddleResourceId");

                    b.HasIndex("HuddleResourceId");

                    b.HasIndex("HuddleActivityId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("HuddleActivityResources", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessLinkLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AccessUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KeyBenefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WhatItHelpsYouDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatItIs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhenToUseIt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("HuddleAgents", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleAgentResource", b =>
                {
                    b.Property<int>("HuddleAgentId")
                        .HasColumnType("int");

                    b.Property<int>("HuddleResourceId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("HuddleAgentId", "HuddleResourceId");

                    b.HasIndex("HuddleResourceId");

                    b.HasIndex("HuddleAgentId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("HuddleAgentResources", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleFacilitatorGuide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiscussionQuestions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HuddleTopicId")
                        .HasColumnType("int");

                    b.Property<string>("KeyTalkingPoints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionIntroduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestedTransitions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WrapUpGuidance")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("HuddleTopicId")
                        .IsUnique();

                    b.ToTable("HuddleFacilitatorGuides", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleFocusArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("HuddleFocusAreas", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleMcemStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("HuddleMcemStages", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddlePhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HuddleTopicId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("HuddleTopicId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("HuddlePhases", null, t =>
                        {
                            t.HasCheckConstraint("CK_HuddlePhases_DurationMinutes", "[DurationMinutes] IS NULL OR [DurationMinutes] > 0");
                        });
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LinkLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("HuddleResources", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleRolePathItem", b =>
                {
                    b.Property<int>("HuddleSegmentRoleId")
                        .HasColumnType("int");

                    b.Property<int>("WeekPosition")
                        .HasColumnType("int");

                    b.Property<int>("HuddleTopicId")
                        .HasColumnType("int");

                    b.HasKey("HuddleSegmentRoleId", "WeekPosition");

                    b.HasIndex("HuddleTopicId");

                    b.ToTable("HuddleRolePathItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_HuddleRolePathItems_WeekPosition", "[WeekPosition] > 0");
                        });
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("HuddleSegments", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleSegmentRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HuddleSegmentId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("HuddleSegmentId", "RoleId")
                        .IsUnique();

                    b.ToTable("HuddleSegmentRoles", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudienceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommitmentPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesiredOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("HuddleFocusAreaId")
                        .HasColumnType("int");

                    b.Property<string>("KeyTakeaway")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RecommendationPriority")
                        .HasColumnType("int");

                    b.Property<string>("ReflectionPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StepsToGetStarted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TodayObjective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UseCase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhyItMatters")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("HuddleFocusAreaId");

                    b.ToTable("HuddleTopics", null, t =>
                        {
                            t.HasCheckConstraint("CK_HuddleTopics_DurationMinutes", "[DurationMinutes] IS NULL OR [DurationMinutes] > 0");
                        });
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopicAgent", b =>
                {
                    b.Property<int>("HuddleTopicId")
                        .HasColumnType("int");

                    b.Property<int>("HuddleAgentId")
                        .HasColumnType("int");

                    b.Property<string>("UsageType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DisplayLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("ShowAgentAccessLink")
                        .HasColumnType("bit");

                    b.HasKey("HuddleTopicId", "HuddleAgentId", "UsageType");

                    b.HasIndex("HuddleAgentId");

                    b.HasIndex("HuddleTopicId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("HuddleTopicAgents", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopicMcemStage", b =>
                {
                    b.Property<int>("HuddleTopicId")
                        .HasColumnType("int");

                    b.Property<int>("HuddleMcemStageId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("HuddleTopicId", "HuddleMcemStageId");

                    b.HasIndex("HuddleMcemStageId");

                    b.HasIndex("HuddleTopicId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("HuddleTopicMcemStages", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopicResource", b =>
                {
                    b.Property<int>("HuddleTopicId")
                        .HasColumnType("int");

                    b.Property<int>("HuddleResourceId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("HuddleTopicId", "HuddleResourceId");

                    b.HasIndex("HuddleResourceId");

                    b.HasIndex("HuddleTopicId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("HuddleTopicResources", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopicRole", b =>
                {
                    b.Property<int>("HuddleTopicId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("HuddleTopicId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("HuddleTopicRoles", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleVote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DownvoteReasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HuddleTopicId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HuddleTopicId");

                    b.HasIndex("OwnerObjectId", "HuddleTopicId")
                        .IsUnique();

                    b.ToTable("HuddleVotes", null, t =>
                        {
                            t.HasCheckConstraint("CK_HuddleVotes_Value", "[Value] IN (-1, 1)");
                        });
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Segment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserHuddleActivityProgress", b =>
                {
                    b.Property<Guid>("UserHuddleSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HuddleActivityId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.HasKey("UserHuddleSessionId", "HuddleActivityId");

                    b.HasIndex("HuddleActivityId");

                    b.ToTable("UserHuddleActivityProgress", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserHuddlePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HuddleSegmentRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("HuddleSegmentRoleId");

                    b.ToTable("UserHuddlePlans", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserHuddlePlanItem", b =>
                {
                    b.Property<Guid>("UserHuddlePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WeekPosition")
                        .HasColumnType("int");

                    b.Property<int>("HuddleTopicId")
                        .HasColumnType("int");

                    b.HasKey("UserHuddlePlanId", "WeekPosition");

                    b.HasIndex("HuddleTopicId");

                    b.ToTable("UserHuddlePlanItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserHuddlePlanItems_WeekPosition", "[WeekPosition] > 0");
                        });
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserHuddleSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CurrentHuddlePhaseId")
                        .HasColumnType("int");

                    b.Property<int>("HuddleTopicId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CurrentHuddlePhaseId");

                    b.HasIndex("HuddleTopicId");

                    b.ToTable("UserHuddleSessions", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("OwnerObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TotalDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OwnerObjectId");

                    b.HasIndex("RoleId");

                    b.HasIndex("OwnerObjectId", "IsFavorite");

                    b.HasIndex("OwnerObjectId", "Name")
                        .IsUnique();

                    b.ToTable("UserWorkflows", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserWorkflows_TotalDurationMinutes", "[TotalDurationMinutes] >= 0");
                        });
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserWorkflowActivity", b =>
                {
                    b.Property<Guid>("UserWorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("UserWorkflowId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserWorkflowId", "SortOrder");

                    b.ToTable("UserWorkflowActivities", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.WorkflowBucket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("WorkflowBuckets", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.WorkflowShare", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RecipientDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("RecipientObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SharedByDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SharedByEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("SharedByObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserWorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecipientObjectId");

                    b.HasIndex("UserWorkflowId");

                    b.HasIndex("UserWorkflowId", "RecipientObjectId")
                        .IsUnique()
                        .HasFilter("[IsRevoked] = 0");

                    b.ToTable("WorkflowShares", (string)null);
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.Activity", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.Role", "Role")
                        .WithMany("Activities")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.WorkflowBucket", "WorkflowBucket")
                        .WithMany("Activities")
                        .HasForeignKey("WorkflowBucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("WorkflowBucket");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.ActivityAiTool", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.Activity", "Activity")
                        .WithMany("ActivityAiTools")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.AiTool", "AiTool")
                        .WithMany("ActivityAiTools")
                        .HasForeignKey("AiToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("AiTool");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleActivity", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddlePhase", "HuddlePhase")
                        .WithMany("Activities")
                        .HasForeignKey("HuddlePhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopic", "HuddleTopic")
                        .WithMany("Activities")
                        .HasForeignKey("HuddleTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HuddlePhase");

                    b.Navigation("HuddleTopic");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleActivityAgent", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleActivity", "HuddleActivity")
                        .WithMany("ActivityAgents")
                        .HasForeignKey("HuddleActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleAgent", "HuddleAgent")
                        .WithMany()
                        .HasForeignKey("HuddleAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HuddleActivity");

                    b.Navigation("HuddleAgent");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleActivityResource", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleActivity", "HuddleActivity")
                        .WithMany("ActivityResources")
                        .HasForeignKey("HuddleActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleResource", "HuddleResource")
                        .WithMany()
                        .HasForeignKey("HuddleResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HuddleActivity");

                    b.Navigation("HuddleResource");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleAgentResource", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleAgent", "HuddleAgent")
                        .WithMany()
                        .HasForeignKey("HuddleAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleResource", "HuddleResource")
                        .WithMany()
                        .HasForeignKey("HuddleResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HuddleAgent");

                    b.Navigation("HuddleResource");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleFacilitatorGuide", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopic", "HuddleTopic")
                        .WithOne("FacilitatorGuide")
                        .HasForeignKey("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleFacilitatorGuide", "HuddleTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HuddleTopic");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddlePhase", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopic", "HuddleTopic")
                        .WithMany("Phases")
                        .HasForeignKey("HuddleTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HuddleTopic");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleRolePathItem", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleSegmentRole", "HuddleSegmentRole")
                        .WithMany("PathItems")
                        .HasForeignKey("HuddleSegmentRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopic", "HuddleTopic")
                        .WithMany()
                        .HasForeignKey("HuddleTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HuddleSegmentRole");

                    b.Navigation("HuddleTopic");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleSegmentRole", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleSegment", "HuddleSegment")
                        .WithMany("SegmentRoles")
                        .HasForeignKey("HuddleSegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HuddleSegment");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopic", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleFocusArea", "HuddleFocusArea")
                        .WithMany("Topics")
                        .HasForeignKey("HuddleFocusAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HuddleFocusArea");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopicAgent", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleAgent", "HuddleAgent")
                        .WithMany()
                        .HasForeignKey("HuddleAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopic", "HuddleTopic")
                        .WithMany("TopicAgents")
                        .HasForeignKey("HuddleTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HuddleAgent");

                    b.Navigation("HuddleTopic");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopicMcemStage", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleMcemStage", "HuddleMcemStage")
                        .WithMany()
                        .HasForeignKey("HuddleMcemStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopic", "HuddleTopic")
                        .WithMany("McemStages")
                        .HasForeignKey("HuddleTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HuddleMcemStage");

                    b.Navigation("HuddleTopic");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopicResource", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleResource", "HuddleResource")
                        .WithMany()
                        .HasForeignKey("HuddleResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopic", "HuddleTopic")
                        .WithMany("TopicResources")
                        .HasForeignKey("HuddleTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HuddleResource");

                    b.Navigation("HuddleTopic");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopicRole", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopic", "HuddleTopic")
                        .WithMany("TopicRoles")
                        .HasForeignKey("HuddleTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HuddleTopic");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleVote", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopic", "HuddleTopic")
                        .WithMany()
                        .HasForeignKey("HuddleTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HuddleTopic");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserHuddleActivityProgress", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleActivity", "HuddleActivity")
                        .WithMany()
                        .HasForeignKey("HuddleActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserHuddleSession", "UserHuddleSession")
                        .WithMany("ActivityProgress")
                        .HasForeignKey("UserHuddleSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HuddleActivity");

                    b.Navigation("UserHuddleSession");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserHuddlePlan", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleSegmentRole", "HuddleSegmentRole")
                        .WithMany()
                        .HasForeignKey("HuddleSegmentRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HuddleSegmentRole");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserHuddlePlanItem", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopic", "HuddleTopic")
                        .WithMany()
                        .HasForeignKey("HuddleTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserHuddlePlan", "UserHuddlePlan")
                        .WithMany("Items")
                        .HasForeignKey("UserHuddlePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HuddleTopic");

                    b.Navigation("UserHuddlePlan");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserHuddleSession", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddlePhase", "CurrentHuddlePhase")
                        .WithMany()
                        .HasForeignKey("CurrentHuddlePhaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopic", "HuddleTopic")
                        .WithMany()
                        .HasForeignKey("HuddleTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentHuddlePhase");

                    b.Navigation("HuddleTopic");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserWorkflow", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserWorkflowActivity", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.Activity", "Activity")
                        .WithMany("UserWorkflowActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserWorkflow", "UserWorkflow")
                        .WithMany("UserWorkflowActivities")
                        .HasForeignKey("UserWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("UserWorkflow");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.WorkflowShare", b =>
                {
                    b.HasOne("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserWorkflow", "UserWorkflow")
                        .WithMany("WorkflowShares")
                        .HasForeignKey("UserWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserWorkflow");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.Activity", b =>
                {
                    b.Navigation("ActivityAiTools");

                    b.Navigation("UserWorkflowActivities");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.AiTool", b =>
                {
                    b.Navigation("ActivityAiTools");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleActivity", b =>
                {
                    b.Navigation("ActivityAgents");

                    b.Navigation("ActivityResources");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleFocusArea", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddlePhase", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleSegment", b =>
                {
                    b.Navigation("SegmentRoles");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleSegmentRole", b =>
                {
                    b.Navigation("PathItems");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.HuddleTopic", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("FacilitatorGuide");

                    b.Navigation("McemStages");

                    b.Navigation("Phases");

                    b.Navigation("TopicAgents");

                    b.Navigation("TopicResources");

                    b.Navigation("TopicRoles");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.Role", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserHuddlePlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserHuddleSession", b =>
                {
                    b.Navigation("ActivityProgress");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.UserWorkflow", b =>
                {
                    b.Navigation("UserWorkflowActivities");

                    b.Navigation("WorkflowShares");
                });

            modelBuilder.Entity("AitoWorkflowAndHuddleGenerator.Domain.Entities.WorkflowBucket", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
