/*
    Huddle placements, plus the compatible role-path items
    Generated from the Frontier Accelerator content workbook by generate.py.
    Do not hand-edit. Re-runnable: every statement is an ExternalId-keyed MERGE, nothing is deleted.
    70 placements: 49 role path, 7 orientation, 14 additional content.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
DECLARE @unresolved INT;
BEGIN TRANSACTION;

;WITH raw AS (
    SELECT * FROM (VALUES
        (N'AE-ORIENT', N'SR-ENT-AE', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation for Account Executives', N'Introduce the eight-session huddle motion, where AI reduces AE preparation and reporting work, which tools may appear, and what to review before next week''s topic.', N'Understand how the AE huddle path runs and where the human checkpoints protect account, deal, and forecast judgment.', N'You are not being asked to learn another tool for its own sake. You are being asked to reclaim time from prep, reporting, and chasing context so more of your week goes to customers and decisions.', N'AEs know how the huddle motion works, which tools may show up, what to review, and what AI experiences to bring back before next week.', 1),
        (N'AE-PLAN', N'SR-ENT-AE', N'WF-X-PLAN-01', N'SEC-ROLEPATH', 2, N'Prioritize Accounts and Build an Actionable Account Plan', N'Turn customer priorities, pipeline, renewals, whitespace, partner coverage, and investment signals into a short account plan built on decisions rather than an inventory.', N'Turn scattered account context into a short, evidence-backed action plan for the accounts that most deserve attention now.', N'Account plans often become static documents. This turns yours into a weekly operating list tied to customer outcomes, pipeline movement, and renewal risk.', N'A prioritized account list with the reason for priority, source signals, role gaps, and one named next action for each top account.', 1),
        (N'AE-PIPE-1', N'SR-ENT-AE', N'WF-X-PIPE-01', N'SEC-ROLEPATH', 3, N'Inspect Pipeline Signal Quality and Restore Trust', N'Use certified business data and MSX context to find where pipeline quality, stage evidence, dates, or next steps misrepresent reality.', N'Find where the pipeline signal is wrong, incomplete, or misleading before it becomes a forecast problem.', N'The easiest forecast conversation is the one where the data is already clean enough to discuss decisions instead of defending the spreadsheet.', N'A short list of pipeline hygiene fixes, stale or at-risk opportunities, source signals, and seller-owned corrections or follow-ups.', 1),
        (N'AE-PIPE-2', N'SR-ENT-AE', N'WF-X-PIPE-01', N'SEC-ROLEPATH', 4, N'Build a Decision-Ready Forecast Narrative', N'Turn pipeline movement, risks, committed deals, and forecast changes into a narrative that holds up to manager and Area inspection.', N'Convert pipeline movement and risk into a forecast narrative that explains the position, not just the number.', N'A forecast is an argument about what will happen and why. AI can assemble the evidence, but you own the judgment and the commitment.', N'A forecast narrative with sourced movement, at-risk commits, gap drivers, open inspection questions, and follow-up actions.', 1),
        (N'AE-OPP', N'SR-ENT-AE', N'WF-X-OPP-01', N'SEC-ROLEPATH', 5, N'Create and Qualify New Opportunities from Buying Signals', N'Convert customer signals, whitespace, meetings, engagement, and account context into qualified opportunities while separating evidence from optimism.', N'Find one real opportunity signal, test whether it is qualified, and define the next customer action.', N'Pipeline gaps are usually discovery gaps. This finds opportunities already hiding in accounts you own, without creating noise in MSX.', N'At least one qualified opportunity hypothesis with the trigger, evidence, stakeholder, next action, and unresolved assumptions named.', 1),
        (N'AE-CONV', N'SR-ENT-AE', N'WF-X-CONV-01', N'SEC-ROLEPATH', 6, N'Prepare an Executive Customer Conversation and Value Narrative', N'Synthesize account context, open commitments, stakeholder dynamics, value evidence, and likely objections into a decision-moving customer conversation.', N'Prepare for a live customer conversation with the outcome, evidence, talking points, objections, and ask made explicit.', N'Calendar pressure makes preparation the first thing to shrink. This makes preparation fast enough to happen without falling back on generic talking points.', N'A conversation brief with source signals, relationship nuance, likely objections, CXO-ready talking points, a primary ask, and a fallback ask.', 1),
        (N'AE-DEAL', N'SR-ENT-AE', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 7, N'Inspect Deal Health and Accelerate the Next Decision', N'Work stage evidence, exit criteria, approvals, commercial dependencies, and account-team ownership into the next real customer decision.', N'Move a live deal from general urgency to the next governed decision, with blockers, roles, and evidence visible.', N'Deals rarely stall because nobody cares. They stall because the next decision, blocker, or owner is fuzzy. This makes the fuzzy part inspectable.', N'A deal inspection brief with the next decision, risks, approval or role gaps, customer follow-up, and owners for the next actions.', 1),
        (N'AE-RENEW', N'SR-ENT-AE', N'WF-X-RENEW-01', N'SEC-ROLEPATH', 8, N'Manage Renewal Risk and Expansion Readiness', N'Read renewal timing, consumption and usage gaps, value evidence, recent engagement, and commercial review needs early enough to change the outcome.', N'Identify the largest renewal risk early enough to act, and connect expansion to evidenced customer value.', N'A renewal is decided long before the renewal date. Seeing risk and value evidence early gives you time to change the result.', N'A renewal view with risk evidence, value proof gaps, expansion hypothesis, account-team owners, and a customer-ready next action.', 1),
        (N'ATS-ORIENT', N'SR-ENT-ATS', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-session huddle motion, where AI reduces ATS research and planning work, which tools may appear, and what to review before next week''s topic.', N'Understand how the ATS huddle path runs and where AI fits technical strategy and account planning.', N'Technical strategy work is where AI either saves real time or wastes it. This is where you find out which.', N'ATSs know how the huddle motion works, which tools may show up, what to review, and what AI experiences to bring back before next week.', 1),
        (N'ATS-INTEL', N'SR-ENT-ATS', N'WF-X-PLAN-01', N'SEC-ROLEPATH', 2, N'Build an Account Intelligence and Meeting Prep Brief', N'Build the current account, stakeholder, KPI, workload, and risk context needed before committing to a technical direction.', N'Create the evidence base behind your account technology decisions.', N'You are asked to justify technical priorities to people who did not see the evidence. This carries the evidence with you.', N'An account intelligence brief with technical risks, workload signals, stakeholder context, and next actions.', 1),
        (N'ATS-NARR', N'SR-ENT-ATS', N'WF-X-CONV-01', N'SEC-ROLEPATH', 3, N'Assemble an Executive Technical Customer Narrative', N'Translate architecture, risk, roadmap, proof, and business value into an executive-ready technical story with a clear ask.', N'Turn account intelligence into a technical story an executive can act on.', N'Executives do not buy architecture. They buy a consequence. This connects the technical path to that consequence.', N'An executive-ready technical narrative with sourced claims, proof points, decision questions, and a technical ask.', 1),
        (N'ATS-WORKLOAD', N'SR-ENT-ATS', N'WF-X-PLAN-01', N'SEC-ROLEPATH', 4, N'Prioritize AI and Azure Workloads by Readiness and Impact', N'Rank the AI and Azure workloads that deserve technical focus using readiness, impact, upside, dependencies, and ownership.', N'Decide which AI and Azure workloads deserve technical focus now.', N'Not every promising workload is ready, valuable, or owned. Prioritization keeps technical strategy from becoming a wish list.', N'A ranked workload view with readiness, impact, evidence, owner, and validation gaps.', 1),
        (N'ATS-TECH', N'SR-ENT-ATS', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 5, N'Develop a Technical Strategy and Decision Trajectory', N'Connect customer objectives, estate, architecture direction, risks, bets, proof needs, and roadmap into a sequenced technical decision path.', N'Set the technical direction and the sequence of decisions that gets the customer there.', N'Technical strategy without a decision sequence is a diagram. The sequence is what makes it actionable.', N'A technical trajectory with priority bets, proof needs, owners, risks, milestones, and open decisions.', 1),
        (N'ATS-EBC', N'SR-ENT-ATS', N'WF-X-CONV-01', N'SEC-ROLEPATH', 6, N'Design an Executive Briefing Experience', N'Design an executive briefing that advances specific customer decisions and prepares the right participants, evidence, roles, timeline, and follow-through.', N'Turn technical strategy into a purposeful executive experience.', N'A briefing is not a deck. It is a designed decision moment with the right people, evidence, and follow-through.', N'An EBC plan with desired decisions, participants, evidence, preparation milestones, and follow-through ownership.', 1),
        (N'ATS-TALK', N'SR-ENT-ATS', N'WF-X-CONV-01', N'SEC-ROLEPATH', 7, N'Adjust the Technical Talk Track from Customer Signals', N'Adapt the technical conversation to current customer signals, likely questions, objections, and the decision in front of the customer.', N'Update the technical talk track before the customer hears it.', N'The best technical story still fails when it ignores the latest customer signal.', N'A signal-adjusted talk track with opening language, questions, objections, responses, and human review flags.', 1),
        (N'ATS-TEAM', N'SR-ENT-ATS', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 8, N'Mobilize the Technical V-Team Around Priorities and Risks', N'Align technical roles, owners, dependencies, investment signals, risks, and follow-through around the customer decision.', N'Get the technical v-team and partners moving on the same priority, with clear handoffs.', N'You have responsibility without authority. Explicit handoffs are the substitute for authority.', N'A technical v-team alignment brief with owners, dependencies, investment signals, checkpoints, and next actions.', 1),
        (N'SSP-ORIENT', N'SR-ENT-SSP', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-session huddle motion, where AI reduces specialist assembly work, which tools may appear, and what to review before next week''s topic.', N'Understand how the SSP huddle path runs and where AI fits solution pursuit, with human judgment explicit.', N'Specialist time is scarce. This motion is designed to cut assembly work so more of it goes to customer decisions and solution-area growth.', N'SSPs know how the huddle motion works, which tools may show up, what to review, and what AI experiences to bring back before next week.', 1),
        (N'SSP-LEAD', N'SR-ENT-SSP', N'WF-X-OPP-01', N'SEC-ROLEPATH', 2, N'Prioritize Prospects and Follow Up on Leads', N'Turn event, lead, account, and buying signals into a ranked solution-area follow-up plan with a named owner for each top prospect.', N'Turn noisy lead and account signals into a ranked follow-up plan you can work today.', N'You stop guessing which prospects deserve the next hour, and you stop losing warm leads to inbox decay.', N'A ranked prospect list with a specific next action and owner for the top five.', 1),
        (N'SSP-PLAN', N'SR-ENT-SSP', N'WF-X-PLAN-01', N'SEC-ROLEPATH', 3, N'Build a Solution-Selling Plan', N'Shape a solution play into a repeatable pursuit plan covering target accounts, stakeholder coverage, proof needs, and the demo or workshop sequence.', N'Shape the solution play into a plan with customer outcomes, proof, owners, and the next decision.', N'Specialists are pulled in every direction. A written plan lets you focus the right pursuits and say no to the wrong ones.', N'A solution-selling plan with customer outcomes, stakeholder coverage, proof needs, and a 30-day progression plan.', 1),
        (N'SSP-VALUE', N'SR-ENT-SSP', N'WF-X-VALUE-01', N'SEC-ROLEPATH', 4, N'Develop a Customer-Specific Value Narrative', N'Translate the solution into the customer''s own priorities, evidence, caveats, and next ask.', N'Build the value logic before customer-facing execution, using evidence the customer will recognize.', N'Generic value decks lose to specific ones. This is how you build the specific story quickly and responsibly.', N'A review-ready value narrative tied to customer priorities, proof, assumptions, and next ask.', 1),
        (N'SSP-CONV', N'SR-ENT-SSP', N'WF-X-CONV-01', N'SEC-ROLEPATH', 5, N'Prepare a Solution-Specific Customer Conversation', N'Prepare the discovery questions, proof, objections, role contributions, and ask that move a solution conversation to a decision.', N'Prepare and rehearse the solution conversation so it advances a decision rather than explaining a product.', N'Specialists get pulled into meetings with no defined outcome. Preparing the decision you are driving changes that.', N'A solution conversation plan with discovery questions, proof, objections, role contributions, and next ask.', 1),
        (N'SSP-ORCH', N'SR-ENT-SSP', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 6, N'Orchestrate the Specialist, Technical Team, Partners, and Funding', N'Coordinate specialists, technical contributors, partner inputs, and funding dependencies into a resourced pursuit plan with confirmed timing.', N'Mobilize the right people, partners, and funding path around the customer objective and next decision.', N'Pursuits stall waiting for a resource, partner input, or funding step nobody formally owned. This makes the ask explicit.', N'A coordinated pursuit plan with roles, dependencies, partner and funding needs, owners, and decision checkpoints.', 1),
        (N'SSP-COMP', N'SR-ENT-SSP', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 7, N'Develop a Competitive Position and Response Plan', N'Build proof-backed differentiation, objection handling, and risk response for the competitive position in front of you.', N'Build the competitive position once customer context, value logic, and solution intent are clear.', N'Competitive conversations are lost by improvisation. A prepared, evidenced position is the difference.', N'A competitive position with differentiators, proof, objections, risks, and response plan.', 1),
        (N'SSP-DEAL', N'SR-ENT-SSP', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 8, N'Advance the Solution Opportunity and Clear the Next Decision', N'Work milestone readiness, stakeholder gaps, proof, blockers, dependencies, and commitments into the next customer decision.', N'Translate the solution strategy into deal progression and a measurable next customer decision.', N'A pursuit is not advanced until the next decision, owner, and evidence are named.', N'A readiness view with blockers, next decision, owners, and a 14- to 30-day action plan.', 1),
        (N'SE-ORIENT', N'SR-ENT-SE', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-session huddle motion, where AI reduces SE rework on proof and response work, which tools may appear, and what to review before next week''s topic.', N'Understand how the SE huddle path runs and which human checkpoints protect technical accuracy.', N'You are not being asked to outsource judgment. You are being asked to use AI to assemble evidence, pressure-test assumptions, and make technical decisions easier to review.', N'SEs know how the huddle motion works, which tools may show up, what to review, and what AI experiences to bring back before next week.', 1),
        (N'SE-CONV', N'SR-ENT-SE', N'WF-X-CONV-01', N'SEC-ROLEPATH', 6, N'Produce a Grounded Technical Response', N'Respond to RFPs, questionnaires, and technical asks with sourced answers, confidence levels, assumptions, exceptions, and SME-needed flags.', N'Create a governed technical response that separates supported answers from assumptions and routes open items to the right reviewer.', N'The risky part of technical response work is not writing. It is knowing which claims are supported, which are uncertain, and who must review them.', N'A grounded technical answer matrix and response package with unresolved items, confidence flags, and reviewer assignments.', 1),
        (N'SE-ARCH-1', N'SR-ENT-SE', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 3, N'Design and Validate the Customer Architecture', N'Translate discovery criteria into architecture options, assumptions, risks, validation steps, and an architecture decision record.', N'Compare architecture options against the customer decision criteria and document the recommended direction with risks and validation needs.', N'Architecture debates get faster when the options, criteria, assumptions, and proof needs are visible before the meeting.', N'A reviewed architecture decision record with options, criteria, risks, dependencies, and validation steps.', 1),
        (N'SE-ARCH-2', N'SR-ENT-SE', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 4, N'Design a Demo or Workshop That Advances the Decision', N'Create a focused demo or workshop experience that proves the most important customer scenario and produces a next decision.', N'Build a demo or workshop plan around the customer decision, not around the full feature set.', N'A demo that tries to show everything often proves nothing. This narrows the experience to the evidence the customer needs to decide.', N'A demo or workshop plan with scenario, audience, decision criteria, evidence, objections, roles, and fallback path.', 1),
        (N'SE-ARCH-3', N'SR-ENT-SE', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 5, N'Scope a PoC with Success and Exit Criteria', N'Define the smallest useful proof, success measures, milestones, owners, dependencies, review gates, and exit decision.', N'Turn a proposed PoC into a bounded proof with explicit success criteria and a clear exit decision.', N'A PoC without exit criteria becomes a project. The value is knowing what proof is enough before work starts.', N'A PoC plan with in-scope scenario, success and exit criteria, milestones, dependencies, owners, and handoff path.', 1),
        (N'SE-DISC', N'SR-ENT-SE', N'WF-X-DISC-01', N'SEC-ROLEPATH', 2, N'Lead Technical Discovery and Define Decision Criteria', N'Use approved customer and technical context to turn discovery into agreed decision criteria, evidence gaps, and the next technical decision.', N'Convert an upcoming discovery conversation into a decision-ready brief with bounded problem, constraints, evidence gaps, and customer decision criteria.', N'Better discovery prevents second discovery meetings. The payoff is a clearer customer decision and fewer surprises during architecture, demo, or PoC work.', N'A discovery brief with agreed decision criteria, open evidence gaps, and the next technical action.', 1),
        (N'SE-HEALTH', N'SR-ENT-SE', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 7, N'Manage Technical Risk and Advance the Deal', N'Inspect exit criteria, proof gaps, blockers, objections, dependencies, and the next technical decision needed to progress the opportunity.', N'Name the technical risk holding the deal, identify the evidence needed to clear it, and assign the next technical action.', N'Deals often wait on a technical answer nobody has explicitly owned. This makes the blocker, owner, and evidence need visible.', N'A technical risk and handoff plan with blocker, impact, owner, mitigation, checkpoint, and next decision.', 1),
        (N'SE-ASSET', N'SR-ENT-SE', N'WF-X-ASSET-01', N'SEC-ROLEPATH', 8, N'Capture and Reuse Technical Assets and Learning', N'Convert proven patterns, demos, scripts, architectures, responses, and lessons into reusable assets or Skill Blueprints with context and safeguards.', N'Package one piece of technical work so another SE can find, trust, adapt, and reuse it.', N'SEs rebuild useful work because the original lacks context, ownership, or searchability. Capture saves future technical time.', N'One reusable technical asset or Skill Blueprint with purpose, prerequisites, parameters, limitations, owner, and validation checks.', 1),
        (N'CE-ORIENT', N'SR-ENT-CE', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-session huddle motion, where AI supports commercial work, where its boundaries sit, which tools may appear, and what to review before next week''s topic.', N'Understand how the CE huddle path runs and where the boundaries sit for AI in commercial work.', N'Commercial work has the least tolerance for AI error. This session sets out where the boundaries are before you rely on anything.', N'CEs know how the huddle motion works, which tools may show up, what to review, and what AI experiences to bring back before next week.', 1),
        (N'CE-HEALTH', N'SR-ENT-CE', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 2, N'Prioritize Commercial Risk and Intervention', N'Surface the commercial risk, structural exposure, and authoritative-source questions that would otherwise appear at approval.', N'Find the commercial risk that will surface at approval, and decide the intervention while it is still cheap.', N'Commercial risk found at approval is a delay. Found earlier, it becomes a structuring decision you can still influence.', N'A prioritized commercial risk view with intervention, owner, and authoritative source for each item.', 1),
        (N'CE-DEAL-1', N'SR-ENT-CE', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 4, N'Develop Commercial Options and Approval Path (1 of 3)', N'Compare viable commercial structures and map the approval requirements each one triggers, before the negotiation starts.', N'Compare viable commercial structures and make the approval path visible before the negotiation starts.', N'Structure decides whether a deal is approvable. Seeing the trade-offs and approval route early prevents rework later.', N'A commercial options matrix with trade-offs, risks, approval requirements, and open decisions.', 1),
        (N'CE-DEAL-2', N'SR-ENT-CE', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 5, N'Build the Commercial Decision Narrative (2 of 3)', N'Turn approved commercial context into an internal recommendation and a customer-specific transition brief.', N'Turn approved commercial context into a decision narrative reviewers can act on.', N'A clear recommendation makes review faster, because the options, assumptions, and risks are visible instead of rediscovered.', N'A recommended commercial path with assumptions, reviewers, transition impacts, and next decision named.', 1),
        (N'CE-DEAL-3', N'SR-ENT-CE', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 6, N'Prepare and Lead the Commercial Negotiation (3 of 3)', N'Build the negotiation position, concession logic, authority boundaries, and validated deal path for customer-facing use.', N'Prepare the negotiation so give-and-get logic and authority limits are settled before customer pressure arrives.', N'Negotiations are where vague structure becomes expensive. Preparing give-and-get logic and authority boundaries keeps judgment human-led.', N'A negotiation plan and validated deal path with authority, concessions, escalation triggers, and review flags.', 1),
        (N'CE-ORCH', N'SR-ENT-CE', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 7, N'Orchestrate Commercial Approvals and Execution', N'Route approval handoffs, exception cases, investment dependencies, and commercial execution to named owners.', N'Move from commercial recommendation to governed execution by naming approvals, owners, handoffs, and blockers.', N'Commercial execution stalls when approval ownership is implied. Naming the route, owner, evidence, and blocker keeps the deal moving without overstating authority.', N'A governed commercial execution plan with approval owners, handoffs, blockers, and the next decision clear.', 1),
        (N'CE-RENEW', N'SR-ENT-CE', N'WF-X-RENEW-01', N'SEC-ROLEPATH', 8, N'Build and Execute the Commercial Renewal Strategy', N'Work renewal economics, commercial structure, risk, expansion potential, and approval path into a renewal strategy.', N'Build the commercial renewal strategy, including risk, structure, expansion potential, and approval path.', N'Renewals are commercial events, not administrative ones. Treating them as strategy is where risk, margin, and expansion become visible.', N'A renewal strategy with commercial risk, structure, expansion potential, approval path, and next decision named.', 1),
        (N'CE-POLICY', N'SR-ENT-CE', N'WF-X-POLICY-01', N'SEC-ROLEPATH', 3, N'Validate Policy, Licensing, and Approval Boundaries', N'Check eligibility questions, licensing risk, and approval routing against authoritative guidance before deal structure hardens.', N'Check policy, licensing, and approval boundaries before structuring decisions harden.', N'Policy questions found at approval cost weeks. Found before structure and negotiation, they cost a conversation.', N'A policy and licensing check with every open question routed to its authoritative owner before the deal path is locked.', 1),
        (N'CSA-ORIENT', N'SR-ENT-CSA', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-session huddle motion, where AI reduces CSA delivery and architecture assembly work, which tools may appear, and what to review before next week''s topic.', N'Understand how the CSA huddle path runs and where AI fits customer architecture and delivery.', N'You inherit whatever is designed and delivered upstream. This explains where you get a say earlier.', N'CSAs know how the huddle motion works, which tools may show up, what to review, and what AI experiences to bring back before next week.', 1),
        (N'CSA-PIPE', N'SR-ENT-CSA', N'WF-X-PIPE-01', N'SEC-ROLEPATH', 2, N'Forecast Consumption and Intervene on Technical Risk', N'Compare consumption against plan, trace each gap to its technical cause, and select the intervention that changes the trajectory.', N'Find where the consumption gap is technically caused, and start one intervention while it still matters.', N'Consumption shortfalls get raised to you after they show up in a report. This is how you see them while there is still time.', N'A consumption position with the technical causes named and one intervention owned.', 1),
        (N'CSA-CONV', N'SR-ENT-CSA', N'WF-X-CONV-01', N'SEC-ROLEPATH', 3, N'Prepare a Technical Advisory Conversation', N'Prepare the recommendation, supporting evidence, and decision request that turn an advisory conversation into a customer decision.', N'Prepare the advisory conversation so the customer leaves with a decision, not a list of options.', N'Advisory conversations drift into education when they are not prepared. Preparation is what keeps them advisory.', N'An advisory plan with the recommendation, the evidence, and the decision you are asking for.', 1),
        (N'CSA-ARCH-1', N'SR-ENT-CSA', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 4, N'Design a Production-Ready Architecture and Validation Path (1 of 2)', N'Compare production architecture options against customer constraints, then turn the chosen direction into a documented design with a validation and proof plan.', N'Choose the production architecture direction and define the validation path that will prove it.', N'You inherit what was designed pre-sale. Designing for production now is how you avoid absorbing it later.', N'A production-ready architecture package with the decision path, validation plan, and dependencies named.', 1),
        (N'CSA-ARCH-2', N'SR-ENT-CSA', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 5, N'Validate the Architecture Evidence and Confirm Delivery Readiness (2 of 2)', N'Pressure-test the architecture evidence, confirm delivery readiness for investment-funded scope, and plan the interventions the design still needs.', N'Validate the evidence behind the design and confirm the scope is ready to deliver.', N'A design that has not been evidence-checked becomes someone else''s escalation. Validating now is cheaper than defending it later.', N'A validated architecture evidence base with delivery-readiness findings and an owned intervention plan.', 1),
        (N'CSA-HEALTH', N'SR-ENT-CSA', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 6, N'Assess Technical Health and Prioritize Risk', N'Rank technical risk by how likely it is to become customer-visible, with evidence and owners attached to each item.', N'Find the technical risk most likely to become customer-visible, and act on it now.', N'Technical risk you catch this week is a conversation. The same risk found by the customer is an escalation.', N'A ranked technical risk list with evidence, owners, and one intervention started.', 1),
        (N'CSA-VALUE-1', N'SR-ENT-CSA', N'WF-X-VALUE-01', N'SEC-ROLEPATH', 7, N'Optimize Cost and Build the FinOps Recommendation (1 of 2)', N'Build the cost and consumption evidence base, then turn it into a costed optimization recommendation the customer can act on.', N'Find the cost the customer is not seeing, and turn it into a defensible optimization recommendation.', N'FinOps findings buy credibility. A concrete saving is the fastest way to be trusted on the larger technical argument.', N'A validated optimization evidence base with one costed FinOps recommendation and an owned intervention plan.', 1),
        (N'CSA-VALUE-2', N'SR-ENT-CSA', N'WF-X-VALUE-01', N'SEC-ROLEPATH', 8, N'Translate Technical Progress into a Customer Value Narrative (2 of 2)', N'Turn technical progress into a value story the customer recognizes, with the evidence behind every claim checked before it is shown.', N'Connect technical progress to the outcome the customer asked for, using evidence that survives scrutiny.', N'Technical work is only credited when someone connects it to what the customer wanted. Unverified claims lose that credit instantly.', N'A customer-ready technical value narrative and review package with each claim evidence-checked.', 1),
        (N'CSAM-ORIENT', N'SR-ENT-CSAM', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-session huddle motion, where AI reduces CSAM status-assembly work, which tools may appear, and what to review before next week''s topic.', N'Understand how the CSAM huddle path runs and where AI fits the customer-success work you already do.', N'You are not being asked to become a tool demo person. You are being given a way to spend less time assembling status and more time driving customer outcomes.', N'CSAMs know how the huddle motion works, which tools may show up, what to review, and what AI experiences to bring back before next week.', 1),
        (N'CSAM-SPLAN', N'SR-ENT-CSAM', N'WF-X-PLAN-01', N'SEC-ROLEPATH', 2, N'Build Outcome-Anchored Success Plans', N'Turn customer priorities into an executable success plan with outcomes, milestones, owners, risks, and review points.', N'Start with the customer outcome and build the plan that makes progress observable.', N'Success plans decay when they become inventories. This turns the plan into a living operating system for customer value.', N'A refreshed success-plan view with outcomes, milestones, owners, risks, and the next review point named.', 1),
        (N'CSAM-HEALTH', N'SR-ENT-CSAM', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 3, N'Assess Customer Health and Predict Risks', N'Combine health, usage, support, sentiment, delivery, and stakeholder signals into a ranked risk view with a chosen intervention.', N'Move from health scores to the next intervention that changes customer trajectory.', N'Risk found early is a customer conversation. Risk found late is an escalation with an audience.', N'A ranked health and risk view with one active intervention, owner, due date, and escalation threshold.', 1),
        (N'CSAM-EXEC', N'SR-ENT-CSAM', N'WF-X-CONV-01', N'SEC-ROLEPATH', 4, N'Map Stakeholders and Drive Executive Alignment', N'Map sponsors, decision makers, workload owners, and relationship risks, then prepare the executive alignment narrative.', N'Prepare the stakeholder conversation that aligns priorities, decisions, and sponsorship.', N'A strong CSAM does not only track activity. They keep the right people aligned before value or risk becomes invisible.', N'A stakeholder map and executive alignment brief with relationship risks, message, evidence, and next ask.', 1),
        (N'CSAM-ORCH', N'SR-ENT-CSAM', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 5, N'Orchestrate Microsoft, Partners and Customer Teams', N'Turn scattered workstreams into a clear operating rhythm across customer stakeholders, Microsoft roles, partners, support, and delivery.', N'Make the customer-success system easier to run by making handoffs and decisions explicit.', N'Most work stalls in the handoff, not the task. Orchestration is how CSAMs create speed without owning every action.', N'A v-team orchestration brief with workstreams, owners, inputs, decisions, dates, and escalations.', 1),
        (N'CSAM-VALUE', N'SR-ENT-CSAM', N'WF-X-VALUE-01', N'SEC-ROLEPATH', 6, N'Accelerate Adoption and Prove Value Realization', N'Identify adoption friction, connect usage to customer outcomes, and prepare a value story the customer recognizes.', N'Turn adoption signals into value proof and the next behavior-change intervention.', N'Adoption without value evidence is fragile. Value that is not communicated is invisible at renewal.', N'A four-week adoption and value plan with gaps, actions, owners, milestones, and customer-ready value evidence.', 1),
        (N'CSAM-RENEW', N'SR-ENT-CSAM', N'WF-X-RENEW-01', N'SEC-ROLEPATH', 7, N'Forecast Consumption, Renewal and Growth Opportunities', N'Connect consumption trajectory, usage commitments, adoption gaps, value evidence, and stakeholder health to renewal and expansion readiness.', N'See renewal and growth conditions early enough to improve them.', N'Renewal readiness is built by value evidence over time, not assembled at the deadline.', N'A renewal and growth readiness view with top risk, value proof, consumption gap, expansion hypothesis, and v-team next action.', 1),
        (N'CSAM-ESCALATE', N'SR-ENT-CSAM', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 8, N'Lead Delivery Risks, Escalations and Recovery Plans', N'Build a grounded brief for incidents, delivery risks, overdue milestones, and the recovery actions that answer them.', N'Turn escalation noise into a recovery plan with accountability and customer-safe communication.', N'Escalations test trust. A grounded brief reduces chasing, avoids surprises, and keeps the customer conversation focused on recovery.', N'A recovery plan with impact, owners, decisions, next actions, communication cadence, and follow-through mechanism.', 1),
        (N'AE-INVEST', N'SR-ENT-AE', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Align Customer Investment to Account Strategy and Opportunity Outcomes', N'Connect customer investment to a live account priority or deal barrier without implying eligibility, funding, or approval.', N'Identify where customer investment could remove a decision, deployment, or adoption barrier and name the next governed action.', N'You are often the first to see the barrier. Naming where investment could unlock the decision helps you start the right conversation without overstepping ownership.', N'An investment hypothesis tied to an account or opportunity, with evidence, open questions, accountable owner, and next human decision.', 1),
        (N'AE-ORCH', N'SR-ENT-AE', N'WF-X-ORCH-01', N'SEC-ADDITIONAL', 2, N'Mobilize the Account Team and Partners Around the Opportunity', N'Make role coverage, handoffs, partner fit, and follow-through explicit for a live account or opportunity.', N'Turn a matrixed account motion into clear roles, handoffs, and partner actions that move the next customer decision.', N'AEs lead through influence. When ownership is explicit, less time is spent chasing context and more time is spent advancing the customer decision.', N'A role and partner orchestration plan with missing roles, owners, inputs, dates, and follow-up rhythm named.', 1),
        (N'AE-VALUE', N'SR-ENT-AE', N'WF-X-VALUE-01', N'SEC-ADDITIONAL', 3, N'Lead a Customer QBR and Executive Value Cadence', N'Turn outcomes, usage, commitments, investments, risks, and expansion plays into an executive-ready customer value cadence.', N'Build a customer-ready value and QBR narrative that connects what happened to what the customer should decide next.', N'Value that is not evidenced is opinion. Value that is not communicated is invisible, especially before renewals and expansion conversations.', N'An executive value and QBR brief with supported outcomes, open commitments, risks, expansion plays, and strategic asks.', 1),
        (N'ATS-INVEST', N'SR-ENT-ATS', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Assess the Strategic and Technical Case for Investment', N'Test a proposed investment against the account technology strategy, deployment readiness, consumption path, and role boundaries.', N'Judge whether a proposed investment advances the account technology strategy and has a credible path to deployment and consumption.', N'Investment that does not move the technology strategy still consumes technical time. Testing fit early is cheaper.', N'A strategic and technical investment assessment with dependencies, readiness, risks, and the next governed decision named.', 1),
        (N'ATS-CBR', N'SR-ENT-ATS', N'WF-X-VALUE-01', N'SEC-ADDITIONAL', 2, N'Prepare the Technical Contribution for a Customer Business Review', N'Contribute the strategic technical narrative, roadmap, key technical decisions, risks, and evidence to a customer business review.', N'Bring the technical strategy into the customer value conversation.', N'Customer business reviews miss value when technical decisions, proof, and roadmap dependencies are absent or disconnected.', N'A technical CBR contribution with roadmap points, evidence, risks, decisions, and follow-through.', 1),
        (N'ATS-HEALTH', N'SR-ENT-ATS', N'WF-X-HEALTH-01', N'SEC-ADDITIONAL', 3, N'Assess Technical Health and Prioritize Risk Response', N'Connect strategic and technical risks to account priorities and specialist alignment.', N'Find the technical risk that most threatens the account strategy and decide what to do about it.', N'Risk found early is a conversation. The same risk found late is an escalation.', N'A prioritized technical risk response with source signals, owner, intervention, and checkpoint.', 1),
        (N'SE-INVEST', N'SR-ENT-SE', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Scope an Investment-Funded Technical Proof with Success Criteria', N'Bound the technical scope, proof evidence, success measures, failure modes, and delivery handoff for investment-funded work.', N'Define the technical scope, evidence, success measures, and handoff boundaries for investment-funded proof work.', N'Investment-funded work underdelivers when the technical proof is vague. SEs create leverage by bounding the scope before work starts.', N'A technical scope, success-measure package, failure-mode register, and delivery handoff with open decisions named.', 1),
        (N'CE-INVEST', N'SR-ENT-CE', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Clarify Commercial, Policy, and Approval Dependencies for Customer Investment', N'Surface the commercial structure, policy, agreement, exception, and approval dependencies an investment request will encounter.', N'Name the commercial and approval dependencies before the investment request reaches review.', N'Investment requests lose time when commercial dependencies are discovered late. Naming the questions and owners early avoids rework without implying approval authority.', N'A dependency and approval map with authoritative questions, owners, unresolved evidence, and the next human decision.', 1),
        (N'CSA-INVEST', N'SR-ENT-CSA', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Validate Delivery Readiness and Technical Outcome Measures', N'Test whether investment-funded scope can be delivered as written, against dependencies, prerequisites, and technical checkpoints.', N'Test whether the investment can actually be delivered as scoped.', N'You will be delivering it. Readiness gaps found now are gaps you do not absorb later.', N'A delivery-readiness assessment with dependencies, prerequisites, and technical checkpoints defined.', 1),
        (N'CSAM-INVEST', N'SR-ENT-CSAM', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Govern Customer Investment Execution and Value Realization', N'Govern investment execution, handoffs, and value evidence as part of the success plan rather than as a side process.', N'Run customer investment as part of the success plan, not as a side process.', N'Customer investment only creates trust when execution, handoffs, and value evidence are governed from the start.', N'An investment execution rhythm with owners, checkpoints, risks, and the evidence needed for the realization review.', 1),
        (N'ATS-PARTNER', N'SR-ENT-ATS', N'WF-X-ORCH-01', N'SEC-ADDITIONAL', 4, N'Align Partner and Specialist Support to Technical Priorities', N'Identify where partner or specialist capacity is needed to advance the technical decision path.', N'Make partner and specialist involvement match the technical priority, not the org chart.', N'Technical strategy often stalls because the right expertise is not involved at the right time.', N'A partner and specialist alignment plan with capability gaps, owners, timing, and next decision.', 1),
        (N'SSP-INVEST', N'SR-ENT-SSP', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Develop and Advance an Investment Request', N'Assemble request readiness, contributor coordination, partner and supplier inputs, and status follow-through into an investment request a reviewer can act on.', N'Get an investment request from idea to review-ready without rework or overstated approval status.', N'You often own the request path. Most delay comes from missing inputs, unclear ownership, or hidden open questions.', N'A request package a reviewer can act on, with confirmed inputs, gaps, owners, and next governed action.', 1),
        (N'ALL-USECASE', N'SR-ENT-ALL', N'WF-X-USECASE-01', N'SEC-ADDITIONAL', 1, N'Identify and Test an AI-Assisted Workflow', N'Bring a recurring workflow the team already owns, make its friction visible, and design one bounded experiment to test this week.', N'Choose one real recurring workflow the team already owns, find the smallest step AI could assist, and leave with one bounded experiment and a named owner.', N'You practice on your own work rather than a worked example, so what you leave with is already relevant to your accounts. It works for any role and any workflow, so the team can run it again without new content.', N'One workflow selected, one assistable step identified, one bounded experiment designed with a human checkpoint, and one person accountable for bringing evidence back.', 1),
        (N'ALL-DEAL', N'SR-ENT-ALL', N'WF-X-DEAL-01', N'SEC-ADDITIONAL', 2, N'Find the Deal Facts Before You Need Them', N'Use the deal-making capabilities in Sales Agent to retrieve what is in a customer''s agreement, what they own, what is expiring, and what has been discounted.', N'Learn how to retrieve real agreement, enrollment, and consumption facts for one of your own accounts, and recognize where the work stops being yours.', N'Every role touches a deal without owning it. You stop waiting on someone else for answers that take ninety seconds to retrieve, and you stop walking into customer conversations without knowing what the customer already bought.', N'One account looked up for real, the facts that surprised you named, and a clear line drawn between what you can answer yourself and what belongs to the deal owner.', 1)
    ) v([ExternalId], [SegmentRoleExternalId], [TopicExternalId], [PathSection], [Sequence], [RoleTopicName], [RoleTopicDescription], [TodayObjective], [Wiifm], [DesiredOutcome], [IsActive])
), src AS (
    SELECT raw.*, sr.Id AS [HuddleSegmentRoleId], t.Id AS [HuddleTopicId]
    FROM raw
    INNER JOIN dbo.HuddleSegmentRoles AS sr ON sr.[ExternalId] = raw.[SegmentRoleExternalId]
    INNER JOIN dbo.HuddleTopics AS t ON t.[ExternalId] = raw.[TopicExternalId]
)
MERGE dbo.HuddlePlacements AS tgt
USING src ON tgt.[ExternalId] = src.[ExternalId]
WHEN MATCHED THEN UPDATE SET
        tgt.[HuddleSegmentRoleId] = src.[HuddleSegmentRoleId],
        tgt.[HuddleTopicId] = src.[HuddleTopicId],
        tgt.[PathSection] = src.[PathSection],
        tgt.[Sequence] = src.[Sequence],
        tgt.[RoleTopicName] = src.[RoleTopicName],
        tgt.[RoleTopicDescription] = src.[RoleTopicDescription],
        tgt.[TodayObjective] = src.[TodayObjective],
        tgt.[Wiifm] = src.[Wiifm],
        tgt.[DesiredOutcome] = src.[DesiredOutcome],
        tgt.[IsActive] = src.[IsActive],
        tgt.[UpdatedAtUtc] = SYSUTCDATETIME()
WHEN NOT MATCHED BY TARGET THEN INSERT ([ExternalId], [HuddleSegmentRoleId], [HuddleTopicId], [PathSection], [Sequence], [RoleTopicName], [RoleTopicDescription], [TodayObjective], [Wiifm], [DesiredOutcome], [IsActive], [CreatedAtUtc])
    VALUES (src.[ExternalId], src.[HuddleSegmentRoleId], src.[HuddleTopicId], src.[PathSection], src.[Sequence], src.[RoleTopicName], src.[RoleTopicDescription], src.[TodayObjective], src.[Wiifm], src.[DesiredOutcome], src.[IsActive], SYSUTCDATETIME());
;WITH raw AS (
    SELECT * FROM (VALUES
        (N'AE-ORIENT', N'SR-ENT-AE', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation for Account Executives', N'Introduce the eight-session huddle motion, where AI reduces AE preparation and reporting work, which tools may appear, and what to review before next week''s topic.', N'Understand how the AE huddle path runs and where the human checkpoints protect account, deal, and forecast judgment.', N'You are not being asked to learn another tool for its own sake. You are being asked to reclaim time from prep, reporting, and chasing context so more of your week goes to customers and decisions.', N'AEs know how the huddle motion works, which tools may show up, what to review, and what AI experiences to bring back before next week.', 1),
        (N'AE-PLAN', N'SR-ENT-AE', N'WF-X-PLAN-01', N'SEC-ROLEPATH', 2, N'Prioritize Accounts and Build an Actionable Account Plan', N'Turn customer priorities, pipeline, renewals, whitespace, partner coverage, and investment signals into a short account plan built on decisions rather than an inventory.', N'Turn scattered account context into a short, evidence-backed action plan for the accounts that most deserve attention now.', N'Account plans often become static documents. This turns yours into a weekly operating list tied to customer outcomes, pipeline movement, and renewal risk.', N'A prioritized account list with the reason for priority, source signals, role gaps, and one named next action for each top account.', 1),
        (N'AE-PIPE-1', N'SR-ENT-AE', N'WF-X-PIPE-01', N'SEC-ROLEPATH', 3, N'Inspect Pipeline Signal Quality and Restore Trust', N'Use certified business data and MSX context to find where pipeline quality, stage evidence, dates, or next steps misrepresent reality.', N'Find where the pipeline signal is wrong, incomplete, or misleading before it becomes a forecast problem.', N'The easiest forecast conversation is the one where the data is already clean enough to discuss decisions instead of defending the spreadsheet.', N'A short list of pipeline hygiene fixes, stale or at-risk opportunities, source signals, and seller-owned corrections or follow-ups.', 1),
        (N'AE-PIPE-2', N'SR-ENT-AE', N'WF-X-PIPE-01', N'SEC-ROLEPATH', 4, N'Build a Decision-Ready Forecast Narrative', N'Turn pipeline movement, risks, committed deals, and forecast changes into a narrative that holds up to manager and Area inspection.', N'Convert pipeline movement and risk into a forecast narrative that explains the position, not just the number.', N'A forecast is an argument about what will happen and why. AI can assemble the evidence, but you own the judgment and the commitment.', N'A forecast narrative with sourced movement, at-risk commits, gap drivers, open inspection questions, and follow-up actions.', 1),
        (N'AE-OPP', N'SR-ENT-AE', N'WF-X-OPP-01', N'SEC-ROLEPATH', 5, N'Create and Qualify New Opportunities from Buying Signals', N'Convert customer signals, whitespace, meetings, engagement, and account context into qualified opportunities while separating evidence from optimism.', N'Find one real opportunity signal, test whether it is qualified, and define the next customer action.', N'Pipeline gaps are usually discovery gaps. This finds opportunities already hiding in accounts you own, without creating noise in MSX.', N'At least one qualified opportunity hypothesis with the trigger, evidence, stakeholder, next action, and unresolved assumptions named.', 1),
        (N'AE-CONV', N'SR-ENT-AE', N'WF-X-CONV-01', N'SEC-ROLEPATH', 6, N'Prepare an Executive Customer Conversation and Value Narrative', N'Synthesize account context, open commitments, stakeholder dynamics, value evidence, and likely objections into a decision-moving customer conversation.', N'Prepare for a live customer conversation with the outcome, evidence, talking points, objections, and ask made explicit.', N'Calendar pressure makes preparation the first thing to shrink. This makes preparation fast enough to happen without falling back on generic talking points.', N'A conversation brief with source signals, relationship nuance, likely objections, CXO-ready talking points, a primary ask, and a fallback ask.', 1),
        (N'AE-DEAL', N'SR-ENT-AE', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 7, N'Inspect Deal Health and Accelerate the Next Decision', N'Work stage evidence, exit criteria, approvals, commercial dependencies, and account-team ownership into the next real customer decision.', N'Move a live deal from general urgency to the next governed decision, with blockers, roles, and evidence visible.', N'Deals rarely stall because nobody cares. They stall because the next decision, blocker, or owner is fuzzy. This makes the fuzzy part inspectable.', N'A deal inspection brief with the next decision, risks, approval or role gaps, customer follow-up, and owners for the next actions.', 1),
        (N'AE-RENEW', N'SR-ENT-AE', N'WF-X-RENEW-01', N'SEC-ROLEPATH', 8, N'Manage Renewal Risk and Expansion Readiness', N'Read renewal timing, consumption and usage gaps, value evidence, recent engagement, and commercial review needs early enough to change the outcome.', N'Identify the largest renewal risk early enough to act, and connect expansion to evidenced customer value.', N'A renewal is decided long before the renewal date. Seeing risk and value evidence early gives you time to change the result.', N'A renewal view with risk evidence, value proof gaps, expansion hypothesis, account-team owners, and a customer-ready next action.', 1),
        (N'ATS-ORIENT', N'SR-ENT-ATS', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-session huddle motion, where AI reduces ATS research and planning work, which tools may appear, and what to review before next week''s topic.', N'Understand how the ATS huddle path runs and where AI fits technical strategy and account planning.', N'Technical strategy work is where AI either saves real time or wastes it. This is where you find out which.', N'ATSs know how the huddle motion works, which tools may show up, what to review, and what AI experiences to bring back before next week.', 1),
        (N'ATS-INTEL', N'SR-ENT-ATS', N'WF-X-PLAN-01', N'SEC-ROLEPATH', 2, N'Build an Account Intelligence and Meeting Prep Brief', N'Build the current account, stakeholder, KPI, workload, and risk context needed before committing to a technical direction.', N'Create the evidence base behind your account technology decisions.', N'You are asked to justify technical priorities to people who did not see the evidence. This carries the evidence with you.', N'An account intelligence brief with technical risks, workload signals, stakeholder context, and next actions.', 1),
        (N'ATS-NARR', N'SR-ENT-ATS', N'WF-X-CONV-01', N'SEC-ROLEPATH', 3, N'Assemble an Executive Technical Customer Narrative', N'Translate architecture, risk, roadmap, proof, and business value into an executive-ready technical story with a clear ask.', N'Turn account intelligence into a technical story an executive can act on.', N'Executives do not buy architecture. They buy a consequence. This connects the technical path to that consequence.', N'An executive-ready technical narrative with sourced claims, proof points, decision questions, and a technical ask.', 1),
        (N'ATS-WORKLOAD', N'SR-ENT-ATS', N'WF-X-PLAN-01', N'SEC-ROLEPATH', 4, N'Prioritize AI and Azure Workloads by Readiness and Impact', N'Rank the AI and Azure workloads that deserve technical focus using readiness, impact, upside, dependencies, and ownership.', N'Decide which AI and Azure workloads deserve technical focus now.', N'Not every promising workload is ready, valuable, or owned. Prioritization keeps technical strategy from becoming a wish list.', N'A ranked workload view with readiness, impact, evidence, owner, and validation gaps.', 1),
        (N'ATS-TECH', N'SR-ENT-ATS', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 5, N'Develop a Technical Strategy and Decision Trajectory', N'Connect customer objectives, estate, architecture direction, risks, bets, proof needs, and roadmap into a sequenced technical decision path.', N'Set the technical direction and the sequence of decisions that gets the customer there.', N'Technical strategy without a decision sequence is a diagram. The sequence is what makes it actionable.', N'A technical trajectory with priority bets, proof needs, owners, risks, milestones, and open decisions.', 1),
        (N'ATS-EBC', N'SR-ENT-ATS', N'WF-X-CONV-01', N'SEC-ROLEPATH', 6, N'Design an Executive Briefing Experience', N'Design an executive briefing that advances specific customer decisions and prepares the right participants, evidence, roles, timeline, and follow-through.', N'Turn technical strategy into a purposeful executive experience.', N'A briefing is not a deck. It is a designed decision moment with the right people, evidence, and follow-through.', N'An EBC plan with desired decisions, participants, evidence, preparation milestones, and follow-through ownership.', 1),
        (N'ATS-TALK', N'SR-ENT-ATS', N'WF-X-CONV-01', N'SEC-ROLEPATH', 7, N'Adjust the Technical Talk Track from Customer Signals', N'Adapt the technical conversation to current customer signals, likely questions, objections, and the decision in front of the customer.', N'Update the technical talk track before the customer hears it.', N'The best technical story still fails when it ignores the latest customer signal.', N'A signal-adjusted talk track with opening language, questions, objections, responses, and human review flags.', 1),
        (N'ATS-TEAM', N'SR-ENT-ATS', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 8, N'Mobilize the Technical V-Team Around Priorities and Risks', N'Align technical roles, owners, dependencies, investment signals, risks, and follow-through around the customer decision.', N'Get the technical v-team and partners moving on the same priority, with clear handoffs.', N'You have responsibility without authority. Explicit handoffs are the substitute for authority.', N'A technical v-team alignment brief with owners, dependencies, investment signals, checkpoints, and next actions.', 1),
        (N'SSP-ORIENT', N'SR-ENT-SSP', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-session huddle motion, where AI reduces specialist assembly work, which tools may appear, and what to review before next week''s topic.', N'Understand how the SSP huddle path runs and where AI fits solution pursuit, with human judgment explicit.', N'Specialist time is scarce. This motion is designed to cut assembly work so more of it goes to customer decisions and solution-area growth.', N'SSPs know how the huddle motion works, which tools may show up, what to review, and what AI experiences to bring back before next week.', 1),
        (N'SSP-LEAD', N'SR-ENT-SSP', N'WF-X-OPP-01', N'SEC-ROLEPATH', 2, N'Prioritize Prospects and Follow Up on Leads', N'Turn event, lead, account, and buying signals into a ranked solution-area follow-up plan with a named owner for each top prospect.', N'Turn noisy lead and account signals into a ranked follow-up plan you can work today.', N'You stop guessing which prospects deserve the next hour, and you stop losing warm leads to inbox decay.', N'A ranked prospect list with a specific next action and owner for the top five.', 1),
        (N'SSP-PLAN', N'SR-ENT-SSP', N'WF-X-PLAN-01', N'SEC-ROLEPATH', 3, N'Build a Solution-Selling Plan', N'Shape a solution play into a repeatable pursuit plan covering target accounts, stakeholder coverage, proof needs, and the demo or workshop sequence.', N'Shape the solution play into a plan with customer outcomes, proof, owners, and the next decision.', N'Specialists are pulled in every direction. A written plan lets you focus the right pursuits and say no to the wrong ones.', N'A solution-selling plan with customer outcomes, stakeholder coverage, proof needs, and a 30-day progression plan.', 1),
        (N'SSP-VALUE', N'SR-ENT-SSP', N'WF-X-VALUE-01', N'SEC-ROLEPATH', 4, N'Develop a Customer-Specific Value Narrative', N'Translate the solution into the customer''s own priorities, evidence, caveats, and next ask.', N'Build the value logic before customer-facing execution, using evidence the customer will recognize.', N'Generic value decks lose to specific ones. This is how you build the specific story quickly and responsibly.', N'A review-ready value narrative tied to customer priorities, proof, assumptions, and next ask.', 1),
        (N'SSP-CONV', N'SR-ENT-SSP', N'WF-X-CONV-01', N'SEC-ROLEPATH', 5, N'Prepare a Solution-Specific Customer Conversation', N'Prepare the discovery questions, proof, objections, role contributions, and ask that move a solution conversation to a decision.', N'Prepare and rehearse the solution conversation so it advances a decision rather than explaining a product.', N'Specialists get pulled into meetings with no defined outcome. Preparing the decision you are driving changes that.', N'A solution conversation plan with discovery questions, proof, objections, role contributions, and next ask.', 1),
        (N'SSP-ORCH', N'SR-ENT-SSP', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 6, N'Orchestrate the Specialist, Technical Team, Partners, and Funding', N'Coordinate specialists, technical contributors, partner inputs, and funding dependencies into a resourced pursuit plan with confirmed timing.', N'Mobilize the right people, partners, and funding path around the customer objective and next decision.', N'Pursuits stall waiting for a resource, partner input, or funding step nobody formally owned. This makes the ask explicit.', N'A coordinated pursuit plan with roles, dependencies, partner and funding needs, owners, and decision checkpoints.', 1),
        (N'SSP-COMP', N'SR-ENT-SSP', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 7, N'Develop a Competitive Position and Response Plan', N'Build proof-backed differentiation, objection handling, and risk response for the competitive position in front of you.', N'Build the competitive position once customer context, value logic, and solution intent are clear.', N'Competitive conversations are lost by improvisation. A prepared, evidenced position is the difference.', N'A competitive position with differentiators, proof, objections, risks, and response plan.', 1),
        (N'SSP-DEAL', N'SR-ENT-SSP', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 8, N'Advance the Solution Opportunity and Clear the Next Decision', N'Work milestone readiness, stakeholder gaps, proof, blockers, dependencies, and commitments into the next customer decision.', N'Translate the solution strategy into deal progression and a measurable next customer decision.', N'A pursuit is not advanced until the next decision, owner, and evidence are named.', N'A readiness view with blockers, next decision, owners, and a 14- to 30-day action plan.', 1),
        (N'SE-ORIENT', N'SR-ENT-SE', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-session huddle motion, where AI reduces SE rework on proof and response work, which tools may appear, and what to review before next week''s topic.', N'Understand how the SE huddle path runs and which human checkpoints protect technical accuracy.', N'You are not being asked to outsource judgment. You are being asked to use AI to assemble evidence, pressure-test assumptions, and make technical decisions easier to review.', N'SEs know how the huddle motion works, which tools may show up, what to review, and what AI experiences to bring back before next week.', 1),
        (N'SE-CONV', N'SR-ENT-SE', N'WF-X-CONV-01', N'SEC-ROLEPATH', 6, N'Produce a Grounded Technical Response', N'Respond to RFPs, questionnaires, and technical asks with sourced answers, confidence levels, assumptions, exceptions, and SME-needed flags.', N'Create a governed technical response that separates supported answers from assumptions and routes open items to the right reviewer.', N'The risky part of technical response work is not writing. It is knowing which claims are supported, which are uncertain, and who must review them.', N'A grounded technical answer matrix and response package with unresolved items, confidence flags, and reviewer assignments.', 1),
        (N'SE-ARCH-1', N'SR-ENT-SE', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 3, N'Design and Validate the Customer Architecture', N'Translate discovery criteria into architecture options, assumptions, risks, validation steps, and an architecture decision record.', N'Compare architecture options against the customer decision criteria and document the recommended direction with risks and validation needs.', N'Architecture debates get faster when the options, criteria, assumptions, and proof needs are visible before the meeting.', N'A reviewed architecture decision record with options, criteria, risks, dependencies, and validation steps.', 1),
        (N'SE-ARCH-2', N'SR-ENT-SE', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 4, N'Design a Demo or Workshop That Advances the Decision', N'Create a focused demo or workshop experience that proves the most important customer scenario and produces a next decision.', N'Build a demo or workshop plan around the customer decision, not around the full feature set.', N'A demo that tries to show everything often proves nothing. This narrows the experience to the evidence the customer needs to decide.', N'A demo or workshop plan with scenario, audience, decision criteria, evidence, objections, roles, and fallback path.', 1),
        (N'SE-ARCH-3', N'SR-ENT-SE', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 5, N'Scope a PoC with Success and Exit Criteria', N'Define the smallest useful proof, success measures, milestones, owners, dependencies, review gates, and exit decision.', N'Turn a proposed PoC into a bounded proof with explicit success criteria and a clear exit decision.', N'A PoC without exit criteria becomes a project. The value is knowing what proof is enough before work starts.', N'A PoC plan with in-scope scenario, success and exit criteria, milestones, dependencies, owners, and handoff path.', 1),
        (N'SE-DISC', N'SR-ENT-SE', N'WF-X-DISC-01', N'SEC-ROLEPATH', 2, N'Lead Technical Discovery and Define Decision Criteria', N'Use approved customer and technical context to turn discovery into agreed decision criteria, evidence gaps, and the next technical decision.', N'Convert an upcoming discovery conversation into a decision-ready brief with bounded problem, constraints, evidence gaps, and customer decision criteria.', N'Better discovery prevents second discovery meetings. The payoff is a clearer customer decision and fewer surprises during architecture, demo, or PoC work.', N'A discovery brief with agreed decision criteria, open evidence gaps, and the next technical action.', 1),
        (N'SE-HEALTH', N'SR-ENT-SE', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 7, N'Manage Technical Risk and Advance the Deal', N'Inspect exit criteria, proof gaps, blockers, objections, dependencies, and the next technical decision needed to progress the opportunity.', N'Name the technical risk holding the deal, identify the evidence needed to clear it, and assign the next technical action.', N'Deals often wait on a technical answer nobody has explicitly owned. This makes the blocker, owner, and evidence need visible.', N'A technical risk and handoff plan with blocker, impact, owner, mitigation, checkpoint, and next decision.', 1),
        (N'SE-ASSET', N'SR-ENT-SE', N'WF-X-ASSET-01', N'SEC-ROLEPATH', 8, N'Capture and Reuse Technical Assets and Learning', N'Convert proven patterns, demos, scripts, architectures, responses, and lessons into reusable assets or Skill Blueprints with context and safeguards.', N'Package one piece of technical work so another SE can find, trust, adapt, and reuse it.', N'SEs rebuild useful work because the original lacks context, ownership, or searchability. Capture saves future technical time.', N'One reusable technical asset or Skill Blueprint with purpose, prerequisites, parameters, limitations, owner, and validation checks.', 1),
        (N'CE-ORIENT', N'SR-ENT-CE', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-session huddle motion, where AI supports commercial work, where its boundaries sit, which tools may appear, and what to review before next week''s topic.', N'Understand how the CE huddle path runs and where the boundaries sit for AI in commercial work.', N'Commercial work has the least tolerance for AI error. This session sets out where the boundaries are before you rely on anything.', N'CEs know how the huddle motion works, which tools may show up, what to review, and what AI experiences to bring back before next week.', 1),
        (N'CE-HEALTH', N'SR-ENT-CE', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 2, N'Prioritize Commercial Risk and Intervention', N'Surface the commercial risk, structural exposure, and authoritative-source questions that would otherwise appear at approval.', N'Find the commercial risk that will surface at approval, and decide the intervention while it is still cheap.', N'Commercial risk found at approval is a delay. Found earlier, it becomes a structuring decision you can still influence.', N'A prioritized commercial risk view with intervention, owner, and authoritative source for each item.', 1),
        (N'CE-DEAL-1', N'SR-ENT-CE', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 4, N'Develop Commercial Options and Approval Path (1 of 3)', N'Compare viable commercial structures and map the approval requirements each one triggers, before the negotiation starts.', N'Compare viable commercial structures and make the approval path visible before the negotiation starts.', N'Structure decides whether a deal is approvable. Seeing the trade-offs and approval route early prevents rework later.', N'A commercial options matrix with trade-offs, risks, approval requirements, and open decisions.', 1),
        (N'CE-DEAL-2', N'SR-ENT-CE', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 5, N'Build the Commercial Decision Narrative (2 of 3)', N'Turn approved commercial context into an internal recommendation and a customer-specific transition brief.', N'Turn approved commercial context into a decision narrative reviewers can act on.', N'A clear recommendation makes review faster, because the options, assumptions, and risks are visible instead of rediscovered.', N'A recommended commercial path with assumptions, reviewers, transition impacts, and next decision named.', 1),
        (N'CE-DEAL-3', N'SR-ENT-CE', N'WF-X-DEAL-01', N'SEC-ROLEPATH', 6, N'Prepare and Lead the Commercial Negotiation (3 of 3)', N'Build the negotiation position, concession logic, authority boundaries, and validated deal path for customer-facing use.', N'Prepare the negotiation so give-and-get logic and authority limits are settled before customer pressure arrives.', N'Negotiations are where vague structure becomes expensive. Preparing give-and-get logic and authority boundaries keeps judgment human-led.', N'A negotiation plan and validated deal path with authority, concessions, escalation triggers, and review flags.', 1),
        (N'CE-ORCH', N'SR-ENT-CE', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 7, N'Orchestrate Commercial Approvals and Execution', N'Route approval handoffs, exception cases, investment dependencies, and commercial execution to named owners.', N'Move from commercial recommendation to governed execution by naming approvals, owners, handoffs, and blockers.', N'Commercial execution stalls when approval ownership is implied. Naming the route, owner, evidence, and blocker keeps the deal moving without overstating authority.', N'A governed commercial execution plan with approval owners, handoffs, blockers, and the next decision clear.', 1),
        (N'CE-RENEW', N'SR-ENT-CE', N'WF-X-RENEW-01', N'SEC-ROLEPATH', 8, N'Build and Execute the Commercial Renewal Strategy', N'Work renewal economics, commercial structure, risk, expansion potential, and approval path into a renewal strategy.', N'Build the commercial renewal strategy, including risk, structure, expansion potential, and approval path.', N'Renewals are commercial events, not administrative ones. Treating them as strategy is where risk, margin, and expansion become visible.', N'A renewal strategy with commercial risk, structure, expansion potential, approval path, and next decision named.', 1),
        (N'CE-POLICY', N'SR-ENT-CE', N'WF-X-POLICY-01', N'SEC-ROLEPATH', 3, N'Validate Policy, Licensing, and Approval Boundaries', N'Check eligibility questions, licensing risk, and approval routing against authoritative guidance before deal structure hardens.', N'Check policy, licensing, and approval boundaries before structuring decisions harden.', N'Policy questions found at approval cost weeks. Found before structure and negotiation, they cost a conversation.', N'A policy and licensing check with every open question routed to its authoritative owner before the deal path is locked.', 1),
        (N'CSA-ORIENT', N'SR-ENT-CSA', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-session huddle motion, where AI reduces CSA delivery and architecture assembly work, which tools may appear, and what to review before next week''s topic.', N'Understand how the CSA huddle path runs and where AI fits customer architecture and delivery.', N'You inherit whatever is designed and delivered upstream. This explains where you get a say earlier.', N'CSAs know how the huddle motion works, which tools may show up, what to review, and what AI experiences to bring back before next week.', 1),
        (N'CSA-PIPE', N'SR-ENT-CSA', N'WF-X-PIPE-01', N'SEC-ROLEPATH', 2, N'Forecast Consumption and Intervene on Technical Risk', N'Compare consumption against plan, trace each gap to its technical cause, and select the intervention that changes the trajectory.', N'Find where the consumption gap is technically caused, and start one intervention while it still matters.', N'Consumption shortfalls get raised to you after they show up in a report. This is how you see them while there is still time.', N'A consumption position with the technical causes named and one intervention owned.', 1),
        (N'CSA-CONV', N'SR-ENT-CSA', N'WF-X-CONV-01', N'SEC-ROLEPATH', 3, N'Prepare a Technical Advisory Conversation', N'Prepare the recommendation, supporting evidence, and decision request that turn an advisory conversation into a customer decision.', N'Prepare the advisory conversation so the customer leaves with a decision, not a list of options.', N'Advisory conversations drift into education when they are not prepared. Preparation is what keeps them advisory.', N'An advisory plan with the recommendation, the evidence, and the decision you are asking for.', 1),
        (N'CSA-ARCH-1', N'SR-ENT-CSA', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 4, N'Design a Production-Ready Architecture and Validation Path (1 of 2)', N'Compare production architecture options against customer constraints, then turn the chosen direction into a documented design with a validation and proof plan.', N'Choose the production architecture direction and define the validation path that will prove it.', N'You inherit what was designed pre-sale. Designing for production now is how you avoid absorbing it later.', N'A production-ready architecture package with the decision path, validation plan, and dependencies named.', 1),
        (N'CSA-ARCH-2', N'SR-ENT-CSA', N'WF-X-ARCH-01', N'SEC-ROLEPATH', 5, N'Validate the Architecture Evidence and Confirm Delivery Readiness (2 of 2)', N'Pressure-test the architecture evidence, confirm delivery readiness for investment-funded scope, and plan the interventions the design still needs.', N'Validate the evidence behind the design and confirm the scope is ready to deliver.', N'A design that has not been evidence-checked becomes someone else''s escalation. Validating now is cheaper than defending it later.', N'A validated architecture evidence base with delivery-readiness findings and an owned intervention plan.', 1),
        (N'CSA-HEALTH', N'SR-ENT-CSA', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 6, N'Assess Technical Health and Prioritize Risk', N'Rank technical risk by how likely it is to become customer-visible, with evidence and owners attached to each item.', N'Find the technical risk most likely to become customer-visible, and act on it now.', N'Technical risk you catch this week is a conversation. The same risk found by the customer is an escalation.', N'A ranked technical risk list with evidence, owners, and one intervention started.', 1),
        (N'CSA-VALUE-1', N'SR-ENT-CSA', N'WF-X-VALUE-01', N'SEC-ROLEPATH', 7, N'Optimize Cost and Build the FinOps Recommendation (1 of 2)', N'Build the cost and consumption evidence base, then turn it into a costed optimization recommendation the customer can act on.', N'Find the cost the customer is not seeing, and turn it into a defensible optimization recommendation.', N'FinOps findings buy credibility. A concrete saving is the fastest way to be trusted on the larger technical argument.', N'A validated optimization evidence base with one costed FinOps recommendation and an owned intervention plan.', 1),
        (N'CSA-VALUE-2', N'SR-ENT-CSA', N'WF-X-VALUE-01', N'SEC-ROLEPATH', 8, N'Translate Technical Progress into a Customer Value Narrative (2 of 2)', N'Turn technical progress into a value story the customer recognizes, with the evidence behind every claim checked before it is shown.', N'Connect technical progress to the outcome the customer asked for, using evidence that survives scrutiny.', N'Technical work is only credited when someone connects it to what the customer wanted. Unverified claims lose that credit instantly.', N'A customer-ready technical value narrative and review package with each claim evidence-checked.', 1),
        (N'CSAM-ORIENT', N'SR-ENT-CSAM', N'WF-ORIENT-01', N'SEC-ORIENTATION', 1, N'Frontier Accelerator Orientation', N'Introduce the eight-session huddle motion, where AI reduces CSAM status-assembly work, which tools may appear, and what to review before next week''s topic.', N'Understand how the CSAM huddle path runs and where AI fits the customer-success work you already do.', N'You are not being asked to become a tool demo person. You are being given a way to spend less time assembling status and more time driving customer outcomes.', N'CSAMs know how the huddle motion works, which tools may show up, what to review, and what AI experiences to bring back before next week.', 1),
        (N'CSAM-SPLAN', N'SR-ENT-CSAM', N'WF-X-PLAN-01', N'SEC-ROLEPATH', 2, N'Build Outcome-Anchored Success Plans', N'Turn customer priorities into an executable success plan with outcomes, milestones, owners, risks, and review points.', N'Start with the customer outcome and build the plan that makes progress observable.', N'Success plans decay when they become inventories. This turns the plan into a living operating system for customer value.', N'A refreshed success-plan view with outcomes, milestones, owners, risks, and the next review point named.', 1),
        (N'CSAM-HEALTH', N'SR-ENT-CSAM', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 3, N'Assess Customer Health and Predict Risks', N'Combine health, usage, support, sentiment, delivery, and stakeholder signals into a ranked risk view with a chosen intervention.', N'Move from health scores to the next intervention that changes customer trajectory.', N'Risk found early is a customer conversation. Risk found late is an escalation with an audience.', N'A ranked health and risk view with one active intervention, owner, due date, and escalation threshold.', 1),
        (N'CSAM-EXEC', N'SR-ENT-CSAM', N'WF-X-CONV-01', N'SEC-ROLEPATH', 4, N'Map Stakeholders and Drive Executive Alignment', N'Map sponsors, decision makers, workload owners, and relationship risks, then prepare the executive alignment narrative.', N'Prepare the stakeholder conversation that aligns priorities, decisions, and sponsorship.', N'A strong CSAM does not only track activity. They keep the right people aligned before value or risk becomes invisible.', N'A stakeholder map and executive alignment brief with relationship risks, message, evidence, and next ask.', 1),
        (N'CSAM-ORCH', N'SR-ENT-CSAM', N'WF-X-ORCH-01', N'SEC-ROLEPATH', 5, N'Orchestrate Microsoft, Partners and Customer Teams', N'Turn scattered workstreams into a clear operating rhythm across customer stakeholders, Microsoft roles, partners, support, and delivery.', N'Make the customer-success system easier to run by making handoffs and decisions explicit.', N'Most work stalls in the handoff, not the task. Orchestration is how CSAMs create speed without owning every action.', N'A v-team orchestration brief with workstreams, owners, inputs, decisions, dates, and escalations.', 1),
        (N'CSAM-VALUE', N'SR-ENT-CSAM', N'WF-X-VALUE-01', N'SEC-ROLEPATH', 6, N'Accelerate Adoption and Prove Value Realization', N'Identify adoption friction, connect usage to customer outcomes, and prepare a value story the customer recognizes.', N'Turn adoption signals into value proof and the next behavior-change intervention.', N'Adoption without value evidence is fragile. Value that is not communicated is invisible at renewal.', N'A four-week adoption and value plan with gaps, actions, owners, milestones, and customer-ready value evidence.', 1),
        (N'CSAM-RENEW', N'SR-ENT-CSAM', N'WF-X-RENEW-01', N'SEC-ROLEPATH', 7, N'Forecast Consumption, Renewal and Growth Opportunities', N'Connect consumption trajectory, usage commitments, adoption gaps, value evidence, and stakeholder health to renewal and expansion readiness.', N'See renewal and growth conditions early enough to improve them.', N'Renewal readiness is built by value evidence over time, not assembled at the deadline.', N'A renewal and growth readiness view with top risk, value proof, consumption gap, expansion hypothesis, and v-team next action.', 1),
        (N'CSAM-ESCALATE', N'SR-ENT-CSAM', N'WF-X-HEALTH-01', N'SEC-ROLEPATH', 8, N'Lead Delivery Risks, Escalations and Recovery Plans', N'Build a grounded brief for incidents, delivery risks, overdue milestones, and the recovery actions that answer them.', N'Turn escalation noise into a recovery plan with accountability and customer-safe communication.', N'Escalations test trust. A grounded brief reduces chasing, avoids surprises, and keeps the customer conversation focused on recovery.', N'A recovery plan with impact, owners, decisions, next actions, communication cadence, and follow-through mechanism.', 1),
        (N'AE-INVEST', N'SR-ENT-AE', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Align Customer Investment to Account Strategy and Opportunity Outcomes', N'Connect customer investment to a live account priority or deal barrier without implying eligibility, funding, or approval.', N'Identify where customer investment could remove a decision, deployment, or adoption barrier and name the next governed action.', N'You are often the first to see the barrier. Naming where investment could unlock the decision helps you start the right conversation without overstepping ownership.', N'An investment hypothesis tied to an account or opportunity, with evidence, open questions, accountable owner, and next human decision.', 1),
        (N'AE-ORCH', N'SR-ENT-AE', N'WF-X-ORCH-01', N'SEC-ADDITIONAL', 2, N'Mobilize the Account Team and Partners Around the Opportunity', N'Make role coverage, handoffs, partner fit, and follow-through explicit for a live account or opportunity.', N'Turn a matrixed account motion into clear roles, handoffs, and partner actions that move the next customer decision.', N'AEs lead through influence. When ownership is explicit, less time is spent chasing context and more time is spent advancing the customer decision.', N'A role and partner orchestration plan with missing roles, owners, inputs, dates, and follow-up rhythm named.', 1),
        (N'AE-VALUE', N'SR-ENT-AE', N'WF-X-VALUE-01', N'SEC-ADDITIONAL', 3, N'Lead a Customer QBR and Executive Value Cadence', N'Turn outcomes, usage, commitments, investments, risks, and expansion plays into an executive-ready customer value cadence.', N'Build a customer-ready value and QBR narrative that connects what happened to what the customer should decide next.', N'Value that is not evidenced is opinion. Value that is not communicated is invisible, especially before renewals and expansion conversations.', N'An executive value and QBR brief with supported outcomes, open commitments, risks, expansion plays, and strategic asks.', 1),
        (N'ATS-INVEST', N'SR-ENT-ATS', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Assess the Strategic and Technical Case for Investment', N'Test a proposed investment against the account technology strategy, deployment readiness, consumption path, and role boundaries.', N'Judge whether a proposed investment advances the account technology strategy and has a credible path to deployment and consumption.', N'Investment that does not move the technology strategy still consumes technical time. Testing fit early is cheaper.', N'A strategic and technical investment assessment with dependencies, readiness, risks, and the next governed decision named.', 1),
        (N'ATS-CBR', N'SR-ENT-ATS', N'WF-X-VALUE-01', N'SEC-ADDITIONAL', 2, N'Prepare the Technical Contribution for a Customer Business Review', N'Contribute the strategic technical narrative, roadmap, key technical decisions, risks, and evidence to a customer business review.', N'Bring the technical strategy into the customer value conversation.', N'Customer business reviews miss value when technical decisions, proof, and roadmap dependencies are absent or disconnected.', N'A technical CBR contribution with roadmap points, evidence, risks, decisions, and follow-through.', 1),
        (N'ATS-HEALTH', N'SR-ENT-ATS', N'WF-X-HEALTH-01', N'SEC-ADDITIONAL', 3, N'Assess Technical Health and Prioritize Risk Response', N'Connect strategic and technical risks to account priorities and specialist alignment.', N'Find the technical risk that most threatens the account strategy and decide what to do about it.', N'Risk found early is a conversation. The same risk found late is an escalation.', N'A prioritized technical risk response with source signals, owner, intervention, and checkpoint.', 1),
        (N'SE-INVEST', N'SR-ENT-SE', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Scope an Investment-Funded Technical Proof with Success Criteria', N'Bound the technical scope, proof evidence, success measures, failure modes, and delivery handoff for investment-funded work.', N'Define the technical scope, evidence, success measures, and handoff boundaries for investment-funded proof work.', N'Investment-funded work underdelivers when the technical proof is vague. SEs create leverage by bounding the scope before work starts.', N'A technical scope, success-measure package, failure-mode register, and delivery handoff with open decisions named.', 1),
        (N'CE-INVEST', N'SR-ENT-CE', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Clarify Commercial, Policy, and Approval Dependencies for Customer Investment', N'Surface the commercial structure, policy, agreement, exception, and approval dependencies an investment request will encounter.', N'Name the commercial and approval dependencies before the investment request reaches review.', N'Investment requests lose time when commercial dependencies are discovered late. Naming the questions and owners early avoids rework without implying approval authority.', N'A dependency and approval map with authoritative questions, owners, unresolved evidence, and the next human decision.', 1),
        (N'CSA-INVEST', N'SR-ENT-CSA', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Validate Delivery Readiness and Technical Outcome Measures', N'Test whether investment-funded scope can be delivered as written, against dependencies, prerequisites, and technical checkpoints.', N'Test whether the investment can actually be delivered as scoped.', N'You will be delivering it. Readiness gaps found now are gaps you do not absorb later.', N'A delivery-readiness assessment with dependencies, prerequisites, and technical checkpoints defined.', 1),
        (N'CSAM-INVEST', N'SR-ENT-CSAM', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Govern Customer Investment Execution and Value Realization', N'Govern investment execution, handoffs, and value evidence as part of the success plan rather than as a side process.', N'Run customer investment as part of the success plan, not as a side process.', N'Customer investment only creates trust when execution, handoffs, and value evidence are governed from the start.', N'An investment execution rhythm with owners, checkpoints, risks, and the evidence needed for the realization review.', 1),
        (N'ATS-PARTNER', N'SR-ENT-ATS', N'WF-X-ORCH-01', N'SEC-ADDITIONAL', 4, N'Align Partner and Specialist Support to Technical Priorities', N'Identify where partner or specialist capacity is needed to advance the technical decision path.', N'Make partner and specialist involvement match the technical priority, not the org chart.', N'Technical strategy often stalls because the right expertise is not involved at the right time.', N'A partner and specialist alignment plan with capability gaps, owners, timing, and next decision.', 1),
        (N'SSP-INVEST', N'SR-ENT-SSP', N'WF-INVEST-01', N'SEC-ADDITIONAL', 1, N'Develop and Advance an Investment Request', N'Assemble request readiness, contributor coordination, partner and supplier inputs, and status follow-through into an investment request a reviewer can act on.', N'Get an investment request from idea to review-ready without rework or overstated approval status.', N'You often own the request path. Most delay comes from missing inputs, unclear ownership, or hidden open questions.', N'A request package a reviewer can act on, with confirmed inputs, gaps, owners, and next governed action.', 1),
        (N'ALL-USECASE', N'SR-ENT-ALL', N'WF-X-USECASE-01', N'SEC-ADDITIONAL', 1, N'Identify and Test an AI-Assisted Workflow', N'Bring a recurring workflow the team already owns, make its friction visible, and design one bounded experiment to test this week.', N'Choose one real recurring workflow the team already owns, find the smallest step AI could assist, and leave with one bounded experiment and a named owner.', N'You practice on your own work rather than a worked example, so what you leave with is already relevant to your accounts. It works for any role and any workflow, so the team can run it again without new content.', N'One workflow selected, one assistable step identified, one bounded experiment designed with a human checkpoint, and one person accountable for bringing evidence back.', 1),
        (N'ALL-DEAL', N'SR-ENT-ALL', N'WF-X-DEAL-01', N'SEC-ADDITIONAL', 2, N'Find the Deal Facts Before You Need Them', N'Use the deal-making capabilities in Sales Agent to retrieve what is in a customer''s agreement, what they own, what is expiring, and what has been discounted.', N'Learn how to retrieve real agreement, enrollment, and consumption facts for one of your own accounts, and recognize where the work stops being yours.', N'Every role touches a deal without owning it. You stop waiting on someone else for answers that take ninety seconds to retrieve, and you stop walking into customer conversations without knowing what the customer already bought.', N'One account looked up for real, the facts that surprised you named, and a clear line drawn between what you can answer yourself and what belongs to the deal owner.', 1)
    ) v([ExternalId], [SegmentRoleExternalId], [TopicExternalId], [PathSection], [Sequence], [RoleTopicName], [RoleTopicDescription], [TodayObjective], [Wiifm], [DesiredOutcome], [IsActive])
)
SELECT @unresolved = 70 - COUNT(*) FROM raw
    INNER JOIN dbo.HuddleSegmentRoles AS sr ON sr.[ExternalId] = raw.[SegmentRoleExternalId]
    INNER JOIN dbo.HuddleTopics AS t ON t.[ExternalId] = raw.[TopicExternalId];
IF @unresolved <> 0
    THROW 51000, 'HuddlePlacements: 70 source rows were expected to resolve their foreign keys but some did not. Run the earlier scripts in order and re-check the workbook.', 1;

-- HuddleRolePathItems kept in step for backward compatibility. Only SEC-ROLEPATH and
-- SEC-ORIENTATION placements fit it: its key is (SegmentRole, WeekPosition), and SEC-ADDITIONAL
-- reuses sequence numbers that would collide. Those placements live in HuddlePlacements only,
-- which is the reason the new table exists.
;WITH raw AS (
    SELECT * FROM (VALUES
        (N'SR-ENT-AE', 1, N'WF-ORIENT-01'),
        (N'SR-ENT-AE', 2, N'WF-X-PLAN-01'),
        (N'SR-ENT-AE', 3, N'WF-X-PIPE-01'),
        (N'SR-ENT-AE', 4, N'WF-X-PIPE-01'),
        (N'SR-ENT-AE', 5, N'WF-X-OPP-01'),
        (N'SR-ENT-AE', 6, N'WF-X-CONV-01'),
        (N'SR-ENT-AE', 7, N'WF-X-DEAL-01'),
        (N'SR-ENT-AE', 8, N'WF-X-RENEW-01'),
        (N'SR-ENT-ATS', 1, N'WF-ORIENT-01'),
        (N'SR-ENT-ATS', 2, N'WF-X-PLAN-01'),
        (N'SR-ENT-ATS', 3, N'WF-X-CONV-01'),
        (N'SR-ENT-ATS', 4, N'WF-X-PLAN-01'),
        (N'SR-ENT-ATS', 5, N'WF-X-ARCH-01'),
        (N'SR-ENT-ATS', 6, N'WF-X-CONV-01'),
        (N'SR-ENT-ATS', 7, N'WF-X-CONV-01'),
        (N'SR-ENT-ATS', 8, N'WF-X-ORCH-01'),
        (N'SR-ENT-SSP', 1, N'WF-ORIENT-01'),
        (N'SR-ENT-SSP', 2, N'WF-X-OPP-01'),
        (N'SR-ENT-SSP', 3, N'WF-X-PLAN-01'),
        (N'SR-ENT-SSP', 4, N'WF-X-VALUE-01'),
        (N'SR-ENT-SSP', 5, N'WF-X-CONV-01'),
        (N'SR-ENT-SSP', 6, N'WF-X-ORCH-01'),
        (N'SR-ENT-SSP', 7, N'WF-X-DEAL-01'),
        (N'SR-ENT-SSP', 8, N'WF-X-DEAL-01'),
        (N'SR-ENT-SE', 1, N'WF-ORIENT-01'),
        (N'SR-ENT-SE', 6, N'WF-X-CONV-01'),
        (N'SR-ENT-SE', 3, N'WF-X-ARCH-01'),
        (N'SR-ENT-SE', 4, N'WF-X-ARCH-01'),
        (N'SR-ENT-SE', 5, N'WF-X-ARCH-01'),
        (N'SR-ENT-SE', 2, N'WF-X-DISC-01'),
        (N'SR-ENT-SE', 7, N'WF-X-HEALTH-01'),
        (N'SR-ENT-SE', 8, N'WF-X-ASSET-01'),
        (N'SR-ENT-CE', 1, N'WF-ORIENT-01'),
        (N'SR-ENT-CE', 2, N'WF-X-HEALTH-01'),
        (N'SR-ENT-CE', 4, N'WF-X-DEAL-01'),
        (N'SR-ENT-CE', 5, N'WF-X-DEAL-01'),
        (N'SR-ENT-CE', 6, N'WF-X-DEAL-01'),
        (N'SR-ENT-CE', 7, N'WF-X-ORCH-01'),
        (N'SR-ENT-CE', 8, N'WF-X-RENEW-01'),
        (N'SR-ENT-CE', 3, N'WF-X-POLICY-01'),
        (N'SR-ENT-CSA', 1, N'WF-ORIENT-01'),
        (N'SR-ENT-CSA', 2, N'WF-X-PIPE-01'),
        (N'SR-ENT-CSA', 3, N'WF-X-CONV-01'),
        (N'SR-ENT-CSA', 4, N'WF-X-ARCH-01'),
        (N'SR-ENT-CSA', 5, N'WF-X-ARCH-01'),
        (N'SR-ENT-CSA', 6, N'WF-X-HEALTH-01'),
        (N'SR-ENT-CSA', 7, N'WF-X-VALUE-01'),
        (N'SR-ENT-CSA', 8, N'WF-X-VALUE-01'),
        (N'SR-ENT-CSAM', 1, N'WF-ORIENT-01'),
        (N'SR-ENT-CSAM', 2, N'WF-X-PLAN-01'),
        (N'SR-ENT-CSAM', 3, N'WF-X-HEALTH-01'),
        (N'SR-ENT-CSAM', 4, N'WF-X-CONV-01'),
        (N'SR-ENT-CSAM', 5, N'WF-X-ORCH-01'),
        (N'SR-ENT-CSAM', 6, N'WF-X-VALUE-01'),
        (N'SR-ENT-CSAM', 7, N'WF-X-RENEW-01'),
        (N'SR-ENT-CSAM', 8, N'WF-X-HEALTH-01')
    ) v([SegmentRoleExternalId], [WeekPosition], [TopicExternalId])
), src AS (
    SELECT raw.*, sr.Id AS [HuddleSegmentRoleId], t.Id AS [HuddleTopicId]
    FROM raw
    INNER JOIN dbo.HuddleSegmentRoles AS sr ON sr.[ExternalId] = raw.[SegmentRoleExternalId]
    INNER JOIN dbo.HuddleTopics AS t ON t.[ExternalId] = raw.[TopicExternalId]
)
MERGE dbo.HuddleRolePathItems AS tgt
USING src ON tgt.[HuddleSegmentRoleId] = src.[HuddleSegmentRoleId] AND tgt.[WeekPosition] = src.[WeekPosition]
WHEN MATCHED THEN UPDATE SET
        tgt.[HuddleTopicId] = src.[HuddleTopicId]
WHEN NOT MATCHED BY TARGET THEN INSERT ([HuddleSegmentRoleId], [WeekPosition], [HuddleTopicId])
    VALUES (src.[HuddleSegmentRoleId], src.[WeekPosition], src.[HuddleTopicId]);
;WITH raw AS (
    SELECT * FROM (VALUES
        (N'SR-ENT-AE', 1, N'WF-ORIENT-01'),
        (N'SR-ENT-AE', 2, N'WF-X-PLAN-01'),
        (N'SR-ENT-AE', 3, N'WF-X-PIPE-01'),
        (N'SR-ENT-AE', 4, N'WF-X-PIPE-01'),
        (N'SR-ENT-AE', 5, N'WF-X-OPP-01'),
        (N'SR-ENT-AE', 6, N'WF-X-CONV-01'),
        (N'SR-ENT-AE', 7, N'WF-X-DEAL-01'),
        (N'SR-ENT-AE', 8, N'WF-X-RENEW-01'),
        (N'SR-ENT-ATS', 1, N'WF-ORIENT-01'),
        (N'SR-ENT-ATS', 2, N'WF-X-PLAN-01'),
        (N'SR-ENT-ATS', 3, N'WF-X-CONV-01'),
        (N'SR-ENT-ATS', 4, N'WF-X-PLAN-01'),
        (N'SR-ENT-ATS', 5, N'WF-X-ARCH-01'),
        (N'SR-ENT-ATS', 6, N'WF-X-CONV-01'),
        (N'SR-ENT-ATS', 7, N'WF-X-CONV-01'),
        (N'SR-ENT-ATS', 8, N'WF-X-ORCH-01'),
        (N'SR-ENT-SSP', 1, N'WF-ORIENT-01'),
        (N'SR-ENT-SSP', 2, N'WF-X-OPP-01'),
        (N'SR-ENT-SSP', 3, N'WF-X-PLAN-01'),
        (N'SR-ENT-SSP', 4, N'WF-X-VALUE-01'),
        (N'SR-ENT-SSP', 5, N'WF-X-CONV-01'),
        (N'SR-ENT-SSP', 6, N'WF-X-ORCH-01'),
        (N'SR-ENT-SSP', 7, N'WF-X-DEAL-01'),
        (N'SR-ENT-SSP', 8, N'WF-X-DEAL-01'),
        (N'SR-ENT-SE', 1, N'WF-ORIENT-01'),
        (N'SR-ENT-SE', 6, N'WF-X-CONV-01'),
        (N'SR-ENT-SE', 3, N'WF-X-ARCH-01'),
        (N'SR-ENT-SE', 4, N'WF-X-ARCH-01'),
        (N'SR-ENT-SE', 5, N'WF-X-ARCH-01'),
        (N'SR-ENT-SE', 2, N'WF-X-DISC-01'),
        (N'SR-ENT-SE', 7, N'WF-X-HEALTH-01'),
        (N'SR-ENT-SE', 8, N'WF-X-ASSET-01'),
        (N'SR-ENT-CE', 1, N'WF-ORIENT-01'),
        (N'SR-ENT-CE', 2, N'WF-X-HEALTH-01'),
        (N'SR-ENT-CE', 4, N'WF-X-DEAL-01'),
        (N'SR-ENT-CE', 5, N'WF-X-DEAL-01'),
        (N'SR-ENT-CE', 6, N'WF-X-DEAL-01'),
        (N'SR-ENT-CE', 7, N'WF-X-ORCH-01'),
        (N'SR-ENT-CE', 8, N'WF-X-RENEW-01'),
        (N'SR-ENT-CE', 3, N'WF-X-POLICY-01'),
        (N'SR-ENT-CSA', 1, N'WF-ORIENT-01'),
        (N'SR-ENT-CSA', 2, N'WF-X-PIPE-01'),
        (N'SR-ENT-CSA', 3, N'WF-X-CONV-01'),
        (N'SR-ENT-CSA', 4, N'WF-X-ARCH-01'),
        (N'SR-ENT-CSA', 5, N'WF-X-ARCH-01'),
        (N'SR-ENT-CSA', 6, N'WF-X-HEALTH-01'),
        (N'SR-ENT-CSA', 7, N'WF-X-VALUE-01'),
        (N'SR-ENT-CSA', 8, N'WF-X-VALUE-01'),
        (N'SR-ENT-CSAM', 1, N'WF-ORIENT-01'),
        (N'SR-ENT-CSAM', 2, N'WF-X-PLAN-01'),
        (N'SR-ENT-CSAM', 3, N'WF-X-HEALTH-01'),
        (N'SR-ENT-CSAM', 4, N'WF-X-CONV-01'),
        (N'SR-ENT-CSAM', 5, N'WF-X-ORCH-01'),
        (N'SR-ENT-CSAM', 6, N'WF-X-VALUE-01'),
        (N'SR-ENT-CSAM', 7, N'WF-X-RENEW-01'),
        (N'SR-ENT-CSAM', 8, N'WF-X-HEALTH-01')
    ) v([SegmentRoleExternalId], [WeekPosition], [TopicExternalId])
)
SELECT @unresolved = 56 - COUNT(*) FROM raw
    INNER JOIN dbo.HuddleSegmentRoles AS sr ON sr.[ExternalId] = raw.[SegmentRoleExternalId]
    INNER JOIN dbo.HuddleTopics AS t ON t.[ExternalId] = raw.[TopicExternalId];
IF @unresolved <> 0
    THROW 51000, 'HuddleRolePathItems: 56 source rows were expected to resolve their foreign keys but some did not. Run the earlier scripts in order and re-check the workbook.', 1;

COMMIT TRANSACTION;
GO
